### PR TITLE
LPS-164906 Add persistence to the panel tabs

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-164906)

## Motivation

Make the tab active if:
- the user is viewing the versions page after navigating from the CD 
- the user reloads the page
- the user expires a version

## Solution proposed

We use session_click and retrieve the stored value, if any, when the component mounts.

#### Test 1

1. Create 2 web contents, one of them with at least 11 revisions
2. Navigate to the content dashboard
3. Click on the info icon of item with many revisions to open the sidebar panel
4. Click on the Versions tab
5. Scroll down, if needed, to the View more button, and click
6. Portal should navigate to the web content versions detail page
7. Click on the back button
8. Portal should navigate to the Content Dashboard
9. The sidebar panel should be open, and the versions tab should be active

#### Test 2

1. Same scenario as before, repeat steps from 1 to 4
2. Click on the ellipsis button of a version and open the version actions dropdown
3. Click on Expire action
4. The item should be expired and the versions tabs should be active

#### Test 3

1. Same scenario as before, repeat steps from 1 to 4
2. Click on the info icon of the other web content
3. The new web content info should be loaded in the sidebar panel
4. The details tab should be active

#### Test 4

1. Same scenario as before, repeat steps from 1 to 4
2. Reload the page
3. The versions tab should be active

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
@claraizquierdo this is ready, I think, could you take a look? Thxs!

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
LGTM!

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
