### PR TITLE
LRQA-74928 Improve assert after running audit of PageAudit#InvalidAPIKeyErrorIsRecovered

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LRQA-74928](https://issues.liferay.com/browse/LRQA-74928)

**Test(s) failing:**
 * PageAudit#InvalidAPIKeyErrorIsRecovered

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
