### PR TITLE
LPS-128194 Delete author information from general Layouts Content Performance Panel.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

The content performance panel for widget and content will be the same that the web content's DPT, except for:
the author's field, that will be removed

**Proposed solution**

1. The Layout implementation of AnalyticsReportsInfoItem won't return the author information
2. The GetDataMVCCommand won't return the "author" information when this is not provided in the AnalyticsReportsInfoItem.
3. We should avoid display the author's ContentRow in JS.

Screenshot 2021-03-02 at 22 43 10
 
 /cc @dgarciasarai I have followed the idea you mentioned by author, we are not able to work into hide the reads, but we can try to hide the Author for the Layouts right now.

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @dgarciasarai and @darquesdev !!

This pull collides with all the other pull related with the Analytics Reports module, but I think it is ok if we start reviewing it, since we have other pulls stoped by the. CI.

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @dgarciasarai and @dgarciasarai !!

I have rebased this pull with the one the we already send to master (https://github.com/liferay-tango/liferay-portal/pull/959).

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
LGTM ;)

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by dgarciasarai — APPROVED** [review]
Hey @cgoncas, the way you display the author is correct 👍  My concern is that the spacing now without the author is more than the design, but we can fix it later and this way, we didn't block the changes. Thanks!

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Forwaded https://github.com/brianchandotcom/liferay-portal/pull/99468

**Pull request closed without merging**
