### PR TITLE
LPS-119475 Changes added to avoid flakyness

### PR DESCRIPTION
**Pull request by CarlosBrichete**
**JIRA Ticket:**
LPS-126768
LPS-119475

**Motivation:**
This PR contains two new automation tests related to the stories described above. Besides, there is some refactor made in all the paths and macros involved.

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by dgarciasarai** [comment]
Hey @manoelcyreno can you review this pull request? Thanks!

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by dgarciasarai** [comment]
🍀 🕯

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by CarlosBrichete** [comment]
ci:close

**Pull request closed without merging**
