### PR TITLE
LPS-146432 Organization segments used in Experiences are not updated after organization creation

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
This PR solves this bug related to the Segments
[LPS-146432](https://issues.liferay.com/browse/146432)

Proposed Solution
========
The proposed solution consist in not adding the userId to the search context. This is because we will only retrieve those elements created by the user

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by jkappler** [comment]
sent directly to Brian since al tests are green and CI is stuck https://github.com/brianchandotcom/liferay-portal/pull/122493

**Pull request closed without merging**
