### PR TITLE
LPS-171798 audit and simulation buttons should be shown for accessibility

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-171798

The simulation and audit buttons are lost when the page is zoomed 400%. This is an accessibility issue since they are no longer accessible to be used.

Please let me know if there are any questions or comments, or if this should be sent elsewhere.
Thank you!

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Review by Mikellorza — APPROVED** [review]
Hey team,

This solution is working for me. Now I can see the buttons.

Thanks.

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by Stephy6 — COMMENTED** [review]
LGTM also!

**Comment by cgoncas** [comment]
vi:forward

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hello @fortunatomaldonado ,

Thank you for sending your PR. Sorry for not having a look at it before. I've seen one problem with this solution. If we are in mobile the icons overlap with the experience selector:
Captura de pantalla 2023-01-10 a las 14 49 51

Maybe the simulation icon can remain hidden because it is very difficult to simulate a desktop from a mobile device, but that is just my opinion. I don't know if we should provide a different design for these icons in small screens. Maybe PEDS team can help us more.

**Comment by fortunatomaldonado** [comment]
Hello @claraizquierdo,

Thank you for taking a look into this! 
I believe we can remove the Simulation Button since there is no need for it since we cannot simulate a desktop view in mobile.
In doing so, it should no longer overlap. Do you believe this would be okay to do?

Thank you again!

**Comment by claraizquierdo** [comment]
> Hello @claraizquierdo,
> 
> Thank you for taking a look into this! I believe we can remove the Simulation Button since there is no need for it since we cannot simulate a desktop view in mobile. In doing so, it should no longer overlap. Do you believe this would be okay to do?
> 
> Thank you again!

Hello again,

it works for me as intermediate solution for this concrete bug. For the long term I think it will be nice to redesign those icons in small devices. What do you think @marcoscv-work?

**Comment by marcoscv-work** [comment]
Ok, let go ahead!

**Comment by edalgrin** [comment]
Hello 👋 , we are also working on this adjustment https://issues.liferay.com/browse/LPS-167156 so hopefully the space will not be a problem anymore.

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
Hello all,

I updated the fix to only show the audit button on smaller screens. Please let me know if there are any changes needed on this.
Thank you!

**Review by claraizquierdo — APPROVED** [review]

**Pull request closed without merging**
