### PR TITLE
LPS-130918 Use SegmentsConfigurationProvider to read if Role Segmentation is enable or not.

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

Assign Site Roles option in Segments editor when the checkbox is disabled

### Proposed Solution

We should call the SegmentConfigurationProvider to obtain if roleSegmentation is enable or not. Currently we are only reading the System Settings Configuration.

### How to test it

Step-by-Step:

1. Enable Assign roles by segment in System Settings
2. Disable Assign roles by segment in Instance Settings
3. Create a Segment
4. Check the Assign Site Roles option is disabled

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Comment by YurenaC** [comment]
Starting review ;)

**Comment by YurenaC** [comment]
LGTM!
Small and beautiful @cgoncas!

**Pull request closed without merging**
