### PR TITLE
LPS-155386 Add Filtering by Pending Status to the Content Dashboard	

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
As a content marketer, I want to filter my content by the Pending status, so that I can see all my content that is currently awaiting approval.

[LPS-155386](https://issues.liferay.com/browse/LPS-155386)

Proposed Solution
========
Add filter by pending status (blogs and web content are indexed in pending status, so no extra work needs to be done)

Steps to Verify:
----------------
1. Activate Workflow for web content and blogs
1. Submit for Subscription a blog and a web content
1. Go to the Content Dashboard
1. The Blog and the Web Content should appear.
1. If you go filter by pending status they still appear in the results.
1. If you clear the results all the contents appear in the table.

Screencaps:
---------------

https://user-images.githubusercontent.com/5776822/187428487-c5fdc4b0-5454-4bef-a37e-10e2519a051a.mp4

Notes:
---------------

No integration tests have been included because I don't think they are needed, as the pending status is a constant and the filter by status is already tested.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
@cgoncas

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
