### PR TITLE
LPS-149519 Test Fix: Change Content Dashboard's tests creation of WC to use UI

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149519](https://issues.liferay.com/browse/LPS-149519)

**Test(s) failing:**
 * LocalFile.ContentDashboard#ShowOnlyContentCreatedByUser
 * LocalFile.ContentDashboard#ShowAllContentsCreatedByUsers

**Error:**
`
java.lang.Exception: "WC Title 2" is not present
`

**Problem:**
The JSONWebcontent.addWebContent , using the second user created, is not returning successful. Not able to identify the root cause.

**Fix:**
Change the creating from using JSONWS to use UI.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! The JSONWS to create a WC in those tests weren't working. I asked for help at [slack](slack|https://liferay.slack.com/archives/CD7939WBE/p1647457149079349), but still not working. So my idea was to fix using UI, to address this Json issue in a future refactor.

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , I sent this PR https://github.com/brianchandotcom/liferay-portal/pull/114842 yesterday which is also related to Content Dashboard, so let's wait until that one is merged to avoid conflicts.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
