### PR TITLE
LPS-151660 Content Performance Panel doesn't load

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
The content performance panel doesn't load
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151660)

Proposed Solution
========
We have reverted the commits that produced the error

Steps to Verify:
----------------
1. AC-DXP synced.
1. Go to home page
1. Click in Content Performance Panel icon

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
