### PR TITLE
LPS-176914 Generate the day part of the query for since, after, before, on, between and ever modifiers

### PR DESCRIPTION
**Pull request by claraizquierdo**
This PR is the continuation of this one https://github.com/liferay-tango/liferay-portal/pull/3286

Motivation
=======
Generate the day part of the query for since, after, before, on, between and ever modifiers
[Link to story or ticket](https://issues.liferay.com/browse/LPS-176914)

Proposed Solution
========
We have added the logic for generating the day part of the query to the ac-grammar library:
`(activities.filterByCount(filter='(activityKey eq ''Document#documentDownloaded#603744226255659006'' and day gt ''last28Days'')',operator='ge',value=1))`

Steps to Verify:
----------------

1. Set the FF feature.flag.LPS-171722=true feature.flag.LPS-172194=true in your portal-ext.properties
2. Sync your DXP site with AC
3. Create a segment with event criteria and using the since date operator in AC
4. In Control Panel -> Job Scheduler -> Scheduled Jobs run the CheckIndividualSegmentsMessageListener job.
5. Go to Control Panel -> Segments and edit the AC segment.
6. Open your Chrome Devtools -> Network tab
7. Click save and check that the query sent in the payload of the http petition is correct
8. Repeat steps 3 - 7 using all the different time operators: ever, before, after, on , since and between

### CODE REVIEW

**Review by Stephy6 — APPROVED** [review]
Works perfectly 🎉

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1297401_6544

**Comment by claraizquierdo** [comment]
@CarlosBrichete @rafaellajordao , could you confirm that the tests failing are not related with this PR please?

**Pull request closed without merging**
