### PR TITLE
LPS-117816 [Content Performance] Add translation component

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Show available translations for the content in the Content Performance panel and be able to view the performance of each language selecting one of language.

**Screenshots**

The dropdown only shows default and translated languages.

Screenshot 2020-08-20 at 18 08 39 Screenshot 2020-08-20 at 18 08 47 Screenshot 2020-08-20 at 18 08 57

### CODE REVIEW

**Comment by dgarciasarai** [comment]
**Mock data**
```js
const languages = [
	{default: true, languageId: 'en-US'},
	{default: false, languageId: 'pt-BR'},
	{default: false, languageId: 'fr-FR'},
	{default: false, languageId: 'ja-JP'},
	{default: false, languageId: 'ca-ES'},
	{default: false, languageId: 'es-ES'},
];
```

**Comment by dgarciasarai** [comment]
Hey @cgoncas @darquesdev, I updated this pull request with the same format as Info sidebar panel `viewURLs` data for the Content Dashboard. I don't need `viewURL`, only `default` and `languageId` attributes 😄  Thanks!!

**Comment by cgoncas** [comment]
Hey @dgarciasarai ,  I think the viewURL is needed since this URL should be clickable, that is the way to navigate between different languages, and see the traffic Sources metrics per them.

**Comment by dgarciasarai** [comment]
You're right @cgoncas!

**Comment by cgoncas** [comment]
Hey @dgarciasarai, now on master, we are returning the viewURLs info in the props object, so maybe we now are able to integrate this pull.

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!

I have updated the pull, now getData return:

{ "context" :{ "getAnalyticsReportsData", "URL"}}

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!

I have needed to force push in your branch since this pull should be rebased with today's master changes. Sorry :(

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!

I have needed to force push in your branch since this pull should be rebased with today's master changes AGAIN. Sorry :(

**Comment by dgarciasarai** [comment]
https://github.com/liferay-frontend/liferay-portal/pull/287

**Pull request closed without merging**
