### PR TITLE
LPS-150864 Inaccessible Experiences in Page editor after export/import

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This PR solves the following issue
[LPS-150864](https://issues.liferay.com/browse/LPS-150864)

Proposed Solution
========
The proposed solution is to assign the ID_DEFAULT value to the segmentEntry in case the segment isn't imported. In this situation we will keep the Experiences in the import and link them to the Anyone segment (the value by default).

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:echo

**Comment by jkappler** [comment]
ci:test:tango

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Review by Mikellorza — APPROVED** [review]
I think that it is a fast and good solution to fix  the bug what we are facing.

**Comment by Stephy6** [comment]
ci:test:tango

**Pull request closed without merging**
