### PR TITLE
LPS-136752 staging-bar-web isolate CSS and minor bug fixes

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-136752

See [Confluence](https://liferay.atlassian.net/wiki/spaces/ENGFRONTENDINFRA/blog/2021/05/19/1557659937/Isolating+Admin+Components+From+CSS+Customizations+for+Site+Creators) for the details behind these changes.

Screenshot:
staging-bar-web

### CODE REVIEW

**Comment by pat270** [comment]
ci:test:sf

**Comment by pat270** [comment]
ci:test:relevant

**Comment by pat270** [comment]
ci:test:relevant

**Comment by JoyceWang08211** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
Hi @pat270 @JoyceWang08211 as mentioned in https://github.com/liferay-frontend/liferay-portal/pull/1338 this is not a Tango team related feature, could you please send the PR back to frontend team? I'll proceed to close this PR.
Sorry for any inconvenience caused

**Pull request closed without merging**
