### PR TITLE
LPS-154019 Dismissible alert for Segments Simulation when Segmentation is disabled

### PR DESCRIPTION
**Pull request by beltranrengifo**
This PR is a follow up of [this one](https://github.com/liferay-tango/liferay-portal/pull/2528)

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by YurenaC — APPROVED** [review]
LGTM!
Hit forward @beltranrengifo :D

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
