### PR TITLE
LPS-137415

### PR DESCRIPTION
**Pull request by RitaSilveira**
https://issues.liferay.com/browse/LPS-137415

### CODE REVIEW

**Comment by RitaSilveira** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @RitaSilveira, please review the SF of your branch locally, it seems to be failing in CI. Thanks! :)

**Comment by RitaSilveira** [comment]
fixed

**Comment by CarlosBrichete** [comment]
Hey @RitaSilveira , it seems SF still failing... did your local SF worked fine?

**Comment by RitaSilveira** [comment]
fixed

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by RitaSilveira** [comment]
ci:test:sf

**Pull request closed without merging**
