### PR TITLE
LPS-152906 Remove download from preview component

### PR DESCRIPTION
**Pull request by claraizquierdo**
### Motivation
We need to add the Share button to the Content Dashboard Info Panel below the preview. Preview and the download and share actions should be independent. The rest of the code for the share button will be added here https://github.com/liferay-tango/liferay-portal/pull/2612 .

### Proposal
We are moving the download action outside the Preview component because the preview has nothing to do with the download. 

### How to test it?
1. Go to documents and Media and create two documents: a jpg and a zip.
2. Go to content dashboard
3. Click in the info action of the jpg document and check that the preview and the Download action are shown
4. Click in the info action of the zip document and check that only the Download action is shown

### CODE REVIEW

**Review by beltranrengifo — COMMENTED** [review]
Hi @claraizquierdo !
For the .zip file I've uploaded, the preview is still visible.
I think this is expected, as we need to handle that bug, but it does not match with the description of this PR 🤷 
image

If that's fine, I'm fine, all things look good ❤️

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
> 

You are right @beltranrengifo . I forgot that we have a bug there, but it was not introduced in this PR. We will fix it in another PR.

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
