### PR TITLE
LPS-152323 Element ID field gets empty after changing from variant

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to the ticket](https://issues.liferay.com/browse/LPS-152323)

This issue solves the lose of the clickable element when creating/changing from variaton

## Proposed Solution

Maintain the namespace of the fragment entry links so that all of the variation have the sameids

## Steps to Verify:

1. Connection with AC
2. A page with a button fragment
3. Create a AB Test
    Go to Page > open AB Test > 'Create Test' > Set any name > Set 'click' as goal > 'Save'
4. Select the button as click goal
    At AB tests sidebar > 'Select Clickable Element' > Click at button element > 'Set Element as Click Target'
5. Create a variant
    At AB tests sidebar > 'Create Variant' > Set any name > 'Save'
6. Change to 'Control' variant

## Screenshots:

variant

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
Everything looks good 🎉

**Comment by cgoncas** [comment]
Hey @claraizquierdo and @jkappler !!

Should we forward this PR?

Thanks!!!

**Comment by claraizquierdo** [comment]
> Hey @claraizquierdo and @jkappler !!
> 
> Should we forward this PR?
> 
> Thanks!!!

Everything ok from my side 👍 I don't know if @jkappler wants to do anything else.

**Comment by jkappler** [comment]
@cgoncas, @claraizquierdo, we were waiting for the AC tests to be available again

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
