### PR TITLE
LPS-126152 Restrict prioritizing experiences if there AB testing running

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-126152)

Proposed Solution
========
We won't allow to move up an experience (exp1) if the experience above (exp2) has an ab test running and it is for the same audience (exp1 and exp 2 have the same audience or exp1 audience is "anyone")

Steps to Verify:
----------------

1. Connect DXP with AC
2. Create new experience (exp1) for an audience A and move to the top (placed first on the experiences list)
3. Create an AB Test for that experience and run the test (status Running)
4. Go back to the experiences dropdown and create a new experience (exp2) for the same audience.
5. Create another experience (exp3) for a different audience (not anyone)
6. Create another experience (exp4) for audience anyone.
7. You shouldn't be able to move exp2 and exp4 above exp1.
8. You should be able to move exp3 above exp1.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
Approved after local testing, all seems to work as expected

**Comment by YurenaC** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
