### PR TITLE
LPS-125793 - [Back] Provide MVC Action Command to Duplicate experiences

### PR DESCRIPTION
**Pull request by darquesdev**
Please, see https://github.com/liferay-tango/liferay-portal/pull/766#pullrequestreview-570589021

**Motivation**
In order to [duplicate experiences](https://issues.liferay.com/browse/LPS-121405), first It's required to expose a MVC Action Command to be called from the front-end. In this PR It's not covered the positioning logic (following the default behavior), It'll be covered in a further one.

**Solution**
Create a MVC Action Command to duplicate an experience given a `segmentsExperienceId`.

**How to test it**
Integration test has been added

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM :)

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:stop

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
