### PR TITLE
LPS-152762 Test Autom for LPS-113248: As a Marketer, I can map web content in fragments fields per experience

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-152762](https://issues.liferay.com/browse/LPS-152762): Test Automation for...
↳ [LPS-113248](https://issues.liferay.com/browse/LPS-113248): As a Marketer, I can map web content in fragments fields per experience

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
