### PR TITLE
LPS-152541 BindSegmentsCompanyConfigurationMVCActionCommandTest

### PR DESCRIPTION
**Pull request by jkappler**
- LPS-152541 Added test for newly created ActionCommand
- LPS-152541 Make test more resilient by setting the configuration for a new company, and also deleting it before every run. Also, change so that we get the configuration just like we do in SegmentsConfigurationProviderImpl
- LPS-152541 Simplify by using CompanyConfigurationTemporarySwapper

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by jkappler** [comment]
Sending directly to BChan https://github.com/brianchandotcom/liferay-portal/pull/122492

**Pull request closed without merging**
