### PR TITLE
LPS-124236 As a content author, I want to be able to export data to an .xls file

### PR DESCRIPTION
**Pull request by YurenaC**
Various fixes requested by Brian applied in this PR

The extraction of the xls creation in a new module won't be done now for the following reasons:

- Tango Team has planned a complete refactor of the content dashboard. 
- Currently, the content dashboard's items structure is very reliant on the items shown so, we'd like to make it more general (using the info-api) and extensible, therefore custom items created by our clients can be also shown there.
- We'd like to avoid exposing any API as during this refactor process, the excel generation will be also affected and restructured in a more generic way, consequently re-adapt can be a pain later on

@4lejandrito please, feel free to add more info here
Thanks!

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @YurenaC,

I like your description but I am missing the main reason which is that we want to avoid exposing public API until that refactor occurs, because then it would change and become a pain.

The rest looks good.

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
