### PR TITLE
LPS-135323 Reverting language targeting when creating an experience

### PR DESCRIPTION
**Pull request by 4lejandrito**
We are reverting this ticket: https://issues.liferay.com/browse/LPS-124170. These changes only revert the Web part. The service part will be done later (since it requires deprecation of methods).

That ticket introduced the possibility to choose some languages when creating an experience, so then, when switching to that experience, only those languages were available in the language selector.

With this revert, it should be working like it was before the story (users don't select any language when creating an experience and all of them are available when switching to it).

We have tested experience creation/modification/removal, and also switching to the experience and adding some fragments works well.

**Pending:**
- [x] @CarlosBrichete please push your test changes here.
- [x] @4lejandrito revert (deprecate) service changes. We won't be reverting the old methods and column for now. Since it's a typesettings we will leave it there to avoid breaking changes. It could end up being useful for something else too.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1117401_9177

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
After an offline conversation with @david-gutierrez-mesa we decided to remove the test ViewLocalizedInlineTextItemsFromCurrentExperienceInPageContentPanel from Echo since it makes no sense anymore.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
