### PR TITLE
LPS-127220 Decouple Analytics Reports code from Layout Display Page Provider

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

First Refactor of the Analytics Report api, so we can decouple it from DPT.

**How to test it**

Integration/Unit test should still be green

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
Great decoupling! LGTM 😄

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
