### PR TITLE
LPS-137277 Remove not needed ignore annotations

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-137277](https://issues.liferay.com/browse/LPS-137277)

**Motivation**:
Remove "@ignore" annotation not removed at LPS-144038

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz, this PR seems to have conflicts to be merged, please rebase with master and resend.

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! I rebase it today, but still has the same conflict. I'll send another one to see if this still happens.

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete , conflicts are now gone.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
