### PR TITLE
LPS-144674 Create segment action is appearing in collections page if there are no available segments in the site

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Impedibug ticket](https://issues.liferay.com/browse/LPS-144674)
[Story ticket](https://issues.liferay.com/browse/LPS-101448)

### Motivation
We should restore the old UI for empty/default states, and their variants, isolating the D&D features from other that should be done in other stories in the near future.
For that, some code has been removed, and the old states presented in the former JSP file are taking into account in the new React component.

Please check the screenshots from the previous version to check the UI, or activate/deactivate the feature flag at your will during the checking:

```
 echo "enabled=B\"true\"" > ../bundles/osgi/configs/com.liferay.asset.list.web.internal.configuration.FFCollectionsVariationsPrioritizationConfiguration.config
```
[com.liferay.asset.list.web.internal.configuration.FFCollectionsVariationsPrioritizationConfiguration.config.zip](https://github.com/liferay-tango/liferay-portal/files/7803285/com.liferay.asset.list.web.internal.configuration.FFCollectionsVariationsPrioritizationConfiguration.config.zip)
1-no-segments-at-all
2-segments-available-no-variations-yet
3-segments-available-with-variations
4-no-more-segments-available

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
