### PR TITLE
LPS-122800 Disable the option “Assign site roles” to a segment in the segment editor

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

As we are disabling the Assign Roles by segment by default, the option “Assign site roles” to a segment in the segment editor must show as disabled too, until the feature is activated.

**Proposed solution**

When the Assign Roles by segment option is disabled, the existing option “Assign site roles” on a segment in the segment editor will show as disabled.

My first approach was to move the code inside the segments_entry_action.jsp to a display context (as a List of dropdowns ), but this option was too costly, and I think frontend changes are needed too in order to follow this path, so I discarded this approach and add the new check to the segments_entry_action.jsp (we can't add a test for that, but we can try to accomplish that in the future)

**How to test it**

1. Go to People/Segments.
2. Create a Segment in a site different than Global.
3. Click in the dropdown menu of the recently created segment.
4. The option "Assign Site roles" is not listed.
6. Go to System Settings > Segments > Segments Services (and enable Segmentation by roles)
7 Go to People/Segments.
8. Click in the dropdown menu of the recently created segment.
9. The option "Assign Site roles" is listed.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
Excellent work Cris! Go ahead, and forward it.

Just one question, do you think it would be worth adding an integration test for `SegmentsPortlet` to check the value of the `isRoleSegmentationEnabled` property of `SegmentsDisplayContext`. If you consider it, I can add it myself ;)

**Comment by cgoncas** [comment]
> Excellent work Cris! Go ahead, and forward it.
> 
> Just one question, do you think it would be worth adding an integration test for `SegmentsPortlet` to check the value of the `isRoleSegmentationEnabled` property of `SegmentsDisplayContext`. If you consider it, I can add it myself ;)

Hey @darquesdev , like the testIsRoleSegmentationEnabled test?

It test the property isRoleSegmentationEnabled in SegmentsDisplayContext

Thanks!!!

**Comment by cgoncas** [comment]
ci:forward

**Comment by darquesdev** [comment]
hahaha, my fault I didn't see the last commit, now I have absolutely nothing to add

**Pull request closed without merging**
