### PR TITLE
LPS-131668 Fix when document, blog and web content edit is checked

### PR DESCRIPTION
**Pull request by YurenaC**
Due an unexpected behaviour discovered, the access to the Page Audit panel needs to be restricted only to valid layouts.
So pages like, create or adit users within the content panel do not show the Page Audit panel icon

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:sf

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
