### PR TITLE
LPS-137497 Test Autom. be able to tell which experiments are affected by ongoing AB Test | A/B Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137497](https://issues.liferay.com/browse/LPS-137497)

Motivation:
As a marketer, I can tell which experiences are affected by ongoing A/B tests"

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
