### PR TITLE
LPS-152541 Save button

### PR DESCRIPTION
**Pull request by claraizquierdo**
### Motivation

We want to show a save button when no company configuration has been saved yet for segments and an update button otherwise.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-152541)

### Proposal 

This is a continuation of https://github.com/liferay-tango/liferay-portal/pull/2538. 

### How to test it

1. Activate FF (add feature.flag.LPS-152541=true in portal-ext.properties).
2. Clean your database so that you don't have a company configuration saved.
3. Go to Instance Settings -> Segments -> Segments Service And check that the save button is shown.
4. Click save button.
5. Go to Instance Settings -> Segments -> Segments Service And check that the update button is shown.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
hi @claraizquierdo 
Everything is working fine! 👏

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
