### PR TITLE
LPS-116331 Use the User Item Selector (and delete custom code).

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

User item selectors in Segments Editor don't keep the selected data

**Proposed solution**

Use Item Selector, so we can delete our custom user selector, with this approach we need a frontend change @dgarciasarai. Every time the select button is clicked and the item selector is called, a parameter with the value: **_checkedUserIds_** should be filled with the current userId.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
We have decided that probably we need to rethink the behavior of the multiple selection in the Segments Editor, since even with this solution, many criteria will be created independently of the previously created ones.

**Pull request closed without merging**
