### PR TITLE
LPS-142930 Add test for new acceptance criteria

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Add new frontend test for new acceptance criteria in audit site vocabularies.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-142930)

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]
🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
