### PR TITLE
LPS-129375 Change style of language dropdown items

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @sandrodw3, I just pushed a new commit with the language labels:

Screenshot 2021-05-24 at 15 01 09

**Comment by sandrodw3** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@sandrodw3 I'm fixing the tests.

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
