### PR TITLE
LPS-124170 Add TypeSettings to the SegmentsExperience model

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

In order to save the locales of a SegmentExperience we need to add a new column (TypeSettings) to the DB Model.

**How to test it**

Integration tests have been provided in this pull request

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:reevaluate:1142004_7707

**Comment by darquesdev** [comment]
ci:test:relavant

**Comment by darquesdev** [comment]
ci:stop

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
Absolutely nothing to add, great @cgoncas!

Just a couple of notes:
1. Normally I use just one commit for the autogenerated files, why did you add one for every step?
2.   I see that in SegmentsExperiments it added this method [getTypeSettingsProperties](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/model/impl/SegmentsExperimentImpl.java#L135). Maybe something similar will be handy in the near future here.

**Comment by cgoncas** [comment]
> Absolutely nothing to add, great @cgoncas!
> 
> Just a couple of notes:
> 
> 1. Normally I use just one commit for the autogenerated files, why did you add one for every step?
> 2. I see that in SegmentsExperiments it added this method [getTypeSettingsProperties](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/model/impl/SegmentsExperimentImpl.java#L135). Maybe something similar will be handy in the near future here.

Hey @darquesdev !!!

Thanks for the review, I usually create one autogenerate commit per change so I can discard all the commits I don't want.
Otherwise, the test won't compile, until the last commit with the autogenerate.

I will add the getTypeSettingsProperties method, thank you a lot :)

Thanks!!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
