### PR TITLE
LPS-137489 Test Autom.for be notified when the AB test is complete. | AB Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137489](https://issues.liferay.com/browse/LPS-137489)

Motivation:
"As a marketer, I get notified when the test is completed".

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
