### PR TITLE
LPS-143333 Remove segmentsExperienceId from reserved params

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-143431)

### CODE REVIEW

**Comment by david-gutierrez-mesa** [comment]
Just started reviewing :)

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by brianchandotcom** [comment]
@claraizquierdo @ealonso I merged this manually.

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
