### PR TITLE
LPS-147229 Hide clipboard when there is not info to show

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
We are showing the Content Dashboard Info Panel the clipboard empty when it shouldn't be shown at all
[Link to story or ticket](https://issues.liferay.com/browse/LPS-147229)

Proposed Solution
========
We check that the object received with the clipboard info is not an empty object.

Steps to Verify:
----------------
1. Create a basic web content
1. Go to Content Dashboard and open the info panel for the web content just added
1. Check that the clipboard is not shown

Screenshots (optional):
-----------------------
Before:
Captura de pantalla 2022-03-18 a las 13 19 38

After:
Captura de pantalla 2022-03-18 a las 13 18 22

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @claraizquierdo, @beltranrengifo and @Stephy6 

I am going to forward this PR, since fix the bug. If after the review you decide to change something, feel free to reopen the task.

Thanks!!

**Comment by cgoncas** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
> Hey @claraizquierdo, @beltranrengifo and @Stephy6 
> 
> I am going to forward this PR, since fix the bug. If after the review you decide to change something, feel free to reopen the task.
> 
> Thanks!!

LGTM!
Thanks!

**Pull request closed without merging**
