### PR TITLE
LRQA-76538 | Test fix for PageAudit#AssertPageAuditLocaleInDisplayPage

### PR DESCRIPTION
**Pull request by rafaellajordao**
Hi! :)
This pr is corresponding to this ticket: [LRQA-76538](https://issues.liferay.com/browse/LRQA-76538)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 171 out of 193 jobs passed in 2 hours 3 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Review by Luizcarlosqueiroz — APPROVED** [review]
Good to go!

**Pull request closed without merging**
