### PR TITLE
LPS-148315 Performance improvements in the Content Performance Panel

### PR DESCRIPTION
**Pull request by beltranrengifo**
## Motivation
Improve Content Performance Panel performance, avoiding lags and unneeded network requests
**This PR tries to address the SECOND task: _Avoid re-fetching unneeded data_**

[Jira issue](https://issues.liferay.com/browse/LPS-148315)
[Spike in Jira](https://issues.liferay.com/browse/LPS-148151)

### Launch initial request on top bar button hover event, as we do in Page Audit panel
Currently we are waiting for the component mounted event to request the data, causing a small visible delay.
We can improve this experience by requesting the data on top-bar button hover event, as we do in Page Audit panel

### Avoid re-fetching unneeded data
If a user visits any traffic channel details, ie. Referral, and then goes back to the main page of the CPP using the provided go-back button, 3 unneeded request are executed. The main component data should be already available in client side and the reload of this main view should happen with no delay for the user.

### Ungroup requests for Traffic Sources
Currently, our trafficSources endpoint return all the payload in a single request. Only a tiny fraction of this info is needed to render the main view of the CPP.
We should split this request in multiple ones, sliming down the first one with only the needed data, and requesting each traffic channel details on user's click event over the traffic channel link.

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sfº

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @beltranrengifo,
Good work with the performance 💪 I just have found two styles problems:

- If we have vertical scroll in the sidebar I'm able to see the Detail view and the Main view
Captura de pantalla 2022-03-25 a las 13 15 24

- In mobile devices I see that the top of the sidebar is not well aligned:
Captura de pantalla 2022-03-11 a las 13 16 36

**Comment by beltranrengifo** [comment]
> Hi @beltranrengifo, Good work with the performance 💪 I just have found two styles problems:
> 
> * If we have vertical scroll in the sidebar I'm able to see the Detail view and the Main view
> 
> Captura de pantalla 2022-03-25 a las 13 15 24
> 
> * In mobile devices I see that the top of the sidebar is not well aligned:
> 
> Captura de pantalla 2022-03-11 a las 13 16 36

Thank you @claraizquierdo !
Pushing changes, feel free to review the PR whenever you can 🥳

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1317401_2573

**Comment by beltranrengifo** [comment]
ci:reevaluate:1317401_2573

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
