### PR TITLE
LPS-153487 Content Performance and Experiments panels are hidden when another panel is opened

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Content Performance panel is hidden when another panel is opened.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-153487)

Proposed Solution
========
We have included the initialization of the content performance panel when the menu icon is rendered. We have done the same with ab testing panel because it was not working properly too.

Steps to Verify:
----------------

1. Go to Home
2. Click on the Content Performance panel
3. Click on another panel (AB testing, Page Audit...)
4. Click on the Content Performance panel again
5. Navigate to another page (for example Content Dashboard)
6. Navigate back to home page and repeat steps 2 - 4

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
Hi @claraizquierdo !
So nice this is resolved now.
I tested in CPP and Experiments panels, all work as expected.

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
