### PR TITLE
LPS-137417 Test Autom. for to be able to delete an experience. | Personalization

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137417](https://issues.liferay.com/browse/LPS-137417)

Motivation:
"As a Marketer, I want to be able to delete an experience"

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
