### PR TITLE
LPS-143093 Use the default segments entry id if the type settings are empty

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by brianchandotcom** [comment]
@ealonso I merged this manually since it's a blocker. Leaving this PR open so we can have results.

fyi

**Comment by cgoncas** [comment]
Hey @ealonso !!!

Could you please follow the Tango's PR Play (described here).

Also, do you mind add a test for this issues?

Thanks!!!

**Comment by ealonso** [comment]
Will resend following the Tango's PR Play and adding a test

**Comment by cgoncas** [comment]
Thanks a lot @ealonso !!!!!

If you need help with the test, let me know :)

**Pull request closed without merging**
