### PR TITLE
LPS-168816 Add the frontend component for the Scope Card in the Segments Editor

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
We are moving the Segmentation from a site to a global scope. In order to that we need to introduce a tool to manage sites and assign them to Segments. We are using a Scope Card to select sites for this purpose. This PR contains the Front-end part with no site selector, just the Scope Card with the current site.
[Link to the task](https://issues.liferay.com/browse/LPS-168816)
[Link to the story](https://issues.liferay.com/browse/LPS-167025)

Proposed Solution
========
The proposed solution consists in using a ClayPanel to render the Card, where the PanelHeader contains the title "Scope" and the PanelBody contains the Site Name.

Steps to Verify:
----------------
1. Go to People -> Segments.
2. Click on '+' to add a new Segment.
3. Check that the Scope Card is displayed correctly.

Screencaps
---------------
Captura de pantalla 2022-11-23 a las 11 32 18

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango-acceptance

**Comment by Stephy6** [comment]
ci:forward

**Review by Stephy6 — COMMENTED** [review]
Tested and works fine! 🎉

**Pull request closed without merging**
