### PR TITLE
LPS-167073 HR_15 When user activates "Page Audit" button and Side panel pop-up, Focus is not moving to Side panel window

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This ticket resolves a Accessibility bug about the usage of the Page Audit panel, related to the focus when navigating with the keyboard. 

[Link to the bug](https://issues.liferay.com/browse/LPS-167073)

Proposed Solution
========
The proposed solution consists in use two eventHandlers to manage the keyboard events when opening and closing the Panel and a function to change the aria-pressed for the Page Audit Toggle so is it possibly to save its state.

Steps to Verify:
----------------
1. Navigate through the Control Menu Navbar pressing  the Tab button and focus on the Page Audit button.
2. Press the Enter button and check that the panel opens up and the Panel is focused on.
3. Click the Tab button and check that he focus moves into the panel.
4. Click the Exit button and checked that the panel is closed and the focused goes back to the toggle Page Audit button.

Screencaps
---------------
Screenshot 2022-12-12 at 18 45 16

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
Ey @Stephy6 ,
I made some changes. Could you have a look and check that everything is working fine? Thank you :)

**Comment by claraizquierdo** [comment]
ci:reevaluate:1287401_5389

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
Just tested and works fine! 🎉

**Comment by claraizquierdo** [comment]
ci:reevaluate:1367401_2636

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
