### PR TITLE
LPS-132234 buildLang

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hi @4lejandrito 🙂
This is a draft for https://issues.liferay.com/browse/LPS-132234. For the moment, I have set the shape of the failing elements as objects with `content` and `title`, but I'll rename them when we clarify the format.

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1257401_451

**Comment by sandrodw3** [comment]
ci:test:relevant

**Pull request closed without merging**
