### PR TITLE
LPS-162311 Add Version History to the Info Panel for Web Content

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-161018)

As a Content Marketer, I want to see a Web Content's version history in the Info Panel of the Content Dashboard, so that I can easily understand the history of that Web Content.

## Steps to Verify:

1. Enable FF for Epic LPS-161013
2. Add a web content and publish it several times
3. Go to Content Dashboard and click on i icon of the web content to open the info panel
4. Click on "Versions" tab
5. The list of versions will be shown, ordered by version descending 

## Gif

versions_history

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
LGTM!

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
