### PR TITLE
LPS-156403 Extensions icons should be colored in filter of Content Dashboard

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-156403)

## Motivation

We have a regression issue where the icons in the Content Dashboard Extension filter do not follow the colours stated in the Design guidelines.
[Original bug ticket](https://issues.liferay.com/browse/LPS-138264)

## Solution proposed

We along with FI migrated the tree component to a new version.
I presume we forgot to add the `className` prop to the icon.
I believe it's all it needs.

## How to verify

- Visit the Content Dashboard
- Open the filters dropdown
- Click in Extension filter

**Expected**: icons are coloured as stated in the original bug table:
image

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
LGTM!

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
