### PR TITLE
[TS] LPS-146149

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-146149

Resent from https://github.com/liferay-tango/liferay-portal/pull/2140 with @cgoncas's [approach](https://github.com/liferay-tango/liferay-portal/pull/2140#issuecomment-1026564784) used.

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @ChrisKian !!!

I need a little bit more time to review it, because I think that every time the user logout, the UserModelListener is executed.

Thanks!!

**Comment by ChrisKian** [comment]
Yes @cgoncas, that is a side-effect of using the UserModelListener.  I'm not sure if there is a way to only run on "substantial" user updates from that class.  Here are my ideas:
1. In the UserModelListener class, compare the fields of the `originalUser` and `user` objects to see if a substantial update has been made.  This has a high overhead and doesn't account for custom fields.
2. Remove the UserModelListener, and instead use a message listener/sending in UserLocalServiceImpl and other specific methods which deal with user updates to hopefully exclude simple updates like `lastLoginDate` and `mvcc`.  This option will be a bit messier and may difficult to find all correct areas we need to send the message.  Also, since UserLocalServiceImpl is in portal-impl, it will not be easy to call segmentsEntry related classes.

**Comment by cgoncas** [comment]
Hey @ChrisKian !!!

I think there is not a good approach for this issue :(. For the client with the problem that open the original PTR, was enough to increase the frequency of the reindexer?

Thanks!!

**Comment by ChrisKian** [comment]
Hi @cgoncas, is there any update for this issue?  We have a client waiting on a solution or at least to know if this is the expected outcome.  Thanks!

**Comment by cgoncas** [comment]
Sorry, @ChrisKian !!!

I have tried a few approaches myself this time, that is the reason I am answering the question so late, my bad :(.

The Listener approach is not possible because we will have many maintenance problems with our segments and also with the clients (we will need to implement a listener per model ; user, organization, userGroup, ...)

The method option is not possible, because new methods will be added and evolve, and this new feature, will stop working.

I think the reindexer method is the right approach, for your client, you can put a sorter time if they could handle the performance impact in their system.

We will document it better, so we don't face this problem in the near future. If you want, I can add this comment to the PR also.

Thanks!!

**Pull request closed without merging**
