### PR TITLE
LPS-154265

### PR DESCRIPTION
**Pull request by liferay-tango**
### Motivation

Currently every time a user go to a content page we get all the segments that the user belongs to and this is a highly costly operation because:

1. Segments are obtained running an ES query that is never cached.
2. A query is executed per every segment in the system.

### Proposed Solution

We will process the segments that have an experience for the current page.:

1. Obtain the segments of the experiences
2. Check if the user belongs to any of these segments.

So if the system has 100 segments, but the experience has 3, only 3 ES queries will be executed.

### How to test it

No guntional changes, all test should be green after the change.

### CODE REVIEW

**Comment by liferay-tango** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
