### PR TITLE
LPS-139239 Hide content performance button

### PR DESCRIPTION
**Pull request by lucassantanasantos**
https://issues.liferay.com/browse/LPS-139239
Hide content performance button

### CODE REVIEW

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
Hey @lucassantanasantos this PR still has some SF issues, please fix, thanks :)

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
