### PR TITLE
[TS] LPS-146149

### PR DESCRIPTION
**Pull request by ChrisKian**
https://issues.liferay.com/browse/LPS-146149

Please let me know if you have any questions, thanks!

### CODE REVIEW

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by ChrisKian** [comment]
ci:test:relevant

**Comment by ChrisKian** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Hey @ChrisKian !!!

Thanks a lot for the pull, first of all, I would want to let you know that in Tango we follow [this guide](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews) to create a PR. Would be lovely if you could adapt this PR to the format that we describe in there.

Thanks!!

**Review by cgoncas — CHANGES_REQUESTED** [review]
Hey @ChrisKian !!!

I have some doubts about the current implementation. Because I see it, every time a user is updated, all the segmets are reindexed right? I think we can have a huge performance issue here.

Could you provide a test with this PR also?

What do you think?

Thanks!!

**Comment by ChrisKian** [comment]
Hey @cgoncas,
To answer your question, yes all segments are reindexed upon user updates.  I don't love the solution either, but I'm not sure if there is a way around this.

For example, if I update one or more fields for a user, I don't know which **_new_** segmentsEntries the user now matches without iterating through all of them.  My only context is which the user currently matches (before the update).

It's possible to create a solution to **_delete_** any segmentsEntryRel entries **_which no longer match the user_** after a user update, but this is "less correct" compared to the current solution, although has a much lower performance cost.  This also doesn't help us if the user initially matched no segmentEntries, but now does after being updated; there will be no new segmentsEntryRel entry after the update.

I could also potentially filter by companyId, but this makes no difference for single-instance bundles.

Please let me know how to proceed.  I will create test(s) for the solution type you think works best.  Thanks!

**Comment by cgoncas** [comment]
Hey @ChrisKian !!

And what do you think about delete all segmentsEntryRel of the user, so you force calculation until the job runs the reindex?

Thanks!!!

**Comment by ChrisKian** [comment]
Resent with changes here: https://github.com/liferay-tango/liferay-portal/pull/2160

**Pull request closed without merging**
