### PR TITLE
LPS-137428 Test automation related to LPS-90588: As a Marketer, I want to be able to create a segment when creating a new experience

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-137428](https://issues.liferay.com/browse/LPS-137428): Test Automation
↳ [LPS-90588](https://issues.liferay.com/browse/LPS-90588): As a Marketer, I want to be able to create a segment when creating a new experience

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete! 
All tests are passing, except for ExperienceDropdownWithNoSegmentsUserWithNoPermisisons, that has a ingnore annotation due to bug [LPS-138108](https://issues.liferay.com/browse/LPS-138108).

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
