### PR TITLE
LPS-125752 Fix test testGetSegmentsEntryIdsWithContextCriterionAndDefaultUser: The context-only segment should match for guest users

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
https://issues.liferay.com/browse/LPS-125752

The context-only segments don't work after [LPS-122643](https://issues.liferay.com/browse/LPS-122643) changes.

To solve this regression, I am reverting original https://github.com/liferay-tango/liferay-portal/commit/55c756f3122768eb0fae7cac18e4485736ec2092 check that is located in the context evaluation section (see my first commit https://github.com/liferay-tango/liferay-portal/commit/cc78342633b220046852b1ae51556238eaa1dfac) and I am moving it to the model evaluation section.

See the new changes in the second commit https://github.com/liferay-tango/liferay-portal/commit/0e0f9c7684aeb26c4eb0d713fa977fe737b77095. I have added this check in the `oDataRetriever.getResultsCount` call only.
https://github.com/liferay-tango/liferay-portal/blob/0e0f9c7684aeb26c4eb0d713fa977fe737b77095/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/internal/provider/BaseSegmentsEntryProvider.java#L266-L289

If context is null or SIGNED_IN is not set, I am executing the call to the `oDataRetriever.getResultsCount` because the caller can set a context but without adding the SIGNED_IN parameter.
(For example see this call in the headless code: https://github.com/liferay-tango/liferay-portal/blob/985126786959cb024dc2083697ea461964df7ffc/modules/apps/headless/headless-admin-user/headless-admin-user-impl/src/main/java/com/liferay/headless/admin/user/internal/resource/v1_0/SegmentResourceImpl.java#L69-L129 , the SIGNED_IN parameter is not set)

I have also fixed the test testGetSegmentsEntryIdsWithContextCriterionAndDefaultUser, see last commit: https://github.com/liferay-tango/liferay-portal/commit/0e0f9c7684aeb26c4eb0d713fa977fe737b77095

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:tango

**Comment by darquesdev** [comment]
Hi @jorgediaz-lr, before reviwing, let me ask you, have you tried just changing this line in [BaseSegmentsEntryProvider:256](https://github.com/liferay/liferay-portal/blob/3ef038d75e130859154b9afb3a8b2c9fad11bd87/modules/apps/segments/segments-service/src/main/java/com/liferay/segments/internal/provider/BaseSegmentsEntryProvider.java#L256)?:

from

```java
if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN))) {
	return false;
}
```

to

```java
if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN))) {
	return matchesContext;
}
```

**Comment by jorgediaz-lr** [comment]
Hi @darquesdev 

I didn't try that solution, I think it could be fine.

However, I would also change:
`if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN))) {`
to
`if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN), true)) {` or `if (!MapUtil.getBoolean(context, Context.SIGNED_IN, true)) {`

If Context.SIGNED_IN is not present inside the context, perhaps it is better to not assume that the user is not logged out.
(for example, see the headless code that is setting the context but without adding the SIGNED_IN param)

**Comment by darquesdev** [comment]
> However, I would also change:
> if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN))) {
> to
> if (!GetterUtil.getBoolean(context.get(Context.SIGNED_IN), true)) { or if (!MapUtil.getBoolean(context, Context.SIGNED_IN, > true)) {
>
> If Context.SIGNED_IN is not present inside the context, perhaps it is better to not assume that the user is not logged out.
> (for example, see the headless code that is setting the context but without adding the SIGNED_IN param)

That sounds good, but I'd rather use a different PR and the current one just to solve the bug

**Comment by darquesdev** [comment]
note you should initialize the `matchesContext` variable and check if `SIGNED_IN` param is actually set

```java

		if (context != null) {
			boolean matchesContext = false;

			if (Validator.isNotNull(contextFilterString)) {
				try {
					matchesContext = oDataMatcher.matches(
						contextFilterString, context);
				}
				catch (PortalException portalException) {
					_log.error(portalException, portalException);
				}

				if (matchesContext &&
					contextConjunction.equals(Criteria.Conjunction.OR)) {

					return true;
				}

				if (!matchesContext &&
					contextConjunction.equals(Criteria.Conjunction.AND)) {

					return false;
				}
			}

			if (context.containsKey(Context.SIGNED_IN) &&
				!GetterUtil.getBoolean(context.get(Context.SIGNED_IN))) {

				return matchesContext;
			}
		}


```

**Comment by jorgediaz-lr** [comment]
Hi @darquesdev

Thanks for your comments, I have updated the commits of this PR with your ideas:

- https://github.com/liferay-tango/liferay-portal/commit/b415bc46971f04b8558c1be6951611b84f6667a8 - We have context-only segments for guest users that doesn't work if we return false
- https://github.com/liferay-tango/liferay-portal/commit/a38112c7e9e69b4ac808a1d193e6350517536301 - If we have context but SIGNED_IN is not set, we cannot assume this is a guest user

I wasn't able to test it and I will be on PTO the rest of the week. 
Please have a look to it before forwarding, thank you!

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:tango

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
LGTM @jorgediaz-lr. Tests run successfully and the issue is no longer reproducible 😃 
Forwarding 🚀

**Comment by darquesdev** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
Thanks, @darquesdev!

**Pull request closed without merging**
