### PR TITLE
LPS-149434 Convert default experience into a regular one

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
Since the default segments experience is not in the database at this moment and we are adding special code to manage the cases where we are using it, we decide to convert it in a regular segments experience. 

[Link to the issue](https://issues.liferay.com/browse/LPS-149434) 

Proposed Solution
========
Adds the necessary code to **LayoutModelListener** in **layout-page-template-service** to create the default segments experience when we are creating a content page, collection page, master page template entry, display page template entry and page template entry.

Also use the default experience in the database instead of using **SegmentsExperienceConstants.ID_DEFAULT**.

This pull also updates cases for:
- Staging
- Translations
- Segments Experience selector
- Tests 
- Segments Experiments
- Headless
- Content Page Editor

I don't know if I made the correct fix for 6dd321f and [878dbf9](https://github.com/liferay-tango/liferay-portal/pull/2334/commits/878dbf9806353e3b5bd17332912f53694f4561f1). The first one is related with test fixes and the second one is related with priorities.

Thanks!!

**NOTE:** We are working on analyze and fix the related errors in ci: test: echo, more details: https://github.com/ealonso/liferay-portal/pull/3157
**Updated 04/04/2022** no tests failures related with the changes on this pr for ci: test: echo routine, more details https://github.com/ealonso/liferay-portal/pull/3157#issuecomment-1087750296

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @CarlosBrichete !!

Do you mind take a look to this PR, executing all the test related with Experiences and A/B Testing?

Thanks!!

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by cgoncas** [comment]
Hey @CarlosBrichete !!

A/B Testing is failing, may you to take a look?

Thanks!!!

**Comment by CarlosBrichete** [comment]
Hey @ealonso @cgoncas , I've just tested manually all the failing tests in the branch and they are all working, they are just failing in CI for non-related reasons to experiences. All other tests related to experiences are passing, so LGTM :)

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @ealonso !!

The failing tests don't fail locally, so another test should create something not very beautifull, I will take a look :)

Thanks!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
