### PR TITLE
LPS-139257 content dashboard assert sync ac

### PR DESCRIPTION
**Pull request by lucassantanasantos**
LPS-139257 content dashboard assert sync ac
https://issues.liferay.com/browse/LPS-139257

### CODE REVIEW

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
@lucassantanasantos The test is failing in CI, please review. Thanks!

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
