### PR TITLE
LPS-152541 Add new method to obtain the roleSegmentationEnabled and the segmentationEnabled values for the system

### PR DESCRIPTION
**Pull request by Stephy6**
### Motivation

We need to create a new custom JSP for Segmentation Service, that helps the user to define the configuration.

### Proposal 

All the code will be done in https://github.com/liferay-tango/liferay-portal/pull/2538, but we are going to start send code needed to the story, so we don't have a rellay big PR to be reviewed and merged.

This first PR only include the new methods roleSegmentationEnabled and  segmentationEnabled and their tests.

### How to test it

No functional changes, and integration tests have been included.

### CODE REVIEW

**Comment by Stephy6** [comment]
Hi @cgoncas ! I've added the providers for Segments Configuration, could you help with the tests please?

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1387401_1593

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
