### PR TITLE
LPS-124236 As a content author, I want to be able to export data to an .xls file

### PR DESCRIPTION
**Pull request by YurenaC**
As per our latest discussion I applied changes requested by Brian Chan:
- Changes added in order to remove the ugly imports. 
- Also simplifying generated excel testing

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
