### PR TITLE
LPS-137149 Test autom. Handle errors

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-137149
LPS-134760

**Motivation:**
Test Automation for "I want to know why Page Audit is not working so that I can fix the causes"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz, this test is failing: CheckErrorDetailsDisplayedInvalidApiKey. Can you review it? Thanks!

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
