### PR TITLE
LPS-129897 Allow select site and organization roles to create segments

### PR DESCRIPTION
**Pull request by robertoDiaz**

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:stable

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Hey @robertoDiaz !!!

In Tango, in order to make the review process easier we have created this small guideline of good practices when a PR is sent to the Team: https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews

Thanks!!!

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:tango

**Comment by robertoDiaz** [comment]
ci:reopen

**Pull request closed without merging**
