### PR TITLE
LPS-121906 Migrate v2 usages in segments/segments-web

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
The <clay:management-toolbar-v2 /> tag has been replaced with the
<clay:management-toolbar /> tag (which uses clay v3).

**Test plan:** 
1. Navigate to **People > Segments**
2. Create a new segment. 
3. Add an organization and a segment in it. 
4. Click on the organization's "Select" button => modal is openend with the management toolbar present in `select_organizations.jsp`
5. Click on the segments's "Select" button => modal is openend with the management toolbar present in `select_segments_entry.jsp`
6. Save the segment. The list of segments corresponds to `view.jsp`, where there is the third management toolbar replaced. 

Everything should work like before. 

Screenshot 2021-02-24 at 11 02 46

/cc @jonmak08 @julien @markocikos

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Reviewing 😃

**Review by dgarciasarai — COMMENTED** [review]
Hey @ambrinchaudhary, thank you for replace the management toolbar to the new one in `segments-web`. Changes seems ok to me 😄 But I saw a few things that I think they are not working perfectly. I don't know if the problem is in our module or it's a base one from the Clay component.

1. Management toolbar returns this console log warning when searching something:
```
Warning: Encountered two children with the same key, `_com_liferay_segments_web_internal_portlet_SegmentsPortlet_keywords`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.
    in form (created by Search)
    in div (created by ClayContainer)
    in ClayContainer (created by ClayContainerFluid)
    in ClayContainerFluid (created by Search)
    in div (created by Search)
    in Search (created by SearchControls)
    in SearchControls (created by ManagementToolbar)
    in div (created by ClayContainer)
    in ClayContainer (created by ClayContainerFluid)
    in ClayContainerFluid (created by ClayManagementToolbar)
    in nav (created by ClayManagementToolbar)
    in ClayManagementToolbar (created by ManagementToolbar)
    in ManagementToolbar
```
2. We are not able to search a part of a word (for example "fe" from "Liferay"), and doesn't return any result. If you search something with the first letters ("li") the modal retrieves results 🤷‍♀️ I don't know why
3. The blue section when searching, with the filters applied or the word searched, changes from "Liferay" to "liferay" when searching "liferay" (you can see this behavior at the end of the video)

I think that this issues happen in all the management toolbars: `view.jsp` (segments list), select organization and select segments.

Let me know if you need more information. Thanks!

https://user-images.githubusercontent.com/15845466/109134772-b1dee600-7756-11eb-8703-091ed49e9c22.mov

**Comment by ambrinchaudhary** [comment]
Hi @dgarciasarai, thank you very much for your detailed comments. 

1. Where exactly did you get this warning? I've tested all the scenarios and did not see it. Did you run a `clean deploy` just to be sure? 
2. Behaviour is the same that before. It looks like the search engine here is only looking for words that **start** with that keyword. But this only happens when searching for segments, not for organizations. So you must check your search configurations I guess. 

Screenshot 2021-02-25 at 14 43 20

3. I have not being able to reproduce it either. Anyway, looks like minor and I wouldn't consider it blocking.

**Comment by dgarciasarai** [comment]
Hey @ambrinchaudhary,

> 1. Where exactly did you get this warning? I've tested all the scenarios and did not see it. Did you run a clean deploy just to be sure?

I run clean deploy in the segments-web module, and now seems that the Loader is complaining 😞  I have the ant all up-to-date (March 1). Do you know why this is hapenning?



> 2. Behaviour is the same that before. It looks like the search engine here is only looking for words that start with that keyword. But this only happens when searching for segments, not for organizations. So you must check your search configurations I guess.

Ok, we will take a look :)
 
> 3. I have not being able to reproduce it either. Anyway, looks like minor and I wouldn't consider it blocking.

Ok, for me it's a strange behavior, seems like it's reloading/searching twice: one with "Liferay" and then with "liferay".

I tried this things with master and it's not happening. Maybe it's something related with the new management toolbar or the way it's initialize? The Loader is working, I can search for any word event if it's in the middle of the word and the it's not doing twice searches... What do you think? Thanks!

**Comment by ambrinchaudhary** [comment]
Hi @dgarciasarai, I just run ant all with this changes and I do not get the loader errors, but I get the same results I posted before. 
Ping me via slack when you have some time and we can check it

**Review by dgarciasarai — APPROVED** [review]
I reviewed this in a call with @ambrinchaudhary and all migrated management toolbars works fine. We saw that the warning (about the keywords) appears sometimes but it's not blocking at all. Also, the user item selector is not in `segments/segments-web`, it is in `users-admin/users-admin-item-selector-*` so it will be migrated in another pull request.
Let's forward it! 😄 ✅

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
