### PR TITLE
LPS-137221 Test fix Page Audit view success

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-137221

**Motivation:**
This PR fixes these testcases:
- PageAudit#NavigateToSecondLevel
- PageAudit#PageWithNoIssues
- PageAudit#AssertProgressBar

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
