### PR TITLE
LPS-117272 Remove blogs support for Content Performance Panel

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Blogs are no longer intended to show Metrics.

**Proposed Solution**

Delete analytcs-report-blogs-impl module

**How to test it**

1. Create a Display Page Template for Blogs (and mark it as default)
2. Create a Blog
3. View the blog.
4. The Content Performance Panel button is no longer visible.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
