### PR TITLE
LPS-166759 The Preview of Versions should include the title when it is not a DPT.

### PR DESCRIPTION
**Pull request by cgoncas**
Continuation of https://github.com/liferay-tango/liferay-portal/pull/2972.

We have to include the parameter _showTitle_ set to true in order to render the title propertly

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
hi @cgoncas!
Using `exclusive` for window state throws many JS errors, also styles are missing. Do you know why? 🤔 

With `pop_up` this does not happen...

image

**Comment by beltranrengifo** [comment]
Asked in [this thread](https://liferay.slack.com/archives/C03CAD9EF/p1667812259721049)

**Comment by beltranrengifo** [comment]
Hi @cgoncas !
After some research, it's no possible to add the theme CSS and JS to the exclusive window state.

One option is to use `undefined`, which helps to hide the control menus and manually hide the product menu in case the user has it open. It works but feels somehow _hacky_.

Other option could be add a custom param to the url and use it for handle this case and its specific needs.

I'm pushing a commit with the first option so we can discuss over it.

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> Hi @cgoncas ! After some research, it's no possible to add the theme CSS and JS to the exclusive window state.
> 
> One option is to use `undefined`, which helps to hide the control menus and manually hide the product menu in case the user has it open. It works but feels somehow _hacky_.
> 
> Other option could be add a custom param, along with the `pop_up` state, to the url and use it for handle this case and its specific needs. The recommendation from the thread is to use `pop_up` because it is indeed intended also for this use case. The naming maybe is not super fortunate, it sounds very specific...
> 
> I'm pushing a commit with the first option so we can discuss over it. [5907eba](https://github.com/liferay-tango/liferay-portal/commit/5907eba14bee62743cb45b0c054f68a2c7aa8f9d)

Hey @beltranrengifo !!

I have added the parameter showTitle set to true in the URL and use POP_UP state again.

Let me know what do you think :)

Thanks!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
