### PR TITLE
LPS-176077 Create EventInput Component for events

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This PR contains is a continuation of [this](https://github.com/liferay-tango/liferay-portal/pull/3269) one. It adds the capability to edit Downloaded Documents and Media event segments. Right now its pending to add the Time modifiers.
[Link to the task](https://issues.liferay.com/browse/LPS-176077)
[Link to the story](https://issues.liferay.com/browse/LPS-173020)

Proposed Solution
========
The solution consist in create a new component, EventInput, to handle the changes in the Downloaded Documents and Media events segments. This component renders the has/has-not, Select Document, at-least/at-most and number of times inputs. The time input is pending to be added. 

Steps to Verify:
----------------
1. Connect to AC to DXP.
2. Go to AC -> Segments -> Dynamic Segment -> Events -> Downloaded Documents and Media and create a segment.
3. Go to Applications Menu -> Control Menu -> Job Scheduler -> Scheduled Jobs -> (page 2) -> Click on Run Now for the CheckIndividualSegmentsMessageListener to sync up the segments between AC and DXP 
4.  Go to ProductMenuPanel -> People -> Segments
5. Edit the segment created in AC by clicking on it and clicking on the toggle button
6. Click on the select button that opens a modal with the DXP documents. 
7. Change the at least/at most and integer inputs.

* By the moment this PR doesn't contains any test, they will be added in another one

Screenshots:
----------------
Screenshot 2023-02-24 at 16 54 02

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]
Hi @Stephy6 ,

I have made some changes in the code. Could have a look and check that it is working properly please? 🙏 

I've been testing and looks like everything is working.

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
It works fine for me @claraizquierdo

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:reevaluate:1297401_6457

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_9398

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_9398

**Comment by Stephy6** [comment]
ci:forward

**Pull request closed without merging**
