### PR TITLE
LPS-117062 Add info and metrics actions to each dashboard item

### PR DESCRIPTION
**Pull request by carloslancha**
Added info and metric actions on each dashboard item.

Steps to reproduce:

- Create Display Page for Web Content
- Create a categorized web content (Audience/Stage) with the created Display Page
- Go to Global Menu > Content Dashboard

image

### CODE REVIEW

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @carloslancha!!

There are few cosmetic changes that need to be done before sending this pull request. If you think it is ok, I will add it to this pull, with some Unit test.

Thanks!

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
continues in https://github.com/liferay-tango/liferay-portal/pull/20

**Pull request closed without merging**
