### PR TITLE
LPS-148315 Avoid render AnalyticsReportsPortlet every time a content page is loaded (the same way we did inLPS-119068). We will load the react component only when the button is clicked.

### PR DESCRIPTION
**Pull request by cgoncas**
## Motivation
Improve Content Performance Panel performance, avoiding lags and unneeded network requests
**This PR tries to address the FOURTH task: _Avoid loading the content performance panel portlet every time a page is loaded_**

[Jira issue](https://issues.liferay.com/browse/LPS-148315)
[Spike in Jira](https://issues.liferay.com/browse/LPS-148151)

### Avoid  render AnalyticsReportsPortlet every time a content page is loaded (the same way we did inLPS-119068). We will load the react component only when the button is clicked.

Instead execute the dispach of the JSP in the includeBotton function we need to render the React component directly, saving a lot of time.

@claraizquierdo @Stephy6 , I need you to include all the JSP code we currently have in the JSP in the **AnalyticsReportsProductNavigationControlMenuEntry** class.

If you have any doubt, let me know.

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @claraizquierdo and @Stephy6 !!

I have updated the PR, but I still get:
Screenshot 2022-04-01 at 10 10 53

Could you help me find the problem?

Thanks!!!

**Comment by cgoncas** [comment]
> Hey @claraizquierdo and @Stephy6 !!
> 
> I have updated the PR, but I still get: Screenshot 2022-04-01 at 10 10 53
> 
> Could you help me find the problem?
> 
> Thanks!!!

Hey @claraizquierdo and @Stephy6  I think I have fix it. Do you mind to review this PR again?

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
> > Hey @claraizquierdo and @Stephy6 !!
> > I have updated the PR, but I still get: Screenshot 2022-04-01 at 10 10 53
> > Could you help me find the problem?
> > Thanks!!!
> 
> Hey @claraizquierdo and @Stephy6 I think I have fix it. Do you mind to review this PR again?

Sorry guys, it is still broken :(

**Comment by claraizquierdo** [comment]
> > > Hey @claraizquierdo and @Stephy6 !!
> > > I have updated the PR, but I still get: Screenshot 2022-04-01 at 10 10 53
> > > Could you help me find the problem?
> > > Thanks!!!
> > 
> > 
> > Hey @claraizquierdo and @Stephy6 I think I have fix it. Do you mind to review this PR again?
> 
> Sorry guys, it is still broken :(

jejejeje, no problem. I will try find where the problem is :)

**Comment by cgoncas** [comment]
> > > > Hey @claraizquierdo and @Stephy6 !!
> > > > I have updated the PR, but I still get: Screenshot 2022-04-01 at 10 10 53
> > > > Could you help me find the problem?
> > > > Thanks!!!
> > > 
> > > 
> > > Hey @claraizquierdo and @Stephy6 I think I have fix it. Do you mind to review this PR again?
> > 
> > 
> > Sorry guys, it is still broken :(
> 
> jejejeje, no problem. I will try find where the problem is :)

Hey @claraizquierdo !!

I can't move the JSP code to the COntrolMenu class without move the JS that we have in view.jsp, we were trying to keep 2 separate pulls, one that moves the code to the JSP, and another one to refactor de component in order to render all the HTML, but I think this won't be possible :(.

**Comment by cgoncas** [comment]
Close this PR, we will try to move the html from the JSP to the React component first in https://github.com/liferay-tango/liferay-portal/pull/2349

**Pull request closed without merging**
