### PR TITLE
LPS-152541 Add warning in segments instance settings

### PR DESCRIPTION
**Pull request by claraizquierdo**
### Motivation

We want to show an alert in Segments Service in Instance Settings when those configurations are disabled in System Settings, so that the user is aware why these configurations are not clickable in Instance Settings.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-152541)

### Proposal 

This is a continuation of https://github.com/liferay-tango/liferay-portal/pull/2538. We have added two alerts to the jsp file to inform the user that segmentation and assign roles by segment are disabled in system settings.

### How to test it

1. Activate FF (add feature.flag.LPS-152541=true in portal-ext.properties)
2. Go to system settings -> Segments -> Segments Service and disable segmentation and assign roles by segments
3. Go to Instance Settings -> Segments -> Segments Service And check that the to alerts are shown.
4. Go to system settings -> Segments -> Segments Service and enable segmentation and assign roles by segments
5. Go to Instance Settings -> Segments -> Segments Service And check that the to alerts are not present.

### Screenshots

Captura de pantalla 2022-06-29 a las 10 39 19

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — COMMENTED** [review]
Hi @claraizquierdo !
Everything looks fine, but after I rebased with my styles PR from yesterday, which is on its way to master branch, I see some CSS classes where missing. I added them in the last commit, would you mind to review it? Also I resolved some conflicts in segments_configuration.jsp
Thxs!

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hi @beltranrengifo , thank you for rebasing and fixing. It looks good to me :) If it passes the CI I will forward it.

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
