### PR TITLE
LPS-134059 Duplicate tag on the dashboard

### PR DESCRIPTION
**Pull request by 4lejandrito**
- When multiple sites are created and the same tag name is used in two or more of them, the tag filtering in the content dashboard can be confusing. 
 - To avoid that confusion, the site name where each tags belongs to is added in brakets. 
 - Filtering can be done by tagId or tag name (only when ids are not provided)

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
On hold until Julia is back from PTO and we decide how to proceed with this.

**Comment by YurenaC** [comment]
After Julia's decision about how to proceed with this story, keeping the original behaviour and only fixing the labels duplicity in the filtering menu, due clarity, I proceed to close this PR and create a new one that only contains the needed changes

**Pull request closed without merging**
