### PR TITLE
LPS-150315 Adds new method to encapsulate the logic of default segments experience creation

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
Since we are going to convert the default experience in a real experience as part of https://issues.liferay.com/browse/LPS-147302, we want to have an easiest way of adding the default segments experience for a layout.

[Link to the issue](https://issues.liferay.com/browse/LPS-150315) 

Proposed Solution
========
Creates a new method on **SegmentsExperienceLocalServiceImpl** called **addDefaultSegmentsExperience** to allow create the default segments experience for a layout. Also, updates the SegmentsExperienceLocalServiceTest to use the new method.

Thanks!!

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Review by cgoncas — APPROVED** [review]
Hey @ealonso !!!

What an amazing job have you done!!!

Thanks a lot!!

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
