### PR TITLE
LPS-151399 Fix content performance panel in content dashboard

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Can't open Metrics sidebar at Content Dashboard
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151399)

Proposed Solution
========
Check that the DOM element exists before using it

Steps to Verify:
----------------
1. AC connection
2. Display Page Template
3. Web Content associated with this DPT
4. Go to Content Dashboard (Menu > Applications > Content > Content Dashboard)
5. At Content, click on toggle menu > click 'View Metrics'

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
