### PR TITLE
LPS-164390 GetContentDashboardItemVersionsResourceCommand Tests

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-164390)

Adds tests for GetContentDashboardItemVersionsResourceCommand

## Change summary:

* Test that we retrieve the default number of versions (10)
* Test that if we pass the versions to retrieve, that number will be retrieved
* Test that if a content dashboard item is not versionable, nothing is retrieved

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Hey @jkappler !!!

We can't add blogs as dependency for the test, we must use a Custom ContentDashboardItem implementation :(

Thanks!!!

**Comment by jkappler** [comment]
Will do so @cgoncas, thanks

**Comment by jkappler** [comment]
ci:reopen

**Pull request closed without merging**
