### PR TITLE
LPS-163569 Remove dslQuery usage from ContentPageLayoutEditorDisplayContext

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR is to not use dslQueries in Context layers because the lack of security that appears.
[LPS-163569](https://issues.liferay.com/browse/LPS-163569)

Proposed Solution
========
The proposed solution consists in create a new finder that provides the data needed when using the dslQueries and use the localService methods generated to retrieve the information.

Steps to Verify:
----------------
1. Connect to Analytics Cloud
2. Open the A/B Testing panel
3. Create a new Variant and add things to it (Heading e.g) and publish it
4. Check that the edit mode works correctly
5. Check that the Experience Selector shows the Experiences names in view mode

### CODE REVIEW

**Comment by jkappler** [comment]
@Stephy6, changes look good! But we would need to split the second commit in 3. One for service.xml, the other for the local service and the other for the auto generation. We'll take a look together on Monday

**Comment by Stephy6** [comment]
> @Stephy6, changes look good! But we would need to split the second commit in 3. One for service.xml, the other for the local service and the other for the auto generation. We'll take a look together on Monday

Ok @jkappler , Thanks a lot!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:test:bundle

**Comment by Stephy6** [comment]
@CarlosBrichete can you take a look?

**Comment by jkappler** [comment]
@CarlosBrichete, just a bit more context, last time this was tried it caused https://issues.liferay.com/browse/LPS-144971

**Comment by jkappler** [comment]
@Stephy6, all looks good ❤️. Let's wait until the test finish and if all looks good we can forward

**Comment by CarlosBrichete** [comment]
LGTM! Thx guys :)

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
