### PR TITLE
LPS-153507 | Test Automation for LPS-95412: Members count is not updated when conjunctions are changed

### PR DESCRIPTION
**Pull request by rafaellajordao**
Hi! :)
This pr is corresponding to this ticket: [LPS-153507](https://issues.liferay.com/browse/LPS-153507)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by Luizcarlosqueiroz — APPROVED** [review]
Good to go! :smile:

**Comment by rafaellajordao** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Pull request closed without merging**
