### PR TITLE
LPS-162823 Test Automation for Add the View Action to the Version History for Documents and Media

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-165457](https://issues.liferay.com/browse/LPS-165457): Test Automation for LPS-162823:
↳[LPS-162823](https://issues.liferay.com/browse/LPS-162823): Add the View Action to the Version History for Documents and Media

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete! If the results are ok, would you mind forwarding?

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
