### PR TITLE
LPS-124170 Read languageIds parameter and save it in DB when the entity is created/updated/duplicate and write languageIds in the JSONObject we send to the frontend.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need to send the field `languageIds` in every experience (create, update and duplicate) since it will be read in order to list the available languages for the experience.

**How to test it**

Future integration test will be provided, but for now you only can test this pull request as part of https://github.com/liferay-tango/liferay-portal/pull/821.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
