### PR TITLE
LPS-122877 No data is shown in the graph when first "In use" vocabulary hasn't got any contents

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**:
This [bug](https://issues.liferay.com/browse/LPS-122877) is related with this [acceptance criteria](https://issues.liferay.com/browse/LPS-114987) which is not met: 
> Given the content audit graph
> When there are not contents with Audience's categories
> Then the X axis will show just one bar per each one of Stage's categories representing the total number of contents labeled with those categories
> And the title will be Content per Stage 

Actually, there's a test integration that covered this acceptance criteria, but the assertion was wrong. [See first commit](https://github.com/liferay-tango/liferay-portal/pull/579/commits/383f2d43013d5b3cd0503929ca8429f155c8c55d).

**Solution**:
Include an aggregation when calling the Liferay Search Framework to group by the second vocabulary so that we have 2 aggregations in just one call:
1. firstVocabularyCategories / secondVocabularyCategories
2. secondVocabularyCategories

[See second commit](https://github.com/liferay-tango/liferay-portal/pull/579/commits/b2739d6644087a1ae6fd5927dc9d583fac7bebbf)
 
**How to test it**:
Running the integration test `com.liferay.content.dashboard.web.internal.portlet.test.ContentDashboardAdminPortletTest.testGetPropsWithMissingCategorizedJournalArticleWithAssetCategory`

Or following the steps:
1. Go to Site Global > Categorization > Categories
2. Create one category "Stage 1" for the vocabulary Stage
3. Create one category "Audience 1" for the vocabulary Audience but do not assign it to any content
4. Go to Site Liferay > Content & Data > Web Content
5. Create a web content and categorize it with Stage 1
6. Go to Applications Menu > Content Dashboard
7. If there's no content for Audience, it should show data for Stage, regardless the order of the "in use" vocabularies. This should happen too in the case that Audience has no categories created at all.

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
Really nice pull!!!

LGTM 👍

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
