### PR TITLE
LPS-116987

### PR DESCRIPTION
**Pull request by RitaSilveira**
JIRA Ticket:
LPS-136987
LPS-134749

Motivation:
Access the most relevant information through the side panel

### CODE REVIEW

**Comment by RitaSilveira** [comment]
https://issues.liferay.com/browse/LPS-134749, cc: @CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by RitaSilveira** [comment]
fixed

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:close

**Pull request closed without merging**
