### PR TITLE
LPS-143294 Disable ExperienceSelector when Simulator panel is active

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira bug ticket](https://issues.liferay.com/browse/LPS-143294)

### Motivation
To avoid incongruences between the selected experience in the Simulation panel and the new Experiences dropdown, we decided to disable this selector when the Simulator is active.

This way, we separate interactions between the actual app and the Simulator app.

### Changes
Inside the `ExperienceSelector` we listen the `SimulationMenu:openSimulationPanel` and `SimulationMenu:closeSimulationPanel` events to disable the dropdown button vía CSS.

### Steps

- Create a Content Page
- Create different segments for different users
- Create experiences for those segments
- Open the simulation panel

Expected: the `ExperienceSelector` is disabled and the user has no way to change the experience rendered behind the overlay.

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
The code works perfect and it's so clear. Only found one thing, that when you handleDisable you also need to set the aria-expanded attribute to false:

`dropdownToggle.setAttribute('aria-expanded', 'false');`

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
