### PR TITLE
LPS-152541 New Bind Action for Segments Company Configuration

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

We need to create a new custom JSP for Segmentation Service, that helps the user to define the configuration.

### Proposal 

All the code will be done in https://github.com/liferay-tango/liferay-portal/pull/2538, but we are going to start send code needed to the story, so we don't have a big PR to be reviewed and merged.

This fourth PR includes the new JSP under a _FF LPS-152541_

### How to test it

1. Activate FF (add feature.flag.LPS-152541=true in portal-ext.properties)
2. Go to Instance Settings
3. Go to Segments
4. Click the last Segments Service Configuration.

### Screen caps

Captura de pantalla 2022-06-23 a las 10 37 29

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Sorry guys!! The FF was not working, I have updated the PR

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hey @cgoncas , everything seems to work fine except that after saving the configuration I'm being redirected to the Instance Settings main page instead of staying in the segments configuration form. Is it a desired behavior?

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
