### PR TITLE
LPS-169180 Track Custom Asset Metrics for Info Items not Web Contents, Blogs or Documents & Media

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Add asset metrics to Info Items not Web Contents, Blogs or Document & Media Display Page Templates
[Link to story or ticket](https://issues.liferay.com/browse/LPS-167982).

When DPT where developed we didn't implement the code needed to sent metrics to AC. 

Proposed Solution
========

Add JS code descibed in AC documentation: https://learn.liferay.com/analytics-cloud/latest/en/touchpoints/events/tracking-events.html to the botton of every DPT that doesn't display WC, Blog or D&M asset. 

This solution is based in the one proposed for blogs in https://github.com/liferay-tango/liferay-portal/pull/2970

Steps to Verify:
----------------
1. Create a Object with Site Scope
2. Create a display page template for the Object and mark it as default
3. Create an Object
4. Add a Button to a content page that points to the Display page Template of the Object and publish it.
5. Click the button
7. Check the event are sent to AC
Captura de pantalla 2022-11-23 a las 14 36 38
8. Go to AC (Events), check the object view has been increased (creating a event analysis for assetViewed)
Captura de pantalla 2023-03-15 a las 14 31 33

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by Mikellorza — APPROVED** [review]
I was able to verify it and It is working fine.

Thanks for share with me the solution :)

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Review by claraizquierdo — COMMENTED** [review]
Ei @cgoncas, I'm able to see the petition to AC sending the correct event but then I don't see the views the AC report:
Captura de pantalla 2022-11-23 a las 9 25 52

Maybe I'm doing something wrong.

**Comment by Mikellorza** [comment]
@cgoncas 

Two things:

1. I have tested it again with your last modification and now I can not see the title of the object instance, is it ok? 
image
2. When I go to the DPT directly typing the URL in the browser I can not see the customEvent.

**Comment by cgoncas** [comment]
> @cgoncas
> 
> Two things:
> 
> 1. I have tested it again with your last modification and now I can not see the title of the object instance, is it ok?
> 
> image
> 
> 2. When I go to the DPT directly typing the URL in the browser I can not see the customEvent.

Hey @Mikellorza !!

1. Now the title should be added.
2. I think it has been sent in the other event:

Captura de pantalla 2022-11-23 a las 14 37 42

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
