### PR TITLE
LPS-130692 Refactor content dashboard testcase teardown

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-130692](https://issues.liferay.com/browse/LPS-130692)

**Motivation**:
Refactor teardown for PageAudit.testcase : Use developed macro to teardown categories

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:test:ci

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
