### PR TITLE
LPS-137413 Add missing stubs for Content Performance

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-137413](https://issues.liferay.com/browse/LPS-137413)

**Motivation**:
Add missing stubs for Content Performance

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Comment by Luizcarlosqueiroz** [comment]
ci:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
