### PR TITLE
LPS-146432 Organization segments used in Experiences are not updated after organization creation

### PR DESCRIPTION
**Pull request by jkappler**
Motivation
=======
This PR solves this bug related to the Segments
[LPS-146432](https://issues.liferay.com/browse/146432)

Proposed Solution
========
The proposed solution consist in not adding the userId to the search context. This is because we will only retrieve those elements created by the user

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
@Luizcarlosqueiroz, I don't think the tests that fail are related to the changes, still, launching tango tests again

**Review by cgoncas — APPROVED** [review]
LGTM!!!!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
See https://github.com/liferay-tango/liferay-portal/pull/2763. If related PR gets stuck again, I'll send directly to BChan

**Pull request closed without merging**
