### PR TITLE
LPS-119372 [Content Dashboard] Fix minor issues.

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**
- Author name is not shown in the info panel
- When the web content doesn't have a display page, the language flags are not listed.

**Proposed solution**

LANGUAGES

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
