### PR TITLE
LPS-117489 Update author item selector with list and card views

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Authors and content marketing team members might need filtering to quickly find content by author or group of authors. With this pull request, we update the user item selector with two new display types: list and user cards.

**Screenshot**

LPS-120295

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @cgoncas , can you review these changes? 🙏 Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Review by cgoncas — COMMENTED** [review]
LGTM 👍 ❤️

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
