### PR TITLE
LPS-143891 Remove unnecessary feature flag for collection's variations

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
Remove previously created feature flag, defined in https://issues.liferay.com/browse/LPS-101448 and https://issues.liferay.com/browse/LPS-141797

Proposed Solution
========
Review the current master code and remove the feature flag and legacy behaviour 

Steps to Verify:
----------------
The expected behaviour should be the same as in https://issues.liferay.com/browse/LPS-101448 and https://issues.liferay.com/browse/LPS-141797 by default, without activating any feature flag.

Change summary:
---------------
* Remove unnecessary feature flag

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:stable

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
@YurenaC I have removed the FF from the .jsp. I've also added Beltran as a reviewer because he is the one who added it to the frontend and I want to be sure that I don't miss anything.

**Review by beltranrengifo — APPROVED** [review]
Hi! I load the new UI without any problem 🎉

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test.sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!

You have deleted the FF, and you have not deleted the code from the JSP: https://github.com/liferay/liferay-portal/blob/7224f6d5d6ed0f84ce795e43d4b57e5db4bd2fa8/modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry.jsp#L47

Thanks!!

**Comment by YurenaC** [comment]
> Hey @YurenaC !!
> 
> You have deleted the FF, and you have not deleted the code from the JSP: https://github.com/liferay/liferay-portal/blob/7224f6d5d6ed0f84ce795e43d4b57e5db4bd2fa8/modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry.jsp#L47
> 
> Thanks!!

Thank you @cgoncas!!

@claraizquierdo @beltranrengifo  we are so blind haha

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
> > Hey @YurenaC !!
> > You have deleted the FF, and you have not deleted the code from the JSP: https://github.com/liferay/liferay-portal/blob/7224f6d5d6ed0f84ce795e43d4b57e5db4bd2fa8/modules/apps/asset/asset-list-web/src/main/resources/META-INF/resources/edit_asset_list_entry.jsp#L47
> > Thanks!!
> 
> Thank you @cgoncas!!
> 
> @claraizquierdo @beltranrengifo we are so blind haha

When I reviewed this that code was not there.
Maybe a push -f bring that back? 🤔

**Comment by claraizquierdo** [comment]
@YurenaC @cgoncas something strange has happened because I don't see my commits in the PR.

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:stop

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
