### PR TITLE
LPS-132509 Delete BaseContentDashboardItem and minor refactor

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Include Blogs in the Content Dashboard
[LPS-132509](https://issues.liferay.com/browse/LPS-132509)

Proposed Solution
========
Delete the code in BaseContentDashboardItem so we can use it as a Util class in all the places where this code is repeated.

Steps to Verify:
----------------
No functional changes (just a refactor), all tests should still be green

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1307401_2043

**Comment by cgoncas** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!!

Could you help me find the diference with [GetContentDashboardItemsXlsMVCResourceCommandTest.testServeResource](https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/AXIS_VARIABLE=1/32987//testReport/com.liferay.content.dashboard.web.internal.portlet.action.test/GetContentDashboardItemsXlsMVCResourceCommandTest/testServeResource)

Thanks!!!

**Comment by YurenaC** [comment]
I am currently taking a look at this PR @cgoncas ;)

**Comment by YurenaC** [comment]
> 

The extension with the new code is "fileName.pdf" instead of just "pdf"
I'll take a proper look at the code asap and try to find where the problem lies

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> > 
> 
> The extension with the new code is "fileName.pdf" instead of just "pdf" I'll take a proper look at the code asap and try to find where the problem lies

I think I found it, I forget to get the extension from the fileName.


Thanks a lot :)

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1337401_1068

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_2213

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_2526

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_2526

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_2526

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
