### PR TITLE
LPS-124415 [Back] Create traffic source detail representation for SOCIAL traffic

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**:
This PR provides a representation for the second level of social traffic: a list of referring social media with the correspoding traffic.

```json
{
       "name":"social",
       "share":"90,0",
       "title":"Social",
       "referringSocialMedia":[
          {
             "name":"twitter",
             "trafficAmount":1165,
             "title":"Twitter"
          },
          {
             "name":"other",
             "trafficAmount":30,
             "title":"Other"
          }
       ],
       "value":5532,
       "helpMessage":"This is the number of page views generated by people coming to your page from social sites."
    }
```
  

**Solution**:
Add a new property to `SocialTrafficChannelImpl` that represents the referring social media and add update the toJSONObject accordingly to include the new property.

**How to test it**:
Unit tests have been included

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
