### PR TITLE
LPS-150720 Call JS Component Directly from the Control Menu button.

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

Performance problem with Experiments Panel

### Proposed Solution

Call the JS Component directly, so we don't need to run the JSP dispach (It takes a lot of time)

### How to test it

1. Connect to AC
2. Go to a Content Page (for example Home)
3. Open the A/B Testing Panel
4. Everything works fine.

### CODE REVIEW

**Comment by liferay-tango** [comment]
Hey @beltranrengifo !!

I think I have updated the PR with the changes we talked about:

1. Fix pathToAsset variable
2.  Use the right variable in the frontend code for the namespace

After that, I still have one doubt:

We use to redirect the user to a URL with the segmentsExperienceId (this property was set in the data-url of the icon):

Could you help me find how should we do it with our JS approach.

Thanks you

**Comment by beltranrengifo** [comment]
About this

> We use to redirect the user to a URL with the segmentsExperienceId (this property was set in the data-url of the icon):

I remember lots of incongruences when migrating `analytics-reports-web` from jsp to React due to a redirect, a refresh, the portal was doing just because a data-attr. Could this be the same?
In that case, that extra render was a pain

**Comment by beltranrengifo** [comment]
Rebased w/ master, clean unwanted commit, add a fix for the tmpl icon && force push

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

Could you rebase this PR with master, so we fix the conflict.

Thanks!!

**Comment by beltranrengifo** [comment]
Sure!

**Comment by beltranrengifo** [comment]
Rebased and force pushed
I've added a commit I had locally fixing some prop types error

**Comment by beltranrengifo** [comment]
@claraizquierdo @cgoncas 
I see the panel working properly, as far as I can understand

**Comment by claraizquierdo** [comment]
> @claraizquierdo @cgoncas I see the panel working properly, as far as I can understand

Yeah! Me too @beltranrengifo . I'm getting an error when creating a new AB test, but I think it is not related, am I right Beltrán, @cgoncas ? I think the the AC team was performing some changes that are affecting the creation of new test.

**Comment by claraizquierdo** [comment]
@cgoncas what should we do with this WIP commit https://github.com/liferay-tango/liferay-portal/pull/2462/commits/fd6816657c3c5e3518d5b7299fbd1f62b276f4f1 ?

**Comment by cgoncas** [comment]
We shopuld swu

> @cgoncas what should we do with this WIP commit [fd68166](https://github.com/liferay-tango/liferay-portal/commit/fd6816657c3c5e3518d5b7299fbd1f62b276f4f1) ?

We should squash all the WIP, fix typo, fix namespace commits ...

**Comment by claraizquierdo** [comment]
> We shopuld swu
> 
> > @cgoncas what should we do with this WIP commit [fd68166](https://github.com/liferay-tango/liferay-portal/commit/fd6816657c3c5e3518d5b7299fbd1f62b276f4f1) ?
> 
> We should squash all the WIP, fix typo, fix namespace commits ...

Perfect. I'm going to do that :)

**Comment by claraizquierdo** [comment]
@cgoncas , could you have a look at the commits after my rebase? Tell if you think that something else should be changed.

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1257401_4012

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1307401_4110

**Comment by beltranrengifo** [comment]
@Luizcarlosqueiroz could you help us with this CI errors? Do you think are they related to the pr?

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @beltranrengifo !
I'm running `ci:test:tango` again because many tests were not executed because apparently we had a served down.
For the one failing at `ci:test:relevant`, they are failing at regular suite too.

**Comment by beltranrengifo** [comment]
Okay @Luizcarlosqueiroz 
Good to know! Let's hit the CI again

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1327401_5232

**Comment by beltranrengifo** [comment]
ci:reevaluate:1327401_5232

**Pull request closed without merging**
