### PR TITLE
LPS-139881 Test Fix PageAudit#PageAuditDisplayPage

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket**:
LPS-139881

**Motivation**:
This PR fixes these testcases:
- PageAudit#PageAuditDisplayPage

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz Please, check the SF in this pull, it seems to be failing.

**Comment by Luizcarlosqueiroz** [comment]
I made changes in code using Github, and was not able to get those changes to local. So I'm closing this PR and sending a new one using https://github.com/liferay-tango/liferay-portal/pull/1655.

**Pull request closed without merging**
