### PR TITLE
LPS-135132 Site settings inheritance issue

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @drewbrokke,

Can you guys please review this fix? I've tried to explain what's going on in https://github.com/liferay-tango/liferay-portal/pull/1371/commits/5516f481fb37b4b398c0997bb5420c95cdb3f9bd. But let me know if you need more clarification.

Thanks!

**Comment by drewbrokke** [comment]
Hey @4lejandrito, thank you for this. Overall I think this is ok, but I'd like to explore an option that doesn't involve string manipulation. My preference would be to prevent the undesired `pid` from being submitted in the first place. To me it does not make sense that the instance-scope configuration `pid` would ever be involved with the form in Site Settings, so I'd like to fix that anyways. I'll look at this more tomorrow.

**Comment by 4lejandrito** [comment]
Hi @drewbrokke thanks for looking into this. 

I agree with you that the undesired `pid` should not be there in the first place. I tried to tackle the problem that way but I ended up having to modify `ConfigurationModel` and I soon broke many unexpected things. 

I then decided to apply the "naive" fix to help you guys understand the problem and hopefully fix it in the right way.

Thanks!

**Comment by drewbrokke** [comment]
See https://github.com/4lejandrito/liferay-portal/pull/554

**Comment by 4lejandrito** [comment]
Merged in https://github.com/brianchandotcom/liferay-portal/pull/104229.

**Pull request closed without merging**
