### PR TITLE
LPS-137411

### PR DESCRIPTION
**Pull request by RitaSilveira**
Jira ticket : https://issues.liferay.com/browse/LPS-137411

Motivation: Test stubs for Personalization tests in Poshi

### CODE REVIEW

**Comment by RitaSilveira** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
hey @RitaSilveira, the SF commit is really weird, deletes a lot of stuff and the SF is not passing. Please review it (if you need help just tell me)

**Comment by RitaSilveira** [comment]
fixed

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
