### PR TITLE
LPS-145045 Test Fix of DuplicateExperience

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-145045](https://issues.liferay.com/browse/LPS-145045)

**Failing Test**:
- ExperienceCreateExperience#DuplicateExperience

**Motivation**:
Text changed after [LPS-141225](https://issues.liferay.com/browse/LPS-141225)

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
