### PR TITLE
LPS-178452 Revert code of Migrate the Segmentation Editor to the Control Panel Epic

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
It has decided to stop segmentation unification, so for that, as a tango team we have decided to revert the code from master and move it to the branch with name LPS-154036-unified-segmentation-experience. The reason to do that, is to prevent problems in the future. The code involved in this PR is related to the epic [LPS-166954-Migrate the Segmentation Editor to the Control Panel](https://issues.liferay.com/browse/LPS-166954) 

[Link to story or ticket](https://issues.liferay.com/browse/LPS-178496)
[Link to technical task](https://issues.liferay.com/browse/LPS-178074)
[Link to technical subtask](https://issues.liferay.com/browse/LPS-178452)

Proposed Solution
========
1. Revert all code from master below FF related to the epic: https://issues.liferay.com/browse/LPS-166954

Steps to Verify:
----------------
1. Keep the FF LPS-166954
2. With the administrator, Go to Control Panel / Users  and you won't see the segments management there.
4. Create a regular role called whatever you want and add the following permissions: 

- Segments / GENERAL PERMISSIONS / Access in Site and Asset Library Administration
- Segments / SEGMENTS / Manage Segments Entries

5. Add a user and add the above role to the user.
6. With the user created, go to Site Administration / People  and you will see the segments management there. 
7. Click on segments and you will see a list of segments associated to the scoped site and the Global site.
8. You only have the permissions to manage the segments that you create. So add a segment, then update it and finally delete it.
9. Add the following permissions to the created role:

- Segments / SEGMENTS ENTRY / Delete
- Segments / SEGMENTS ENTRY / Update

10. Update, delete segments created by other users.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
Starting review

**Comment by YurenaC** [comment]
I love ❤️  the commits structure and the messages, it was very easy to review @Mikellorza 😄

**Comment by Mikellorza** [comment]
Hey @CarlosBrichete  and @rafaellajordao ,

As expected we have some tests that are failing because the changes of the PR. What do we proceed with this? Are you going to delete the failing test related with this PR and revert the old ones? .

Let me know.  

Thanks!

**Comment by Mikellorza** [comment]
ci:tango

**Comment by ealonso** [comment]
ci:close

**Comment by ealonso** [comment]
see: https://github.com/liferay-tango/liferay-portal/pull/3342

**Pull request closed without merging**
