### PR TITLE
LRQA-74205 Test Fix for ContentDashboardWithAC#ViewMetricsButtonKebabWhenDocumentHasDPT

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74205](https://issues.liferay.com/browse/LRQA-74205)

**Test(s) failing:**
 * ContentDashboardWithAC#ViewMetricsButtonKebabWhenDocumentHasD

**Error:**
`
 com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class, 'dropdown-menu show')]//*[text()='View Metrics']"
`

**Problem:**
View Metrics button path has changes, therefore, it's not being found.

**Fix:**
Fixed path.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
ci:reevaluate:1257401_2232

**Comment by Luizcarlosqueiroz** [comment]
ci:reevaluate:1257401_2232

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
