### PR TITLE
LPS-152539 | Tests Automation Add a link to the "segmentation disabled" alerts

### PR DESCRIPTION
**Pull request by rafaellajordao**
JIRA Ticket:
[LPS-152539](https://issues.liferay.com/browse/LPS-152539)
↳ [LPS-156783](https://issues.liferay.com/browse/LPS-156783)
Motivation:
Add a link to the "segmentation disabled" alerts

### CODE REVIEW

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 148 out of 182 jobs passed in 1 hour 37 minutes
> Click here for more details.

these failures have nothing to do with the test automation :)

**Review by Luizcarlosqueiroz — APPROVED** [review]
:100: out of :100:!

**Comment by Luizcarlosqueiroz** [comment]
Hey @rafaellajordao! I won't forward now because this other [PR#2625](https://github.com/liferay-tango/liferay-portal/pull/2625#issuecomment-1189406407`) will soon be forward and it might generate conflicts.

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
