### PR TITLE
LPS-129591 Migrate selection modals in content-dashboard modules

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-tango,

Attached is an update for http://issues.liferay.com/browse/LPS-129591.

**Test Plan**:

1. Login to Liferay
2. Click on the **Product Navigation Menu**
3. Go to **Categorization** -> **Categories**
4. Click the `+` to add a new vocabulary
5. Click the `+` of the new vocabulary to add a new category
6. Click on **Application Menu**
7. Click on **Content** -> **Content Dashboard**
8. Go to the **Management Toolbar** -> **Filter and Order** drop down
9. Select **Categories**

content-dashboard

10. Click on the **Product Navigation Menu**
11. Go to **Content & Data** -> **Web Content**
12. Click the `+` and select **Basic Web Content**
13. Under **Categorization**, click the **Select** button for one of the vocabularies you created
14. In the modal window click the `+` to add a new vocabulary
15. Click the **Save** button
16. Select the desired category and click **Done**
17. Click on the **Product Navigation Menu**
11. Go to **Content & Data** -> **Blogs**
12. Click the `+`
13. Under **Categorization**, click the **Select** button for one of the vocabularies you created
14. In the modal window click the `+` to add a new vocabulary
15. Click the **Save** button
16. Select the desired category and click **Done**

web content

17. Click on the **Application Menu**
18. Select the **Global** site
19. Click on the **Product Navigation Menu**
20. Go to **Content & Data** -> **Web Content**
21. Click the `+` and select **Basic Web Content**
22. Under **Categorization**, click the **Select** button for one of the vocabularies you created
23. Select the desired category and click **Done**
24. Add a **Basic Web Content** and click **Publish**
25. Click on the **Application Menu**
26. Select the **Liferay DXP** site
27. Click on the **Product Navigation Menu**
28. Go to **Content & Data** -> **Web Content**
29. Click the `+` and select **Basic Web Content**
30. Under **Categorization**, click the **Select** button for one of the vocabularies you created
31. Select the desired category and click **Done**
32. Add a **Basic Web Content** and click **Publish**
33. Click on the **Application Menu**
34. Click on **Content** -> **Content Dashboard**
35. Go to the **Management Toolbar** -> **Filter and Order** drop down
36. Select **Subtype...**

web content

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by markocikos — APPROVED** [review]
LGTM!

**Comment by 4lejandrito** [comment]
Hi @jonmak08,

I've tested this and can't get it to work (tried with both Firefox and Chrome):

**Without your changes:**

Screenshot 2021-05-04 at 10 48 30

**With your changes:**

Screenshot 2021-05-04 at 10 50 10

I tested it on top of a31589a97b13d747dcc409156d4e67907ead0bfd.

Thanks!

**Comment by kresimir-coko** [comment]
I'm having the exact same error message when trying to migrate the modal inside [edit_asset_category_cp_display_layout.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/commerce/commerce-product-asset-categories-web/src/main/resources/META-INF/resources/display_layout/edit_asset_category_cp_display_layout.jsp). 
It's probably related as they both have `Category` in their title so they're probably calling [SelectCategory.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/asset/asset-categories-selector-web/src/main/resources/META-INF/resources/js/SelectCategory.es.js#L45) which might be the root cause.

**Comment by markocikos** [comment]
Hey all! Sorry for not noticing this before. This PR should be on hold, until https://github.com/liferay-echo/liferay-portal/pull/4436 is merged. @4lejandrito If you prefer it, feel free to close and we'll reopen it later.

**Comment by 4lejandrito** [comment]
Hi @markocikos,

I'll close it for now to keep our inbox smaller. Please reopen when necessary.

Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-tango/liferay-portal/pull/1153

**Pull request closed without merging**
