### PR TITLE
LPS-104509 Use flush instead the callback of the transactional commit.

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Not all variants are deleted from the database after removing AB Test

**Steps to reproduce it**

1. Create segment seg1
2. Create page cp1
3. Create exp1 with seg1
4. Create A/B Test test1 with exp1
5. Create variants v1 and v2
6. Delete test
7. There are still some experiences in the DB (select * from lportal.SegmentsExperience;)

**Proposed solution**

A transactional exception is being call because we are updating the experiences (changing the priority of the ones left) at the same time we are deleting them.

So we need to flush the deleted experience, and run all the changes in only one transaction.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Hi @cgoncas , is it ready to review?

**Comment by cgoncas** [comment]
> Hi @cgoncas , is it ready to review?

I will wait until tests are green.

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Close, I have renamed the branch, because it has a bad ticket.

**Pull request closed without merging**
