### PR TITLE
LRQA-74597 Test fix for Content Dashboard tests related to labels format

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LRQA-74597](https://issues.liferay.com/browse/LRQA-74597)

**Test(s) failing:**
 * ContentDashboardAuditGraph#AuditGraphApplySecondFilter
 * ContentDashboardAuditGraph#AuditGraphFilterByGrayBar
 * ContentDashboard#FilterTheListOfContentsByTag
 * ContentDashboardAuditGraph#AuditGraphClickOnBarDeleteOneFilter
 * ContentDashboardAuditGraph#AuditGraphClickOnBar
 * ContentDashboardAuditGraph#AuditGraphSaveFiltersAfterSwapping
 * ContentDashboard#SaveFiltersAfterEditing

**Error:**
`    
java.lang.Exception: Element is not present at "//li[contains(@class,'tbar')]//span[contains(@class,'label-item-expand')][starts-with(.,'Category:Audience 1')]"
`

**Problem:**
Poshi can't find the labels.

**Fix:**
 Label has an extra space after ":", as a consequence of bug LPS-151750.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
