### PR TITLE
LPS-163792 Add pagination page link for Web Contents

### PR DESCRIPTION
**Pull request by beltranrengifo**
[See original PR](https://github.com/liferay-tango/liferay-portal/pull/2862)

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1307401_4782

**Comment by beltranrengifo** [comment]
ci:reevaluate:1307401_4782

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forwar

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
rebased & push -g

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by jkappler** [comment]
@beltranrengifo, @claraizquierdo, conflicts resolved

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by jkappler** [comment]
Sent to BChan directly https://github.com/brianchandotcom/liferay-portal/pull/124067

**Pull request closed without merging**
