### PR TITLE
LPS-139257 open content dashboard and assert content performance itens

### PR DESCRIPTION
**Pull request by lucassantanasantos**
LPS-139257 open content dashboard and assert content performance itens
https://issues.liferay.com/browse/LPS-139257

### CODE REVIEW

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @lucassantanasantos , the SF is not passing please review. Also, modify the commit message. Thanks :)

**Pull request closed without merging**
