### PR TITLE
LPS-129897 Allow select site and organization roles to create segments #1079

### PR DESCRIPTION
**Pull request by robertoDiaz**
Motivation
=======
Right now it is not possible to select site or organization roles
(https://issues.liferay.com/browse/LPS-129897)

Proposed Solution
========
Add a new User Group Role selector (called "Site and Organization Role Selector") to allow users select this role. To do so, I had to create new ItemSelectorCriteria for this types and adapt current logic

The selector Role has been renamed as "Regular Role"

Screencaps
========

Screenshot 2021-04-15 at 19 05 42

How to test it
========
1. Create a user and assign Site Role: Site Administrator
2. Create a Segment and add the Site and Organization Role Criterion.
3. Check that the number of members are correctly updated.

https://user-images.githubusercontent.com/5776822/114910666-74c1d680-9e1e-11eb-875c-647aaac2188f.mov

### CODE REVIEW

**Comment by robertoDiaz** [comment]
ci:test:sf

**Comment by robertoDiaz** [comment]
ci:test:relevant

**Comment by robertoDiaz** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @robertoDiaz !!

This PR good really good to me.

@4lejandrito !! what do you think?

Thanks!!!

**Comment by 4lejandrito** [comment]
I'll review tomorrow if that's ok.

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Hey @robertoDiaz and @4lejandrito !!

I have updated the description in order to make easier review this PR :)

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
