### PR TITLE
LPS-170054 Add error page when an invalid operation occurs

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
For the Segmentation Initiative, we want to introduce a new error page for when an invalid operation occurs for created segments.
[Link to the task](https://issues.liferay.com/browse/LPS-170054)
[Link to the story](https://issues.liferay.com/browse/LPS-168143)

Proposed Solution
========
The proposed solution consists in use an Empty Result message by using its taglib and also adding a ClayButton so it redirects to the SegmentsApp when the error message is shown. Right know we're using a mocked variable 'noSegments' to know when an invalid operation occurs until we have the backend needed for that and the message will appear even when we add a new segment.

Steps to Verify:
----------------
1. Go to People -> Segments.
2. Click on '+' to add a new Segment.
3. Check that the message error appear.

Screencaps
---------------
Screenshot 2022-12-01 at 10 25 39

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
Great work! Everything seems to be working fine 🎉

**Comment by claraizquierdo** [comment]
ci:reevaluate:1307401_5674

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango-acceptance

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1287401_5390

**Comment by claraizquierdo** [comment]
@CarlosBrichete , @Luizcarlosqueiroz , @rafaellajordao , could you have a look at the failing tests please?

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo, the tests failing are integration test, so a backend dev should take a look on them :)

**Comment by claraizquierdo** [comment]
> Hey @claraizquierdo, the tests failing are integration test, so a backend dev should take a look on them :)

Thank you very much @CarlosBrichete

**Comment by Stephy6** [comment]
ci:test:sf

**Pull request closed without merging**
