### PR TITLE
LPS-141706 Improve AB test description styles

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-141706)

Proposed Solution
========
We have set the padding left to 0 in order to have more space for the test details. Moreover, in the design we don't have that padding: https://www.figma.com/file/BodTnJ55QzOPhltwsdVbuG/LPS-132404-Tango-Side-panels?node-id=14%3A12242

When we have a very long word that will overflow, it will break into another line.

Steps to Verify:
----------------
1. At Product Menu, click on 'A/B Test' icon to open sidebar > Click on 'Create Test'
2. At modal, set any 'Test Name' > set a really large 'Description' > 'Save'

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Review by beltranrengifo — APPROVED** [review]

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
