### PR TITLE
LPS-137435 Test Autom. for to able access through a link to Analytics Cloud segments details | Segmentation

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137435](https://issues.liferay.com/browse/LPS-137435)

Tests Add:
- RedirectToSegmentPageAC
- ShoudNotRedirectToSegmentPageAC
- RedirectToSegmentPageErrorAC

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
