### PR TITLE
LPS-117306 | Segment criteria for custom fields of type number (decimal or integer) cannot be compared as numbers

### PR DESCRIPTION
**Pull request by ricardocousolr**
Hi @darquesdev,

I'm sending a new pr because some commit messages in #28 had typos. 

I've addressed the sorting issue and added the required tests. 

Since there was some repeated code in the tests, I refactored it into a single auxiliary method. Feel free to revert if you'd rather keep it explicit. 

Thanks!

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
SF is failing.

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
https://github.com/liferay-tango/liferay-portal/pull/46

**Pull request closed without merging**
