### PR TITLE
LPS-152539 Add breacrumb to Assign Roles warning

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

Add breacrumb to Assign Roles warning

### Proposed Solution

Use the clay:stripe tag with a link when the user has permission to view the configuration URL.

We have found a problem though, it is not possible to use the clay:alert tag and avoid the ":", we will talk with Susana about that problem and will try to find a solution.

### How to tests it

1. Log in with the user test
2. Go to Roles > Regular Roles
3. Select a Role
4. Click in Assigness > Segments
5. A warning is shown with a link to the Instance Settings.

### Screencaps

1. With Permissions
Screenshot 2022-05-19 at 15 03 45

6. Without Permissions

Screenshot 2022-05-19 at 15 03 24

7. Navigation Video

https://user-images.githubusercontent.com/5776822/169313247-ec59c76c-4a53-4959-a966-6aefb53ea748.mp4

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @CarlosBrichete and @Luizcarlosqueiroz !!!

could you take a look to the posh I test. The Fail is related with this PR.

Thanks!!!

**Comment by Luizcarlosqueiroz** [comment]
Hey @cgoncas !
The test is failing because the "Assigning roles by segment is disabled" in System Settings, but the warning is informing that the user must enable it at Instance Settings, not at System Settings.

**Comment by cgoncas** [comment]
Hey @Luizcarlosqueiroz !!

Do you mind to change the test and add the commit to this PR, so we can send this change to master?

Thanks!!!

**Comment by YurenaC** [comment]
Starting the review :)

**Comment by YurenaC** [comment]
LGTM

**Review by YurenaC — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by liferay-tango** [comment]
ci:test:sf

**Comment by liferay-tango** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
