### PR TITLE
LPS-134875 Test Autom. Categories in Facets

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-134875
LPS-118293

**Motivation:**
Test Automation for "Avoid internal categories to show in facets and results in public searches"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , the SF is failing :( Please review it

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete It might have been a conflict problem as I have a PR already merged editing same files.

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
