### PR TITLE
LPS-177013 Add filter by Extensions in D&M

### PR DESCRIPTION
**Pull request by ambrinchaudhary**
Hey Tango team, 

in order to use your filter by extensions in D&M, we had to make some changes in your Item Selector classes. Please review the changes and let us know if you have any doubt. Thanks!! 

Issue: https://issues.liferay.com/browse/LPS-177013

### CODE REVIEW

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:sf

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hello @ambrinchaudhary ,

thank you for your PR. We will have a look at it asap :)

**Comment by ambrinchaudhary** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
Hi @adolfopa ,

I am wondering if from now on make sense to keep the implementation of the item selector in the content dashboard module since it will be a common item selector  directly related to Files. In my opinion it will be moved to the document-library-web module, what do you think?



Thanks for the contribution

**Comment by adolfopa** [comment]
@Mikellorza Sounds good, but we'll move that in a different ticket.

If there's nothing else, could you forward this pr? Thanks!

**Comment by Mikellorza** [comment]
@adolfopa ok, let's wait to @claraizquierdo  to do a double check from a functional perspective . 

Thanks

**Review by claraizquierdo — APPROVED** [review]
Everything seems to be working fine 🎉

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
@CarlosBrichete we already forwarded it but we'd like to double check with you that the tango-tests failing aren't blocking anything

Thanks!

**Pull request closed without merging**
