### PR TITLE
LPS-161017 Add the Download Action to the Version History for Documents and Media

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this PR is to add a Download action for Documents and Media in the Content Dashboard. This allow to download different versions of the document in the info panel.
[LPS-161017](https://issues.liferay.com/browse/LPS-161017)
[LPS-165603](https://issues.liferay.com/browse/LPS-165603)

Proposed Solution
========
The proposed solution consist in implement a new action using the ContentDashboardItemVersionAction class with the download action using the InfoItemFieldValues class.

Steps to Verify:
----------------
1. Add a document, publish it and modify (Title, fileName, description) it a couple of times so it has more versions.
2. Repeat the step one a couple of times.
4. Go to the ContentDashboad, open the InfoPanel for some of the Document
5. Go to the Verions tab, open the ellipsis menu for the versions and download it.
6. Check that the download process works and the fileName is changed when is downloading.

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
