### PR TITLE
LPS-117364 The user icon is not shown in the Content Performance Panel

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Show the user portrait instead of the default avatar in the Content Performance panel.

**Type**

Bug

@cgoncas @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
@cgoncas @darquesdev can you help me with the backend part? I need to inject the `authorImage` (or another name that you prefer, now in frontend side I'm using `authorImage`) to the performance panel to show in the `ClaySticker` component.

Thanks!

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Please @dgarciasarai continue here, thanks!

https://github.com/liferay-tango/liferay-portal/pull/91

**Comment by dgarciasarai** [comment]
Continues in https://github.com/liferay-tango/liferay-portal/pull/91

**Pull request closed without merging**
