### PR TITLE
LPS-166326.2 User with page permissions can't see information at A/B Test sidebar

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This bug is about permissions related to the A/B Testing panel. A user with permissions for updating pages is not able to access the A/B Panel, and it should be.
[Link to the story](https://issues.liferay.com/browse/LPS-166326)

Proposed Solution
========
This PR contains on changing the URL used to get the data related to the A/B Testing panel from ControlPanel type url type to DefaultURL type, as the doesn't look to make sense to use a ControlPanel url when retrieving the data for the A/B Testing Panel. Also, a property has to be added to the SegmentsExperimentPortlet (corresponds to the A/B Testing panel) for being able to use the Default type URL.

Steps to Verify:
----------------
1. Connect to AC
2. Create a User with Update Page permissions
3. Create an AB Test with Test Test (Admin) user
4. Login with the second User
5. Open A/B Test sidebar
6. Check that the A/B Test panel is rendered correctly

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:forward

**Review by cgoncas — APPROVED** [review]
LGTM

**Pull request closed without merging**
