### PR TITLE
LPS-146471  Support Filtering in Content Dashboard for Blogs

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Fix impedibugs found in the review of
[LPS-146471](https://issues.liferay.com/browse/LPS-146471 )

Proposed Solution
========

The subtypes should include the type class too, as blogsEntry doesn't have any subtype-

Steps to Verify:
----------------
Fix

1.
Given The Type filter modal
When the user selects the Blogs Entry option
Then the subtype selected appears as filter box above the Content table in the Content Dashboard, with the format "Subtype: [Blogs Entry]"

2.
Given The Type filter modal
When the user selects the Blogs Entry option + any other subtype/s
Then the subtype Blogs + other subtypes preselected will be shown as a text with the format "[number] Subtypes selected"

When filtering by Type > Blogs + Basic Document, only Blogs appear. However, filtering by Type > Blogs + Web Content works normally

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
Review in progress @cgoncas

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
LGTM

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Review by YurenaC — APPROVED** [review]

**Pull request closed without merging**
