### PR TITLE
LPS-137481 Test Autom. to be able to edit the content of the AB test variant in DXP. | A/B Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137481](https://issues.liferay.com/browse/LPS-137481)

Motivation:
"As a marketer, I can edit AB test variant content on DXP".

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
