### PR TITLE
LPS-157778 Add new frontend tests for content preview in Content Dashboard

### PR DESCRIPTION
**Pull request by claraizquierdo**

### CODE REVIEW

**Review by beltranrengifo — APPROVED** [review]
👍

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:teat:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
