### PR TITLE
LPS-176122 Unifying integration tests

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
Adding needed integration tests after change in LPS-176122 (whose PR was sent to Tango Repo)
[LPS-17622](https://issues.liferay.com/browse/LPS-176122)

Proposed Solution
========
Added test to verify that still works as expected

Change summary:
---------------
- LPS-176122 Add integration test to Segments Vocabulary Configuration's Listener

**Changes requested in** https://github.com/brianchandotcom/liferay-portal/pull/131203#issuecomment-1455857663

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
@CarlosBrichete could you please check that the failing tests are not related and force the forward? 
Thanks!

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Hey @YurenaC, the test failing is a smoke test. You are just adding integration tests, right? I think it is not related, but it is a smoke test so just in case I've run the relevant again. If it doesn't pass, I think you can do a forward-force :)

**Comment by YurenaC** [comment]
ci:forward-force

**Comment by YurenaC** [comment]
ci:forward:force

**Pull request closed without merging**
