### PR TITLE
LRQA-74173 Test fix for ContentDashboardWithAC#ViewMetricsButtonKebabWhenBlogHasDPT

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74173](https://issues.liferay.com/browse/LRQA-74173)

**Test(s) failing:**
 * ContentDashboardWithAC#ViewMetricsButtonKebabWhenBlogHasDPT

**Error:**
`
    com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//button[contains(@class, 'dropdown-toggle') and contains(@class, 'btn-unstyled') and contains(@class, 'btn-monospaced') and contains(@class, 'component-action')]"
`

**Problem:**
The blogs was not being created due the lack of property.

**Fix:**
Added property.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
