### PR TITLE
LPS-143263 Test Fix: Remove unnecessary assert

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-143263](https://issues.liferay.com/browse/LPS-143263)

**Failing Test**:
- PageAudit#AssertProgressBar

**Motivation**:
A macro used in this test changed, making it fail.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete !
I removed the Assert that was being used, as the macro itself already does this check, and was breaking this test.

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
