### PR TITLE
LPS-120513 Error updating segment which contains a non-existing segment

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**:
This PR solves this bug: https://issues.liferay.com/browse/LPS-120513

**Solution**:
Taking into account the that the source type REFERRED might change. Now, every time the segment is updateds the source type is set depending on the previous source and on its criteria type.

**How to test it**:
An new integration test was introduced. On The other hand the manual steps described in the ticket can be followed too.

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Review by cgoncas — APPROVED** [review]
LGTM :)

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
