### PR TITLE
LPS-137483 Test Autom. for review the test details before run the test. A/B Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137483](https://issues.liferay.com/browse/LPS-137483)
[LPS-137406](https://issues.liferay.com/browse/LPS-137406)

Motivation:
As a marketer, I can review the test details before I run the test on DXP;
Remove ignore from ticket LPS-137480;
Add CheckTestChangesInAC testcase.

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1257401_430

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
Hey @mateusralv , 2 tests are failing, please fix:
ABTesting#CheckTestChangesInAC
ABTesting#CheckVariantDeletedInAC

**Comment by mateusralv** [comment]
Hello Carlos, I saw this yesterday, and the same tests work on my PC, I showed Luiz too, and we didn't find out where the error could be.

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
