### PR TITLE
LPS-167892 Show A/B test icon in small screens

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
A/B test icon is not visible in small screen or using big zooms
[Link to story or ticket](https://issues.liferay.com/browse/LPS-167892)

Proposed Solution
========
We have removed the CSS classes of the A/B test icon that were hiding it in small screens.

Steps to Verify:
----------------

- Goto Home page
- Zoom 400% of the page
- Observe the page

Screenshots (optional):
-----------------------
**Using 400% zoom**
Captura de pantalla 2023-03-16 a las 11 12 56

**Using the developer tools to simulate a mobile screen**
Captura de pantalla 2023-03-16 a las 11 12 12

### CODE REVIEW

**Review by p2kmgcl — APPROVED** [review]

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward:force

**Pull request closed without merging**
