### PR TITLE
LPS-131314 Fix category selection modal

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-131314)

Proposed Solution
========
Category selection modal wasn't working ok because the iframe body had the cadmin class. Inspired by what Victor did in this PR: https://github.com/brianchandotcom/liferay-portal/pull/106635/files I decided to do the same and everything works ok now.

Change summary:
---------------
* Fix category selection modal by removing cadmin class from iframe body

Steps to Verify:
----------------

1. Create a web content
2. Create an internal vocabulary (global site)
3. Add a new category to the vocabulary created in the previous step
4. Assign the global category to the web content created in step 1
5. Go to content dashboard
6. Filter by categories
7. Select a category

### CODE REVIEW

**Review by beltranrengifo — APPROVED** [review]
Nice catch 🎉 
I think I should remember this way for overriding classes in this modals...

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
