### PR TITLE
LPS-130917 As an Admin, I want to configure Segments Analytics Cloud settings from Instance Settings 

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Motivation
Currently, segmentation settings exist only at System level, so there’s no way to configure the feature at the instance level.

In order to facilitate the cloud-based products development, we need to make it available at the instance level.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-130917)

Proposed Solution
========
Create a new configuration at instance level, and a provider so we can read the properties from Instance and System level.

Steps to Verify:
----------------
1. Tems of interest and Anonymous users should works after this change (No functional changes)

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
