### PR TITLE
LPS-171842 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# **Element is not present at Collections#FilterCollectionItemsByGlobalCategory**

Hi! :)
This pr is corresponding to this ticket: [LPS-171842](https://issues.liferay.com/browse/LPS-171842)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 175 out of 191 jobs passed in 2 hours 18 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Review by Luizcarlosqueiroz — APPROVED** [review]

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
