### PR TITLE
LRQA-74364 Test fix for for PageAudit tests related to user permissions

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74364](https://issues.liferay.com/browse/LRQA-74364)

**Test(s) failing:**
 * PageAudit#CheckPageBlockedFromIndexingWithoutPermission
 * PageAudit#CheckMissingMetaDescriptionWithoutPermission
 * PageAudit#CheckInvalidCanonicalURLWithoutPermissio

**Error:**
`
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//*[contains(@class, 'lexicon-icon-reload')]"
`

**Problem:**
 Poshi is not navigating to the page. This is because the content page is not published, so it isn't found by the user without the permissions for it.

**Fix:**
 Published the content page.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! The issue for this ticket was fixed. But the test PageAudit#CheckInvalidCanonicalURLWithoutPermission still failing because of another issue ([LRQA-74359](https://issues.liferay.com/browse/LRQA-74359)).

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
