### PR TITLE
LPS-168975 HR_506 SR is not announcing members dialog opens when dialog opens

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation in this story is to make the View Members Dialog more accessible by adding a informative message that is readable by the browser voice over.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-168975)

Proposed Solution
========
The solution consists in adding a ClayAlert component (which is accessible and readable by the browsers screen readers) to the View Members modal when there aren't members within the segment.

Steps to Verify:
----------------
1. Activate JAWS/Voiceover in the browser
2. Go to People -> Segments -> Add a Segment
3. Click on the View Members button
4. Listen and check that the VoiceOver says the message that the modal displays.

Screenshots:
----------------
Screenshot 2023-03-13 at 20 58 57

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Review by p2kmgcl — APPROVED** [review]

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
After our talk with the PEDs team we decided to use this pull request to illustrate that the search container taglib might have an accessibility problem with the empty state.

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
@Stephy6 @claraizquierdo this looks totally unrelated to the PR

**Pull request closed without merging**
