### PR TITLE
LPS-173670 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Element is editable at ContentDashboard#ExportXLSDisabled

Hi! :)
This pr is corresponding to this ticket: [LPS-173670](https://issues.liferay.com/browse/LPS-173670)

### Problem:
The Export XLS button appears editable because the DXP site has elements in the Content Dashboard list.

### Fix:
Test refactoring by adding a step to filter the list by a site that has no elements in the Content Dashboard and check if the button is disabled.

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
> ExportXLSDisabled

these failures have nothing to do with the test correction :)

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 187 out of 197 jobs passed in 1 hour 39 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
