### PR TITLE
LPS-171837 Everything Everywhere all at once

### PR DESCRIPTION
**Pull request by cgoncas**
In this PR we have a full view of the story LPS-171837

### CODE REVIEW

**Comment by claraizquierdo** [comment]
Hi @cgoncas ,

I cannot access the segment editor page for the segments created in AC because when I click in the name it redirects me to AC. I'm also having problems creating a new segment in AC because it doesn't let me select a page. Maybe both problems are related.

**Comment by claraizquierdo** [comment]
Hi @cgoncas ,

I've added a commit adding the rest of event fields available in AC. The only one I could not check was the commented on blog criteria. I've not been able to comment on a blog entry. I will try again later.

I will add a commit with the necessary translations asap.

**Comment by claraizquierdo** [comment]
Hello again @cgoncas,

I've added the translations needed. Feel free to rebase the commits as you like.

I've notice that the assetId received in the frontend is a number and, for the case of downloaded documents and Media, should be the name of the file right?

**Comment by claraizquierdo** [comment]
Hello @cgoncas ,
I've detected a behavior that I don't know if it is expected. In the segments list page , if I click in a DXP segment it opens the segment editor in the same tab, but if I open an AC segment it opens in a new tab. I think that if both option open the segment editor the links should behave the same. This is something that I can contribute but I would like to have your confirmation.

**Comment by cgoncas** [comment]
> Hello @cgoncas , I've detected a behavior that I don't know if it is expected. In the segments list page , if I click in a DXP segment it opens the segment editor in the same tab, but if I open an AC segment it opens in a new tab. I think that if both option open the segment editor the links should behave the same. This is something that I can contribute but I would like to have your confirmation.

Yeahh, only external links should be opened in a different page.

**Comment by cgoncas** [comment]
Everything has been merged

**Pull request closed without merging**
