### PR TITLE
LPS-146471 Filter Blogs by Subtype Blog

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
As we've added blogposts to the Content Dashboard, we need to add a filter to extract only blogposts. As blogs are an asset type with no subtypes, and the current filter works from subtypes, we need to adapt it.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-146471)

Proposed Solution
========
Add the property entryClassName to the subtype filtering, so we can filter by entryClassName too.

Steps to Verify:
----------------
1. Create a Blog and a Web Content
1. Go to the Content Dashboard
1. Filter by Type (WebContent and Blog)
1. The Web Content and the Blog should be listed.
1. Unselect the filter by Web Content
1. Only the blog should be lister

Screenshots :
-----------------------
Screenshot 2022-02-23 at 13 22 38

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!

Could you help me to find the problem with the XLS test?

Thanks!!

**Comment by YurenaC** [comment]
> Hey @YurenaC !!
> 
> Could you help me to find the problem with the XLS test?
> 
> Thanks!!

On my way!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
