### PR TITLE
LPS-139247 change title, url, language and assert

### PR DESCRIPTION
**Pull request by lucassantanasantos**
https://issues.liferay.com/browse/LPS-139247
LPS-139247 change title, url, language and assert

### CODE REVIEW

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
