### PR TITLE
LPS-124170 Create Upgrade process that adds TypeSettings to SegmentExperience

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

As we already add TypeSettings to Segment Experience DB Model, we need to create

**How to test it**

1. Go to GoGo Shell
2. Run upgrade:check
3. The Segment module should be listed
4. Run upgrade:execute
5. The column TypeSettings should be added to Segment Experience

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:1212004_7581

**Comment by dgarciasarai** [comment]
ci:reevaluate:1212004_7581

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:open

**Comment by cgoncas** [comment]
ci:reopen

**Pull request closed without merging**
