### PR TITLE
[TS] LPS-144732 Display "Deleted User" when user doesn't exist

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-144732

Thanks,
Balázs

ps.: one more thing can be considered related to this: Setting "Deleted User" for JournalArticleContentDashboardItem#getUserName

### CODE REVIEW

**Comment by beltranrengifo** [comment]
Hi @balazssk
Thank you for this fix!
My manual testing went fine, we're reviewing the code.

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
@balazssk @YurenaC 
I think we have a test failing ☝️ 
Can you please take a look? 🥰

**Comment by balazssk** [comment]
Hi @beltranrengifo ,
This has something to do with LanguageUtil, not sure of the exact reason, but I'm investigating

**Comment by balazssk** [comment]
Hi @beltranrengifo ,
Think I've got the test fixed with https://github.com/liferay-tango/liferay-portal/pull/2093/commits/20e6b1ee692c4124478c2bf2f570d68c76603cb4

**Comment by balazssk** [comment]
ci:test:sf

**Comment by balazssk** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @balazssk!!

Thanks a lot for the fix, but we have decided we can't use it, because even if the NullPointer is fixed, with the current Content Dashboard code, sometimes the image shown in the info panel is going to be different than the one shown in the content dashboard.

That is the reason we have ended with a different fix in https://github.com/liferay-tango/liferay-portal/pull/2102.

Thanks!!

**Comment by balazssk** [comment]
Cheers @cgoncas ,
I see, indeed the search container and the side panel used different data to calculate the user icons. I do have a question regarding the user data.
Various entities store one or more userName(s) maybe to enhance performance. Removing a User does not update these fields. Could it be a privacy concern if we keep displaying the userName after that User was deleted?

**Comment by cgoncas** [comment]
Hey @balazssk !!!

Probably you are right, but we have keep this behaviour from old times. What do you think about open a PTR to the User and System Management Team?, Probably they have more info about what is the information that could be shown once a user is deleted from the system.

Thanks!!!

**Comment by cgoncas** [comment]
Hey @balazssk !!!

I am going to close the PR, since the fix has been merged on master, and everything work fine.

Thanks!!!

**Comment by balazssk** [comment]
Thanks for the help @cgoncas  !

**Pull request closed without merging**
