### PR TITLE
LPS-176122 Remove duplicated stream usages

### PR DESCRIPTION
**Pull request by JanisZhang**
Forwarded from: https://github.com/liferay-core-infra/liferay-portal/pull/3567
https://issues.liferay.com/browse/LPS-176122

## Investigation
Hi Tango team!

I found this problem when removing the stream usage in _SegmentsContextVocabularyConfigurationModelListener.java_ and _SegmentsContextVocabularyCompanyConfigurationModelListener.java_.

In https://github.com/liferay-core-infra/liferay-portal/commit/c7d2c0bf54eda6be22fdbebd767cd137aac028e1, the companyConfigurationStream was added to SegmentsContextVocabularyConfigurationModelListener.java to listen to the company configuration.

After the author added the company configuration itself listener SegmentsContextVocabularyCompanyConfigurationModelListener.java in https://github.com/liferay-core-infra/liferay-portal/commit/98cd2b1fba02f74ef520dacd76833da379f45407. 
I think companyConfigurationStream is no longer needed.

The same problem occurs in SegmentsContextVocabularyCompanyConfigurationModelListener.java.

## Solution
Remove duplicated stream usage.

Thanks.
Janis

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @YurenaC !!

Could you review this PR and also add a test?

Thanks!!

**Comment by YurenaC** [comment]
Starting review

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
> Hi @cgoncas there are some test available in SegmentsContextVocabularyConfigurationModelListenerTest.java that cover the functionality

yeahh @YurenaC !!

Sorry, I should be more specific, could you update testCreateValidVocabularyForCompanyWhenOtherAlreadyCreatedForOtherCompany, and remove 	@Test(expected = Test.None.class) and create the right asserts with the expected behavior?

We need to have a test with the behavior that @JanisZhang has changed.

Thanks!!

**Comment by YurenaC** [comment]
> 
The onBeforeSave(...) method tested there, executes a few checks before allow the user save that configuration.
Only returns an error when a provided field is empty or the whole provided configuration is already defined. 

In the case that everything looks alright, nothing is returned (so the save execution can continue), that's why I wrote the `@Test(expected = Test.None.class)` to explicitly say that nothing is returned if all goes as expected.

What I mean is that there's nothing returned to check in an assert. 

Something like the follow could be added, but I'm not sure if is worth the effort as it's the same we have right now

`Assertions.assertThatCode(() -> _segmentsContextVocabularyConfigurationModelListener.onBeforeSave(
			pid, properties))
			.doesNotThrowAnyException();`

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> > 
> 
> The onBeforeSave(...) method tested there, executes a few checks before allow the user save that configuration. Only returns an error when a provided field is empty or the whole provided configuration is already defined.
> 
> In the case that everything looks alright, nothing is returned (so the save execution can continue), that's why I wrote the `@Test(expected = Test.None.class)` to explicitly say that nothing is returned if all goes as expected.
> 
> What I mean is that there's nothing returned to check in an assert.
> 
> Something like the follow could be added, but I'm not sure if is worth the effort as it's the same we have right now
> 
> `Assertions.assertThatCode(() -> _segmentsContextVocabularyConfigurationModelListener.onBeforeSave( pid, properties)) .doesNotThrowAnyException();`

Yeahh Yure!!

but this test doesn't define a behavior of the code, do we have any test were we test that once you add a Configuration for the vocabularies if this is not duplicated the configuration is successfully saved?

**Comment by YurenaC** [comment]
Investigating...

**Comment by YurenaC** [comment]
> > > 
> > 
> > 
> > The onBeforeSave(...) method tested there, executes a few checks before allow the user save that configuration. Only returns an error when a provided field is empty or the whole provided configuration is already defined.
> > In the case that everything looks alright, nothing is returned (so the save execution can continue), that's why I wrote the `@Test(expected = Test.None.class)` to explicitly say that nothing is returned if all goes as expected.
> > What I mean is that there's nothing returned to check in an assert.
> > Something like the follow could be added, but I'm not sure if is worth the effort as it's the same we have right now
> > `Assertions.assertThatCode(() -> _segmentsContextVocabularyConfigurationModelListener.onBeforeSave( pid, properties)) .doesNotThrowAnyException();`
> 
> Yeahh Yure!!
> 
> but this test doesn't define a behavior of the code, do we have any test were we test that once you add a Configuration for the vocabularies if this is not duplicated the configuration is successfully saved?

I think this method is somehow called from the portal config persistence module,... let me take a closer look

**Review by cgoncas — CHANGES_REQUESTED** [review]
Hey @JanisZhang !!

After this change, I have detected the following behavior:

1. Go to Sytem Settings > Segments
1. Go to System Scope > Session Property Vocabulary
1. Link a Session property name to a Vocabulary
1. Go to System Scope > Session Property Vocabulary
1. Make the Same association

The expected behavior is to show an error message, but this is never seen.

This is the code that has been deleted in this PR, so I don't think it can be deleted, what do you think @YurenaC .

I have added a video with my review:


https://user-images.githubusercontent.com/5776822/221598994-c58cc751-a8f2-43e4-b75c-966fcb1cd3f5.mp4

**Comment by cgoncas** [comment]
> Hey @JanisZhang !!
> 
> After this change, I have detected the following behavior:
> 
> 1. Go to Sytem Settings > Segments
> 2. Go to System Scope > Session Property Vocabulary
> 3. Link a Session property name to a Vocabulary
> 4. Go to Virual Scope > Session Property Vocabulary
> 5. Make the Same association
> 
> The expected behavior is to show an error message, but this is never seen.
> 
> This is the code that has been deleted in this PR, so I don't think it can be deleted, what do you think @YurenaC .
> 
> I have added a video with my review:

I think this is actually failing on master,  so we will take a look after this code is merged :).

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Comment by JanisZhang** [comment]
Thanks @cgoncas @YurenaC !

**Pull request closed without merging**
