### PR TITLE
LPS-130349 Added test stubs for Experiences using segments based on Segments context

### PR DESCRIPTION
**Pull request by CarlosBrichete**

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
@manoelcyreno

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by manoelcyreno** [comment]
ci:forward

**Pull request closed without merging**
