### PR TITLE
LPS-177421 Update segment vocabulary with same data should not fail

### PR DESCRIPTION
**Pull request by ces-totrinh**
Hi team,
Please help review this PR and leave your feedback. Thanks.
Ticket: https://issues.liferay.com/browse/LPS-177421
cc @locpham97

### CODE REVIEW

**Comment by tototrinh** [comment]
ci:test:sf

**Comment by tototrinh** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
Starting the review

**Comment by YurenaC** [comment]
@CarlosBrichete could you please takes a look as well?

**Comment by YurenaC** [comment]
@cgoncas this is the PR that I mentioned to you this morning
Thanks!

**Review by cgoncas — APPROVED** [review]
Everything LGTM.

**Comment by CarlosBrichete** [comment]
No tests are failing due to this PR @YurenaC! LGTM :)

**Comment by ealonso** [comment]
ci:forward

**Comment by YurenaC** [comment]
@ealonso this PR wasn't forwarded earlier as we were waiting for another one that's closely related to this one. 
I also wanted to add a test and send it just once

**Pull request closed without merging**
