### PR TITLE
LPS-162525 added code to copy experience data from edit layout to visualization layout in add and duplicate segment actions

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
Blank page is displayed when creating or duplicating experience.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-162525)

Proposed Solution
========
It is forced to Copy layout from edit layout to visualization layout in add and duplicate segment actions to fix the problem.

Steps to Verify:
----------------

1. Go to a Content Page > Edit it
2. Create new Experience or copy one of them
3. Go to visualization mode and select the experience that you have created

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @Mikellorza !!

Thanks a lot for the code you have submited, could you explain a little bit further the proposed solution?

I am not able to understand the sentence:

_It is forced to Copy layout from edit layout to visualization layout in add and duplicate segment actions to fix the problem._

Also, in the motivation, could you describe the original problem?

Thanks!!

**Comment by Mikellorza** [comment]
> Hey @Mikellorza !!
> 
> Thanks a lot for the code you have submited, could you explain a little bit further the proposed solution?
> 
> I am not able to understand the sentence:
> 
> _It is forced to Copy layout from edit layout to visualization layout in add and duplicate segment actions to fix the problem._
> 
> In the motivation, could you describe the original problem?
> 
> Also, it is possible to add a test for this problem? Everytime we fix a bug, we should start creating a test to reproduce the original error we are trying to fix :).
> 
> Thanks!!

Hi @cgoncas ,

I have just added a description, sorry because I thought that it was there.  

For the other part, I will try to add a new test for this bug.

Thanks for your feedback!

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:stable

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
Please see https://github.com/liferay-tango/liferay-portal/pull/2852

**Pull request closed without merging**
