### PR TITLE
LPS-150511 Test Autom. for Bug: Can't scroll down in segments editor sidebar

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-150511](https://issues.liferay.com/browse/LPS-150511): Test Automation for LPS-135462:
↳[LPS-135462](https://issues.liferay.com/browse/LPS-135462): Can't scroll down in segments editor sidebar

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Review by CarlosBrichete — CHANGES_REQUESTED** [review]

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
