### PR TITLE
LPS-176396 Generate activityKey part of the AC grammar expression

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Generate activityKey part of the AC grammar expression
[Link to story or ticket](https://issues.liferay.com/browse/LPS-176396)

Proposed Solution
========
We have added the logic for generating the filter part of the query to the ac-grammar library:
` (activities.filterByCount(filter='(activityKey eq ''Document#documentDownloaded#603744226255659006'')',operator='ge',value=1)) `

Steps to Verify:
----------------
1. Set the FF feature.flag.LPS-171722=true feature.flag.LPS-172194=true in your portal-ext.properties
2. Sync your DXP site with AC
3. Create a segment with event criteria in AC
4. In Control Panel -> Job Scheduler -> Scheduled Jobs run the CheckIndividualSegmentsMessageListener job.
5. Go to Control Panel -> Segments and edit the AC segment.
6. Open your Chrome Devtools -> Network tab
7. Click save and check that the query sent in the payload of the http petition is correct

Screenshots (optional):
-----------------------
Captura de pantalla 2023-02-27 a las 21 30 43

### CODE REVIEW

**Review by p2kmgcl — APPROVED** [review]
Works perfectly :smile:

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by Stephy6 — APPROVED** [review]
LGTM 🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
