### PR TITLE
LPS-122643 Avoid checking model segments with guest users

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**

Skip validations when no necessary to improve the segmentation performance: when the current user is the guest user (not sign in user) we don't need check whether the user belong to a segment with model criteria or not because the guest user is not part of the system, indeed the default user is not indexed.  

**How to test it**
A couple of new integration tests have been added

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @slnn!!

Could you run the segments performance tests with this pull?

Thanks!!

/cc @shuyangzhow

**Review by cgoncas — APPROVED** [review]
LGTM 👍

**Comment by darquesdev** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reopen

**Comment by cgoncas** [comment]
Hey @darquesdev!!, wait until @slnn provides the performance results for this pull!!

**Comment by darquesdev** [comment]
Sorry!! of course @cgoncas

**Comment by cgoncas** [comment]
Hey  @slnn!!!

Do you have an estimation about when could we execute these segments performance tests?

Thanks!!!

**Comment by slnn** [comment]
I will try this one tomorrow, as our servers are not free now.

Regards
Lily

**Comment by slnn** [comment]
Hi @cgoncas 

Test result for this pull please see  Test 16 in the doc: https://docs.google.com/spreadsheets/d/163CDSA1SIyLgdcKCBJvSHe5PhEDWt7iyHdu9p-FMsos/edit?usp=sharing

From test results, this pull makes the performance worse than before.

You can find detailed test results and cpu tracing in the folder of Test 16 in: https://drive.google.com/drive/folders/1-5uMisKcmk7DIT3dr1KHWMYZWOw31UZG?usp=sharing

Regards
Lily

**Comment by cgoncas** [comment]
Hey @slnn!!

Could you rerun the segments performance tests with this pull. After the changes in https://github.com/liferay-tango/liferay-portal/pull/489, we would want to check if the results are still very bad?

Thanks!!

/cc @shuyangzhow

**Comment by slnn** [comment]
Hi @cgoncas 

Test result please see Test 18 https://docs.google.com/spreadsheets/d/163CDSA1SIyLgdcKCBJvSHe5PhEDWt7iyHdu9p-FMsos/edit?usp=sharing which contains changes in these pulls:
https://github.com/liferay-tango/liferay-portal/pull/466
https://github.com/liferay-tango/liferay-portal/pull/489
https://github.com/shuyangzhou/liferay-portal/pull/9496

Lily

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
