### PR TITLE
LPS-159250 Refactor ContentDashboard testcase

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Ticket:
[LPS-159261](https://issues.liferay.com/browse/LPS-159261)
↳ [LPS-159250](https://issues.liferay.com/browse/LPS-159250): Audit and refactor tests for ContentDashboard.testcase

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
LGTM! Good job Luiz!

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
