### PR TITLE
LPS-119486 & LPS-113917 Traffic channels with mocks

### PR DESCRIPTION
**Pull request by dgarciasarai**
Mocked data to verify:
1. https://issues.liferay.com/browse/LPS-113917
2. https://issues.liferay.com/browse/LPS-119486

Screenshot 2020-12-04 at 12 40 57

@CarlosBrichete

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Super mock thanks to @darquesdev 🚀 

```json
[
   {
      "name":"social",
      "share":"30,0",
      "title":"Social",
      "referringSocialMedia":[
         {
            "name":"linkedin",
            "trafficAmount":1256,
            "title":"Linkedin"
         },
         {
            "name":"twitter",
            "trafficAmount":1165,
            "title":"Twitter"
         },
         {
            "name":"facebook",
            "trafficAmount":229,
            "title":"Facebook"
         },
         {
            "name":"youtube",
            "trafficAmount":150,
            "title":"Youtube"
         },
         {
            "name":"other",
            "trafficAmount":30,
            "title":"Other"
         }
      ],
      "value":9100,
      "helpMessage":"This is the number of page views generated by people coming to your page from social sites."
   },
   {
      "countryKeywords":[
         {
            "keywords":[
               {
                  "searchVolume":3600,
                  "position":1,
                  "keyword":"liferay",
                  "traffic":2882
               },
               {
                  "searchVolume":755,
                  "position":1,
                  "keyword":"liferay inc",
                  "traffic":855
               },
               {
                  "searchVolume":556,
                  "position":1,
                  "keyword":"liferay portal",
                  "traffic":850
               },
               {
                  "searchVolume":390,
                  "position":1,
                  "keyword":"what is liferay",
                  "traffic":312
               },
               {
                  "searchVolume":390,
                  "position":1,
                  "keyword":"liferay india",
                  "traffic":312
               }
            ],
            "countryCode":"us",
            "countryName":"United States"
         },
         {
            "keywords":[
               {
                  "searchVolume":3600,
                  "position":1,
                  "keyword":"liferay portal",
                  "traffic":2882
               }
            ],
            "countryCode":"es",
            "countryName":"Spain"
         }
      ],
      "name":"organic",
      "share":"30,0",
      "title":"Organic",
      "value":9000,
      "helpMessage":"This is the number of page views generated by people coming from a search engine."
   },
   {
      "referringPages":[
         {
            "trafficAmount":125461,
            "url":"https://www.liferay.com/resources/ebooks/Becoming+a+Digital+Business-4+Common+Enterprise+Challenges+Conquered"
         },
         {
            "trafficAmount":85485,
            "url":"https://www.liferay.com/resources/whitepapers/B2B+E-Commerce+RFP+Kit"
         },
         {
            "trafficAmount":84564,
            "url":"https://www.liferay.com/es/resources/whitepapers/6+Tactics+to+Modernize+Your+Intranet"
         },
         {
            "trafficAmount":5846,
            "url":"https://www.liferay.com/resources/case-studies/materion-case-study"
         },
         {
            "trafficAmount":3521,
            "url":"https://www.liferay.com/web/l/a1-hrvatska-case-study"
         },
         {
            "trafficAmount":2513,
            "url":"https://www.liferay.com/resources/case-studies/excellus-case-study"
         },
         {
            "trafficAmount":2200,
            "url":"https://www.liferay.com/resources/case-studies/terres-inovia-case-study"
         },
         {
            "trafficAmount":1230,
            "url":"https://www.liferay.com/resources/case-studies/vodafone-business"
         },
         {
            "trafficAmount":1100,
            "url":"https://www.liferay.com/web/guest/resources/case-studies/agia"
         },
         {
            "trafficAmount":100,
            "url":"https://www.liferay.com/resources/case-studies/vitality-case-study"
         }
      ],
      "referringDomains":[
         {
            "trafficAmount":17985230,
            "url":"http://youtube.com/"
         },
         {
            "trafficAmount":12218030,
            "url":"http://www.google.com/"
         },
         {
            "trafficAmount":9062949,
            "url":"http://microsoft.com/"
         },
         {
            "trafficAmount":4601453,
            "url":"http://linkedin.com/"
         },
         {
            "trafficAmount":253399,
            "url":"https://www.liferay.com"
         }
      ],
      "name":"referral",
      "share":"25,0",
      "title":"Referral",
      "value":7500,
      "helpMessage":"This is the number of page views generated by people coming to your page from other sites which are not search engine pages or social sites."
   },
   {
      "name":"direct",
      "share":"5,0",
      "title":"Direct",
      "value":3000,
      "helpMessage":"This is the number of page views generated by people arriving directly to your page."
   },
   {
      "countryKeywords":[
         {
            "keywords":[
               {
                  "searchVolume":4400,
                  "position":1,
                  "keyword":"dxp enterprises",
                  "traffic":206
               }
            ],
            "countryCode":"us",
            "countryName":"United States"
         }
      ],
      "name":"paid",
      "share":"5,0",
      "title":"Paid",
      "value":1500,
      "helpMessage":"This is the number of page views generated by people that find your page through Google AdWords."
   }
]
```

**Comment by dgarciasarai** [comment]
Hey @cgonas! These are all the commits front/back and a mock for all traffic channels ready to be used. cc: @carlosbrichete

**Comment by dgarciasarai** [comment]
I don't know why we have conflicts here...I think that maybe is caused because I updated the master branch and change the base for the pull request 🤷‍♀️

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:bundle

**Comment by darquesdev** [comment]
PR with mocks for 7.3.x https://github.com/cgoncas/liferay-portal-ee/pull/56

**Comment by darquesdev** [comment]
ci:test:bundle

**Comment by darquesdev** [comment]
It continues here https://github.com/liferay-tango/liferay-portal/pull/674

**Pull request closed without merging**
