### PR TITLE
LPS-167437 Add aria-label to search and clear search buttons

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Screen reader is announcing the search icon as "Unlabeled 1 Button"
[Link to ticket](https://issues.liferay.com/browse/LPS-167437)

Proposed Solution
========
We have added aria-label to the search and clear search buttons.

Steps to Verify:
----------------

1. Navigate to People > Segments, click the "+" to add a new User Segment
2. Turn on the screen reader
3. Press the Search button of the properties sidebar using the tab key

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango-acceptance

**Review by Stephy6 — COMMENTED** [review]
Hey @claraizquierdo ! LGTM 🎉

**Comment by claraizquierdo** [comment]
ci:reevaluate:1317401_5992

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_6045

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
