### PR TITLE
LPS-173685 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# "No results were found." is not present at ContentDashboard#NoMimeType

Hi! :)
This pr is corresponding to this ticket: [LPS-173685](https://issues.liferay.com/browse/LPS-173685)

### Problem:
The modal should appear empty. But the PNG extension is present.

### Fix:
Refactor the test so that when there are contents the teardown is executed and the verification can proceed correctly.

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by CarlosBrichete — APPROVED** [review]

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 186 out of 197 jobs passed in 2 hours 21 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
