### PR TITLE
LPS-160210 Add WebDAV URL to Info Panel

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-160210)

## Motivation

Add WebDAV URL to the info panel in Content Dashboard.

This PR is a follow up of [the main one](https://github.com/liferay-tango/liferay-portal/pull/2713).
Here we are proposing a Typescript refactor and moving the Specific Fields object to a new component.

#### TO DO
- Group and sort the specific field, as shown in the Figma
- Review units and write some for the new item(s) (webDAV URL, I think that's all, but better review what's being tested and complete if needed)
- Some manual testing before submitting
- Any other improvements or simplifications to the code are welcome

## Proposed Solution

Send URL fields in the SpecificFields section of the infoPanel endpoint:

```
"specificFields": {
    "extension": {
      "title": "Extension",
      "type": "String",
      "value": "png"
    },
    "size": {
      "title": "Size",
      "type": "String",
      "value": "359 KB"
    },
    "web-dav-url": {
      "title": "WebDAV URL",
      "type": "URL",
      "value": "http://localhost:8080/webdav/guest/document_library/tree.png"
    },
    "latest-version-url": {
      "title": "Latest Version URL",
      "type": "URL",
      "value": "http://localhost:8080/documents/d/guest/tree-png"
    }
  }
```

Support URL fields in the Content Dashboard Info Panel Section

## Screencaps

image

## How to

- Upload some files to the DL
- Navigate to the CD
- Open the info panel
- Check for the components in the details section

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
> 

It cannot work with bad formed commit names, LOL

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by liferay-tango** [comment]
ci:test:relevant

**Comment by liferay-tango** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
