### PR TITLE
LPS-131598 Discard variant doesn't close the edit mode

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
cc @victorg1991

**Comment by victorg1991** [comment]
You probably want to remove it also from here: https://github.com/liferay/liferay-portal/blob/bb75dc4da56cb35043b567b191545931c453e0f3/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/types/config.d.ts#L99

Apart from that LGTM :) 👏

**Comment by sandrodw3** [comment]
> You probably want to remove it also from here: https://github.com/liferay/liferay-portal/blob/bb75dc4da56cb35043b567b191545931c453e0f3/modules/apps/layout/layout-content-page-editor-web/src/main/resources/META-INF/resources/page_editor/types/config.d.ts#L99
> 
> Apart from that LGTM :) 👏

Done! Thanks 🥰

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
