### PR TITLE
LPS-156964

### PR DESCRIPTION
**Pull request by elocamp**

### CODE REVIEW

**Comment by fabiocampelo07** [comment]
ci:test:sf

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by fabiocampelo07** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hi @fabiocampelo07 ! Thank you for submitting your PR 🤗 . 

In the Tango team we follow this guide for the pull requests: https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews. Please, follow the guide as possible :)

I think that this file is maintained by the Echo Team, maybe @victorg1991 can also have a look at the changes and decide if we need to add some tests or not so that this bug doesn't happen again.

**Comment by victorg1991** [comment]
Hey @fabiocampelo07 !

I have tested that and it seems that i works for the simple case, but not for others, so the solution is not complete. Can you try the following:

- Create an Experience
- Go to page editor
- Open Experience's menu > New Experience > Set a name and select the segment "Anyone" segment > Save
- **Go back to the default experience and add a heading fragment to the page**
- **Select the other experience**
- Navigate to somewhere else in portal
- Delete the experience
- Go to page editor > Open Experience's Menu
- Delete the experience

This also fails. I believe the problem is that we don't load the fragmentEntryLinks that belong to the default experience when we delete the other. Could you take a look?  If you need help don't hesitate to reach us and ask for it :)

Thanks!

**Comment by elocamp** [comment]
Hello, everyone! :smile: 

Thank you both @claraizquierdo and @victorg1991 for this explanation.
I'll be reviewing the solution and send another PR according with the guide, so i'm gonna close this one.

**Pull request closed without merging**
