### PR TITLE
[TS] LPS-135808

### PR DESCRIPTION
**Pull request by crodriguezy**

### CODE REVIEW

**Comment by YurenaC** [comment]
@crodriguezy with the current modification a message will be logged only if the portal is set to debug or warn mode.
Previously the error message was logged in any case (debug, warn, info, fatal,... mode), should't that behaviour be kept?

**Comment by crodriguezy** [comment]
Hi @YurenaC , sorry I didn't mention this change was previously discussed in https://issues.liferay.com/browse/PTR-2558.
Please let me know if I've misunderstood the conclusions and we should be **always** logging a **warn** message no matter which log level is configured. 
Thanks for reviewing it!

**Comment by YurenaC** [comment]
Hi @crodriguezy,
Thanks for your quick response and the extra bit of information.

What I understand reading https://issues.liferay.com/browse/PTR-2558  is that a warning message will be always logged instead of the error one (so, no relevant info is lost) and if we are in debug mode, the exception will be additionally logged too.

Let me know your thoughts! :)

**Comment by crodriguezy** [comment]
Hi @YurenaC ,

Ok, now re-reading the expected results of the PTR I think what you say makes sense. Please see the additional commit I just added to achieve what we actually want: to always log a **WARN** message instead of **ERROR**. I just configured `BaseSegmentsEntryProvider ` class, let me know if you think it is worth it to include the full package (`com.liferay.segments.internal.provider)` for future issues related.

On the other hand, the complete stack trace will only be logged in case DEBUG leve is configured on purpose.

Thanks again!

**Comment by YurenaC** [comment]
Hi @crodriguezy,
I meant something like this:

`catch (PortalException portalException) {
					if (_log.isDebugEnabled()) {
						_log.debug(portalException, portalException);
					} else {
					        _log.warn(portalException.getMessage());
					}
				}`

**Comment by crodriguezy** [comment]
Hi @YurenaC ,

I haven't seen that pattern applied in the portal so far and that's why I added the extra commit:
```
else {
    _log.warn(portalException.getMessage());
}
```
I mean, logging a warn without checking if its enabled. 

Let me know if we should make an exception for this case.

**Comment by YurenaC** [comment]
Hi @crodriguezy,
Just reviewing the PR and your last comment, I realized that you were right, and your first commit covers the expectations.

Could you please revert your latest change and send it again?
I'll run the test asap.

Thanks and sorry for the the inconvenience!!

**Comment by crodriguezy** [comment]
No problem @YurenaC , please see the new PR: https://github.com/liferay-tango/liferay-portal/pull/1458

**Pull request closed without merging**
