### PR TITLE
LPS-123730 [Content Dashboard] [BUG] Using capital letters doesn't show results in search by filter Subtype 

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Using capital letters doesn't show results in search by filter Subtype in Content Dashboard.

**How to test it**

1. Create a Web Content subtype: **Subtype One**
2. Go to Content Dashboard and filter by subtype
3. Check that in the list appears our subtype **Subtype One**
4. Search Subtype in the up part of the modal (our subtype should appear)
5. Search subtype in the up part of the modal (our subtype should appear)
6. Search Subtype One in the up part of the modal (our subtype should appear)
7. Search subtype one in the up part of the modal (our subtype should appear)
8. Search one in the up part of the modal (our subtype should appear)

Integration tests have been provided with this pull

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by darquesdev — APPROVED** [review]
Great job!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
