### PR TITLE
LPS-150249 Test Autom of Bug: Filter by extension does not shown any result after duplicate a MIME type

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-150249](https://issues.liferay.com/browse/LPS-150249): Test Automation for LPS-138281:
↳[LPS-138281](https://issues.liferay.com/browse/LPS-138281): Apostrophe in segment property value breaks filter

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , this PR will probably have conflicts with this other PR https://github.com/liferay-tango/liferay-portal/pull/2329 that I've just sent, so lets wait till the other is merged and rebase it with master, thanks!

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
