### PR TITLE
LPS-129700 Migrate selection modals in segments modules

### PR DESCRIPTION
**Pull request by kresimir-coko**
Fixes [LPS-129700](https://issues.liferay.com/browse/LPS-129700).

As part of this PR I've removed the usage of `Liferay.Util.selectEntityHandler` because that behaviour is already handled in [Modal.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/modal/Modal.js#L410-L420).

This PR is a part of our [effort to standardize selection modals](https://issues.liferay.com/browse/LPS-129246) across the portal.

## 🧪 Testing
1. Go to People > Segments in the left sidebar
2. Add an arbitrary segment
3. Start adding a new segment, but drag over the Segment component located in the right sidebar to the content
4. Click on Select in the newly dragged Segment component
5. Select the Segment you want to choose by clicking on its name
6. Profit 💰

### CODE REVIEW

**Comment by kresimir-coko** [comment]
ci:test:sf

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
Hey @kresimir-coko,

Don't we need to update https://github.com/jonmak08/liferay-portal/blob/master/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/field/select_js.jsp as well?

Please let me know if you have any questions. Thanks!

**Comment by dgarciasarai** [comment]
Hey @kresimir-coko @jonmak08, 

> Don't we need to update https://github.com/jonmak08/liferay-portal/blob/master/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/field/select_js.jsp as well?

That JS file is used here: https://github.com/liferay-tango/liferay-portal/blob/9f25181fd56c5923b4da9b62d56e6a8eb0ba39a1/modules/apps/segments/segments-web/src/main/resources/META-INF/resources/field/select_organizations.jsp#L76-L80

Thanks!

**Comment by kresimir-coko** [comment]
@jonmak08 @markocikos I've attempted to remove `searchContainer.on` but I'm having issues with my `form` being `null`, for some reason. It exists in the DOM, and after I _cache it in_ the Elements panel in DevTools, the JS can find it, but before that it doesn't find it. Gonna continue messing with it tomorrow, but some guidance would be awesome.

**Comment by markocikos** [comment]
> I'm having issues with my `form` being `null`, for some reason. It exists in the DOM, and after I _cache it in_ the Elements panel in DevTools, the JS can find it, but before that it doesn't find it. Gonna continue messing with it tomorrow, but some guidance would be awesome.

@kresimir-coko  Where is the form in https://github.com/liferay-tango/liferay-portal/pull/1040/commits/ee2ef3d015181f5320d589667cdfad6a9634f0f8#diff-84eaabdb1d093761872875f26bd875372e66beb8ec8afedba77dc237a012dd5dL50-R69 coming from? This change seems unrelated to the original code.

**Review by dgarciasarai — COMMENTED** [review]
Hey @kresimir-coko, we are going to remove our custom item selector for organizations. See this related pull request: https://github.com/liferay-tango/liferay-portal/pull/1051. I'll take a look at this pull request tomorrow again because I think the changes changed and try it out and see if everything works as expected. Do you need to add more code or it's the final one? Thanks!

**Comment by dgarciasarai** [comment]
Seems that we have a mix of codes here within this pull request and in https://github.com/liferay-tango/liferay-portal/pull/1051. Sorry for that! See https://github.com/liferay-tango/liferay-portal/pull/1051#issuecomment-814239657.

**Comment by markocikos** [comment]
@dgarciasarai This PR is blocked until https://github.com/pei-jung/liferay-portal/pull/824 is merged. That's why @kresimir-coko set it as draft, it's not ready for review. If it is easier for you, feel free to close this PR and we'll reopen it when it's ready.

**Comment by kresimir-coko** [comment]
Hey @dgarciasarai, as @markocikos said, I set it as a draft because it depends on https://github.com/pei-jung/liferay-portal/pull/824. Please do comment here whenever https://github.com/liferay-tango/liferay-portal/pull/1051 is merged, so we're all on the same page ❤️

**Comment by dgarciasarai** [comment]
Hey @kresimir-coko, we change the organization custom selector an use the proper one from `organization/organization-item-selector-web`. The pull was merged here: https://github.com/brianchandotcom/liferay-portal/pull/100598. If this pull request does not make sense anymore, please close it. Thanks!

**Comment by kresimir-coko** [comment]
Thanks for the update @dgarciasarai, from a quick glance at the changes in that PR, this PR should still be relevant. We're still waiting on https://github.com/pei-jung/liferay-portal/pull/824 🤷

**Comment by kresimir-coko** [comment]
Hey @dgarciasarai, I've force-pushed the same commit after testing it works on master.

There are no other references to any of the modal usages that we need to migrate, this is the only one, so it should be easy to merge.

**Comment by kresimir-coko** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Reviewing 😃

**Review by dgarciasarai — APPROVED** [review]

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
