### PR TITLE
LPS-117280 Add MVCResourceCommand to show info about a Content Dashboard Item

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need to create an MVCResourceCommand that returns a JSON with all the info that needs to be shown in the Info Panel.

**Provide Solution**

An MVCResourceCommand that returns a JSON with the needed info.

**How to test it**

We have added unit tests to test it.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by carloslancha** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
