### PR TITLE
LPS-130694 Audit and refactor tests for ExperienceCreateExperience.testcase tests to use SACRED model

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-130694](https://issues.liferay.com/browse/LPS-130694)

**Motivation**:
Refactor setup and teardown for ExperienceCreateExperience.testcase

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
hey @Luizcarlosqueiroz I've noticed that some tests with priority 4 & 5 have the property acceptance set to false, when it should be set to true, can you review it please? Thanks!

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Pull request closed without merging**
