### PR TITLE
LPS-122799 Show warning message when role segmentation is disabled.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

As we are disabling the Assign Roles by segment by default, we have to warn users in the role configuration screen that this kind of assignment won't work.

**Proposed Solution**

Show warning message when role segmentation is disabled

Screenshot 2020-11-11 at 13 12 02

**How to test it**

1. Go to App Menu > Roles > Create Role > Select Segments
2. The warning message is shown. 
3. Go to System Settings > Segments > Segments Services (and enable Segmentation by roles)
4. The warning message is not shown.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!!

Could you take a look at this pull?

What I need for you in the frontend side is:

1. Review the code in _**liferay-portal/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_assignments_segments_entry.jsp**_.
2. Fix styles for the warning message.

Thanks!!

**Comment by cgoncas** [comment]
> Hey @dgarciasarai !!!
> 
> Could you take a look at this pull?
> 
> What I need for you in the frontend side is:
> 
> 1. Review the code in _**liferay-portal/modules/apps/roles/roles-admin-web/src/main/resources/META-INF/resources/edit_role_assignments_segments_entry.jsp**_.
> 2. Fix styles for the warning message.
> 
> Thanks!!

Also, I have seen that a part of the key is in bold, and the other part is not. Don't feel obliged to use the key I have defined in my commit.

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by dgarciasarai — COMMENTED** [review]
Hey @cgoncas,
I moved the `clay:stripe` to `edit_role_assignments.jsp` file because the `aui:form` includes some spaces at the edges that we don't want for our alert. Don't worry because the alert only appear if the tab is `segments`. Also, I removed the margin of the management toolbar to "stick" the alert at the bottom of it. Regarding the copies, I separate the message: the first part for the `title` property (bold) and the second one for the `message` property (normal).

Screenshot 2020-11-11 at 10 23 37

I'm going to verify this with @susanavr before sending it. Thanks!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
@susanavr approves 😄

**Comment by dgarciasarai** [comment]
Hey @cgoncas, should the copies be: "roles by segment**s**? 🤔  Because the option to enable in System Settings is "Enable Assign Roles by Segments". What do you think?

**Comment by cgoncas** [comment]
> Hey @cgoncas, should the copies be: "roles by segment**s**? (with an s) 🤔 Because the option to enable in System Settings is "Enable Assign Roles by Segments". What do you think?

Hey @dgarciasarai, this is the copy defined by UX in FIGMA, but it is different in the ticket, so please, if you have any concerns, ask it in the Jira ticket :), so Julia and Susana could define their view about this issue.

Thanks!!

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
I saw an error in the CSS that I added here: `margin: 0;`. I'm going to fix it 😄

**Comment by dgarciasarai** [comment]
ci:test:sf

**Review by dgarciasarai — APPROVED** [review]

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
All in green 🎉  But I don't know if we can forward this or we have to wait for someone else review. Let me know what do you think @cgoncas 😄

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!!

I will handle the forward once @darquesdev review https://github.com/liferay-tango/liferay-portal/pull/536!!!

Thanks!!!

**Comment by dgarciasarai** [comment]
Sure! Thanks! I put the label "on hold" until https://github.com/liferay-tango/liferay-portal/pull/536 is merged 👍

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
