### PR TITLE
LPS-124954 Popover move when scrolling using a scroll wheel

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======

[Link to story or ticket](https://issues.liferay.com/browse/LPS-124954)

Proposed Solution
========
We changed the Popover position to fixed

Change summary:
---------------
* LPS-124954 Changed Popover position to fixed so it doesn't follow the scroll outside the sidebar

Steps to Verify:
----------------

1. Navigate to a Web Content page and open the Content Performance Panel 
2. In the Content Performance Panel, hover over the help tip
3. Wait for the tool tip to appear
4. Scroll up and down using a scroll wheel

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]
🎉

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
