### PR TITLE
LPS-151399.3 Improve bug fix and add and improve tests

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Improve the quick fix made in this PR: https://github.com/liferay-tango/liferay-portal/pull/2413
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151399)

Proposed Solution
========
Added a little bit of semantics so that the code is more readable. We also improved few tests and added new ones.

Steps to Verify:
----------------

1. AC connection
2. Display Page Template
3. Web Content associated with this DPT
4. Go to home page, open the content performance panel, check that it works and then close it
5. Go to Content Dashboard (Menu > Applications > Content > Content Dashboard)
6. At Content, click on toggle menu > click 'View Metrics'

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Review by Stephy6 — APPROVED** [review]
Hi @claraizquierdo 
Just reviewed, everything looks good for me!
Regards.

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
