### PR TITLE
LPS-174620 The segments should be created at Global level by default.

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Currently new segments are created in the current site even when the FF feature.flag.LPS-166954 is set to true

[Link to story](https://issues.liferay.com/browse/LPS-167023)
[Link to impedibug](https://issues.liferay.com/browse/LPS-174620)

Proposed Solution
========
The current solution checks if the current site is the Control Panel site, if the answer is yes, then we can assume we are in the Control Panel and the site we should use is Global.

This approach has a problem when we reach the control panel with the guest site URL, in this case the current site is not ControlPanel but guest.

We can check this case and try to find the right group (the company.getGroupId), but maybe this is a lot of over engineering, as we want once the FF is removed, to create all segments at Global level.

That is the reason we are using the FF to return the company.getGroupId so the new Segment can be created in the right Site.

Steps to Verify:
----------------
1. Set feature.flag.LPS-166954 to true
1. Create a Segment
1. The Segment should be created in the Global Site

Screencaps:
----------------

https://user-images.githubusercontent.com/5776822/216603589-b4d97888-8850-4d41-8735-76ca74085903.mp4

Notes:
----------------
No unit tests are included in this PR because I would need to test this FF, I will do it in the PR that deletes the FF.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:tango

**Review by Mikellorza — COMMENTED** [review]
Hello,

When I was checking this PR. I have found this strange behavior. @claraizquierdo or @Stephy6  can you take a look ? 

https://user-images.githubusercontent.com/46810560/216614131-2212a186-8a02-4b56-b463-3e114ea20b28.mp4

Thanks in advance.

**Comment by cgoncas** [comment]
> 

Hey @Mikellorza !!

Could you open a impedibug with this behavior?

Thanks!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
