### PR TITLE
LPS-178452

### PR DESCRIPTION
**Pull request by claraizquierdo**
This prs includes:

- https://github.com/liferay-tango/liferay-portal/pull/3338
- https://github.com/liferay-tango/liferay-portal/pull/3335
- https://github.com/liferay-tango/liferay-portal/pull/3331
- https://github.com/liferay-tango/liferay-portal/pull/3344

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
Hi @rafaellajordao @CarlosBrichete , we have some QA tests using the FF LPS-166954 and LPS-171722. Would you like to delete them?

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by rafaellajordao** [comment]
> Would you like to delete them?

Hey @claraizquierdo ! I will delete these tests! :relaxed:

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
see: https://github.com/liferay-echo/liferay-portal/pull/11513

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
