### PR TITLE
LPS-120676 [Content Dashboard] Fix language message

### PR DESCRIPTION
**Pull request by dgarciasarai**
Follow up pull request from https://github.com/brianchandotcom/liferay-portal/pull/98933.

Fixing this commit: https://github.com/brianchandotcom/liferay-portal/commit/bdd1d74c78be557d1d358550319d3eae4c9c975a.

From:

press-escape-to-remove-the-bar's-category-filters=Press escape to the remove bar's category filters.

To:

press-escape-to-remove-the-**bars**-category-filters=Press escape to remove **the** bar's category filters.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@dgarciasarai can I do this? 64ccaf095d72dc2a56133197f5abe26ebc620e2d

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
Hey @brianchandotcom, I tried your change (https://github.com/liferay-tango/liferay-portal/commit/64ccaf095d72dc2a56133197f5abe26ebc620e2d) and yes, you can do that. It's compiling fine and the end result is:

Screenshot 2021-02-19 at 18 25 40


Thank you so much! 😄

**Comment by dgarciasarai** [comment]
Oh, my bad, I think it's not working... 😢 I didn't deploy the right changes

**Comment by dgarciasarai** [comment]
I'm closing the PR because the change is ok, I double-checked to be sure. Thanks!

**Pull request closed without merging**
