### PR TITLE
LPS-158043 Remove FF

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This PR includes only the removal of the feature flag.
[LPS-158043](https://issues.liferay.com/browse/LPS-158043)

For texting it:
(1) Create a Web Content
(2) Go to the Content Dashboard and open the Info Panel for the Web Content created
(3) Check if the Subscribe button is available 

Screenshot 2022-09-05 at 19 15 14

### CODE REVIEW

**Comment by jkappler** [comment]
Thanks @Stephy6, looks great!

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
