### PR TITLE
LPS-173714 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# "3 Results for" is not present at ContentDashboard#SelectedExtensionNumbers

Hi! :)
This pr is corresponding to this ticket: [LPS-173714](https://issues.liferay.com/browse/LPS-173714)

### Problem:
The number of results showed that it is wrong.

### Fix:
Correction of the number of results in the test.

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 186 out of 197 jobs passed in 2 hours 19 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
