### PR TITLE
LPS-150536 Test Autom for bug: Traffic sources with link and full pie chart when the content was published today and there is some data for that content in AC side

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-150536](https://issues.liferay.com/browse/LPS-150536): Test Automation for LPS-128891:
↳[LPS-128891](https://issues.liferay.com/browse/LPS-128891): Traffic sources with link and full pie chart when the content was published today and there is some data for that content in AC side

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
