### PR TITLE
LPS-174726 Show the descriptive name of the site after selecting it

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
When a Site is selected its name is not appearing in the scope card.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-174726)

Proposed Solution
========
When a site is selected using the site selector we will show the `groupdescriptivename` if present. If not, we will use the `groupscopelabel`.

Steps to Verify:
----------------
1. Go to Control Panel -> Segments
1. Click on "Add new user segment"
1. Change the scope to Liferay DXP site
1. The name of the selected site should be displayed in the scope card

### CODE REVIEW

**Review by cgoncas — COMMENTED** [review]
Can you create a test for this bug?

**Comment by claraizquierdo** [comment]
> Can you create a test for this bug?

Yeah, I can test that we show the `groupdescriptivename` if it is present in the object returned by the site selector, but I can not test all the behavior because that means integration between back and front.

**Comment by Stephy6** [comment]
LGTM 🎉

**Review by Stephy6 — APPROVED** [review]

**Comment by claraizquierdo** [comment]
@cgoncas , I just added some tests 👍

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
> @cgoncas , I just added some tests 👍

Awesome!!, thank you very much

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango-acceptance

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
