### PR TITLE
LPS-119831 Rename getAnalyticsReportsData to analyticsReportsDataURL, and alt to name

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Use best names for the get_data endpoint

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by dgarciasarai — APPROVED** [review]
It's perfect @cgoncas!! 😄 Thank you so much for updating the tests as well ❤️

Screenshot 2020-08-27 at 16 09 44

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
