### PR TITLE
LPS-131668 As a content management, I want to see the Page Audit panel if I have permissions to edit the page

### PR DESCRIPTION
**Pull request by YurenaC**
Users with any of these conditions fulfilled will have access to the panel.
- Permissions to edit web content OR documents OR blogs
- Permissions to edit pages

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:stable

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:reevaluate:1207401_9461

**Comment by 4lejandrito** [comment]
ci:reevaluate:1207401_9461

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
