### PR TITLE
LPS-147478 Improve SegmentsExperience and LayoutPageTemplateStructure services to accept custom SegmentsExperienceKey

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
We want to convert the default experience into a regular one, to make it possible we need to update some APIs:

- Adds new methods in **SegmentsExperience** services to accept a custom **SegmentsExperienceKey** instead of using an autogenerated id.
- Adds new methods in **LayoutPageTemplateStructure** and **LayoutStructureUtil** to allow us get the layout data through a **SegmentsExperienceKey**.
- At this moment the **SegmentsExperienceKey** is unique by **groupId**, we need to update it to make it unique by **groupId** and **plid**. In that way, we can have the same segmentsExperienceKey per layout, so we can use this field to set the default segments experience using **SegmentsExperienceConstants.KEY_DEFAULT** as SegmentsExperienceKey.

[Link to ticket](https://issues.liferay.com/browse/LPS-147478)

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1257401_1685

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
@cgoncas I need to update the pr to include the upgrade process to create the new index and delete the old one

**Comment by ealonso** [comment]
Hey @cgoncas,

After the changes introduced in LPS-134196, it is not necessary to create an upgrade process for delete the old index and create the new one.

Regards,
Eudaldo.

**Review by cgoncas — APPROVED** [review]
LGTM :)

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
