### PR TITLE
LPS-120017 [Blocker] Move FriendlyURLMapperProvider to service, so it can be used from LayoutSEOLinkManagerImpl.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

top_js.jsp uses a bad cacnonicalURL

**Proposed Solution**

LayoutSeoLinkManager should return a valid canonical and alternates urls.

**How to test it**

1. Create a Display Page Template for Basic Web Contents
2. Create a Web Content and associate it to the display page template create in step 1 (name it english).
3. Log out and navigate to the recently created web page
4. Inspect html > head attributes and look for the href attribute in the link with rel="canonical" (<link data-senna-track="temporary" href="*http://localhost:8080/en/english*" rel="canonical">)
4. Log in again and navigate to the web page
5. Inspect network communication and check the pageViewed event sent to AC
6. Check canonicalURL value inside context ("canonicalUrl": "http://localhost:8080/en/english")**

FYI @4lejandrito @adolfopa

This is not a very beautiful solution, I needed to use a ThreadLocal :(, but it works.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
