### PR TITLE
LPS-160096 Incorrect size in icons in sidebar

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-160096)

## Motivation

We are using an incorrect icon size in our sidebars

## Solution proposed

Fix the icon size using Lexicon guidelines

## How to test

- Visit Content Dashboard and open the Info Panel
- Visit the homepage and open
  - Page audit
  - Content Performance
  - A/B Testing
 
**In all cases icons should be 16px**

image

image

image

image

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
LGTM!

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1317401_4971

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
