### PR TITLE
LPS-176150 Generate empty AC query with not operator when saving the segment

### PR DESCRIPTION
**Pull request by claraizquierdo**
**This PR depends on** https://github.com/liferay-tango/liferay-portal/pull/3256 !!!

Motivation
=======
When saving a segment with event criteria, the frontend sends to the backend a basic expression in AC Grammar.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-176150)

Proposed Solution
========
We have created a file for all the methods related to generating AC grammar queries.

Steps to Verify:
----------------
1. Set the FF feature.flag.LPS-171722=true feature.flag.LPS-172194=true in your portal-ext.properties
2. Sync your DXP site with AC
3. Create a segment with event criteria in AC
4. In Control Panel -> Job Scheduler -> Scheduled Jobs run the CheckIndividualSegmentsMessageListener job.
5. Go to Control Panel -> Segments and edit the AC segment.
6. Open your Chrome Devtools -> Network tab
7. Click save and check that the query sent in the payload of the http petition is correct
8. Go to AC, edit the segment and select the "has not" modifier
9. Run again the CheckIndividualSegmentsMessageListener job
10. Edit the segment in DXP and check that the query sent in the payload of the http petition is correct

Screenshots (optional):
-----------------------
Captura de pantalla 2023-02-22 a las 11 17 21

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by Stephy6 — APPROVED** [review]
Looks and works fine!

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
