### PR TITLE
LPS-143214 Add id information to content dashboard autogenerated xls file

### PR DESCRIPTION
**Pull request by YurenaC**
**Motivation**
----------------

Bug fixing:  id of each element present in the content dashboard table should be printed in the autogenerated excel created when a user click in the export button.
https://issues.liferay.com/browse/LPS-143214

**Proposed Solution**
----------------

Modify the current implementation to add the corresponding id column in the excel generation code.

**Steps to Verify:**
----------------

1. Go to the content dashboard UI
2. Check that some data is already shown in the table (if not, add documents and/or web contents)
3. Click the "Export XLS" button
4. The generated document should contain the same data shown in the content dashboard table and the info panel.

**Change summary:**
----------------

- LPS-143214 Adding id to excel generation
- LPS-143214 Update Excel generation test to also check if the id is present

### CODE REVIEW

**Comment by YurenaC** [comment]
Hi @cgoncas, 
It is a pretty simple modification to a previous behaviour but I'd like you to take a look to get familiar with this new feature

Thanks!

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:tango

**Comment by YurenaC** [comment]
ci:test:stable

**Comment by cgoncas** [comment]
Probably we should use the external reference code instead the DB id.

I will put this PR on hold until Julia answer in https://issues.liferay.com/browse/LPS-143214.

**Comment by cgoncas** [comment]
Hey @YurenaC !!!

We should use ExternalReferenceCode instead the ClassPK. I will wait for Julia answer in https://issues.liferay.com/browse/LPS-143214.

**Comment by jkappler** [comment]
Closing this for the moment, since we will go with external reference code once we get to the LPS

**Pull request closed without merging**
