### PR TITLE
LPS-178075 Support adding event criteria to a segment

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Be able to drag and drop event criteria from the segment editor sidebar to the criteria builder. Also be able to delete and event criteria from the segment.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-178075)

Proposed Solution
========
We have updated the drag and drop functions in the CriteriaRow and CriteriaGroup components to support event criteria. 

We have also updated the ac-grammar query generator function in order to support deleting the criteria (receiving an empty criteria).

Steps to Verify:
----------------
1. Go to the segment editor and create a segment.
2. Edit the segment created in step 1 and drag and drop an event criteria from the sidebar and check the the criteria is being added correctly to the criteria builder.
3. Delete all the criteria from the segment and check that the criteria are correctly deleted.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by p2kmgcl — COMMENTED** [review]
Hey @claraizquierdo, I just reviewed this and works perfectly. Just a question: I tried to add a "Viewed Page" event, and it doesn't allow me to select any page (it throws an error to the console). Should this work or this is just not part of the PR?

[Screencast from 2023-03-13 08-47-34.webm](https://user-images.githubusercontent.com/800645/224639166-4b9f0b9e-1d4c-44a4-8001-70c4b3311edc.webm)

**Comment by claraizquierdo** [comment]
Hi @p2kmgcl !

Thank you for your review :)

I guess that the error you mention have been fixed here: https://github.com/liferay-tango/liferay-portal/pull/3308/commits , at least for the document's selector. Anyway, as you say, fixing that is not part of this PR.

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by p2kmgcl — APPROVED** [review]

**Review by Stephy6 — APPROVED** [review]
LGTM! 🎉

**Comment by Stephy6** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward:force

**Pull request closed without merging**
