### PR TITLE
LPS-132597 Test Autom. Icon Associated With Display Page

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-132597
LPS-113904

**Motivation:**
Test Automation for "Icon to identify contents with an associated display page"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete , two tests are equal to other two I created very recently:

- Created now: CheckDisplayPageIconofApprovedWebContent
- Equal to: ShouldExhibitWebContentAssociatedWithDisplayPage

- Created now: CheckDisplayPageIconofApprovedWebContentNotDisplayed
- Equal to: ShouldExhibitWebContentNotAssociatedWithDisplayPageTemplate

Last PR: https://github.com/liferay-tango/liferay-portal/pull/1168

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
