### PR TITLE
LPS-137665 Test fix of SegmentationCreateSegment

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-137665
LPS-132249

**Motivation:**
This PR fixes these testcases:
- ContentDashboardAuditGraph#KeepInfomationOfDeleteVocabularyInSegment
- ContentDashboardAuditGraph#VocabulariesListedInSystemSettingsSegments

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , the test ContentDashboardAuditGraph#KeepInfomationOfDeleteVocabularyInSegment is still failing. Please review.

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
