### PR TITLE
LPS-130918 As an Admin, I want to configure Segments Service settings from Instance Settings

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Currently, segmentation settings exist only at System level, so there’s no way to configure the feature at the instance level.

In order to facilitate the cloud-based products development, we need to make it available at the instance level.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-130918)

Proposed Solution
========
Create a new Configuration at Instance Level for segmentsEnabled and RoleSegmentationEnabled.

Steps to Verify:
----------------
1. Go to Instance Setting
1. Click Segments
1. Click Segment Service

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
@cgoncas I am having the same errors in mi PR https://github.com/liferay-tango/liferay-portal/pull/2284 
They are not relates to our changes I think

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
