### PR TITLE
LPS-129591 Migrate selection modals in content-dashboard modules

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @liferay-tango,

Attached is an update for http://issues.liferay.com/browse/LPS-129591.

**Test Plan**:

1. Login to Liferay
2. Click on the **Product Navigation Menu**
3. Go to **Categorization** -> **Categories**
4. Click the `+` to add a new vocabulary
5. Click the `+` of the new vocabulary to add a new category
6. Click on **Application Menu**
7. Click on **Content** -> **Content Dashboard**
8. Go to the **Management Toolbar** -> **Filter and Order** drop down
9. Select **Categories**

content-dashboard

10. Click on the **Product Navigation Menu**
11. Go to **Content & Data** -> **Web Content**
12. Click the `+` and select **Basic Web Content**
13. Under **Categorization**, click the **Select** button for one of the vocabularies you created
14. In the modal window click the `+` to add a new vocabulary
15. Click the **Save** button
16. Select the desired category and click **Done**
17. Click on the **Product Navigation Menu**
11. Go to **Content & Data** -> **Blogs**
12. Click the `+`
13. Under **Categorization**, click the **Select** button for one of the vocabularies you created
14. In the modal window click the `+` to add a new vocabulary
15. Click the **Save** button
16. Select the desired category and click **Done**

web content

17. Click on the **Application Menu**
18. Select the **Global** site
19. Click on the **Product Navigation Menu**
20. Go to **Content & Data** -> **Web Content**
21. Click the `+` and select **Basic Web Content**
22. Under **Categorization**, click the **Select** button for one of the vocabularies you created
23. Select the desired category and click **Done**
24. Add a **Basic Web Content** and click **Publish**
25. Click on the **Application Menu**
26. Select the **Liferay DXP** site
27. Click on the **Product Navigation Menu**
28. Go to **Content & Data** -> **Web Content**
29. Click the `+` and select **Basic Web Content**
30. Under **Categorization**, click the **Select** button for one of the vocabularies you created
31. Select the desired category and click **Done**
32. Add a **Basic Web Content** and click **Publish**
33. Click on the **Application Menu**
34. Click on **Content** -> **Content Dashboard**
35. Go to the **Management Toolbar** -> **Filter and Order** drop down
36. Select **Subtype...**

web content

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:reevaluate:1187401_5832

**Comment by 4lejandrito** [comment]
@jonmak08 can you rebase on top of the latest `master` and push force? The tests keep failing and that might (or might not) fix them.

**Comment by jonmak08** [comment]
Ok I will rebase on latest master and force push to the branch and kick off the tests again once I have completed that.  Thanks and sorry for the hassle @4lejandrito

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
🎉 All tests passed! I will review and forward today. Thanks @jonmak08!

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
