### PR TITLE
LPS-161527 com.liferay.segments.test.SegmentsEntryRetrieverTest.testGetSegmentsEntryIds randomly failing

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This PR solves a Segments failing test
[LPS-161527](https://issues.liferay.com/browse/LPS-161527)

Proposed Solution
========
The proposed solution is to change the verification method in the test. To check that the test works correctly, the method verified that an array of Segments Ids contains two specific Ids in a specific order and caused the test to fail because the array was created as HashMap (which doesn't consider the order). Now the verification is made without considering the order in the array of segments Ids.

### CODE REVIEW

**Comment by Stephy6** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:forward

**Comment by jkappler** [comment]
Awesome @Stephy6!

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
