### PR TITLE
LPS 130919 Test fix and renames

### PR DESCRIPTION
**Pull request by YurenaC**
Changes/fixes needed after changes made in https://github.com/brianchandotcom/liferay-portal/pull/115812 
Also rebased to latest master available version atm

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
