### PR TITLE
LPS-119068 Add new ignored module

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

To ensure that a page is optimized for search engine indexing and visibility, it is necessary to check the page's compliance with best practices in terms of performance, accessibility, search engine metadata and SEO. Page audit test allows to make a quick check of that compliance and get warnings and tips to improve each one of the categories.

As an API key for the Page Speed service is needed, we must include some information in the panel to facilitate on-boarding.

We also need to add a new icon in the Control bar to display the panel.

**In this pull**

Add new module, ignored for now, to start working on this new feature. To know more about the feature see the Epic [LPS-111803 As a marketer, I want to be aware of the issues in my page that may affect accessibility and SEO](https://issues.liferay.com/browse/LPS-111803)

**New ignored module**

`~/modules/analytics/analytics-reports-web`

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Hi @cgoncas and @dgarciasarai, Am I late to suggest a different module? What do you think about this naming and location?

Naming: ` layout-audit-*`
Location: `modules/apps/layout/layout-seo-*`

As happens with `layout-seo-*`.

The drawbacks, there's already a module using audit: `modules/apps/portal-security-audit/*`

Other than that I'm ok with `analytics-reports-*` but the fact that is already used in dxp could be confusing.

**Comment by cgoncas** [comment]
Hey @darquesdev !!

If we chose another module, we will need to replicate all the analytics-reports infrastructure, separate metrics for DPT, Content pages, widget pages ...

Do you think it is worth it?

Do you think we can move all the APIs to layout-audit-* or layout-seo-* and deprecate all the old analytics-reports APIs? 

Thanks!!

**Comment by darquesdev** [comment]
Good point @cgoncas, I didn't realize we can reuse the `analytics-reports-api`. Does this change imply to move the `analytics-reports` modules (except web and test) from `dxp` to `apps`?

**Comment by cgoncas** [comment]
> Good point @cgoncas, I didn't realize we can reuse the `analytics-reports-api`. Does this change imply to move the `analytics-reports` modules (except web and test) from `dxp` to `apps`?

Theorically yes, nothing in the API, for now, it is related with AC itself. I think we can implement it as a new "metric" and a new "button" in analytics-reports-web.

I thought that as a first approach we can add the button and reuse all the API, but I think it could be interesting to create a new API in layout-metrics ... and use it in analytics-reports as well.

I think both approaches has good points, so whatever you decide it is good with me.

I have checked that for https://issues.liferay.com/browse/LPS-128194 we will need to create a new API inside Analytics Reports to see the list of available metrics for a specific layout, and I think this approach fits really good with this issue as well.

Let me know what do you think :)

**Comment by darquesdev** [comment]
Yes, I think both approaches are valid. But as you said having a new API for whatever metrics a layout has would be more helpful. 

So the main ideas would be:
- Move analytics-reports code not related to AC from dxp to apps
- Create a new API providing metrics for layouts in layout-metrics-api: reads, views, audit.

I'm struggling with the portlet that currently exists in dxp AnalyticsReportsPortlet, it should be moved to `apps`, right?

**Comment by cgoncas** [comment]
I think that the layout-metric-api is not needed, if we use the module analytics-reports, we should create a new API inside this module, that handle all the read, views, audit ...

Like we did with the ContentDashboardActions.

**Comment by dgarciasarai** [comment]
I'm closing this pull request because new module was sent here: https://github.com/liferay-tango/liferay-portal/pull/977 with the path: `~/modules/apps/layout/layout-reports-web`.

Thanks!

**Pull request closed without merging**
