### PR TITLE
LPS-137278 Fix stubs, annotation and move ContentPerformance tests

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Epic**:
[LPS-137278](https://issues.liferay.com/browse/LPS-137278)

**Motivation**:
- Change stubs after changes of [LPS-144028](https://issues.liferay.com/browse/LPS-144028), [LPS-144029](https://issues.liferay.com/browse/LPS-144029) and [LPS-144030](https://issues.liferay.com/browse/LPS-144030) 
- Remove missing @ignore annotation from already created tests
- Move test of [LPS-139239](https://issues.liferay.com/browse/LPS-139239) to lower the number of files

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
