### PR TITLE
LPS-130327 Add test to AddNewExperienceSessionBrowserSegment

### PR DESCRIPTION
**Pull request by CarlosBrichete**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302

CC @austinchiang

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by liuxingye** [comment]
Hi @CarlosBrichete, I've rebased the above tests and resent them with a new case [LPS-130309]( https://issues.liferay.com/browse/LPS-130309) to https://github.com/CarlosBrichete/liferay-portal/pull/26

**Comment by liuxingye** [comment]
ci:close

**Pull request closed without merging**
