### PR TITLE
LPS-163042 Integration tests for view version URL

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-163042)

Adds integration tests for "Add a Redirect When There Are Too Many Web Content Version History Entries" story

## Change summary:

* Refactor existing tests so that we can specify the versions that will be tested
* Add a new test to check that the view versions URL will be empty if the count of versions is lower than the max specified one

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
