### PR TITLE
LPS-118615 [Content Dashboard] Support metrics action in content dashboard for journal articles

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

The content performance metrics show relevant information for content authors such as views, reads, and SEO insights. As the content dashboard is intended to be the one-stop-place for content authors and marketers to review all their content, a view of the content performance metrics from the content dashboard is needed in order to facilitate the access to them.

**Proposed solution**

Implement a ContentDashboardItemActionProvider of VIEW_IN_PANEL type that returns a valid Content Performance panel URLs.

**How to test it**

1. Connect DXP to AC.
2. Create a Display Page Template for a Web Content
2. Create a Web Content and associate it to the Display Page Template created in step 1.
3. Go to Global App Menu > Content Dashboard
4. Select view Metrics in a row of Content Dashboard
5. The content performance panel should be visible.

Metrics (1)

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Waiting for GA5 to be released.

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
