### PR TITLE
LPS-152123: Test fix for for CollectionsWithAssetPublisher#ViewCollectionProvidersInAssetPublisher

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Test(s) failing:**
* CollectionsWithAssetPublisher#ViewCollectionProvidersInAssetPublisher 

**Error:**
`    
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//button[contains(@class,'close')] | //a[contains(@id,'closePanelAdd') and contains(@class,'close')]"
`

**Problem:**
`Alert.viewSuccessMessage();` function is breaking the test, but is not necessary for the test.

**Fix:**
Removed this function.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
