### PR TITLE
LPS 144656 Fix page audit issue title styles when text is too long

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Issues title breaks line incorrectly when text is too long
[Link to ticket](https://issues.liferay.com/browse/LPS-144656)

Proposed Solution
========
We changed the CSS of the Page Audit sidebar header and also removed unused styles.

Steps to Verify:
----------------

1. Go to Liferay > Open Page Audit panel (from upper bar button) > Click 'Launch Page Audit'
2. After it returns the results, click on issue 'Missing Input ALT Attributes' or 'Incorrect Image Aspect Ratios'. If the title doesn't break into two lines, make the title longer with Chrome devtools.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
LGTM
image
🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
