### PR TITLE
LPS-153090

### PR DESCRIPTION
**Pull request by mbowerman**
https://issues.liferay.com/browse/LPS-153090

/cc @SelenaAungst

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1377401_2135

**Comment by cgoncas** [comment]
ci:reevaluate:1377401_2135

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
