### PR TITLE
LPS-147454 Fix Unsupported operation exception when custom fields are used in the segment editor

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Custom fields are no longer supported in the Segments Editor

**Steps to reproduce:**

1. Go to the menu --> Control Panel --> Configuration --> Custom Fields, then add a User custom field "Text Area". Name it Business Unit and add the start value as "COIN".
Checkpoint: Make sure that the custom field is added to your User
1. Go to Liferay Site --> People --> Segmentation and add a User segment "COIN'ers" and add the property "Business Unit" that contains COIN.
1. Go back to the segments editor and click in the "COIN'ers" segment to edit/view
Expected result
The "COIN'ers" segment is visible and editable

**_Current result_**
The error "COIN'ers is temporarily unavailable." is displayed

**_Stack trace error:_**
java.lang.UnsupportedOperationException: Unsupported method visitComplexPropertyExpression with complex property expression customField/_44207_Business_Unit

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> Hey @beltranrengifo !!
> 
> We are having a strange behaviour in the Segments Editor once we create a Custom Field Segment. I have added a Video here:
> 
> https://liferay.slack.com/archives/D02S28MC30X/p1646213310358759
> 
> **Steps to reproduce:**
> 
> 1. Create a segment with a custom field
> 2. Save the segment.
> 3. Click edit the segment
> 
> A error is shown:
> 
> Screenshot 2022-03-02 at 09 30 00
> 
> Thanks!!

I have upodated the PR with a fix to this problem, it was a backend problem :)

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!

Do you mind to take a look to this PR?

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
Finally nothing to do on the frontend side, looks good!
Thxs Cris

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
