### PR TITLE
LPS-167969 Sort attributes aphabetically

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Add asset metrics to Document and Media File Display Page Templates
[Link to story or ticket](https://issues.liferay.com/browse/LPS-166633).

When DPT where developed we didn't implement the code needed to sent metrics to AC. 

Per Brian's comment in https://github.com/brianchandotcom/liferay-portal/pull/126183 we will sort alphabetically the attributes in the new div markup

Proposed Solution
========

We have needed to follow the same approach we did for blogs and web-content and add the attribute

```
<div analytics-asset-action="preview" data-analytics-asset-id="classPK" data-analytics-asset-title="title" data-analytics-asset-version="1.0">
...
</div>
```

Steps to Verify:
----------------
1. Create a display page template for Basic Documents and mark it as default
2. Create a Document
3. Go to the Content Dashboard
4. Click the eye icon for the new Document
5. Check the event are sent to AC
6. Go to AC, check the document view has been increased

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1347401_3184

**Comment by cgoncas** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:test:stable

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
