### PR TITLE
LRQA-75279 Test fix for Content Dashboard tests after files changes

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LRQA-75279](https://issues.liferay.com/browse/LRQA-75279)

**Test(s) failing:**
 * ContentDashboard#PaginationDisplaySelectedNumberOfRows
 * ContentDashboard#PaginationMoveAcrossPagesWithButtons
 * ContentDashboard#PaginationMoveAcrossPagesWithNumber
 * ContentDashboard#SelectedExtensionNumbers
 * ContentDashboard#NoMimeType
 * ContentDashboard#ExportXLSDisabled

**Problem:**
Changes after LPS-147440.

**Solution:**
Added macro to delete the _tree.png_ document from default site.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! I think the best solution for this is case is to delete the Document using JSONWS, so tests can run in a cleaner environment. Pls let me know if its ok for u

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
