### PR TITLE
LPS-135691 Test fix AuditGraphUncheckCheckbox

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-135691

**Motivation:**
Test fix for ContentDashboardAuditGraph#AuditGraphUncheckCheckbox

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:stop

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Pull request closed without merging**
