### PR TITLE
LPS-118107 Return 0 as the full pie chart value when AC returns null

### PR DESCRIPTION
**Pull request by cgoncas**
Hey @brianchandotcom!! 

Could you backport this pull to 7.3?

**Motivation**

When no data is provided from AC, the value in the chart should be 0, instead of unknown.

**How to test it**

Unit/Integration tests have been provided for this pull

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by darquesdev — APPROVED** [review]
LGTM ;)

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by dgarciasarai** [comment]
Hey @cgoncas!
I think there is something else missing to achieve what we discuss this morning. If I'm not wrong:
1. If there is no value, display 0 in each traffic channel
2. If there is an error, display "-" in each traffic channel

Now, when the endpoint has an error, the frontend receives:
```
{
    error: "An unexpected error occurred."
}
```

And I don't have the information about all the traffic channels to display it in the UI. I mean now, when the endpoint fails, the UI looks like this (with a warning on top of the sidebar "Some data is temporarily unavailable."):

Screenshot 2020-11-03 at 17 05 30

Let me know what do you think. Thanks! 😄

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!!

This is exactly the  contract we have frontend/backend.

When backend find a problem (and doesn't have a response), an error is returned, we have the same behaviour with organic/paid before, do you what us to change it? .

Thanks!!!

**Comment by dgarciasarai** [comment]
@cgoncas I'm not concern about the contract, because we decided to do it that way. My question is:
* We want to display all the traffic channels with "-" in case the endpoint fails? (endpoint returns error)

If that's what we want, I think we need to implement a **fallback response** with all the traffic channels and the messages (without share and value). Should we do that? Do you have another idea?

On the other hand, I think it's nice to have the message "Your page has no incoming traffic from traffic channels yet." when all the values are 0. But the variable used in frontend maybe has to change to a proper name. Now we have `missingTrafficSourceValue` and checks if there is some value `undefined`.

Screenshot 2020-11-03 at 17 24 01

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
