### PR TITLE
LPS-137414 Test Autom. to be able to change the priority of experiences| Personalization

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137414](https://issues.liferay.com/browse/LPS-137414)

Motivation:
"As a Marketer, I want to be able to change the priority of experiences"

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by mateusralv** [comment]
@CarlosBrichete Carlos, I saw on the testray that the tests sent in this PR are passing and what are failing are the TestAb ones I'm fixing

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
