### PR TITLE
LPS-117420 Add filter by categories selector.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need to add a filter by multiple categories, and the first step is to add a selectable filter.

**Provided Solution**

Use an item selector to select the asset categories. This pull contains only the selector, the filter will be included in another pull.

**How to test it**

1. Go to Global App Menu > Application > Content Dashboard
2. Click Filter by > Categories
3. Select multiple categories
4. Check that all the categories are selected in the Content Dashboard filter

CategorySelector

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @dgarciasarai and @darquesdev !!

As this pull has backend and frontend, would be nice if both of you could take a look :).

Thanks in advance!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
