### PR TITLE
LPS-131936 Modify CheckForMoreCategories test after UI changes

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-131936](https://issues.liferay.com/browse/LPS-131936)

**Test(s) failing:**
 * ContentDashboard#CheckForMoreCategories

**Error:**
`java.lang.Exception: Element is not present at "//span[contains(@class,'label-secondary') and contains (.,'...')]"`

**Problem:**
UI has change. Instead of showing "..." to indicate more categories as previously, now it shows the number of categories.

**Fix:**
Fixed path and value.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
