### PR TITLE
LPS 147258 Remove custom font-sizes in Content Dashboard CSS and use new utility classes defined in Clay

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
Is advisable to use the minimum custom values as possible in order to be more flexible if we have to make changes in the future. This changes standardize the font-size value in the Content Dashboard by including a [Clay](https://clayui.com/docs/css/utilities/markup-text.html) utility related to text. [LPS-147258](https://issues.liferay.com/browse/LPS-147258).

Proposed Solution
========
The solution consists in delete the font-size variable from de SCSS and include the utility class 'text' in the attributes of the correspondent element.

Steps to Verify:
----------------
1. Go to Categorization -> Categories
2. Add a new Vocabulary -> Add new Category for the created Vocabulary
3. Go to Design -> Display Page Templates -> Add a new DPT(Content Type=Web Content Article, Subtype=Basic Web Content). Mark the DPT as Default.
4. Go to Content & Data -> Web Content -> Add a new Basic Web Content.
5. Go to Content Dashboard -> hover over the Web Content created -> click on info icon
6. in the Categorization section, inspect the Public Categories title and check if has the string 'text-2' as an attribute(or a font-size of 0.75 rem). 

Screenshots:

Captura de pantalla 2022-02-17 a las 16 04 58

### CODE REVIEW

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Ei Stefan! I think that there is one more font-size to be deleted in the tree.scss file.

Great work removing this first font-size 💪

**Comment by Stephy6** [comment]
Hi @claraizquierdo, I removed the last custom font-size(hope you don't find another one). This one corresponds to the number of items selected ("n number of items") when you using filters in the content dashboard:

Captura de pantalla 2022-02-21 a las 8 16 36

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
