### PR TITLE
 LPS-128350 Language switcher (Flag icon) is not working in the content performance panel

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Language switcher (Flag icon) is not working in the content performance panel

**How to test it**

1. Get DXP connected and synced with AC
2. In the view mode of a content page, click on the Metrics icon and display the content performance panel
3. In the content performance panel, click on the flag to change language
4. The dropdown displays, I can select another language and the dropdown closes, so URL and title of the page in the panel are changed.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Reviewing 😃

**Review by dgarciasarai — APPROVED** [review]
You found it! Great 🎉 🚀 😄 

The `chartState` was changed here in this story: https://issues.liferay.com/browse/LPS-124200. See pull request: https://github.com/liferay-frontend/liferay-portal/pull/578. All the files has `const chartState = useChartState();` but I didn't change it in `Translation` component.

I tried this solution and seems to work fine now. Web Content title and URL change if the user change the language in the dropdown.

Awesome! ❤️

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
