### PR TITLE
LPS-174004 ContentDashboardAdminPortletTest.testGetSearchContainerWithDefaultOrderForTitle is failing

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
The test [testGetSearchContainerWithDefaultOrderForTitle](https://testray.liferay.com/home/-/testray/case_results/2179884459?redirect=https%3A%2F%2Ftestray.liferay.com%2Fhome%2F-%2Ftestray%2Fcase_results%2Findex%3FtestrayBuildId%3D2179877862%26cur%3D1%26delta%3D200%26orderByCol%3Dstatus_sortable%26orderByType%3Dasc) is failing in ContentDashboardAdminPortletTest class.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-174004)

Proposed Solution
========
Some documents are added by default to the portal, so order by title will return other results apart from tested documents title1 and title2.

I have renamed the web contents as 0title1 and 0title2 so they are returned as the first results.

Steps to Verify:
----------------
No functional changes, all tests should be green.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by Mikellorza — APPROVED** [review]
Now the test is working.

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
