### PR TITLE
LPS-174133 User without Segment's portlet permissions can access

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
User without Segment's portlet permissions can access to the segments administration.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-174133)

Proposed Solution
========
Delete check of FF in isShow method because it was avoiding the portal permission check.

Steps to Verify:
----------------

1. Create a role Segmentator
2. Add Access to the Control Panel permissions to the Segmentator role
3. Create a user u1
4. Add the role Segmentator to the user u1
5. Login with the user u1
6. User u1 won't access to the segment administration.
7. Add  Segments / Access in Control Panel permissions to the Segmentator role
8. The user can access to the segments administration

Screenshots (optional):
-----------------------

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by cgoncas — CHANGES_REQUESTED** [review]
This PR doesn't contain tests, it is not explained why, the proposed solution also doesn't explain why this change is required.

**Review by Stephy6 — COMMENTED** [review]
Works fine for me

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
