### PR TITLE
LPS-131944 It's not possible to select current site tags when creating a segment

### PR DESCRIPTION
**Pull request by 4lejandrito**
Fixes https://issues.liferay.com/browse/LPS-131944.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:reevaluate:1047401_8200

**Comment by 4lejandrito** [comment]
ci:reevaluate:1047401_8200

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by michaelhashimoto** [comment]
ci:forward

**Pull request closed without merging**
