### PR TITLE
LPS-167004 Collections variations: buttons do not have discernible text

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Accessibility collections variations: buttons do not have discernible text
[Link to story or ticket](https://issues.liferay.com/browse/LPS-167004)

Proposed Solution
========
We added an aria-label attribute to the button.

Steps to Verify:
----------------

- Go to People -> Segments and create one segment.
- Go to Site Builder -> Collections and create one collection.
- Create one variation for the collection.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
Hi @claraizquierdo, LGTM!

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:reevaluate:1327401_6662

**Comment by claraizquierdo** [comment]
ci:reevaluate:1327401_6662

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
