### PR TITLE
LPS-134606 Test Autom Numb Categories Audit Graph

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-134606
LPS-116690

**Motivation:**
Test Automation for "Limit the number of categories selected from config in the audit graph"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz don't forget to add the "property portal.acceptance = "true";" for the priority 5 tests

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
