### PR TITLE
LPS-167477 Prevent not needed requests

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-167477)

## Motivation

We are calling `getItemVersionsURL` and fetching the data before the user interacts with its tab. We should wait, spare requests, and only call for the data if the user demands it.

Also, we introduced a bug [here](https://github.com/liferay-tango/liferay-portal/pull/2847/commits/b78341223bf2df95a20ae8a443b57990a9468a86) provoking the info panel perform and additional rendering and consequently an additional unneeded request to the backend, fetching data already available in the component.

## Solution proposed

- Prevent fetching if the versions tab is not active
- Store a flag in a ref indicating if the versions data is already available in the component, so we wont request if not needed
- Stick to the main `useEffect` for getting the data, instead of calling `getData` from the imperative handler: just setting the proper url in the state property will trigger the `useEffect`, so no need for calling the method directly. Also, we can safely remove the parameter of the `getData` function, as this value is a global variable in the component.

## How to verify

No UI changes.

#### For the versions

- Open browser's devtools, Network tab
- Navigate to the Content Dashboard
- Click the info in a web content or the default `tree.png` file - the info panel should open
- A request should appear, asking for the item data, along with others, but none of them refers to the item versions
image
- Click on Versions tab, a new request should appear, regarding the item versions
image
- Navigate between tabs, no requests should happens, besides the `session_click` ones

Mess around in any way you can figure. At the end only one request should happen regarding the item versions. And should only happen in the user request the tab content or reloads the page with that tab active

#### For the info panel request

- Visit the Content Dashboard
- Load an item in the info panel by clicking the info icon
- Load another item
- Only one request should appear in the network tab of the devtools

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
Ei @beltranrengifo , this looks good. The only thing I miss is the `VersionsContent.d.ts` file updated with the new `active` prop.

**Comment by beltranrengifo** [comment]
> Ei @beltranrengifo , this looks good. The only thing I miss is the `VersionsContent.d.ts` file updated with the new `active` prop.

hey @claraizquierdo nice catch thanks!
i'm so obsessed with the SF errors that I didn't commit that LOL

**Comment by beltranrengifo** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
hi @claraizquierdo !
would you mind to review the last commit, it just prevent the second request when the info item showed in the panel changes

**Comment by beltranrengifo** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]
Everything works perfect! Great work :)

**Comment by beltranrengifo** [comment]
rebase w/ master and push -f

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 5 minutes
> Click here for more details.

IDK what else doing here @claraizquierdo 
I think if this pr pass the relevant, we send it directly to Brian after QA validation

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
Let's wait until next Monday. FI has merged a fix for TS types stability. [See Slack thread](https://liferay.slack.com/archives/CNBG06JS3/p1667563554919819)
Let's try CI again when [this](https://github.com/brianchandotcom/liferay-portal/pull/125765) is on master branch

**Comment by beltranrengifo** [comment]
rebase and pushed. npm-scripts versions is now `47.10.0`

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
