### PR TITLE
LPS-137687 File URL to be copyable and placed in first section

### PR DESCRIPTION
**Pull request by beltranrengifo**
[See Jira Ticket](https://issues.liferay.com/browse/LPS-137687)

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Review by claraizquierdo — COMMENTED** [review]
Everything works fine. I just see one visual detail. I think that the input with the url should be in a disabled state, like in Documents and Media:
Captura de pantalla 2021-10-18 a las 22 22 20
:

**Comment by beltranrengifo** [comment]
> > Everything works fine. I just see one visual detail. I think that the input with the url should be in a disabled state, like in Documents and Media: Captura de pantalla 2021-10-18 a las 22 22 20 :
> 
> Hi @claraizquierdo, thank you for your comment! I think the more appropriate state for the input is readonly, I hesitated between disabled and readonly, I finally went for this last option as it is more accurate.
> 
> I did not see any special state for the input in the Document Library, it is editable and this can lead to potential errors.

Added `readonly` attr for ML copy-url inputs

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
