### PR TITLE
LPS-152541 Test for SegmentsCompanyConfigurationDisplayContext class

### PR DESCRIPTION
**Pull request by Stephy6**
### Motivation

We need to create a new custom JSP for Segmentation Service, that helps the user to define the configuration.

### Proposal 

All the code will be done in https://github.com/liferay-tango/liferay-portal/pull/2538, but we are going to start send code needed to the story, so we don't have a rellay big PR to be reviewed and merged.

This PR only include the test for the bind action method in Segments Company Display Context class.

### How to test it

No functional changes, and integration tests have been included.

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @YurenaC and @Stephy6 !!

How are you doing with this test?

Thanks

**Comment by YurenaC** [comment]
Hi @cgoncas,
The bind test is done and @Stephy6 is working in the other two needed, hopefully will be done soon as well

**Comment by Stephy6** [comment]
Hi @YurenaC and @cgoncas ! Tests are working, let me know what you think.
Thank you

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:reopen

**Comment by Stephy6** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:forward

**Pull request closed without merging**
