### PR TITLE
LPS-130693 Refactor ContentDashboardAuditGraph testcase

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-130693](https://issues.liferay.com/browse/LPS-130693)

**Motivation:**
Audit and refactor tests for ContentDasboardAuditGraph.testcase tests to use SACRED model

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
