### PR TITLE
LPS-122467 [Bug] Avoid recalculate getSegmentsEntryIds when you have it already in the HttpRequest.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

There is an important performance regression in Segmentation.

**Proposed solution**

Reuse the parameter SegmentEntryIds from the HttpRequest in ServicePreaction and SegmentsRoleContributor

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
