### PR TITLE
LPS-139239 Test Autom Assert Title, URL, Views and Traffic

### PR DESCRIPTION
**Pull request by lucassantanasantos**
https://issues.liferay.com/browse/LPS-139239
Create a assert of Title, URL, Views and Traffic.

### CODE REVIEW

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
Hey @lucassantanasantos , the test is failing, can you take a look? Thanks!

**Comment by lucassantanasantos** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
