### PR TITLE
LPS-154012 Tests Automation for LPS-151065 Show the asset's Type to the Content Dashboard's Info Panel

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-154012
LPS-151065

**Motivation:**
Test automation for the story Show the asset's Type to the Content Dashboard's Info Panel

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:relevant

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz Please add the description to this PR with the JIRA tickets and motivation

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
