### PR TITLE
LPS-149603 Test fix: ExperienceCreateExperience#CreatingContentInDifferentExperiences

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149603](https://issues.liferay.com/browse/LPS-149603)

**Test(s) failing:**
 * ExperienceCreateExperience#CreatingContentInDifferentExperiences

**Error:**
`
java.lang.Exception: Expected text "Some of the fields have invalid values. If you continue publishing, the latest valid values will display." does not match actual text (case insensitive) "" at "//*[contains(@class,'modal-dialog')]//*[contains(@class,'modal-body')]"
`

**Problem:**
The modal was kept open after configuration, and this would impact the next macros.

**Fix:**
Added IFrame macro to close modal.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
