### PR TITLE
LPS-149556 Test fix: change value of select function

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149556](https://issues.liferay.com/browse/LPS-149556)

**Test(s) failing:**
 *  LocalFile.ExperienceCreateExperience#AddNewExperienceSessionSignedInSegment 

**Error:**
`
org.openqa.selenium.NoSuchElementException: Cannot locate element with text: FALSE For documentation on this error, please visit: https://www.seleniumhq.org/exceptions/no_such_element.html Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'cloud-10-0-19-135.lax.liferay.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.14.138-rancher', java.version: '1.8.0_121' Driver info: driver.version: unknown
`

**Problem:**
The value argument of 'Select' function is case sensitive. So it was not working with 'FALSE' value.

**Fix:**
Changed value to 'False''.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
