### PR TITLE
LPS-138207 Test Autom. PageSpeed in System Settings

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-138207](https://issues.liferay.com/browse/LPS-138207)
[LPS-125851](https://issues.liferay.com/browse/LPS-125851)

**Motivation**:
Test automation: 'As a system admin, I want to configure PageSpeed from system settings'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
