### PR TITLE
LPS-173704 Reduce props drilling

### PR DESCRIPTION
**Pull request by claraizquierdo**
This is part of a bigger PR: https://github.com/liferay-tango/liferay-portal/pull/3202

Motivation
=======
Reduce properties drilling in the react components so that the code is easier to maintain.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-173704)

Proposed Solution
========
We do not pass the properties from parent to children if those properties are constants defined in the constants file.

Steps to Verify:
----------------
1. Go to people -> segments and create a new segment
2. Add different types of properties and save
3. View the new created segment and check that all the criteria are correct
4. Edit the new created segment and check that all the criteria can be edited

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_8611

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_8611

**Comment by claraizquierdo** [comment]
ci:test:tango

**Review by Stephy6 — APPROVED** [review]
Done reviewing, looks and works great for me 🎉

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_8643

**Review by cgoncas — APPROVED** [review]
Everything works good on my side.

**Comment by cgoncas** [comment]
Hey @CarlosBrichete and @rafaellajordao !!

Could you check if the failing Tango tests are related with this PR?

Thanks!!

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_8643

**Review by Mikellorza — APPROVED** [review]

**Comment by rafaellajordao** [comment]
> Hey @CarlosBrichete and @rafaellajordao !!
> 
> Could you check if the failing Tango tests are related with this PR?
> 
> Thanks!!

Hey @claraizquierdo, tests are not related to your PR :)

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
