### PR TITLE
 LPS-151950 Content Performance Panel doesn't load if we render the React component directly from the control menu

### PR DESCRIPTION
**Pull request by YurenaC**
Restore reverted changes from https://github.com/liferay-tango/liferay-portal/pull/2376 and minor bug regarding visualization is fixed.

Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-148315)

Proposed Solution
========
The react component is loaded directly in the control menu, so we can avoid the dispach of the portlet and save some time.

Steps to Verify:
----------------
1. Go to the home page
2. Click the Analytics Report Icon
3. The panel loads successfully.

### CODE REVIEW

**Comment by YurenaC** [comment]
Hi @Stephy6,
We'd like you to test this PR to have another confirmation that ir works before move it to master.

Steps to reproduce:
- Please, clean your environment, ensuring caches are also clean (git clean -fdx)
- Set your env to DXP: ant setup-profile-dxp
- Build the portal (ant all)
- Please check that the Performance Panel is properly shown in the home page
- Please also check that the Performance Panel is properly shown in the Content Dashboard.

Thank you!!

cc: @claraizquierdo

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
Hi @YurenaC!
It seems that works fine, I adjunct a video in case I miss something:

https://user-images.githubusercontent.com/91207948/164682155-735dd7b7-54e2-4162-a733-d6d2bce5f004.mov

cc: @claraizquierdo

**Comment by YurenaC** [comment]
Great! Thanks @Stephy6!

@CarlosBrichete could you please also take a look? Please follow the steps described in my first comment
Thanks!

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
