### PR TITLE
LPS-119068 Disable by default Layout Reports.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need more time to investigate the performance issue that we describe in this PR: https://github.com/liferay-tango/liferay-portal/pull/1057

So, in other to let the performance team work without taken this regression into account, we will disable the Page Audit button, and once the Performance is fixed, we will reactivate it.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Test are passing successfully locally. Trying forward again :)

```
com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShow STARTED

com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShow PASSED

com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithLayoutTypeAssetDisplay STARTED

com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithLayoutTypeAssetDisplay PASSED

com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithoutEnableConfiguration STARTED

com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithoutEnableConfiguration PASSED

> Task :apps:layout:layout-reports-test:stopTestableTomcat


BUILD SUCCESSFUL in 33s
52 actionable tasks: 38 executed, 14 up-to-date
```

**Comment by cgoncas** [comment]
> Test are passing successfully locally. Trying forward again :)
> 
> ```
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShow STARTED
> 
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShow PASSED
> 
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithLayoutTypeAssetDisplay STARTED
> 
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithLayoutTypeAssetDisplay PASSED
> 
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithoutEnableConfiguration STARTED
> 
> com.liferay.layout.reports.web.internal.product.navigation.control.menu.test.LayoutReportsProductNavigationControlMenuEntryTest > testIsShowWithoutEnableConfiguration PASSED
> 
> > Task :apps:layout:layout-reports-test:stopTestableTomcat
> 
> 
> BUILD SUCCESSFUL in 33s
> 52 actionable tasks: 38 executed, 14 up-to-date
> ```

Hey @dgarciasarai !!

Thanks a lot for trying to resend it. But the test is flacky :(, i will fix it and resend.

Thanks!!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
