### PR TITLE
LPS-119487 [Content Perfomance Panel] fix bug

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

The metrics button doesn't appear sometimes in the Content Performance Panel.

**Proposed Solution**

Use layoutDisplayPageObjectProvider.getGroupId() instead themeDisplay.getScopeId()

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by darquesdev — APPROVED** [review]
good catch! 👌🏻

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
