### PR TITLE
LPS-141225 Wrong name when user duplicates experience

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-141225)

Steps to verify:
- clone pr
- use the portal in spanish
- edit homepage
- create an experience named _Experiencia 1_
- duplicate this experience
- the name of the duplicated experience should be _Copia de Experiencia 1_

The same applies for all languages

### CODE REVIEW

**Review by 4lejandrito — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
