### PR TITLE
LPS-143032 Test for XLS button

### PR DESCRIPTION
**Pull request by CarlosBrichete**
**JIRA Ticket:**
LPS-143032
LPS-124236

**Motivation:**
Test automation for XLS button in poshi.

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
