### PR TITLE
LPS-165039 Remove FF for actions in the Content Dashboard

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
This ticket just remove the use of a feature flag for actions in the Content Dashboard.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-165039)

Steps to Verify:
----------------
1. Download the PR.
2. Create some versions for Documents and Media and Web Contents.
3. Go to the Content Dashboard.
4. Open the Info Panel for some items and check that the actions are shown for versions.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
Ei @Stephy6 , should we remove this FF? I see that we still have this story in development: https://issues.liferay.com/browse/LPS-161020

**Comment by Stephy6** [comment]
> Ei @Stephy6 , should we remove this FF? I see that we still have this story in development: https://issues.liferay.com/browse/LPS-161020

Right, maybe we should wait, as all the actions are under the same FF.

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
LGTM!

**Comment by Stephy6** [comment]
ci:forward

**Comment by Stephy6** [comment]
ci:stop

**Comment by Stephy6** [comment]
ci:forward

**Pull request closed without merging**
