### PR TITLE
LPS-146163 Delete FF.

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation

Delete FF and habilitate Blogs in the Content Dashboard

### CODE REVIEW

**Comment by cgoncas** [comment]
hey @CarlosBrichete and @Luizcarlosqueiroz 

Do you mind to enable blogs testing in the Content Dashboard for this PR?

Thanks!!

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @cgoncas! The tests are supposed to work with and without FF, so they should pass either way. I will run our test routine to check the tests are passing

**Comment by cgoncas** [comment]
Hey @CarlosBrichete !!

I think the failing tests are not related, what do you think?

Thanks!!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
LGTM!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
