### PR TITLE
LPS-124170 [Impedibug] After change the default language, user cannot edit experiences without that language

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**
After change the default language, user cannot edit experiences without that language

**Steps to reproduce it**

1. Create a Content Page
2. Create a experience with the default language (English, USA) and with other language (for example Spanish, Spain)
3. Go to Applications Menu > Control Panel > Instance Settings > Localization
4. Change the default language to Portuguese (Brazil)
5. Go to the Content Page and try to edit the experience previously created

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Review by dgarciasarai — COMMENTED** [review]
Hey @cgoncas, maybe we should send this impedibug with the Story LPS (LPS-124170) instead of the impedibug LPS. What do you think? Thanks! 😃

**Comment by cgoncas** [comment]
> Hey @cgoncas, maybe we should send this impedibug with the Story LPS (LPS-124170) instead of the impedibug LPS. What do you think? Thanks! 😃

Hey @dgarciasarai , I was still updating the bug, but thank you to remember it.

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Forwarding, since this is a minor change, and @darquesdev is not available to review it.

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
