### PR TITLE
LPS-165839 Add revert action to document items in content dashboard

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
As a Content Marketer, I want to revert back to a previous version of a document from the info panel, so that I can easily manage which version of a document is being displayed.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-162824)

Proposed Solution
========
It is added a new action for document item version in content dashboard.

Steps to Verify:
----------------

1. Go to Content Dashboard 
2. Click on info link of the kebab men.
3. Go to versions tab
4. Click on kebab menu of the item and you will se the revert action available .

image

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
