### PR TITLE
LPS-151955 Improve segments experience priority

### PR DESCRIPTION
**Pull request by lfbesada**
Motivation
=======
Improve the logic we apply to manage the segment experiences priority.

https://issues.liferay.com/browse/LPS-151955

Proposed Solution
========

We have deleted some redundant steps to simplify the logic.

Steps to Verify:
----------------
1. In a site where Staging with Page Versioning is enabled
2. Create a content page
3. Create a few experiences, for example, 3
4. Change the order: check the order is changed and check DB, SegmentExperience table, the priority is updated not only in the experience you moved, the others are updated to in order to maintain consecutive priorities.
5. Delete one experience (not the last one): check DB, SegmentExperience table, the priority is updated for all the experiences with a hight priority than those you deleted in order to maintain consecutive priorities.

https://issues.liferay.com/browse/LPS-151955

Hi @liferay-tango 
This PR improves the way we handle the segment experiences priority. Could you please review it? 
Thanks! ❤️ 
Regards

cc: @ealonso

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:sf

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @lfbesada !!

Thanks a lot for this PR. In Tango we follow a [PR Etiquete.](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews) Do you mind to review it for this PR.

Thanks!!!

**Comment by lfbesada** [comment]
The failed tests are related to this pull request, I will fix it and resend it.
Regards

**Pull request closed without merging**
