### PR TITLE
LRQA-74886 Test fix for for ABTesting#DeleteSegmentABTestDraft 

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Test(s) failing:**
 * ABTesting#DeleteSegmentABTestDraft

**Error:**
`
    com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//button[contains(@class, 'dropdown-toggle btn-monospaced btn btn-outline-borderless btn-outline-secondary')]"
`

**Problem:**
 When user returns to page, AB panel is closed, so Poshi can't find element.

**Fix:**
 Added a function to open AB Test.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
