### PR TITLE
LPS-152760 Test Automation for LPS-120417: By default, the content dashboard list should NOT be filtered by Author:me

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-152760](https://issues.liferay.com/browse/LPS-152760): Test Automation for...
↳ [LPS-120417](https://issues.liferay.com/browse/LPS-120417): By default, the content dashboard list should NOT be filtered by Author:me

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
