### PR TITLE
LRQA-74442 Fix LanguageCacheData test

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74442](https://issues.liferay.com/browse/LRQA-74442)

**Test(s) failing:**
 * PageAudit#LanguageCacheData

**Error:**
`
    java.lang.Exception: Element is not present at "//span[contains(@class, 'text-secondary') and contains(@class, 'w-100') and contains(@class, 'c-inner') and contains (text(), 'Small Tap Targets')]"
`

**Problem:**
 Sidebar is closed after returning to page.

**Fix:**
 Added function to open page audit in case panel is closed.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
