### PR TITLE
[Carlos review needed] master-lps-130295 &LPS-130269&LPS-130275

### PR DESCRIPTION
**Pull request by liulukiwi**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302
https://issues.liferay.com/browse/LPS-130309
https://issues.liferay.com/browse/LPS-130310
https://issues.liferay.com/browse/LPS-130311

https://issues.liferay.com/browse/LPS-130295
https://issues.liferay.com/browse/LPS-130296
https://issues.liferay.com/browse/LPS-130297
https://issues.liferay.com/browse/LPS-130298
https://issues.liferay.com/browse/LPS-130299
https://issues.liferay.com/browse/LPS-130300
https://issues.liferay.com/browse/LPS-130301

https://issues.liferay.com/browse/LPS-130269
https://issues.liferay.com/browse/LPS-130275

### CODE REVIEW

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Thank you @liulukiwi ! I forward this pull :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
