### PR TITLE
LPS-137399 Sort languages shown in Analytics Cloud

### PR DESCRIPTION
**Pull request by YurenaC**
Alphabetically sorting language's list shown in Analytics Cloud tab by languageLabel instead of languageID

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@YurenaC make sure [tests](https://github.com/liferay/liferay-portal/blob/78d2af9ea99dc111a2d1bb2c6496ab3497b5173b/modules/apps/layout/layout-reports-test/src/testIntegration/java/com/liferay/layout/reports/web/internal/portlet/action/test/LayoutReportsDataMVCResourceCommandTest.java#L80) pass and if possible add one for this.

**Review by 4lejandrito — CHANGES_REQUESTED** [review]
See my previous comment.

**Comment by YurenaC** [comment]
@4lejandrito all test are passing for me.
I just added a specific test for the language sorting

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Review by beltranrengifo — APPROVED** [review]
🎉

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1327401_288

**Comment by YurenaC** [comment]
ci:reevaluate:1327401_288

**Comment by 4lejandrito** [comment]
ci:reevaluate:1327401_288

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
