### PR TITLE
LPS-173245 Fix paddings and scroll in the properties sidebar

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Left part of the segment editor properties sidebar is hidden.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-173245)

Proposed Solution
========
We changed some css properties so that the scroll only applies to the collapsable sections.

Steps to Verify:
----------------

1. Use a mouse or, if using a MAC go to System Settings -> General select to always show the scroll bar.
2. Navigate to People > Segments > click the "+" to add a new User Segment
3. Hover the properties of the right sidebar

Screenshots (optional):
-----------------------

how it should be

### CODE REVIEW

**Review by Mikellorza — APPROVED** [review]
It is working for me.

**Review by Stephy6 — APPROVED** [review]
LGTM 🎉

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_7371

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_7371

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_7371

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
