### PR TITLE
LPS-160790 Extract ContentDashboardItemSearchClassMapperTracker to Info Framework

### PR DESCRIPTION
**Pull request by jkappler**
### Motivation

ContentDashboardItemSearchClassMapperTracker provides a flexible way of interchanging between a searchClassName (used mainly for asset searching) and a className (used in info framework). Since it's in content dashboard other places cannot benefit from it.

The goal of the task is to extract the logic to the info framework so that it can be used in other places

More info in the task: [LPS-160790](https://issues.liferay.com/browse/LPS-160790)

### Proposed Solution

Copy logic from ContentDashboardItemSearchClassMapperTracker to InfoSearchClassMapperTracker and replace usages

### Note

No functional tests, integration tests have been provided with this PR.

Check that nothing was broken was made here: https://github.com/liferay-echo/liferay-portal/pull/9325. 
Issues with compiling tests was not related to the changes, and PR was sent here: https://github.com/liferay-tango/liferay-portal/pull/2705

### CODE REVIEW

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@cgoncas, hopefully this will pass some day :D

**Comment by jkappler** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
stable stuck again

**Pull request closed without merging**
