### PR TITLE
LPS-145565 Test fix for ContentPerformance tests using Display Page Template

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-145565](https://issues.liferay.com/browse/LPS-145565)

**Failing Test**:
 - ContentPerformance#MetricsUserWithoutPermissionsDPT
 - ContentPerformance#MetricsWithEditPermissions
 - ContentPerformance#MetricsWithEditPermissionsNotEditPage
 - ContentPerformance#MetricsWithoutEditPermissionsYesEditPage

**Motivation**:
- Tests are failing due to 'java.lang.Exception: FAIL. Cannot find structureId.' , but are working locally. Did some refactor that might solve the issue at CI.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! When using the UI, all those tests pass.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
