### PR TITLE
LRQA-73967 Test fix: add property to RemoveFragmentAndChangeBackToDefaultExperience test

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-73967](https://issues.liferay.com/browse/LRQA-73967)

**Test(s) failing:**
 * ExperienceCreateExperience#RemoveFragmentAndChangeBackToDefaultExperience

**Problem:**
Other tests were running is the same batch, and as so, it was impacting this test. 

**Solution**
Added a test.name.skip.portal.instance property, so this tests would run in another instance.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
