### PR TITLE
LPS-138336 Style adjustments for documents and media info panel in content dashboard

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-138336)

UI fixes for panel info sidebar in Content Dashboard.

- LPS-138336 Fix close button position in panel info
- LPS-138336 Fix labels UI in categorization sections inside panel info
- LPS-138336 Fix spacings in panel info sidebar first sections
- LPS-138336 Fix unit test snapshots

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1317401_195

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
