### PR TITLE
LPS-151680 Migrate to new TreeView component

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Migrate Tango trees to the new TreeView component
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151680)

Proposed Solution
========
We have adjusted the styles a little bit for the filters modals and removed the feature flag check in order to always show the new TreeView.

Steps to Verify:
----------------
1. Create some web contents and documents
1. Go to Content Dashboard
1. Filter contents by type and check that the selection tree works ok
1. Filter contents by extension  and check that the selection tree works ok
1. Open the categories filter modal and check that the width of the modal is the same than the type and extension filter modals.

Screenshots (optional):
-----------------------
The new tree view should look similar to:

Captura de pantalla 2022-05-06 a las 13 47 31

### CODE REVIEW

**Review by Stephy6 — COMMENTED** [review]
It works well for me @claraizquierdo!

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
Hi @claraizquierdo, some things I've noticed testing this:

- After selecting a value in the filter, when the user opens the filter modal again, the type previously filtered is not selected in the modal, so if the user selects another type, the previous filter is lost.
- The user can only select a filter by clicking on the checkbox, if the user clicks on the name it is not selected (not sure if this is intended or not)
-When the user opens the filter modal, only the first tree is opened, even when the user has previously filtered by a child of another tree.

This behavior is the same for Type and Extension filters.

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz, this test failed: ContentDashboard#FilterBySubtypeBlogsEntry. I think the failure is not related with the changes of this PR, but maybe we can fix it before merging

**Comment by claraizquierdo** [comment]
> 

Hi @CarlosBrichete ,

I have checked that the bug with the previously selected filters is present in master branch, but only with the type filter. So, I guess that is not related with this PR.

About the tree behaviour with selecting nodes and expanding them, this is the default behaviour. We have been discussing about this a lot and we have agreed that we are going to maintain this default behaviour and Clay is going to change this in the near future so that when we click in the node text the node gets checked. I made a comment about this in the task: https://issues.liferay.com/browse/LPS-151680?focusedCommentId=2676071&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-2676071

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
@Luizcarlosqueiroz I think that the format source is failing in the ContentDashboard.macro file. Do you mind to have a look at it?

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:stop

**Pull request closed without merging**
