### PR TITLE
LPS-152541 Use custom settings component for Segments Instance Settings

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The purpose of this PR is to implement a Custom Configuration module for Segments.
[LPS-152540](https://issues.liferay.com/browse/LPS-152540)

Proposed Solution
========
Create a ConfigurationScreen following the instructions [here](https://learn.liferay.com/dxp/latest/en/building-applications/core-frameworks/configuration-framework/completely-custom-configuration.html) that implements the new requirements

PRs:

1. https://github.com/liferay-tango/liferay-portal/pull/2550
2. https://github.com/liferay-tango/liferay-portal/pull/2555
3. https://github.com/liferay-tango/liferay-portal/pull/2560
4. https://github.com/liferay-tango/liferay-portal/pull/2562
5. https://github.com/liferay-tango/liferay-portal/pull/2570
6. https://github.com/liferay-tango/liferay-portal/pull/2573
7. https://github.com/liferay-tango/liferay-portal/pull/2575
8. https://github.com/liferay-tango/liferay-portal/pull/2577
9. https://github.com/liferay-tango/liferay-portal/pull/2583

How to test it
========

1. Go to Instance Settings > Segments > Segments Service
2. The new screen should appears.

### CODE REVIEW

**Comment by liferay-tango** [comment]
Hey @Stephy6 and @claraizquierdo !!

I have updated th PR with the changes needed to add our custom JSP, so you can contribute your code here @claraizquierdo !!

Thanks a lot for your work.

**Comment by cgoncas** [comment]
Hey @claraizquierdo and @Stephy6 !!

I have updated the PR, with the right commits.

Let me know if you have any problem, so we can send it tomorrow :)

Thanks!!

**Comment by claraizquierdo** [comment]
@cgoncas @Stephy6 the data that I need for the jsp is:

- bindConfigurationActionURL for the form action
- Url for reset default values
- Url for export
- The value of configurationModel.hasScopeConfiguration(configurationScopeDisplayContext.getScope())

**Comment by claraizquierdo** [comment]
Hello again :) I also need to know if `configurationModel.isReadOnly()` could be true for our segments settings.

**Comment by cgoncas** [comment]
Hey @claraizquierdo, @Stephy6  and @YurenaC !!

Here you hace the bind action :)

Let me know if you have any doubt :)

Thanks

**Comment by cgoncas** [comment]
Hey @claraizquierdo !!

Are you ok if I rebase this PR with master and sort the commits?

Thanks!!

**Comment by claraizquierdo** [comment]
Hey @cgoncas ,

I think that the value for the setting "Enable Assign Roles by Segment" is not being saved correctly. Could you have a look at it please? Thank you 😇

**Comment by cgoncas** [comment]
> Hey @cgoncas ,
> 
> I think that the value for the setting "Enable Assign Roles by Segment" is not being saved correctly. Could you have a look at it please? Thank you 😇

Hey @claraizquierdo !!

Could you describe the cases where it is failing? Thanks!!

**Comment by cgoncas** [comment]
> Hey @cgoncas ,
> 
> I think that the value for the setting "Enable Assign Roles by Segment" is not being saved correctly. Could you have a look at it please? Thank you 😇

For sure, we have not implement it yet, so would be awesome if it where working :P

**Comment by cgoncas** [comment]
Hey @YurenaC , @Stephy6 and @claraizquierdo!!

I have updated this PR with the changes we are trying to send in https://github.com/liferay-tango/liferay-portal/pull/2560
and https://github.com/liferay-tango/liferay-portal/pull/2562.

Thanks!!

**Comment by cgoncas** [comment]
Close it, as everything was merged into master

**Pull request closed without merging**
