### PR TITLE
LPS-128998 Dispatch loading action inside add data set items dispatch

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:bundle

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:bundle

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
