### PR TITLE
LPS-145441 Add test to ContentDashboardGroupUtil

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation*
=======
Curretly all the Documents and Web Content are retrieved from the DB (Elastic Search) every time the button (Export XLS) is clicked. We should avoid execute queries like this, so we need to paginate this query

[Link to story or ticket](https://issues.liferay.com/browse/LPS-145441)

Proposed Solution*
========
This is the first refactor for the solution,  wee have only fix a minor issue with the ContentDashboardGroupUtil class.

Steps to Verify*:
----------------
Unit test are provided (No changes have affected the UI)

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
LGTM

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
