### PR TITLE
LPS-138340 Add new test scenarios for TreeFilter

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
TreeFilter component needed more test coverage
[Link to story or ticket](https://issues.liferay.com/browse/LPS-138340)

Proposed Solution
========
We added tests to TreeFilter component and removed unnecessary tests from SelectTypeAnsSubtype and SelectExtension components.

Change summary:
---------------
* LPS-138340 Add new test scenarios for TreeFilter a remove unnecessary tests from SelectFileExtension and SelectTypeAndSubtype

### CODE REVIEW

**Review by beltranrengifo — COMMENTED** [review]
So great have this components covered, nice work Clara, thank you 🎉 
A minor suggestion, feel free to decide whatever you prefer:
I like to have the mocks in separate files, keeping shorter the test files and having the chance to reuse the mocked objects. I would create a `tree-props.js` file and export from there the items...

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]
🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
