### PR TITLE
LPS-151362-Variation Add segmentation disable warning for Variations

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
As a Marketer, I want to be warned in context when Segmentation is disabled, so that I am aware that my Segments, Experiences and Collections will not function properly without this configuration enabled.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-151362)

Proposed Solution
========
The proposed solution consists in adding the keywords needed for being able to add a warning with the correct message in Variations(Collections) and add the necessary code to render it.

Steps to Verify:
----------------
1. Go to Menu -> Control Panel -> Instance Settings -> Segments
2. In Segments click on Segments Service -> Enable Segmentation (disable it if the box is checked)
3. Go to Site Builder -> Collections
4. Add a Manual Collection and open it
5. Check that an Alert Warning message is displayed correctly
6. Repeat step 4-5 with Dynamic Collection
---------------

Screenshots (optional):
-----------------------

Screenshot 2022-05-23 at 18 32 40
Screenshot 2022-05-23 at 18 32 23

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
We made most of this changes together so LGTM

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
ci:test:relevant

**Comment by AliciaGarciaGarcia** [comment]
Hi

I checked on local and it seems that the test do not fails. I rebased your PR with my master (7b38d425ae44094c4e79cb29b0904f46c1e03c9f)

Relaunching the relevant-test to check it again

PD: (on my local works :D)

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_201

**Comment by AliciaGarciaGarcia** [comment]
ci:reevaluate:1397401_201

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
