### PR TITLE
LPS-119068 Fix Page Audit and enable it

### PR DESCRIPTION
**Pull request by dgarciasarai**

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @4lejandrito, here is the commit you request. Once the pull is ready to move forward, please, remove the draft status and run the CI. Thanks!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
@dgarciasarai, @CarlosBrichete I've added back the commit that disables the failing tests: https://github.com/liferay-tango/liferay-portal/pull/1111/commits/d5ade58710b8e703ac227dbc90ad2d6809cb199a.

**Comment by 4lejandrito** [comment]
@CarlosBrichete I don't know why but your commit causes the poshi failure. Can you have a look?

In the meantime I will send this directly to Brian without it.

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
What happen with this pull request @4lejandrito @CarlosBrichete? 🤔

**Comment by 4lejandrito** [comment]
@CarlosBrichete and I found that the test failures were caused by our code. 

I found the issue and fixed it. See https://github.com/liferay-tango/liferay-portal/pull/1111/commits/89405c393666bd560e2f9097e5420978b37eed3d.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
I think you put a wrong LPS in the last commit 89405c3 @4lejandrito

**Comment by 4lejandrito** [comment]
Gracias @dgarciasarai!

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/101252. @CarlosBrichete please verify those failures are not caused by us (which I am pretty sure not).

**Comment by 4lejandrito** [comment]
Merged!

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Pull request closed without merging**
