### PR TITLE
LPS-118823 Change alert style and copy when there is no selected vocabularies in Content Dashboard configuration

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Change alert error to alert warning and change copy to "You have not selected any vocabularies. The graph will feature the last used configuration." in Content Dashboard configuration when the user saves and the "In Use" box is empty.

**Screenshots**

Screenshot 2020-09-09 at 12 11 13 Screenshot 2020-09-09 at 12 11 26

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
I reviewed this change with @susanavr and Julia Molano 👍

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
Hey @cgoncas @darquesdev, can you review this PR? It has backend code... :) Thanks.

**Comment by cgoncas** [comment]
Hey @dgarciasarai!!

I am taking a look to this pull right now, I need to check some things with the error in the session, I let you know when the review is finished.

Thanks!!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
