### PR TITLE
LPS-140482 Filtering out Google Drive Shortcuts

### PR DESCRIPTION
**Pull request by 4lejandrito**
This filters out Google Drive Shortcuts in the Content Dashboard.

**Pending things**
- [x] Filter out the Google Drive Shortcut subtype from the types filter view.
- [x] Write integration tests.

@YurenaC @beltranrengifo I'll leave you those to you guys for now.

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:reevaluate:1337401_458

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1337401_458

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:forward

**Review by YurenaC — APPROVED** [review]

**Review by beltranrengifo — APPROVED** [review]
🎉

**Pull request closed without merging**
