### PR TITLE
LPS-144038 Move Content Dashboard tets that use AC to proper file

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-144038](https://issues.liferay.com/browse/LPS-144038)

**Test(s) failing:**
 * ContentDashboard#CloseMetricsPanel
 * ContentDashboard#ViewMetricsButtonKebabWhenDocumentHasDPT
 * ContentDashboard#ViewMetricsButtonWhenDocumentHasDPT

**Error:**
`
org.openqa.selenium.InvalidArgumentException: invalid argument   (Session info: chrome=86.0.4240.111) Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03' System info: host: 'test-1-34-42.lax.liferay.com', ip: '127.0.0.1', os.name: 'Linux', os.arch: 'amd64', os.version: '5.4.0-84-generic', java.version: '1.8.0_121' Driver info: org.openqa.selenium.chrome.ChromeDriver Capabilities {acceptInsecureCerts: false, browserName: chrome, browserVersion: 86.0.4240.111, chro...
`

**Problem:**
ContentDashboard.testcase file does not support AC properties. 

**Fix:**
A new ContentDashboardWithAC.testcase file was created to run those test properly.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
