### PR TITLE
LPS-151622 Adds new dummy step to force index update, removes the old IX_789CF949 and creates the new ones

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
====
Failed upgrade process for module com.liferay.layout.page.template.service
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151622)

Proposed Solution
====
At this moment, it is not happening because when you comes from 7.4.13, the segments service upgrade it is not executing the upgrade process, since the segments service module is in the last step (2.4.0). So, we need to create a DummyUpgradeStep to force index update, since we need to remove the old IX_789CF949 and we need to create the new ones.

Steps to Verify:
----
1. Import attached database dump, you can find it here [ticket](https://issues.liferay.com/browse/LPS-151622)
-  place attached data folder
-  clear logs, osgi/state folder
2. Run upgrade

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
