### PR TITLE
LPS-163157 View versions in side bar

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-163157)

Tango Team is working in improving the information panel in content dashboard, and one of these improvements is adding the version history of the elements in the sidebar. Since an element can have many versions, we would like to limit the amount of versions that are shown.

## Proposed Solution

Create an endpoint that can be called with a number of versions to show and the response includes the versions to display

## Change summary:

* Extract version methods to a new interface called VersionableContentDashboardItem
* Remove versions from the initial payload of info panel
* Create endpoint to retrieve versions

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
