### PR TITLE
LPS-146476 Add AC property.group to ACSegmentsInDXP

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by pyoo47** [comment]
ci:test:tango (Moving original test invocation off an overloaded server)

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
New pull: https://github.com/liferay-tango/liferay-portal/pull/2664

**Pull request closed without merging**
