### PR TITLE
LRQA-74214 Test fix for Collections#ContentMatchesSegmentCriteria

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74214](https://issues.liferay.com/browse/LRQA-74214)

**Test(s) failing:**
 * Collections#ContentMatchesSegmentCriteria

**Error:**
`
    java.lang.Exception: Element is present at "//div[contains(@data-fragments-editor-item-type,'fragments-editor-mapped-item')]//*[contains(@class,'asset-title')][normalize-space(text())='WC WebContent Title 1']"
`

**Problem:**
 Variation must be prioritized over default.

**Fix:**
 Added function to prioritize variation.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
