### PR TITLE
LPS-163043 Add tests for sidebar tabs

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Add frontend tests for version tab in the Content Dashboard sidebar
[Link to story or ticket](https://issues.liferay.com/browse/LPS-163043)

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
@CarlosBrichete @Luizcarlosqueiroz , could you help me checking if this PR breaks anything? It just adds some frontend tests but it is not passing the ci:test:sf and the ci:test:relevant :(

**Comment by CarlosBrichete** [comment]
ci:test:bundle

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo I'll take a look at the bundle, but if you are only including tests it should be fine.

**Comment by claraizquierdo** [comment]
@CarlosBrichete i just realized that there might be something wrong with the format. Sorry for the inconvenience.

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
