### PR TITLE
LPS-143047 Donut chart unexpected behavior when traffic values are too big

### PR DESCRIPTION
**Pull request by beltranrengifo**
[JIRA ISSUE](https://issues.liferay.com/browse/LPS-143047)

### Motivation
Large numbers from Analytics were displacing the Traffic Sources pie chart.
The numbers got hidden behind the pie chart.

### Solution proposed in this PR

The formatter takes care of numbers above the defined threshold (10,000) applying the `compact` option available in the `Intl.NumberFormat` API, which at this time seems compatible with all browsers supported by Liferay.
This threshold can optionally be passed as a parameter to the format function, for example:
```
numberFormat(
  languageTag,
  entry.value,
  {
    compactThreshold: 1000,
    useCompact: true,
  }
)

```
Below the threshold no format changes should be applied.

### How to verify this pr

- Cherry pick [this commit](https://github.com/beltranrengifo/liferay-portal/pull/3/commits/c6023dbb41de97eb176a2201747451d4e5dcca0d)
- Deploy `analytics-reports-web` module
- Configure AC in your instance
- Change you system date to tomorrow
- Open CPP

##### Expected:
- The pie chart is in the right place, no displaced to the right
- The numbers above the threshold (10000) are in the `compact` format
- The numbers in the pie chart tooltip are render in full format

image

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
Great work!

**Comment by beltranrengifo** [comment]
ci:test:tango

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
