### PR TITLE
LPS-134059 Duplicate tag on the dashboard

### PR DESCRIPTION
**Pull request by YurenaC**
- When multiple sites are created and the same tag name is used in two or more of them, the tag filtering in the content dashboard can be confussing. 
 - To avoid that confussion, the site name where each tags belongs to is added in brakets. 
 - Filtering can be done by tagId or tag name (only when ids are not provided)

### CODE REVIEW

**Comment by YurenaC** [comment]
@4lejandrito please review

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant
ci:test:sf

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-tango/liferay-portal/pull/1334.

**Pull request closed without merging**
