### PR TITLE
LPS-154019 The alert should be dismissible if segmentation service is disabled

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira story](https://issues.liferay.com/browse/LPS-154019)
[Figma](https://www.figma.com/file/HnjplNbAOME8rwjBVk60o2/LPS-129007-configure-segmentation-per-virtual-instance?node-id=748%3A65247)

## Motivation

Allow user to dismiss the alerts when Segmentation is disabled 

## How to

- Navigate to instance settings > Segments > Segments service > uncheck the "Enable Segmentation" checkbox
- Navigate to Homepage > open product menu > People > Segments

**A dismissible warning should appear in the main Segments list and clicking the cross make it disappear**

image

- Click on the + button to create a new segment

**A dismissible warning should appear in detail Segment page and clicking the cross make it disappear, restoring the original page height**

image

- Navigate to Site Builder > Collections > New collection

**A dismissible warning should appear in the page and clicking the cross make it disappear**

image

- Navigate to Homepage > Click on edit page btn (the pencil icon on top bar)
- Open the Experiences Selector dropdown

**A dismissible warning should appear in the dropdown and clicking the cross make it disappear**

image

In all cases, reloading the page or navigating back to them should restore the warnings!

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Updating test, rebasing and force pushing.
Running CI again

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Hi @claraizquierdo 
This [commit](https://github.com/liferay-tango/liferay-portal/pull/2528/commits/ff0d58f212443500fcefc8b69f1c6c235ae7f4cd) fixes a problem with a css class not being removed on alert close. I spotted it when unit testing 🙌

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — COMMENTED** [review]
Hi @beltranrengifo!
The code looks really good. Great job. I've only seen a pair of weir things in the experience selector:

1.  I don't think that the alert is following the styles defined in the figma: https://www.figma.com/file/HnjplNbAOME8rwjBVk60o2/LPS-129007-configure-segmentation-per-virtual-instance?node-id=748%3A100955 
 Captura de pantalla 2022-06-10 a las 12 57 40
2. If I close the alert about segmentation being disabled, another alert shows indicating that changes to experiences apply immediately. Is it the desired behavior?

**Comment by beltranrengifo** [comment]
> 1. I don't think that the alert is following the styles defined in the figma: https://www.figma.com/file/HnjplNbAOME8rwjBVk60o2/LPS-129007-configure-segmentation-per-virtual-instance?node-id=748%3A100955

Hi @claraizquierdo Thanks for your feedback
I believe we should not modify Clay alert styles, the component should render as is. Maybe we can discuss this with Susana and see if we need to inform Clay about anything... what do you think?

**Comment by beltranrengifo** [comment]
> If I close the alert about segmentation being disabled, another alert shows indicating that changes to experiences apply 
immediately. Is it the desired behavior?

I was wondering the same yesterday. As nothing is stated I prefer to deliver ir as it is and let's think the product and design teams decide in the future review from their side.
This behaviour I think has sense, anyway, because the alert about the experiences being saved immediately is always present

**Comment by beltranrengifo** [comment]
Pushed commit with styles fixes for the alert inside a dropdown

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
I have checked that the alert styles inExperiences has been fixed 👍 

I find the behavior of the alerts a little bit weird, but as it is not defined in the acceptance criteria we can continue with this behavior and change it later if needed.

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Review by Stephy6 — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
Closing & reopening due to CI persistent problems

**Comment by beltranrengifo** [comment]
ci:close

**Comment by beltranrengifo** [comment]
[See](https://github.com/liferay-tango/liferay-portal/pull/2542)

**Pull request closed without merging**
