### PR TITLE
LPS-121063 [Bug] View Members in Segments doesn't display the correct number of members after second clicking

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
When the segment is not saved yet or the conditions were changed (each time the conditions change, the members are calculated), the list of members that affect that segment is not updated or is wrong. This is not happening when the segment is already saved.

**Solution**
Remove session attribute on creation/edition and preview from the segments list  but not in the preview action inside the segment editor.

**How to test it manually**
https://issues.liferay.com/browse/LPS-121063

- Go to People > Segments
- Add a new user segment
- Drag the user to the condition field
- Select the current user
- Assert there's "Conditions Match1 Member" displayed
- Click View Members
- Assert the selected user displays
- Close the window and click View Members again
- Assert the selected user displays

**How to test it automatically**
There are integration tests for every use case. See following section.

**Test cases to verify the fix**
- Create a new user segment (as how to test it) and verify that the second time that the user clicks on View Members, the list of members is correct
- Open an existing user segment, click on View Members, check the list, go to other segment and verify that the list is different
- Open an existing user segment, click on View Members, check the list, click on new user segment and verify that the list is empty
- Open an existing user segment, click on View Members, check the list, change the conditions to match more users, click View Members again

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
Hey @cgoncas and/or @darquesdev, can you review this, please? Let me know if you need more context or anything else. Thanks! 😄

**Review by cgoncas — CHANGES_REQUESTED** [review]
Hey @dgarciasarai !!!

Maybe I am wrong, but I am not able to see any test in the resolution of this bug :(. Am I right?

If this is the case, we should mark this pull as WIP, and add some tests before starting the final reviewing process, if you think add backend test is too complex for you, @darquesdev or I will take control of the pull and add the needed tests once we re view the solution.

Thanks!!

**Comment by dgarciasarai** [comment]
Hey @cgoncas! I totally agree. I'll change this pull request to _Draft_ and marked as WIP until you or @darquesdev can add tests to this solution because I think I can't be able to do it (backend stuff, haha). Thanks for the feedback! 👍

**Comment by cgoncas** [comment]
> Hey @cgoncas! I totally agree. I'll change this pull request to _Draft_ and marked as WIP until you or @darquesdev can add tests to this solution because I think I can't be able to do it (backend stuff, haha). Thanks for the feedback! 👍

Thanks a lot for your hard work, now this bug is really close to being fixed :).

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — COMMENTED** [review]
Thanks @dgarciasarai! I'm taking the PR: adding integrations tests and covering all the use cases ;)

**Comment by darquesdev** [comment]
WIP: I still need to add more integration tests

**Comment by dgarciasarai** [comment]
Sure! Thank you so much @darquesdev. My backend knowledge is limited 😂

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
❤️

**Comment by dgarciasarai** [comment]
Hey @cgoncas, I think this pull is ready to be reviewed. @darquesdev improved the solution and added some tests. CI is all green so it seems that everything is ok. Can you review it and give some feedback? Thanks!

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
