### PR TITLE
LPS-172389 Use https://www.antlr.org/ in order to read AC grammar

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
View AC Event Segments in DXP. We intent to visualize the Event Segment Criteria of AC Segments in DXP Segments Editor.

To do so, the first requirement is to be able to read AC grammar.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-171785))
[Link to substory](https://issues.liferay.com/browse/LPS-172389))

Proposed Solution
========
AC Grammar is described here:

https://liferay.atlassian.net/wiki/spaces/ENGAC/pages/1958478097/Custom+QueryBuilder+Language+FilterStringToQueryBuilder+Documentation

And in an ANTTLR file in https://github.com/brianchandotcom/com-liferay-osb-asah-private/blob/f3fdbee4f11b639acc4045bfb2d3cdf937be860c/osb-asah-filter-parser/src/main/antlr/com/liferay/osb/asah/common/filterexpression/parser/FilterExpression.g4

We have added this FilterExpression.g4 file to the segments-asah-connector module, in order to be able to read this grammar.

Steps to Verify:
----------------
Currently there is no integration/functional tests for these changes, in a separate PR we will convert this Expression to OData, and we will add test to verify that everything is correct in that moment.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
Hi @cgoncas ,

I've testing the json returned to the Javascript and I've only found two details that might be changed in the propertyGroups field:
- In the new property group for events, the label right now is "contributor.event" and I think it should be "event".
-  In the new property group for events, the properties first element label is "downloaded-document-and-media" and it should be "Downloaded Documents and Media".

**Comment by claraizquierdo** [comment]
Hi @cgoncas,

I' not able to see any information about the event criteria in the `contributors` field that is returned to the json.
Captura de pantalla 2023-02-08 a las 13 40 03

Also, the `propertyKey` is "user-kb-article" and I don't know if that is the correct value.

**Comment by cgoncas** [comment]
This Branch can't be updated anymore, changes send in https://github.com/brianchandotcom/liferay-portal/pull/129869

**Comment by cgoncas** [comment]
> Hi @cgoncas,
> 
> I' not able to see any information about the event criteria in the `contributors` field that is returned to the json. Captura de pantalla 2023-02-08 a las 13 40 03
> 
> Also, the `propertyKey` is "user-kb-article" and I don't know if that is the correct value.

Please @claraizquierdo use the branch where you merge the backend with the frontend code

**Pull request closed without merging**
