### PR TITLE
LPS-137419 Test Autom.for to be able edit experiences. | Personalization

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137419](https://issues.liferay.com/browse/LPS-137419)

Motivation:
"As a marketer, I can edit experiences"

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by mateusralv** [comment]
@CarlosBrichete Failures unique again.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
