### PR TITLE
LPS-144063 Add missing stubs for AB Test

### PR DESCRIPTION
**Pull request by mateusralv**
Ticket:
[LPS-144063](https://issues.liferay.com/browse/LPS-144063)

Motivation:
Add missing stubs for AB Test.

Tests Add:
- DeleteButtonShows
- DeleteABTestCancel
- DeleteABTestInDXPViewInAC
- DeleteABTestInACViewInDXP

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
Ci:test:tango

**Comment by mateusralv** [comment]
ci:test:tango

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
