### PR TITLE
LPS-131187 Show Type and subtype for content listed in the Content Dashboard

### PR DESCRIPTION
**Pull request by YurenaC**
**Motivation**
As a content manager, I want to know to which Type and subtype of content each row of the list in the Content Dashboard belongs
Link to story

**Enable the feature:**
echo "enabled=B\\"true\\"" > ../bundles/osgi/configs/com.liferay.content.dashboard.web.internal.configuration.FFContentDashboardDocumentConfiguration.config
Create at least two web content of different types (web content and document)
Go to content Dashboard
Check that we have now columns type and subtype in the content table

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:relevant

**Comment by YurenaC** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Review by 4lejandrito — APPROVED** [review]

**Pull request closed without merging**
