### PR TITLE
LPS-130694 Refactor ExperienceCreateExperience testcase setup

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-130694](https://issues.liferay.com/browse/LPS-130694)

**Motivation**:
Refactor setup and teardown for ExperienceCreateExperience.testcase

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete These tests are failing due to bugs, not necessarily error in this PR (no way of knowing). I'll be closing this PR, and sending it again when bug is fixed.

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
