### PR TITLE
LPS-119966 Initial support for documents in the content dashboard

### PR DESCRIPTION
**Pull request by YurenaC**
Modifications requested by Brian in a previos PR:
- Sort params name in a new method
- Renaming getInfoItemFieldValue to getInfoFieldValue so the method name match the interface class that is returned (Keeping old method deprecated in order to allow compatibility with user custom implementation)

### CODE REVIEW

**Comment by YurenaC** [comment]
@jkappler

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
Just started reviewing :)

**Comment by jkappler** [comment]
https://github.com/liferay-tango/liferay-portal/pull/1434

**Comment by jkappler** [comment]
ci:close

**Pull request closed without merging**
