### PR TITLE
LRQA-74173 Test fix for ContentDashboardWithAC#ViewMetricsButtonKebabWhenBlogHasDPT

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74173](https://issues.liferay.com/browse/LRQA-74173)

**Test(s) failing:**
 * ContentDashboardWithAC#ViewMetricsButtonKebabWhenBlogHasDPT

**Error:**
`
 com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@class, 'dropdown-menu show')]//*[text()='View Metrics']"
`

**Problem:**
View Metrics button path has changes, therefore, it's not being found.

**Fix:**
Fixed path and improved macro.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
