### PR TITLE
LPS-119068 [Page Audit] Add tests for configuration and minor refactor

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need to increase the test coverage for layout-reports-web in order to test all the use cases that involve System/Instance and Site Settings.

**Proposed Solution**

Create a new test case LayoutReportsGooglePageSpeedSiteFormNavigatorTest

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:1197401_8075

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:1097401_4598

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
🍀

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1147401_8017

**Comment by cgoncas** [comment]
ci:reevaluate:1147401_8017

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
