### PR TITLE
LPS-165334 Move BlogsEntryContentDashboardItemTest unit test to integration test

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to task](https://issues.liferay.com/browse/LPS-165334)

Recently, Tango Team moved ContentDashboarItem to API module, with this, we can migrate the unit tests to integration tests for BlogsEntryContentDashboardItem

## Change summary:

* Migrate existing unit tests to integration tests
* Increase coverage
* Delete unit test class

## How to test

* Execute tests for BlogsEntryContentDashboardItemTest in content-dashboard-blogs-test module

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
