### PR TITLE
LPS 142530 User can move more than one vocabulary at the same time

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
User can move more than one (and more than two) vocabulary at the same time, even if those vocabularies are from different sites.
There was also a resize of the boxes when the right box was left with no options, so we also fixed that.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-142530)

Change summary:
---------------
 * LPS-142530 Disable unselectable options when selecting multiple items
 * LPS-142530 Avoid select resize when it is left with no options
 * LPS-142530 Disallow moving more than two vocabularies to the right box

Steps to Verify:
----------------
1. Go to Content Dashboard
2. Open the graph configuration
3. Leave the In use box with no vocabularies
4. Select 3 vocabularies from the Available box
5. Move them to In use box

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]
Hi @claraizquierdo !
I've reviewed and tested this PR, everything seems to work fine for me.
Good job! 🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
