### PR TITLE
LPS-125314 Different labels for AND / OR operators when combining conditions from the same filter

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

In Content Dashboard there are filters that are combined used OR operand and other filters that are combined using AND operand.

We have decided that would be cleared for the user to have different labels for OR and AND operand. 

**Propsed solution**

- Author (use OR operand) , will be displayed as Author: author1, author2

Screenshot 2021-01-12 at 15 53 15

- Subtype (use OR operand), will be displayed as Subtype: subtype1, subtype2

Screenshot 2021-01-12 at 15 52 17

**How to test it**

Preconditions: 

- Create multiple web content structures
- Create multiple users

Steps:

_Author user case_

1. Go to App Menu > Content Dashboard
2. Select Filter > Author > (multiple authors)
3. Check that the multiple authors are shown inside the same label

_Sybtype user case_

1. Go to App Menu > Content Dashboard
2. Select Filter > Subtype > (multiple subtypes)
3. Check that the multiple subtypes are shown inside the same label

_Clear user case_

1. Go to App Menu > Content Dashboard
2. Select Filter > Subtype > (multiple subtypes)
3. Click X in the subtype label
4. Check that no Subtype filter is applied.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:test:stop

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:stop

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
LGTM 🚀

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
