### PR TITLE
LPS-121105 DXP logo shown in Segments CE build

### PR DESCRIPTION
**Pull request by 4lejandrito**
Quoting previous PR:

**Description**

A DXP icon appears when creating/editing a Segment in the portal (no difference between CE and DXP). We remove that icon from the edition because you can only edit Liferay Segments through the Segments Editor, in other words, you cannot edit Analytics Cloud segments in the Segments Editor. See [LPS-121105](https://issues.liferay.com/browse/LPS-121105). 

Screenshot 2020-09-28 at 16 12 09

Also, we add some logic to differentiate CE or DXP, when the user has the portal connected with Analytics Cloud, in the Segments list (see Screenshots). If AC is not connected, the column `Source` does not appear.

**Screenshots**

* Not connected with AC (doesn't matter CE or DXP)

Screenshot 2020-09-28 at 12 15 59

* Connected with AC and Liferay DXP

Screenshot 2020-09-28 at 15 45 34

* Connected with AC and Liferay CE

Screenshot 2020-09-28 at 12 15 37

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
@CarlosBrichete can you test this before forwarding?

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
Hey @4lejandrito , it seems these changes are correctly applied in this PR, you can move it forward :)

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
