### PR TITLE
LPS-121570 This portlet could be viewed from another portlets.

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Content Performance Panel could no be viewed from Content Dashboard from users that don't have Control Panel permission.

*Steps to reproduce it*
1. Sync AC with DXP
2. Create a web content with an associated Display Page Template.
3. Create a user with the permissions:
    - Control Dashboard (all)
    - Web Content (all)
4. Login with the new user
5. Open the View Metrics option for the web content
6. Check the Metrics side panel info

**Proposed solution**

Mark the Analytics Reports portlet with _"add-default-resource=true"_

[add-default-resource](http://content.liferay.com/4.3/doc/devel/liferay_4_portlet_development_guide/multipage/ch02.html)

If the add-default-resource value is set to false, and the portlet does not belong to the page but has been dynamically added, then the user will see that he does not have permissions to view the portlet. If the add-default-resource value is set to true, the default portlet resources and permissions are added to the page. The user can then view the portlet. Most portlets are harmless and can benefit from this flexibility. However, to prevent security loop holes, the default value is false.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by dgarciasarai — APPROVED** [review]
I created a new user with these permissions within a new Role called "Content Dashboard Members":

Screenshot 2020-09-30 at 15 42 18

And now, the user can see the performance of the content from the Content Dashboard:

Screenshot 2020-09-30 at 15 45 27

Perfect @cgoncas ❤️

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
