### PR TITLE
LPS-175261 Add test to AsahBackendClient 

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
Add more test to the Http implementation for the calls to AC.

Story: [LPS-171785 View AC Event Segments in DXP](https://issues.liferay.com/browse/LPS-171785)
Technical task : [LPS-175261 Add test to AsahBackendClient
](https://issues.liferay.com/browse/LPS-175261)

Proposed Solution
========
-Add mock Http class to mock Http utility.
-Add more test to test all de integration with AC.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Review by cgoncas — APPROVED** [review]
Great Job @Mikellorza !!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:reevaluate:1387401_6632

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1297401_6502

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward:force

**Pull request closed without merging**
