### PR TITLE
LPS-145283 Copy type settings also for manual collections

### PR DESCRIPTION
**Pull request by ealonso**

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
Hi @ealonso !
Thanks for taking care of this.

I tested the functionality and everything seems to be fine.
However, I see the SF is failing.

@YurenaC and @CarlosBrichete  are going to take a look too

Thank you all!

**Comment by ealonso** [comment]
Ups sorry, I've already updated it

**Comment by ealonso** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @ealonso !!!

Could you please follow the Tango's PR Play (described [here](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews)).

Also, do you mind add a test for this issues?

Thanks!!!

**Comment by ealonso** [comment]
Will resend following the Tango's PR Play and adding a test

**Comment by cgoncas** [comment]
Awesome!!!

If you need any help with the test, let me know :)

Thanks in advance!!!

**Pull request closed without merging**
