### PR TITLE
LPS-139947 Execute several search queries to avoid hitting the index.max_result_window Elasticsearch limit

### PR DESCRIPTION
**Pull request by YurenaC**
https://issues.liferay.com/browse/LPS-139947

Error obtaining all the users of a segment using the segmentsEntryProvider.getSegmentsEntryClassPKs(segmentId, start, end) API if it contains more than 10000 users due some limitations in Elasticsearch

To avoid this error, I am changing the ODataSearchAdapterImpl.search to do several queries to the Elasticsearch maintaining the 10000 limit.

For more information see https://liferay.slack.com/archives/CLA9TDYLQ/p1632739722024700

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
Hi @jorgediaz-lr the test failures are caused by these changes. See the error [here](https://testray.liferay.com/reports/production/logs/2021-10/test-1-29/test-portal-acceptance-pullrequest(master)/457/functional-tomcat90-mysql57-jdk8/0/6/jenkins-console.txt.gz):

```
[exec] 2021-10-15 07:16:17.720 WARN  [http-nio-8080-exec-31][ProxyMessageListener:86] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
     [exec] java.lang.RuntimeException: org.elasticsearch.ElasticsearchStatusException: ElasticsearchStatusException[Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]]
     [exec] 	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:176) ~[elasticsearch-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:2011) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1988) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1745) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1702) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1672) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1128) ~[elasticsearch-rest-high-level-client-7.14.1.jar:7.14.1]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchSearchRequestExecutorImpl.getSearchResponse(SearchSearchRequestExecutorImpl.java:95) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.SearchSearchRequestExecutorImpl.execute(SearchSearchRequestExecutorImpl.java:66) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.search.ElasticsearchSearchRequestExecutor.executeSearchRequest(ElasticsearchSearchRequestExecutor.java:59) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.engine.adapter.search.SearchSearchRequest.accept(SearchSearchRequest.java:45) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.engine.adapter.search.SearchSearchRequest.accept(SearchSearchRequest.java:34) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.search.engine.adapter.ElasticsearchSearchEngineAdapterImpl.execute(ElasticsearchSearchEngineAdapterImpl.java:103) ~[bundleFile:?]
     [exec] 	at com.liferay.portal.search.elasticsearch7.internal.ElasticsearchIndexSearcher.search(ElasticsearchIndexSearcher.java:127) ~[bundleFile:?]
     [exec] 	at sun.reflect.GeneratedMethodAccessor757.invoke(Unknown Source) ~[?:?]
     [exec] 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_121]
     [exec] 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_121]
     [exec] 	at com.liferay.portal.kernel.messaging.proxy.ProxyRequest.execute(ProxyRequest.java:82) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.messaging.proxy.ProxyMessageListener.receive(ProxyMessageListener.java:58) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.kernel.messaging.InvokerMessageListener.receive(InvokerMessageListener.java:74) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.messaging.internal.SynchronousDestination.send(SynchronousDestination.java:46) ~[?:?]
     [exec] 	at com.liferay.portal.messaging.internal.sender.DirectSynchronousMessageSender.send(DirectSynchronousMessageSender.java:59) ~[?:?]
     [exec] 	at com.liferay.portal.kernel.messaging.proxy.BaseMultiDestinationProxyBean.synchronousSend(BaseMultiDestinationProxyBean.java:53) ~[portal-kernel.jar:?]
     [exec] 	at com.liferay.portal.messaging.proxy.MultiDestinationMessagingProxyInvocationHandler.invoke(MultiDestinationMessagingProxyInvocationHandler.java:58) ~[portal-impl.jar:?]
     [exec] 	at com.sun.proxy.$Proxy148.search(Unknown Source) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.IndexSearcherHelperImpl.search(IndexSearcherHelperImpl.java:70) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.searcher.IndexSearcherHelperImpl.search(IndexSearcherHelperImpl.java:42) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.indexer.IndexerSearcherImpl.doSearch(IndexerSearcherImpl.java:145) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.indexer.IndexerSearcherImpl._search(IndexerSearcherImpl.java:199) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.indexer.IndexerSearcherImpl.search(IndexerSearcherImpl.java:99) ~[?:?]
     [exec] 	at com.liferay.portal.search.internal.indexer.DefaultIndexer.search(DefaultIndexer.java:277) ~[?:?]
     [exec] 	at com.liferay.segments.internal.odata.search.ODataSearchAdapterImpl.search(ODataSearchAdapterImpl.java:150) ~[?:?]
     [exec] 	at com.liferay.segments.internal.odata.search.ODataSearchAdapterImpl.search(ODataSearchAdapterImpl.java:79) ~[?:?]
     [exec] 	at com.liferay.segments.internal.odata.retriever.OrganizationODataRetriever.getResults(OrganizationODataRetriever.java:54) ~[?:?]
     [exec] 	at com.liferay.segments.internal.criteria.contributor.UserOrganizationSegmentsCriteriaContributor.contribute(UserOrganizationSegmentsCriteriaContributor.java:70) ~[?:?]
     [exec] 	at com.liferay.segments.web.internal.portlet.action.ActionUtil.getCriteria(ActionUtil.java:53) ~[?:?]
     [exec] 	at com.liferay.segments.web.internal.portlet.action.GetSegmentsEntryClassPKsCountMVCResourceCommand.getText(GetSegmentsEntryClassPKsCountMVCResourceCommand.java:128) ~[?:?]
     [exec] 	at com.liferay.segments.web.internal.portlet.action.GetSegmentsEntryClassPKsCountMVCResourceCommand.serveResource(GetSegmentsEntryClassPKsCountMVCResourceCommand.java:71) ~[?:?]
```

**Comment by jorgediaz-lr** [comment]
ci:close

**Pull request closed without merging**
