### PR TITLE
LPS-173666 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Expected text does not match actual text in Content Dashboard pagination

Hi! :)
This pr is corresponding to this ticket: [LPS-173666](https://issues.liferay.com/browse/LPS-173666)

### Problem:
The entries number does not match the correct number of entries present in the content dashboard.

### Fix:
Test refactoring to add the correct number of entries

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 185 out of 197 jobs passed in 1 hour 35 minutes
> Click here for more details.

these failures have nothing to do with the test correction :)

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
