### PR TITLE
LPS-167441 Add context to aria-labels

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
We want to add meaningful context to the aria-labels previously included to fix this bug
[Link to ticket](https://issues.liferay.com/browse/LPS-167441)

Proposed Solution
========
Wa have added the property label to the aria-label.

Steps to Verify:
----------------

1. Open the URL
2. Navigate to People > Segments, click "+" to add a new user segment
3. Put the First Name field in the condition
4. Then add some other fields, such as Site and Organization Role, User Agent, Segment
5. Open an screen reader or open the developer tools and inspect the input of different types of properties
6. Traverse the combo boxes, edit boxes, select buttons, and/or buttons using the tab key

### CODE REVIEW

**Review by Stephy6 — COMMENTED** [review]
Done reviewing! LGTM 🎉

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1327401_7105

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
