### PR TITLE
LPS-149227 Test Fix: Change configure button path

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149227](https://issues.liferay.com/browse/LPS-149227)

**Test(s) failing:**
- PageAudit#CheckPageAuditClosedAfterLogout
- PageAudit#PageAuditWidgetPage
- PageAudit#PageAuditDisplayPage
- PageAudit#PageAuditContentPage
- PageAudit#NavigateToSiteSettingsWhenApiKeyNotConfigured
- PageAudit#PageAuditCancelButton
- PageAudit#PageAuditBackButton
- PageAudit#CheckPageAuditOpenAfterNavigation

**Error:**
`
java.lang.Exception: Element is not present at "//*[not(self::div)][contains(@class,'btn')][normalize-space()='Add Personalized Variation'][not(contains(@class,'navbar'))]"
`

**Problem:**
 Button can not be found, as path was too general.

**Fix:**
 Used a button.path path, more reusable and reliable.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:stop

**Pull request closed without merging**
