### PR TITLE
LPS-166998 Order documents and web content versions actions

### PR DESCRIPTION
**Pull request by Mikellorza**
[Task](https://issues.liferay.com/browse/LPS-166995)
[Subtask](https://issues.liferay.com/browse/LPS-166998)

## Motivation 
We need to order actions for documents and web content versions in content dashboard according to figma design

- Documents: [Figma](https://www.figma.com/file/ZpecwjhViyZGsP8hWxqOSe/LPS-134694-UX-Improvements-in-info-panels-of-content-dashboard?node-id=1163%3A378460)

- Web contents: [Figma](https://www.figma.com/file/ZpecwjhViyZGsP8hWxqOSe/LPS-134694-UX-Improvements-in-info-panels-of-content-dashboard?node-id=1166%3A390583)

## Solution proposed

Add service ranking property to the osgi annotation of the provider classes. 

## How to verify

1. Go to content dashboard and see the actions of the file and content ordered.

- Web content item version actions:

image

- File item version actions:

image

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
