### PR TITLE
LPS-117116 Add side panel for content info and metrics

### PR DESCRIPTION
**Pull request by carloslancha**
https://issues.liferay.com/browse/LPS-117116

Adding empty sidebar that could be opened and closed on Info or Metrics action click.

For now just shows a loading icon, content will be added on further tasks/prs.

This pr needs https://github.com/liferay-tango/liferay-portal/pull/40 to be merged before being forwared to avoid conflicts

**Steps to reproduce**

- Add this [configs files](https://github.com/liferay-tango/liferay-portal/files/4948229/configs.zip) to your portal
- Create a categorized Basic Web Content with an Audience and Stage.
- Go to Global Menu > Content Dashboard
- Click on the actions menu of the web content and click info.

lLnlhNRG1q

Note: Sidebar position and markup will be improved, this is just a first version we can iterate over.

### CODE REVIEW

**Comment by carloslancha** [comment]
cc @jbalsas @wincent @cgoncas @dgarciasarai

**Comment by carloslancha** [comment]
ci:test:sf

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
@cgoncas could we remove those tests for the moment? I needed to remove `setHref('#')` because if that's not an url but an anchor `event.preventDefault` doesn't work properly  in `ActionsComponentPropsTransformer` and page reloads while sidebar is opening.

We will need to update those tests once we move forward and add as href the API endpoint so... 😅

**Comment by cgoncas** [comment]
Hey @carloslancha !!

I think it is ok to remove it form now since we are still iterating :)

**Comment by cgoncas** [comment]
Also, this pull has a conflict with https://github.com/liferay-tango/liferay-portal/pull/43 :(, we need to wait until this pull is merged and rebase it because we have made changes on the view.jsp.

**Comment by carloslancha** [comment]
> Could you do it yourself, or do you need my help?

I think I can do it :)

> Also, this pull has a conflict with #43 :(, we need to wait until this pull is merged and rebase it because we have made changes on the view.jsp

Oki doki. I'm closing this pr then, removing those test, wait until https://github.com/liferay-tango/liferay-portal/pull/43 is merged, rebase and send it again to `liferay-frontend` (since I've been informed that should be the process 😄 )

Thanks!

**Comment by carloslancha** [comment]
Resent https://github.com/liferay-frontend/liferay-portal/pull/142

**Pull request closed without merging**
