### PR TITLE
LPS-157433 Error when opening Metrics at Content Dashboard	

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

Currently it is not possible to open the metrics panel in the Conent Performance Panel

### Proposal

When the endpoints URL are created in the Analytics Reports module, only the public parameters should be added, since otherwise the mvcPath of the analytics_reportal_panel.jsp will be added to them.

### How to test it

_Requirement:_

1. Connection with AC
2. 1 Web Content
3. 1 default Display Page Template related to the Web Content

_Step-by-Step:_

1. Liferay Menu > Applications > Content Dashboard
2. Hover the Web Content at table > Click 'Metrics' icon
3. Metric sidebar to open normally.

### Screencaps

Captura de pantalla 2022-07-19 a las 17 51 43

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
So good to see this working again @cgoncas !

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
cci:test:sf

**Pull request closed without merging**
