### PR TITLE
LPS-120009 The default URL should not include the I18Path

### PR DESCRIPTION
**Pull request by cgoncas**
FYI @4lejandrito

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by darquesdev — APPROVED** [review]
LGTM

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
no longer necessary

**Comment by dgarciasarai** [comment]
ci:stop

**Pull request closed without merging**
