### PR TITLE
LPS-152539 Fix back URL Link in Simulation Panel

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

When we send the PR: https://github.com/liferay-tango/liferay-portal/pull/2574, @claraizquierdo detect that the back link in Instance Settings was broken.

So in this PR we will try to solve it

### Proposed Solution

We have added a backURL parameter to the simulation panel URL, so it can be used once we build the configuration URL.

### How to test it

1. Deactivate Segmentation at instance level
2. Open a Simulation Panel
3. Click the link to Instance Settings
4. Click back in Instance Settings
5. You should be redirected to the original content page.

### Screencaps

https://user-images.githubusercontent.com/5776822/176642484-cff9b84b-6bbf-4e0e-81bf-2e3738647c70.mp4

_The red alert on the video recording is not related with these changes_

Continuation of https://github.com/liferay-tango/liferay-portal/pull/2576

/cc @claraizquierdo

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]
LGTM!

**Comment by Stephy6** [comment]
LGTM too!

**Review by Stephy6 — APPROVED** [review]

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_3861

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
