### PR TITLE
LPS-121207 Show an error when there is not a layoutDisplayPageObjectProvider

### PR DESCRIPTION
**Pull request by cgoncas**
**Description**

Content Performance info is not displayed in the Content Dashboard's Metrics side panel

**Cause**

After the changes in https://issues.liferay.com/browse/LPS-120203 and https://issues.liferay.com/browse/LPS-118906 we are not using the right canonical URL to call the AC endpoints.

**Proposed solution**

Show an error when no LayoutDisplayPageObjectProvider is associated with the page (this way we will be sure a LayoutDisplayPageObjectProvider is added to the HttpRequest as an attribute, so the canonical could be calculated).

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by dgarciasarai — APPROVED** [review]
We did it! 🎉 

Screenshot 2020-10-01 at 13 44 52

❤️

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
