### PR TITLE
LRQA-74642: Test fix for ContentPerformanceWithoutAC#MetricsInContentDashboardACDisabled

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LRQA-74642](https://issues.liferay.com/browse/LRQA-74642)

**Test(s) failing:**
 * ContentPerformanceWithoutAC#MetricsInContentDashboardACDisabled

**Error:**
`    
java.lang.Exception: Element is not present at "//span[contains(@class,'taglib-text') and contains(.,'Start Free Trial')]"
`

**Problem:**
Poshi tries to check if element is present before sidebar has open completely.

**Fix:**
Add function to wait for sidebar.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
