### PR TITLE
LPS-119068 New module for the Layouts Reports

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

This pull is based on https://github.com/liferay-tango/liferay-portal/pull/968, but I have decided to extract the sidebar code to a new module, we were thinking to do this step as the final one, but probably is better is we keep the development in a separate module.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
