### PR TITLE
LPS-137429 Test Autom. Content recommendation disabled

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-137429](https://issues.liferay.com/browse/LPS-137429)
[LPS-93726](https://issues.liferay.com/browse/LPS-93726)

**Motivation**:
Test automation: 'As a Channel Manager, I want to drive engagement by promoting content relevant to a visitor's interest'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
