### PR TITLE
LPS-161330 Add filter by expired status

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
As a content marketer, I want to filter my content by the Expired status, so that I can see all my content that is currently awaiting approval.

[LPS-155386](https://issues.liferay.com/browse/161330)

Proposed Solution
========
Add filter by expired status (web content are indexed in expired status, so no extra work needs to be done)

Steps to Verify:
----------------
1. Create a Web Content and mark it as expired
2. Go to the content dashboard
3. Filter by expired
4. Only the Expired Wen Content should be visible
 
Screencaps:
---------------

https://user-images.githubusercontent.com/5776822/187496266-e02ee3b0-8b69-47cc-be14-0bc5eb15d4b5.mp4

Notes:
---------------

No integration tests have been included because I don't think they are needed, as the expired status is a constant and the filter by status is already tested.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by jkappler — APPROVED** [review]

**Comment by jkappler** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
