### PR TITLE
LPS-117419

### PR DESCRIPTION
**Pull request by RitaSilveira**
JIRA Ticket:
LPS-117419
LPS-134022

Motivation:
Filter by tags on sites to streamline searches

### CODE REVIEW

**Comment by RitaSilveira** [comment]
https://issues.liferay.com/browse/LPS-134022, cc: @CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
