### PR TITLE
LPS-128998 Revert "LPS-128998 [Content Performance] Remove data providers from components and wait until all finished to display the data"

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

For the Content Performance panel, we decided to wait until all endpoints were settled to display the data. In the meantime, a loading indicator shows up to inform the user that the panel is loading. This decision was not so good and we lost some performance within the panel because we have between 3 and 5 endpoints to be fulfilled and the one to retrieve the traffic channels has so much cost. This is the pull request that caused the performance issues: https://github.com/brianchandotcom/liferay-portal/pull/100040.

**Solution**

This panel is now available for all types of pages and display page templates, so we decide to revert those commits to recover our previous performance for 7.4 DXP EP1/CE GA1. We will think in another way to do this without losing performance.

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Hey @cgoncas, I reverted the commits that caused the performance issues. This is the actual behavior of the sidebar panel. We recover the previous state. What do you think?

https://user-images.githubusercontent.com/15845466/112458178-d2518e80-8d5c-11eb-81d6-9a7c89807abe.mov

Thanks!

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!

That is awesome!! Thank you very much for the hard work.

Thanks!!!!

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
