### PR TITLE
LPS-114930 Remove Audit Graph feature flag

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Remove the feature flag to show the Audit Graph in the Content Dashboard.

@cgoncas @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
We can keep this pull request on hold and wait until https://github.com/liferay-frontend/liferay-portal/pull/142 is merged or I can rebase it and see if there are conflicts or not between pulls. What do you think is better @cgoncas? 

Thanks!!

**Comment by cgoncas** [comment]
> We can keep this pull request on hold and wait until [liferay-frontend#142](https://github.com/liferay-frontend/liferay-portal/pull/142) is merged or I can rebase it and see if there are conflicts or not between pulls. What do you think is better @cgoncas?

I think would be fine if rebase it, and wait until  [liferay-frontend#142](https://github.com/liferay-frontend/liferay-portal/pull/142) is merged, the CI is not in its best moment, so maybe we need to wait until tomorrow, but it is totally fine.

**Comment by carloslancha** [comment]
Yep, there will be conflicts since all `view.jsp` structure is changing in https://github.com/liferay-frontend/liferay-portal/pull/142 😅

**Comment by dgarciasarai** [comment]
Np, we can wait until that PR is merged. Thanks!

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!!

The labels that you have added to this pull just made my day, I am very happy :).

Thanks!!!

**Comment by dgarciasarai** [comment]
I just rebased this pull request, updated the branch and tried it out and it's working fine so I'm going to forward it 😄

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by carloslancha** [comment]
image
image

**Comment by dgarciasarai** [comment]
Master branch is no up-to-date 🤷‍♀️

**Comment by carloslancha** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
