### PR TITLE
LPS-138256 The info panel of custom doc types in the Content Dashboard is not showing the file name and shows "Translated into" label

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to bug](https://issues.liferay.com/browse/LPS-138256)

Proposed Solution
========
The info panel of custom doc types in the Content Dashboard was showing "Translated into" label because we were not detecting correctly Document types, so we change the way we calculate if an item is a document. The problem with the file name was fixed this way too.

We also removed the autofocus from de close panel icon.

Change summary:
---------------
* LPS-138256 Adding type to info available to be shown in content dashboard items' info panel
* LPS-138256 Hide item languages for custom document types
* LPS-138256 Remove autofocus from sidebar close button and add aria-label
* LPS-138256 Fix tests for SidebarPanelInfoView

Steps to Verify:
----------------
1. Create a custom doc type and then add a doc with that structure
1. Go to the Content Dashboard
1. Open the info panel

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by beltranrengifo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:stop

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
