### PR TITLE
LPS-134682 Test Autom. Internal Categories in Widget

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-134682
LPS-115314

**Motivation:**
Test Automation for "As a categories administrator I can flag a vocabulary for internal use only"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
