### PR TITLE
LPS-116840

### PR DESCRIPTION
**Pull request by RitaSilveira**
JIRA Ticket:
LPS-134149
LPS-116840

Motivation:
Test Automation for "Quick access to Content-related actions on the dashboard"

### CODE REVIEW

**Comment by RitaSilveira** [comment]
https://issues.liferay.com/browse/LPS-134149, cc: @CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by RitaSilveira** [comment]
fixed

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
