### PR TITLE
LPS-171840 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Element is not present when using Tags
Hi! :)
This pr is corresponding to this ticket: **[LPS-171840](https://issues.liferay.com/browse/LPS-171840)**

### Problem:
The path is not finding the element on the page

### Fix:
Manually tested behavior is correct, probably just a path fix.

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @rafaellajordao, it seems there are conflicts in the path, please rebase master and resend, thanks!

**Comment by rafaellajordao** [comment]
> Hey @rafaellajordao, it seems there are conflicts in the path, please rebase master and resend, thanks!

Hey @CarlosBrichete , I think someone else fixed this path! I tested it and the tests are passing now, I'll keep an eye out if tomorrow they'll pass the CI! :)

**Pull request closed without merging**
