### PR TITLE
LPS-145480 Not show anyone's items when combined segments from manual collections 

### PR DESCRIPTION
**Pull request by YurenaC**
**Motivation**
----------------

Bug fixing: Manual collections should not shown the items under the anyone segment if the user belongs to any other collection when combining all segments that the user belongs.

**Proposed Solution**
----------------

Modify the current implementation to remove the anyone segment items from the items shown when segments shown to the current user are combined

**Steps to Verify:**
----------------

1. Go to Site Builder > Collections
2. Create a Dynamic Collection
3. Create some variations with different content and for the previous segments
4. Create a content page with Asset Publisher and another with Collection Display widgets
5. Go to System Settings > Assets > Collections
6. Enable the combine segments option for Dynamic Collections
7. Go to the content pages

**Expected**
----------------

Only the variation's content where the user belongs to is shown. Also, the content only appear once.

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!!

Could you add tests for this PR?

Thanks!!

**Comment by YurenaC** [comment]
@liferay-echo could you please take a look at this PR, I think it lands in your area of expertise more than in Tango.
Thanks!

**Comment by YurenaC** [comment]
Fixed/included in https://github.com/liferay-tango/liferay-portal/pull/2212

**Pull request closed without merging**
