### PR TITLE
LPS-145327 Improve accesibility for categories popover in content dashboard

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation*
=======
In the Content Dashboard we need to be able to open the categories popover when navigating with the keyboard. 
[Link to ticket](https://issues.liferay.com/browse/LPS-145327)

Proposed Solution*
========
Use ClayButton instead of ClayLabel for the PopOver trigger.

Steps to Verify*:
----------------

1. Create a basic web content
2. Create one vocabulary with at least 2 categories
3. Assign the categories to the web content created in step 1.
4. Go to the Content Dashboard and try to open the categories popOver navigating with the keyboard.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant
ci:test:tango

**Review by beltranrengifo — APPROVED** [review]

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
