### PR TITLE
LPS-145967 Move previewURL calculation to D&M info api

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
We are using themeDisplay and LiferayPortletURL in Content Dashboard API (these are not correct parameters for an API)
[LPS-145967](https://issues.liferay.com/browse/LPS-145967)

Proposed Solution
========
Move previewURL code to the Document&Media Info API and remove LiferayPortletRequest and ThemeDisplay as parameters

Steps to Verify:
----------------
1.This is not a change with funtional impact so all Content Dashboard Info Panel tests should work as in the previous versions.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_1860

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
It looks great to me @cgoncas, amazing refactor!

**Review by YurenaC — APPROVED** [review]

**Comment by cgoncas** [comment]
Sending to the lima team, since they should review the changes in Document and Media

**Pull request closed without merging**
