### PR TITLE
LPS-119624 [Content Dashboard] Fix Asset Categories for Content Dashboard

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Asset Categories Item Selector is not working as expected.

**Proposed Solution**

Revert the change from itemSelectorDialog to openSelectionModal  (as proposed solution of https://github.com/liferay-echo/liferay-portal/pull/1966)

**How to test it**

1. Go to Content Dashboard
2. Click Filter by .. > Categories
3. A NOT empty dialog should appear.

LPS-119624

FYI @jbalsas

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by jbalsas** [comment]
LGTM! 👍

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
