### PR TITLE
LPS-116288 Partially Revert info panel, since it is going added with a new frontend component

### PR DESCRIPTION
**Pull request by cgoncas**
***Motivation***

Rever info panel previous work, since the content dashboard side panel is going o be added using a React Component

***Proposed Solution***

Revert all the previous commits

***How to test it***

1. Add a web content
2. Go to Content Dashboard
3. NO check is available in the row, NO info icon is shown.

/cc @carloslancha

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by carloslancha** [comment]
image

**Comment by cgoncas** [comment]
Yeahh @dgarciasarai , this commit, the same that brian SF, still makes sense, I have renamed the title as partially revert :).

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Perfect!

**Pull request closed without merging**
