### PR TITLE
LRQA-76691 Test fix for ContentDashboard#LanguageVersion

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-76691](https://issues.liferay.com/browse/LRQA-76691)

**Test(s) failing:**
 * ContentDashboard#LanguageVersion 

**Error:**
`com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "xpath=(//div[contains(@id,'fragment-')][.//*[contains(@class,'heading')]])[1]//*[contains(@data-lfr-editable-id,'element-text')]"`

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
