### PR TITLE
LPS-145480 Minor variable name fix

### PR DESCRIPTION
**Pull request by YurenaC**
Quick fix to rename variable to a more meaningful name

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
