### PR TITLE
LPS-146003 Test Autom for bug LPS-143333

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-146003](https://issues.liferay.com/browse/LPS-146003): Test Automation for LPS-143333: 'Can't edit variant using top toolbar edit button'
↳[LPS-143333](https://issues.liferay.com/browse/LPS-143333): Can't edit variant using top toolbar edit button

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
