### PR TITLE
LPS-168169 After upgrading to 7.4 personalized variations in a collections are not assigned an explicit priority (except Anyone)

### PR DESCRIPTION
**Pull request by ricardocousolr**
(Comes from https://github.com/liferay-echo/liferay-portal/pull/10253)

Motivation
=======
[LPS-141797](https://issues.liferay.com/browse/LPS-141797) introduced an upgrade step to set the priority to personalized variations, since this column was introduced as a feature. 

However, this step only set the priorities for the Anyone personalized variation (to `1`) and left the others alone (with a `null` value). 

This underspecification of the priority means that the non-Anyone personalized variations are ordered "randomly" because null values are read as `0` and the code in `EditAssetListDisplayContext#_getAssetListEntrySegmentsEntryRelJSONArray` sorts by `getPriority`. 

Note: When a user reorders the personalized variations the priority values start being set (only those personalized variations that are interacted with, not all). 

See [LPS-168169](https://issues.liferay.com/browse/LPS-168169) for reproducing steps.

Proposed Solution
========
The first part of the solution changes the upgrade step to set a value of priority for all entries. We get all entries in `AssetListEntrySegmentsEntryRel` ordered by `AssetListEntryId` and `createDate` and we go over each setting priorities starting at 0 (more precedence) and resetting to `0` when we `AssetListEntryId` changes. 

The second part of the solution adds a second criterion in `EditAssetListDisplayContext#_getAssetListEntrySegmentsEntryRelJSONArray` to sort also by `createDate`. This will cover the case when two priorities are the same (or null) and users that had already executed the previous version of the upgrade step (and haven't fiddled with the ordering in the UI).

Notes
========
* An alternative approach would be to add a new upgrade step instead of changing the current one. The code for this step wouldn't be as simple, though. The reason is that we would need to get all entries in the table sorted by `AssetListEntryId`, then `priority` and then `createDate`. But some values of `priority` could be `null` and the sorting properties of `null` values depend on the particular database manager, so there wouldn't be a simple SQL query as there is with the proposed fix.
* I haven't included any tests but I could if need. If so, let me know what would be the best information to test.

Steps to Verify:
----------------
1. Start a 7.3. Liferay.
2. Create a couple of segments.
3. Create a collection (the type is irrelevant: dynamic or manual).
4. Create a personalized variation for Anyone and the two created segments.
5. Stop the installation.
6. Upgrade to 7.4/master.
7. Check the table `AssetListEntrySegmentsEntryRel` and notice there's a new column Priority.
8. Check that all entries in the table have an assigned value of `priority`, with lowest value (`0`) for the entry with more recent `createDate`. The entry associated with Anyone (`segmentEntryId` equal to `0`) should have the highest value of `priority`.

Checklist (optional):
========
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works [see second note above]
- [ ] New and existing unit tests pass locally with my changes [I ran test in a self-pr and the errors I got don't seem related]
- [ ] Any dependent changes have been merged and published in downstream modules [doesn't apply]

### CODE REVIEW

**Comment by cgoncas** [comment]
Hey @ricardocousolr !!

The PR looks good so far, I will create a new Step, so old installations can update the priority too.

Thanks!!!

**Comment by cgoncas** [comment]
Hey @ricardocousolr !!!

I have added a new commit to your PR: https://github.com/liferay-tango/liferay-portal/pull/3022/commits/fb13e0176ebf258d211aea514b38c926dfc22053

It add two new upgrade steps:

1. Set all priorities as -1 when priority is NULL
2. Your upgrade process sorted by priority too.

What do you think?

**Comment by ricardocousolr** [comment]
Hi @cgoncas!

I think it's a nice solution that makes sure that all customers have the correct priorities in the database and overcomes the problem of how different databases use the NULL value. 

With this, do you want to keep the commit [0a485cb](https://github.com/liferay-tango/liferay-portal/pull/3022/commits/0a485cbe1802d4d8e8fc6c253234fcdb2e1551fe) that sorts by createDate in case two priorities coincide (which shouldn't happen in theory)?

**Comment by cgoncas** [comment]
> Hi @cgoncas!
> 
> I think it's a nice solution that makes sure that all customers have the correct priorities in the database and overcomes the problem of how different databases use the NULL value.
> 
> With this, do you want to keep the commit [0a485cb](https://github.com/liferay-tango/liferay-portal/pull/3022/commits/0a485cbe1802d4d8e8fc6c253234fcdb2e1551fe) that sorts by createDate in case two priorities coincide (which shouldn't happen in theory)?

I think we should keep it, maybe there are some cases we are not taking into account, even if I can't recall any of them.

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
> > Hi @cgoncas!
> > I think it's a nice solution that makes sure that all customers have the correct priorities in the database and overcomes the problem of how different databases use the NULL value.
> > With this, do you want to keep the commit [0a485cb](https://github.com/liferay-tango/liferay-portal/pull/3022/commits/0a485cbe1802d4d8e8fc6c253234fcdb2e1551fe) that sorts by createDate in case two priorities coincide (which shouldn't happen in theory)?
> 
> I think we should keep it, maybe there are some cases we are not taking into account, even if I can't recall any of them.

Hey @ricardocousolr !!

After the SF problem, I have decided to NOT sort by createDate, the code looks very ugly to complain SF rules, and I haven't found a use case where we need to do it.

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:1297401_5475

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
