### PR TITLE
LPS-136430 Test Autom. Rediret to site settings

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-136430
LPS-136430

**Motivation:**
Test Automation for "When I get the invalid API error in the Page Audit panel I want to be redirected to Site settings so I can fix the problem"

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
