### PR TITLE
LPS-149459 Removes deprecated methods, classes and constants from segments-api and segments-service

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
Since we are working on creating the default experience as a regular one and we need to update all places where we are using the default experience (**SegmentsExperienceConstants.ID_DEFAULT**) we are removing all deprecated code to avoid unnecessary updates.

[Link to the issue](https://issues.liferay.com/browse/LPS-149459) 

Proposed Solution
========
Removes all deprecated methods, classes and constants from segments-api and segments-service

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:stop

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
c:test:sf

**Comment by ealonso** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @ealonso !!!

I am going to send this PR to Brian, and then I will review https://github.com/liferay-tango/liferay-portal/pull/2293.

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by ealonso** [comment]
Hey @cgoncas,

Are we waiting for tango test? or we can forward it to Brian

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
