### PR TITLE
LPS-150725 Mix all asset queries with a should clause, so they can work together

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

Activating the setting of "Combine Assets from All Segments in Asset Publisher for Dynamic Collections" is mixing all Contents from all existing collections in Asset Publishers mapped to a collection.

### Proposal

I have added two new methods _search_ and _searchCount_ to the AssetHelper API, this new methods receive a _list of assetQueries_, so we can call the AssetHelper with the fullQueries of every assetQuery using the clause should (
that works like a OR), so we won't mix results.

### How to test it

1. Create a new Structure with some fields. Let's call it Structure 1
1. Create one Content using this new Structure
1. Create another Content using the Basic Web Content Structure
1. Configure a Collection to filter all contents belonging to the Structure 1
1. Configure another Collection to filter all contents belonging to the Basic Web Content structure
1. Create a page and add a Asset Publisher into it and connect it to the first Collection. Publish it
1. Confirm that by default, you only see contents created with the Structure 1
1. Change the setting in System Settings > Assets > Collection: check "Combine Assets from All Segments in Asset Publisher for Dynamic Collections"
1. Refresh the page
1. You still see the same amount of contents: only the one that is based on the structure that is filtered in the Collection and connected in the Asset Publisher

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:echo

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:echo

**Comment by cgoncas** [comment]
Hey @rafaellajordao and @Luizcarlosqueiroz !!!

Could take a look to this PR, so we can be sure that this PR doesn't add new bugs for collections?

Thanks!!!

**Comment by cgoncas** [comment]
Hey @david-gutierrez-mesa!!

Could you take a look to the failing Echo tests so we now if they are failing for the changes in this PR?

Thanks!!

**Comment by cgoncas** [comment]
> * 1. [LocalFile.ContentPagesWithExperiencePersonalization#ViewCollectionItemsOnContentPageWhenSelectSegment](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116096//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/LocalFile.ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/LocalFile.ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/jenkins-console.txt.gz)
> *

I think that maybe [LocalFile.ContentPagesWithExperiencePersonalization#ViewCollectionItemsOnContentPageWhenSelectSegment](https://test-1-27.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/116096//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment_) - [Poshi Report](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/LocalFile.ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment/index.html.gz) - [Poshi Summary](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/LocalFile.ContentPagesWithExperiencePersonalization_ViewCollectionItemsOnContentPageWhenSelectSegment/summary.html.gz) - [Console Output](https://testray.liferay.com/reports/production/logs/2022-07/test-1-26/test-portal-acceptance-pullrequest(master)/4009/functional-tomcat90-mysql57-jdk8/5/8/jenkins-console.txt.gz)

Is a little suspicious :P

Could you describe the steps for this test?

**Comment by cgoncas** [comment]
> Hi @cgoncas
> 
> LocalFile.ContentPagesWithExperiencePersonalization#ViewCollectionItemsOnContentPageWhenSelectSegment is failing due to https://issues.liferay.com/browse/LPS-156839. Not related with this PR.
> 
> I'm doing analysis of Echo routine. I'll let you know as soon as I finish.

Thanks a lot @david-gutierrez-mesa !!!

**Comment by david-gutierrez-mesa** [comment]
Hi again @cgoncas 

No test failing in the echo test suite is related to your changes in this PR.

cc @Luizcarlosqueiroz

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by ealonso** [comment]
Hey @cgoncas,

Everything looks good to me.

My only concern is about groupIds, so adding a new tests that check it, should be really good, something like:

```
assetQuery1 -> groupId1
assetQuery2 -> groupId2
```

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> Hey @cgoncas,
> 
> Everything looks good to me.
> 
> My only concern is about groupIds, so adding a new tests that check it, should be really good, something like:
> 
> ```
> assetQuery1 -> groupId1
> assetQuery2 -> groupId2
> ```

Hey @ealonso !!

I have updated the PR with the required test, I want to add more test, but they are complex and I would prefer to send it in another PR.

Thanks!!

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by beltranrengifo** [comment]
@cgoncas what is expected after step 9? the collection being displayed in the AP should be the same as before, same items, right? Just to confirm, thxs

**Comment by cgoncas** [comment]
> @cgoncas what is expected after step 9? the collection being displayed in the AP should be the same as before, same items, right? Just to confirm, thxs

Yeahh @beltranrengifo I have updated the PR description :)

Thanks a lot for notice :)

**Review by beltranrengifo — APPROVED** [review]
hi @cgoncas !
the asset publisher behaviour is the expected, as far as I can test, in my opinion we can send this to the QA team for verification, can't we?

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
> hi @cgoncas ! the asset publisher behaviour is the expected, as far as I can test, in my opinion we can send this to the QA team for verification, can't we?

Hey @beltranrengifo !!

Luiz and David have already  reviewed this PR.

Thanks!!

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:reevaluate:1337401_2034

**Comment by cgoncas** [comment]
ci:reevaluate:1287401_3695

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
