### PR TITLE
LPS-117341 Solution when several categories applied to the same content

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

The content can be categorized with multiple categories and this could generate a scale problem in each row. To avoid this, we change the way that the categories are displayed as labels in the rows. We display the first category and then a label with "..." and a tooltip indicating the other categories for that content.

**Screenshot**

Screenshot 2020-07-27 at 16 07 11

@cgoncas @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @cgoncas @darquesdev,
I provide a solution with my little backend skills for this story but I think it can be improved (hope so 🙏). I left this pull request as a draft. I'm not proud of this code 😂

**Comment by cgoncas** [comment]
Hey @dgarciasarai !!

Is not the most beautiful solution I have ever seen, but I think it is good enough :)

Forward it, if you are ok with it.

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
@cgoncas I am not proud of this code... 😂 I hope it will be a better solution 🙏 .
If you think it's good enough for now...Let's forward it 🤷‍♀️ The CI is all in green now.

**Comment by dgarciasarai** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
See https://github.com/brianchandotcom/liferay-portal/pull/91915#issuecomment-665172722

**Comment by dgarciasarai** [comment]
@cgoncas @darquesdev we have to look for a better solution here 😞

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
ci:forward

**Comment by dgarciasarai** [comment]
Thanks @cgoncas!!

**Pull request closed without merging**
