### PR TITLE
LRAC-7404 analytics-reports-web: add OSB-Asah-Project-ID header

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**
https://issues.liferay.com/browse/LRAC-7404

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by darquesdev — APPROVED** [review]
Thanks @rachaelkoestartyo. LGTM! you can forward it ;)

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
