### PR TITLE
LPS-138572 Site name not showing correctly after subtypes in the type/subtype filter in the Content Dashboard

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:forward

**Review by YurenaC — APPROVED** [review]

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:reevaluate:1297401_178

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
