### PR TITLE
LPS-124743 Change top referral help messages accordingly to the actual number of pages/domains, 10

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**:
Update the number of pages/domains in the help messages with the right value of **10**. Currently, the info is wrong:

Top referring pages from 30 to 10
image

Top referring domains from 5 to 10
image

**Solution**: 
[Change copies
](https://github.com/liferay-tango/liferay-portal/pull/666/commits/d928d62d9880fdd765e8bf7991a291434d758a1e)

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:abort

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by dgarciasarai — APPROVED** [review]
LGTM 🚀 

Also, frontend tests are passing successfully 😄 

Screenshot 2020-12-10 at 16 30 39

Thanks! ❤️

**Comment by dgarciasarai** [comment]
These changes should be backported to 7.3.x.

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
ci:forward

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Manually forwarded [here](https://github.com/brianchandotcom/liferay-portal/pull/96808) 

Please, see [slack's thread](https://liferay.slack.com/archives/C19PWQ74J/p1607619984249000?thread_ts=1607606653.244500&cid=C19PWQ74J)

**Pull request closed without merging**
