### PR TITLE
LPS-166779 Change aria-checked for aria-current and delete unnecessary role

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Ensures ARIA attributes are allowed for an element's role in the experiences list
[Link to story or ticket](https://issues.liferay.com/browse/LPS-166779)

Proposed Solution
========
Change aria-checked for aria-current and delete unnecessary role

Steps to Verify:
----------------
1. Make the experience modal always open by changing this code in the ExperienceSelector.js file:
`{open && (
				<ReactPortal className="cadmin">`
to:
`{true && (
				<ReactPortal className="cadmin">`
1. deploy the layout-content-page-editor-web module
1. Go to the page editor and create one experience
1. Audit the page accessibility with the axe DevTools plugin for Chrome

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by Stephy6 — APPROVED** [review]
Hi @claraizquierdo ! The ARIA issue isn't shown anymore, so LGTM!

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:reevaluate:1287401_4967

**Comment by beltranrengifo** [comment]
> # Motivation
> Ensures ARIA attributes are allowed for an element's role in the experiences list [Link to story or ticket](https://issues.liferay.com/browse/LPS-166779)
> 
> # Proposed Solution
> Change aria-checked for aria-current and delete unnecessary role
> 
> ## Steps to Verify:
> 1. Make the experience modal always open by changing this code in the ExperienceSelector.js file:
>    `{open && ( <ReactPortal className="cadmin">`
>    to:
>    `{true && ( <ReactPortal className="cadmin">`
> 2. deploy the layout-content-page-editor-web module
> 3. Go to the page editor and create one experience
> 4. Audit the page accessibility with the axe DevTools plugin for Chrome

hi @claraizquierdo !
when testing this issue, what is expected in the final results? I can't find the same error stated in the issue in Axe tool, but maybe I'm looking in the wrong place.
On the other hand, I see other stuff like:
`.dropdown-menu__experience.list-group-item[role="listitem"]:nth-child(1)` in `<li aria-checked="false" role="listitem" class="d-flex dropdown-menu__experience list-group-item">`
 Fix the following:
ARIA attribute is not allowed: aria-checked="false"
Maybe this is what you commented about Echo team solving other stuff
image

**Comment by claraizquierdo** [comment]
> > # Motivation
> > Ensures ARIA attributes are allowed for an element's role in the experiences list [Link to story or ticket](https://issues.liferay.com/browse/LPS-166779)
> > # Proposed Solution
> > Change aria-checked for aria-current and delete unnecessary role
> > ## Steps to Verify:
> > 
> > 1. Make the experience modal always open by changing this code in the ExperienceSelector.js file:
> >    `{open && ( <ReactPortal className="cadmin">`
> >    to:
> >    `{true && ( <ReactPortal className="cadmin">`
> > 2. deploy the layout-content-page-editor-web module
> > 3. Go to the page editor and create one experience
> > 4. Audit the page accessibility with the axe DevTools plugin for Chrome
> 
> hi @claraizquierdo ! when testing this issue, what is expected in the final results? I can't find the same error stated in the issue in Axe tool, but maybe I'm looking in the wrong place. On the other hand, I see other stuff like: `.dropdown-menu__experience.list-group-item[role="listitem"]:nth-child(1)` in `<li aria-checked="false" role="listitem" class="d-flex dropdown-menu__experience list-group-item">` Fix the following: ARIA attribute is not allowed: aria-checked="false" Maybe this is what you commented about Echo team solving other stuff image

Hi @beltranrengifo , this PR is supposed to fix that bug. Do you still reproduce it?

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_6007

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1257401_5223

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
