### PR TITLE
LPS-138206 Test Autom. Failing Elements Details

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-138206](https://issues.liferay.com/browse/LPS-138206)
[LPS-132234](https://issues.liferay.com/browse/LPS-132234)

**Motivation**:
Test automation: 'As a content manager, I want to know the detail of the failing elements affecting my page'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
