### PR TITLE
LPS-144036 Test Autom. Documents metadata in content dashboard

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-144036](https://issues.liferay.com/browse/LPS-144036)
[LPS-119966](https://issues.liferay.com/browse/LPS-119966)

**Motivation**:
Test automation: 'Retrieve documents'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
