### PR TITLE
LPS 145336 Increment categories PopOver maximum height

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Depending on the navigator that the user is using we may no be able to see the categories popover scroll. In order to let the user know that there is more content to see, we need to increment the categories PopOver height so that we can see the half of the next labels. 
[Link to story or ticket](https://issues.liferay.com/browse/LPS-145336)

Proposed Solution
========
We have incremented the categories popover maximum height so that the user can see a little bit of the next categories.

Steps to Verify:
----------------
1. Add a vocabulary with aprox. 14 categories
1. Add a basic we content and assign it all the 14 categories created in step 1
1. Go to content dashboard and in the configuration select the vocabulary created in step 1
1. Check the table with all the contents

Change summary (optional):
---------------
* - LPS-145336 Increment categories popover max height

Screenshots (optional):
-----------------------

Captura de pantalla 2022-01-13 a las 17 14 11

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
🎉

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
