### PR TITLE
LPS-150720 Call JS Component Directly from the Control Menu button

### PR DESCRIPTION
**Pull request by claraizquierdo**
### Motivation

Performance problem with Experiments Panel

### Proposed Solution

Call the JS Component directly, so we don't need to run the JSP dispach (It takes a lot of time)

### How to test it

1. Connect to AC
2. Go to a Content Page (for example Home)
3. Open the A/B Testing Panel
4. Everything works fine.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Resolve conflicts in `ConnectToAC` component, rebased and push -f

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @Luizcarlosqueiroz @rafaellajordao!!

The Tango failing tests are related with this PR?

Thanks!!

**Comment by Luizcarlosqueiroz** [comment]
Hey @cgoncas! At our suite, those tests are failing differently" from our regular suite. And some are failing only in this PR. 
image

**Comment by beltranrengifo** [comment]
Test creation is failing locally using master.
IIRC yesterday this was working

image


```
Caused by: javax.portlet.PortletException: processAction method not implemented
	at javax.portlet.GenericPortlet.processAction(GenericPortlet.java:223) ~[portlet.jar:3.0.1]
	at com.liferay.portal.kernel.portlet.LiferayPortlet.callActionMethod(LiferayPortlet.java:187) ~[portal-kernel.jar:?]
	... 196 more
```

**Comment by cgoncas** [comment]
We need to fix the bugs in master, before we try to merge this PR.

**Comment by claraizquierdo** [comment]
Hi @cgoncas @beltranrengifo ! 

I'm now able to create an ab test. Have those bugs been solved so that we can try to pass this PR again?

**Comment by cgoncas** [comment]
Can you send this PR: https://github.com/liferay-tango/liferay-portal/pull/2721 to Brian directly? It solves AB testing problems, but It is stuck on the CI :(

**Comment by beltranrengifo** [comment]
Keep an eye on this 
https://issues.liferay.com/browse/LPS-162472

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
@CarlosBrichete @Luizcarlosqueiroz could you have a look at the failing tests in the tango suit? I don't know if there is something broken related with this PR.

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo, all the AC-related tests are failing in CI due to an Analytics Cloud failure in osb-asah-private-faro. Until this is solved, we have no way to know if the tests are failing because of this PR's changes or not :( We can try to test these changes manually and locally using an AC instance.

**Comment by claraizquierdo** [comment]
@CarlosBrichete Would you or @Luizcarlosqueiroz test it locally? 🙏 👼

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz Can you test this PR manually using a local AC instance? at least the most smoke tests, just to be sure this is not broking anything. Thanks!

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @claraizquierdo! AC is working locally and at CI again!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
