### PR TITLE
LPS-151399 Fix Content performance panel in Content Dashboard

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Can't open Metrics sidebar at Content Dashboard
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151399)

Proposed Solution
========
Set isPanelStateOpen to true when we are in the Content Dashboard. This is a quick fix, we are currently developing a better one but we will need more time.

Steps to Verify:
----------------
1. AC connection
2. Display Page Template 
3. Web Content associated with this DPT
4. Go to home page, open the content performance panel, check that it works and then close it
5. Go to Content Dashboard (Menu > Applications > Content > Content Dashboard)
6. At Content, click on toggle menu > click 'View Metrics'

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by YurenaC — APPROVED** [review]
Quick fix that will solve the problem right now

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by brianchandotcom** [comment]
@CarlosBrichete @YurenaC @claraizquierdo I merged this manually to master and the temp branch.

**Review by CarlosBrichete — APPROVED** [review]

**Review by cgoncas — APPROVED** [review]

**Comment by cgoncas** [comment]
Closed, since it is merged on master.

**Pull request closed without merging**
