### PR TITLE
LPS-149605: Test fix for test related to ABTest sidebar path

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149605](https://issues.liferay.com/browse/LPS-149605)

**Test(s) failing:**
 * LocalFile.ABTesting#CheckABTestPanelInfoNotSyncAC
 * LocalFile.ABTestWithoutACConnection#CheckHiddenABTestPanel

**Error:**
`
java.lang.Exception: Element is not visible at "//h4[contains(.,'Sync to Liferay Analytics Cloud')]"
`
`
java.lang.Exception: Element is not visible at "//a[contains(@class,'d-block')]//*[contains(text(),'Do not show me this again.')]"
`

**Problem:**
 The path was finding two elements (one for AB, and other for Content Performance).

**Fix:**
 Added a single path for AB.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
