### PR TITLE
LPS-123845 Fix unnecessary nesting generated by backend parser

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======

The structure used when creating the criteria with different conditions should remain the same after saving the segment. This [PR](https://github.com/liferay-tango/liferay-portal/pull/2066) is nesting the different conditions one inside the previous one, one time and another.

So, the easiest way to reproduce it is:

[Link to story or ticket](https://issues.liferay.com/browse/LPS-123845)

Proposed Solution
========
We reviewed and rewrite some sections of the backend parser in order to be able to manage this information, avoiding unnecessary nesting when several same-type operations are chained (Eg: A and B and C and D)

Steps to Verify:
----------------
1. Go to the segment edit and create a new User Segment called "4 criteria at the same level"
2. Drop 4 conditions at the same level, for example 4 User > Date modified
3. Check that all conditions are at the same level (no nesting)
4. Save the segment and click on it to see the detail
5. The nesting structure has changed, and now the last conditions **has not** been nested in the previous one and so on

Change summary:
---------------

1. LPS-123845 Remove odata-v4-parser library
2. LPS-123845 Remove translateQueryToCriteria use
3. LPS-123845 Check conjunction name in lowercase
4. LPS-123845 Localize true/false values
5. LPS-123845 Fix tests
6. LPS-123845 Fill initialQuery with the right structure, so we avoid calling the parser in the frontend side.
7. LPS-123845 Add test.
8. LPS-123845 Auto sf vintage code
9. LPS-123845 Refactor in order to avoid unnecessary operations nesting and simplify the resulting JSON
10. LPS-123845 Added tests for nested and not nested operations

Screenshots:
-----------------------
Videos of expected and wrong behaviour in [here](https://github.com/liferay-tango/liferay-portal/pull/795#issuecomment-766735603)

Checklist:
========
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @YurenaC !!!

Do you mind create a PR withe just the commits:

- LPS-123845 Refactor in order to avoid unnecessary operations nesting … 
- LPS-123845 Added tests for nested and not nested operations

Thanks!!!

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_2006

**Comment by YurenaC** [comment]
ci:reevaluate:1327401_2006

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Review by cgoncas — APPROVED** [review]
LGTM

**Pull request closed without merging**
