### PR TITLE
LPS-153687 Adding frontend components

### PR DESCRIPTION
**Pull request by beltranrengifo**
### Motivation

As a content marketer, I want to see all my collaborators after sharing an asset, so that I can easily view and manage my collaborators on a specific asset.

### Proposed Solution

This solution use the same approach described in https://github.com/liferay-tango/liferay-portal/pull/2612.

We have created ManageCollaborators component which displays the button generated in the backend using the Sharing JSP taglib.

### How to test it

- Activate FFs
  - feature.flag.LPS-153687=true (for this particular PR and functionality)
  - feature.flag.LPS-152906=true (for this [other correlated functionality](https://github.com/liferay-tango/liferay-portal/pull/2634), already merged in master)
- Deploy needed modules
- Create a blog post, add some documents, add a web content and a user to share the items with:
  - the blog post and the documents should render a Share button
  - once used and shared with anyone, the manage collaborators component should appear
- the web content should NOT display nor the share button nor the manage collaborators component

image
 
image

### Other
As we are using Typescript in one component, a SF check `JSONPackageJSONRedundantDependenciesCheck` has been disabled for this module [in this commit](https://github.com/liferay-tango/liferay-portal/pull/2637/commits/f2c91dee9f662fa55cd39baa74eb605f0f196149) to avoid the dependency removal from the package.json of the `frontend-js-web` module.

Not doing so will throw an error on module deploy:

```
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: "development"
src/main/resources/META-INF/resources/js/components/SidebarPanelInfoView/ManageCollaborators.tsx(15,42): error TS2307: Cannot find module 'frontend-js-web' or its corresponding type declarations.
test/js/components/SidebarPanelInfoView/ManageCollaborators.test.tsx(16,42): error TS2307: Cannot find module 'frontend-js-web' or its corresponding type declarations.
Command /Users/beltranrengifo/Dev/Liferay/lr-portal/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/tsc --emitDeclarationOnly exited with code 2
```

[See](https://liferay.slack.com/archives/CNBG06JS3/p1656581472573019) thread in Slack

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
we

> ### ❌ ci:test:sf - 0 out of 1 jobs passed in 16 minutes
> Click here for more details.

We need [this commit available](https://github.com/liferay-tango/liferay-portal/pull/2636/commits/8fb468b727340bced12d3f5ba2570f0f73a794e7) to pass the SF suite

**Comment by beltranrengifo** [comment]
@Stephy6 Fixed, rebased and force pushed. Ready for review, on my side is working all perfectly 👌

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
@Stephy6 y @beltranrengifo !!!

tenéis q quitar el exclude del SF

**Comment by beltranrengifo** [comment]
> @Stephy6 y @beltranrengifo !!!
> 
> tenéis q quitar el exclude del SF

Hello @cgoncas !!
Imagino que te refieres a [este commit](https://github.com/liferay-tango/liferay-portal/pull/2637/commits/f2c91dee9f662fa55cd39baa74eb605f0f196149)

Según [conversaciones](https://liferay.slack.com/archives/CNBG06JS3/p1656581472573019) de Bryce  y Pablo, desde que el SF empezó a borrar contenido, para usar TS hay que añadir esa línea, me temo

**Comment by cgoncas** [comment]
> > @Stephy6 y @beltranrengifo !!!
> > tenéis q quitar el exclude del SF
> 
> Hello @cgoncas !! Imagino que te refieres a [este commit](https://github.com/liferay-tango/liferay-portal/pull/2637/commits/f2c91dee9f662fa55cd39baa74eb605f0f196149)
> 
> Según [conversaciones](https://liferay.slack.com/archives/CNBG06JS3/p1656581472573019) de Bryce y Pablo, desde que el SF empezó a borrar contenido, para usar TS hay que añadir esa línea, me temo

Yeahhh

**Comment by beltranrengifo** [comment]
> > > @Stephy6 y @beltranrengifo !!!
> > > tenéis q quitar el exclude del SF
> > 
> > 
> > Hello @cgoncas !! Imagino que te refieres a [este commit](https://github.com/liferay-tango/liferay-portal/pull/2637/commits/f2c91dee9f662fa55cd39baa74eb605f0f196149)
> > Según [conversaciones](https://liferay.slack.com/archives/CNBG06JS3/p1656581472573019) de Bryce y Pablo, desde que el SF empezó a borrar contenido, para usar TS hay que añadir esa línea, me temo
> 
> Yeahhh

Ok to proceed with that @cgoncas ?

**Comment by cgoncas** [comment]
> > > > @Stephy6 y @beltranrengifo !!!
> > > > tenéis q quitar el exclude del SF
> > > 
> > > 
> > > Hello @cgoncas !! Imagino que te refieres a [este commit](https://github.com/liferay-tango/liferay-portal/pull/2637/commits/f2c91dee9f662fa55cd39baa74eb605f0f196149)
> > > Según [conversaciones](https://liferay.slack.com/archives/CNBG06JS3/p1656581472573019) de Bryce y Pablo, desde que el SF empezó a borrar contenido, para usar TS hay que añadir esa línea, me temo
> > 
> > 
> > Yeahhh
> 
> Ok to proceed with that @cgoncas ?

The PR can’t be send to Brian with that commit, please, delete it and then forward it

**Comment by beltranrengifo** [comment]
But the module won't deploy other way 🤷

**Comment by beltranrengifo** [comment]
> > But the module won't deploy other way 🤷
> 
> Have you try it today?

Yeah! The SF command `JSONPackageJSONRedundantDependenciesCheck`is removing the import of the `frontend-js-web` so TS wont compile as the compiler cant find the type definitions. It results in this error:

```
$ liferay-npm-scripts build
Using pre-existing NODE_ENV: "development"
src/main/resources/META-INF/resources/js/components/SidebarPanelInfoView/ManageCollaborators.tsx(15,42): error TS2307: Cannot find module 'frontend-js-web' or its corresponding type declarations.
test/js/components/SidebarPanelInfoView/ManageCollaborators.test.tsx(16,42): error TS2307: Cannot find module 'frontend-js-web' or its corresponding type declarations.
Command /Users/beltranrengifo/Dev/Liferay/lr-portal/liferay-portal/modules/node_modules/@liferay/npm-scripts/node_modules/.bin/tsc --emitDeclarationOnly exited with code 2
```

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
@cgoncas @Stephy6 I'm thinking about forwarding this pr, my manual testing was successful and double checked

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
