### PR TITLE
LPS-125730 Fix style in segment editor sidebar

### PR DESCRIPTION
**Pull request by edalgrin**
**This PR Fixes:**
- https://issues.liferay.com/browse/LPS-125730 Visual glitch on new Segment accordion closed
- https://issues.liferay.com/browse/LPS-94137 Lines in Accordions disappear with smaller screens
- https://issues.liferay.com/browse/LPS-103957 The animation have a different behaviors in segments editor contributors

I had to refactor most of the CSS code and remove a few extra markup we didn't need.

**Result:**
ezgif com-gif-maker (1)

I managed to fix the animation with search filters but it's not optimal. The opened accordion is taking more space than needed but it's not necessarily a bug

image

---

**Notes:**
- removed the nesting of the CSS classes to decrease their specificity
- removed the utility classes from the markup since we are using dedicated CSS where we can add those rules

**Clay:**
I tried to [upgrade the code to ClayPanel](https://github.com/edalgrin/liferay-portal/pull/115/files) but the API are not ready to support this case (missing the callback function, we are working on it https://github.com/liferay/clay/pull/3760)

**Accessibility:**
Since we will need to upgrade it to `ClayPanel` and the drag-and-drop function is not accessible, I didn't add the missing accessibility attributes.

**Responsive:**
The page needs to be reviewed. Issues in `width: 320px` and other undefined breakpoints

### CODE REVIEW

**Comment by edalgrin** [comment]
@dgarciasarai Please, take a look 😁

**Comment by marcoscv-work** [comment]
LGTM!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Thanks @edalgrin!! I'll take a look and try the changes to see if everything works fine!! Thanks for the contribution!!

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
Hey @edalgrin, just to clarify. We can't use `ClayPanel` at the moment because when you open a section, the other ones opened, remains opened, right? Instead of been closed. Because of that we need that callback that you mention above.

**Comment by dgarciasarai** [comment]
Hey @carlosbrichete, can you take a look to this change? I update the paths that was failing in `ci:test:tango`:
* https://github.com/liferay-tango/liferay-portal/pull/760/commits/028f41f299ff33905404f8b78361ea5f29d67330

Now the menus (organization and session) are links (<a> tag) with `sidebar-collapse-header` class.

Thanks!

**Review by dgarciasarai — APPROVED** [review]
LGTM! 👍 

I opened a [ticket](https://issues.liferay.com/browse/LPS-125915) to migrate the sidebar to ClayPanel as you mention (that was your first attempt but there isn't a callback to control when one collapse is opened, the others have to be closed). With the migration we will fix/improve other things like remove custom CSS or avoid using a custom animation 😄

Thanks @edalgrin!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
