### PR TITLE
LPS-130080 Simulation sidebar color change

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
Hi @claraizquierdo! I'm sending this fixing format issue from https://github.com/liferay-tango/liferay-portal/pull/1449. Take a look at my commit so you can see what the problem was 🙂. It seems you added some undesired spaces.

In case you don't know it, there is a command to run format source in all the modules you have changed in your branch. You have to run `ant format-source-current-branch` in `portal-impl`. It can help you next time.

Good job! 😄

**Comment by sandrodw3** [comment]
ci:forward

**Review by claraizquierdo — COMMENTED** [review]
Thank you so much @sandrodw3 🤗

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
