### PR TITLE
LQRA-72018 fix the experience selector on AB tests

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LRQA-72018](https://issues.liferay.com/browse/LRQA-72018)

Automated tests fixed:
- ABTestIconInExperience 
- CheckABTestPanelAtContentPages 
- DeleteSegmentABTestDraft 
- DeletExperienceWithDraftABTest 
- DeleteSegmentABTestTerminated 
- DeletExperienceWithDraftABTestCancel 
- EditExperienceAfterTerminatedABTest 
- EditExperienceWithDraftABTest
- NotPossibleToEditExperienceWithRunningABTest 
- PanelOpenCloseAfterClickIcon 
- ReassignSegmentABTestDraft 
- ReassignSegmentABTestRunning 
- RenameSegmentABTestDraft 
- RenameSegmentABTestRunning
- RenameSegmentABTestTerminated 
- SwitchExperienceSelected 
- SwitchSitePage

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete , the tests sent in this PR passed

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
