### PR TITLE
LPS-165315 Use keydown event for closing the experiences selector

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-165315)

## Motivation
Improve the UX of the Experiences dropdown.
In this PR we enable the dropdown close on ESC keydown event.

We use the `useEventListener` hook from FI.

## How to test

- get pr
- deploy `layout-content-page-editor-web`
- visit homepage
- edit page and open experiences dropdown
- once it's open press ESC

**Expected**: the dropdown should now be closed

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]
LGTM!

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1357401_2807

**Comment by beltranrengifo** [comment]
ci:reevaluate:1357401_2807

**Comment by beltranrengifo** [comment]
ci:reevaluate:1357401_2807

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:reevaluate:1387401_4252

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
