### PR TITLE
LPS-160241 Move File Extension Item Selector to Document Library Impl module

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

As a content marketer, I want to see the type of document in the info panel, so that I can better understand the asset I am previewing.

More info in the story: [LPS-153204](https://issues.liferay.com/browse/LPS-153204)

### Proposed Solution

We need to move the File ExtensionItem Selector to their own module, so the file extension classification code can be used to print the subtype of the document.

### How to test it

No functional tests, integration tests have been provided with this PR.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!!

This PR is failing because that JS error related with the custom package.json:

package.json: BAD - package name content-dashboard-document-library-impl should be under @liferay/ named scope - https://git.io/JOgy7


if you run it locally, you can see it.

Thanks!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo !!!
> 
> This PR is failing because that JS error related with the custom package.json:
> 
> package.json: BAD - package name content-dashboard-document-library-impl should be under @liferay/ named scope - https://git.io/JOgy7
> 
> if you run it locally, you can see it.
> 
> Thanks!!

hi @cgoncas !
Let me check it and I get back

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
hi @cgoncas!
I think the package.json error is fixed, I see another one but I believe is Java related

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> hi @cgoncas! I think the package.json error is fixed, I see another one but I believe is Java related

Yeahh, fixed :)

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

I think that maybe there is a failing JS test, could you check it?

Thanks!!!

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo !!
> 
> I think that maybe there is a failing JS test, could you check it?
> 
> Thanks!!!

I've removed the test script from the package.json in the doc impl module. Running the CI to verify it works.

**Comment by cgoncas** [comment]
> > Hey @beltranrengifo !!
> > I think that maybe there is a failing JS test, could you check it?
> > Thanks!!!
> 
> I've removed the test script from the package.json in the doc impl module. Running the CI to verify it works.

Hey @beltranrengifo !!

I have push another commit, because there was a Backend test failing too. Now everything should we green :)

Thanks!!

**Comment by beltranrengifo** [comment]
> > > Hey @beltranrengifo !!
> > > I think that maybe there is a failing JS test, could you check it?
> > > Thanks!!!
> > 
> > 
> > I've removed the test script from the package.json in the doc impl module. Running the CI to verify it works.
> 
> Hey @beltranrengifo !!
> 
> I have push another commit, because there was a Backend test failing too. Now everything should we green :)
> 
> Thanks!!

Awesome! I keep an eye on this.
Happy bday Cris, enjoy!! 🥳

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Resolved conflicts & p -f

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
ci:test:relevant - Failed due to [Testray Outage](https://liferay.slack.com/archives/C19PWQ74J/p1660253108886939).

**Comment by beltranrengifo** [comment]
Solve conflict and p -f

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Trying to rebase and baseline, not working :(

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

Could you fix the package.json SF problem?

Thanks!!

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo !!
> 
> Could you fix the package.json SF problem?
> 
> Thanks!!

On my way

**Comment by cgoncas** [comment]
> > Hey @beltranrengifo !!
> > Could you fix the package.json SF problem?
> > Thanks!!
> 
> On my way

No problem, I run formatSource and everything looks ok

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
> > > Hey @beltranrengifo !!
> > > Could you fix the package.json SF problem?
> > > Thanks!!
> > 
> > 
> > On my way
> 
> No problem, I run formatSource and everything looks ok

Good, thnxs!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_4627

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_4627

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_4627

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_4627

**Comment by cgoncas** [comment]
ci:reevaluate:1317401_4627

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:reevaluate:1277401_4524

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
