### PR TITLE
LPS-142862

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-142862](https://issues.liferay.com/browse/LPS-142862)

**Motivation**:
Move tests from AssetList and AssetListUseCase.testcase to Collections.testcase

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
Hi @Luizcarlosqueiroz please modify the component property to segmentation, in order to execute these tests in the Tango ci jobs.

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
