### PR TITLE
LPS-145397 Test fix for ContentPerformanceWithoutButtonCD#MetricsInContentDashboardACEnabled

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-145397](https://issues.liferay.com/browse/LPS-145397)

**Failing Test**:
 - ContentPerformanceWithoutButtonCD#MetricsInContentDashboardACEnabled 

**Motivation**:
- Inconsistencies in the test. Refactored using better macros to accomplish a more reliable result.

**OBS**:
It was also needed to refactor ContentPerformanceWithoutAC#NotSyncedPanel , as the changes made on the previous commit made this test unreliable too.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
