### PR TITLE
LPS-124236 As a content author, I want to be able to export data to an .xls file

### PR DESCRIPTION
**Pull request by YurenaC**
Review of latest changes sent by Brian in his previous review.

Only a small fix was needed to make it work as expected

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
