### PR TITLE
LPS-176394 Fix "Has not" does not appear in Events Segments in DXP

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
"has not" is not translated correctly from AC Event Segments.

[Link story](https://issues.liferay.com/browse/LPS-171785)
[Link impedibug](https://issues.liferay.com/browse/LPS-176394)

Proposed Solution
========
Implement visitNotExpression in com.liferay.segments.asah.connector.internal.expression.IndividualSegmentsExpressionVisitorImpl, so we can read NOT expressions in AC grammar and store them in SegmentsEntry table.

Implement visitNotExpression in com.liferay.segments.asah.connector.internal.expression.JSONObjectIndividualSegmentsExpressionVisitorImpl, so we can return ("operatorNot", "true") inside the JSONObject that represents the filterByCount expression.

Steps to Verify:
----------------
1. Go to Control Panel > Segments
1. Open the view mode for the segment using "has not" modifier
1. The segment appears with the "has not" modifier

Screencaps:
----------------
Captura de pantalla 2023-02-24 a las 10 40 54
Captura de pantalla 2023-02-24 a las 10 40 06

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango-acceptance

**Review by claraizquierdo — APPROVED** [review]
LGTM 🎉

**Review by Mikellorza — APPROVED** [review]

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward:force

**Pull request closed without merging**
