### PR TITLE
LPS-163095 Test Automation: SegmentRequestContentContributor are not propertly registered

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-163215](https://issues.liferay.com/browse/LPS-163215): Test Automation for LPS-163095:
↳[LPS-163095](https://issues.liferay.com/browse/LPS-163095): SegmentRequestContentContributor are not propertly registered

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! 
Do you thin those two tests cover what we need for this bug?

**Comment by CarlosBrichete** [comment]
LGTM! Thanks Luiz 👍

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
