### PR TITLE
LPS-123845 Remove the frontend OData parser and use a backend parser instead

### PR DESCRIPTION
**Pull request by darquesdev**
**Description**
We want to add IN and NOT IN operators in the Segments Editor but the library that we were using on the frontend side called `odata-v4-parser` does not support those operations. Also, the library is not up-to-date, the last commits are from 2018.

We are going to replace first the parser from the frontend to the backend and then we are going to add those new operators.

This pull removes the frontend parser and uses the backend one. Backend parser was merged here: https://github.com/brianchandotcom/liferay-portal/pull/96209.

**How to test it**
Go to People > Segments and everything should work as before but now the Segments Editor uses a backend parser.

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
As it was requested, I'm trying to better explain the issue I found the first time I reviewed the PR.

Basically, the structure used when creating the criteria with different conditions should remain the same after saving the segment. The current PR is nesting the different conditions one inside the previous one, one time and another. 

So, the easiest way to reproduce it is:
1. Go to the segment edit and create a new User Segment called "4 criteria at the same level"
2. Drop 4 conditions at the same level, for example 4 User > Date modified
3. Check that all conditions are at the same level (no nesting)
4. Save the segment and click on it to see the detail
5. The nesting structure has changed, and now the last conditions has been nested in the previous one and so on

Expected (master):

https://user-images.githubusercontent.com/10129814/105697506-ec115980-5f04-11eb-80a7-deb00c7e03d5.mov

Actual:

https://user-images.githubusercontent.com/10129814/105697573-03e8dd80-5f05-11eb-9d3e-efa140fae242.mov

**Comment by dgarciasarai** [comment]
Hey @darquesdev, thank you so much for your videos and explanation. For me, it's crystal clear now 😄  How weird that nesting. I'll take a look! Thanks! ❤️

**Comment by 4lejandrito** [comment]
This story has been discarded for now. Closing.

**Comment by 4lejandrito** [comment]
Reopening as this seems to be the right step in order to fix https://issues.liferay.com/browse/LPS-134561.

**Comment by 4lejandrito** [comment]
We will get back to this after the 7.4 release and backport it when it's ready.

**Pull request closed without merging**
