### PR TITLE
LPS-176789 Migrate DateTimeInput to a functional Component + TypeScript

### PR DESCRIPTION
**Pull request by p2kmgcl**
Motivation
=======
Before adding the new "range" property to the component, I have updated it to be a functional component and migrated the code to typescript.

**Update**: I have added support for ranges, this should complete the task. Now there is a boolean property "range", which is optional and `false` by default, that enables managing ranges inside the component.

The expected format for `value` and `onChange` properties is the one described in JIRA:

```
{ end: '2022/12/12', start: '2022/12/12' }
```

https://issues.liferay.com/browse/LPS-176789

Proposed Solution
========

Using functional components allow us write modern React code that increases re-usability and simplicity. For example, I've been able to reuse the `usePrevious` hook instead maintaining two different states by myself.

Also migrating it to TypeScript is part of portal FrontEnd goals (ex. Clay is written in TypeScript). It enables a high-quality development experience and increases robustness with type checks. In the case of React components, it also allow us to stop depending on the `prop-types` library, having prop checking during the deploy process and zero cost in runtime.

Both `tsconfig.json` and `*.d.ts` files are auto-generated and updating during deploy, but they must be committed.

~~There are no UI or behavior changes, the code should work the same way.~~

**Update**: I have added support for ranges. In order to test this you need to update the default value of range [here](https://github.com/liferay-tango/liferay-portal/pull/3288/commits/eca00f58032965ee27c481702c62a51b5f09b69b#diff-dc8177ef00e6c7187ecd066c4cff1f33b80fab29a1ed5e9a34af55be5a09a1f8R44) and deploy the `segments-web` module, then any DateTimeInput will behave as a range selector.

The backend ignores the result that is being sent, but you can check that it is sending the correct formatted value as expected in devtools:

image

Checklist (optional):
========
- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes
- [X] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:tango

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:tango

**Comment by p2kmgcl** [comment]
ci:test:sf

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @p2kmgcl ,

Great work! Just two comments: 

It was difficult to understand the `saveDateTimeValue` function. What do you think about extracting some of the code in that function to other aux 
functions with beautiful semantic names so that we can understand the code better?

I also have seen a possible bug in the ClayDatePicker when using ranges. If you modify the range it changes the format of the dates to yyyy-mm-dd instead of yyyy/mm/dd and the state of DateTimeInput is not updated correctly.

**Comment by p2kmgcl** [comment]
Hey @claraizquierdo! I just updated the PR simplifying the date management. I think now it is more easy to follow :smile:

**Comment by p2kmgcl** [comment]
ci:test:sf

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_8040

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by p2kmgcl** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
@CarlosBrichete @rafaellajordao , could you confirm that the failing tests are not related with this PR?

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo, these errors seems to not be related to the PR :)

**Comment by p2kmgcl** [comment]
@claraizquierdo @CarlosBrichete do you think we can force forward this to bchan or should we rerun tests? :four_leaf_clover:

**Comment by CarlosBrichete** [comment]
> @claraizquierdo @CarlosBrichete do you think we can force forward this to bchan or should we rerun tests? 🍀

Yep, I think you can force forward it :)

**Comment by p2kmgcl** [comment]
ci:forward:force :partying_face:

**Pull request closed without merging**
