### PR TITLE
LPS-159252 Audit and refactor tests for ContentDashboardAuditGraph.testcase

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-159261](https://issues.liferay.com/browse/LPS-159261)
↳ [LPS-159252](https://issues.liferay.com/browse/LPS-159252): Audit and refactor tests for ContentDashboardAuditGraph.testcase

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete! One more.

**Comment by CarlosBrichete** [comment]
LGTM! :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
