### PR TITLE
LPS-164974 Labels are different from Lexicon at localization dropdown at Segmentation Editor

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-164974)

## Motivation

Texts in labels do not match Lexicon guidelines

## Solution proposed

The text have been modified.

## How to verify

- Create a segment
- Click on the localization button, near the title, in edit page
- In the dropdown, verify the texts:
    - Translated
    - Not translated
    - Default

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
