### PR TITLE
LPS-150991

### PR DESCRIPTION
**Pull request by holatuwol**
## Motivation

https://issues.liferay.com/browse/LPS-150991
https://issues.liferay.com/browse/PTR-3050

## Proposed solution

Searching in the source code, we found several dozen instances where something called getStaticResourceURL and getContextPath, without also calling getPathProxy.

```bash
git ls-files -- '*.java' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
git ls-files -- '*.jsp*' | xargs grep -Fl 'getStaticResourceURL' | xargs grep -Fl 'getContextPath()' | xargs grep -L 'getPathProxy()'
```

I asked the TSE to open [PTR-3050](https://issues.liferay.com/browse/PTR-3050) in order to get a perspective on how to best fix the issue, and the conclusion was that we should fix all instances where we see the pattern appear, rather than fix the API itself to automatically account for potentially incomplete parameter values (as is done with ComboServlet).

After preparing the pull request https://github.com/liferay-core-infra/liferay-portal/pull/964, the core infrastructure team recommended that we split up the pull request by reviewer. According to the DXP Product Teams page, Tango is responsible for Content Dashboard, and so we're sending some of the changes here.

## Steps to verify

The TSE was not able to figure out how to reproduce the issue in all the instances where the pattern appears, but they were able to identify steps to reproduce for all of the issues fixed in this pull request. They have shared a Google Drive document describing what we need to access in the portal in order to see the issue introduced by that file having an erroneous pattern.

https://docs.google.com/document/d/1dmiP23za68PAbbvxp-GrTO_EkRQ6Di0Z1-cqlDZXNts/edit

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by holatuwol** [comment]
ci:test:sf

**Comment by holatuwol** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Pull request closed without merging**
