### PR TITLE
LPS-161017 Test Automation for Add the Download Action to the Version History for Documents and Media

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-165897](https://issues.liferay.com/browse/LPS-165897): Test Automation for LPS-161017:
↳[LPS-161017](https://issues.liferay.com/browse/LPS-161017): Add the Download Action to the Version History for Documents and Media

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete! If the results are ok, would you mind forwarding?

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
