### PR TITLE
LPS-146550 Test Autom. for bug LPS-134561

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-146550](https://issues.liferay.com/browse/LPS-146550): Test Automation for LPS-134561:
↳[LPS-134561](https://issues.liferay.com/browse/LPS-134561): Apostrophe in segment property value breaks filter

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:tes:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
