### PR TITLE
LPS-148315 Retrieve traffic sources data only when the detail view is loaded

### PR DESCRIPTION
**Pull request by cgoncas**
## Motivation
Improve Content Performance Panel performance, avoiding lags and unneeded network requests
**This PR tries to address the THIRD task: _Ungroup requests for Traffic Sources_**

[Jira issue](https://issues.liferay.com/browse/LPS-148315)
[Spike in Jira](https://issues.liferay.com/browse/LPS-148151)

### Launch initial request on top bar button hover event, as we do in Page Audit panel
Currently we are waiting for the component mounted event to request the data, causing a small visible delay.
We can improve this experience by requesting the data on top-bar button hover event, as we do in Page Audit panel

### Avoid re-fetching unneeded data
If a user visits any traffic channel details, ie. Referral, and then goes back to the main page of the CPP using the provided go-back button, 3 unneeded request are executed. The main component data should be already available in client side and the reload of this main view should happen with no delay for the user.

### Ungroup requests for Traffic Sources
Currently, our trafficSources endpoint return all the payload in a single request. Only a tiny fraction of this info is needed to render the main view of the CPP.
We should split this request in multiple ones, sliming down the first one with only the needed data, and requesting each traffic channel details on user's click event over the traffic channel link. 

Change backend response, so in the first request we just return the endpoints to the second level, instead the data.

The response per endpoint will be:

**/analytics_reports/get_traffic_sources**

```
{
  "trafficSources": [
    {
      "name": "direct",
      "share": "100.0",
      "title": "Direct",
      "value": 14,
      "helpMessage": "This is the number of page views generated by people arriving directly to your page."
    },
    {
      "name": "referral",
      "share": "0.0",
      "title": "Referral",
      "value": 0,
      "helpMessage": "This is the number of page views generated by people coming to your page from other sites which are not search engine pages or social sites.",
      "endpointURL", "URL"
      
    },
    {
      "name": "social",
      "share": "0.0",
      "title": "Social",
      "value": 0,
      "helpMessage": "This is the number of page views generated by people coming to your page from social sites.",
      "endpointURL", "URL"
    },
    {
      "name": "paid",
      "share": "0.0",
      "title": "Paid",
      "value": 0,
      "helpMessage": "This is the number of page views generated by people that find your page through Google AdWords.",
       "endpointURL": "URL"
    },
    {
      "name": "organic",
      "share": "0.0",
      "title": "Organic",
      "value": 0,
      "helpMessage": "This is the number of page views generated by people coming from a search engine.",
      "endpointURL": "URL"
    }
  ]
}
```

**/analytics_reports/get_referral_traffic_sources**

```
{
  "referringPages": [],
  "referringDomains": []
}
```

**/analytics_reports/get_social_traffic_sources**

```
{
  "referringSocialMedia": []
}
```

**/analytics_reports/get_social_traffic_sources**

```
{
  "referringSocialMedia": []
}
```

**get_country_search_keywords_traffic_sources&name=paid**

```
{
  "countrySearchKeywords": []
}
```

**get_country_search_keywords_traffic_sources&name=organic**

```
{
  "countrySearchKeywords": []
}
```

### CODE REVIEW

**Review by beltranrengifo — COMMENTED** [review]
Hey @cgoncas ! 
The resultant object looks good to me. I do not like calling each URL property different and so specific, does it make sense to use a generic property name, like `detailDataURL` or something similar?

**Comment by cgoncas** [comment]
> Hey @cgoncas ! The resultant object looks good to me. I do not like calling each URL property different and so specific, does it make sense to use a generic property name, like `detailDataURL` or something similar?

Hey @beltranrengifo !!

I think exactly the same, actually, a lot of code could be delete if all the URL are called endpoint or something. I just take the old code and make it work, but I think that we should use 'endpointURL' and get rid of all the duplicated objects!!

Thanks!!!

**Comment by beltranrengifo** [comment]
> endpointURL

Perfect thxs!

**Comment by beltranrengifo** [comment]
I see new stuff here @cgoncas !
Is this ready for FE work?

Thxs

**Comment by cgoncas** [comment]
> I see new stuff here @cgoncas ! Is this ready for FE work?
> 
> Thxs

Testing to ficha ge the endpointURL para meter.

**Comment by cgoncas** [comment]
> > endpointURL
> 
> Perfect thxs!

Some tests needs to be fixed, but In theory you can use this PR to create the fronten @beltranrengifo

**Comment by cgoncas** [comment]
Heyt @beltranrengifo and @Stephy6 !!!

I have updated this PR and merged it with master

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
> 

Hi @cgoncas, it looks good to me. 
Just wondering if we want to do the refactor now or will create a ticket for later

**Review by YurenaC — APPROVED** [review]

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:tango

**Pull request closed without merging**
