### PR TITLE
LPS-138211 Test Autom. Side panels closed

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-138211](https://issues.liferay.com/browse/LPS-138211)
[LPS-132406](https://issues.liferay.com/browse/LPS-132406)

**Motivation**:
Test automation: 'As a user, I want the side panel to be closed when I sign in, even if I left it open'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , we have conflicts again :( Please rebase master and resend, thanks!

**Pull request closed without merging**
