### PR TITLE
LRQA-74332 Test fix for tests that must open sidebar associated with AC

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74332](https://issues.liferay.com/browse/LRQA-74332)

**Test(s) failing:**
 * ABTestWithoutACConnection#HideABTestPanel
 * ABTestWithoutACConnection#CheckHiddenABTestPanel
 * ABTesting#CheckABTestPanelInfoNotSyncAC
 * ContentPerformanceWithoutAC#FreeTrialButtonPresent
 * ContentPerformanceWithoutAC#DontShowButton
 * ContentPerformanceWithoutAC#ContentPerformanceClosed
 * ContentPerformanceWithoutAC#HideContentPerformancePanel
 * ContentPerformanceWithoutButtonCD#MetricsInContentDashboardACEnabled *
 * ContentPerformanceWithoutAC#MetricsInContentDashboardACDisabled *
*Those tests will keep failing due to a bug.

**Error:**
`
    java.lang.Exception: Element is not present at "xpath=(//a[contains(@class,'d-block')]//*[contains(text(),'Do not show me this again.')])[2]"
`

**Problem:**
 Poshi is trying to perform actions and asserts while the sidebar it hasn't been fully open.

**Fix:**
 Added wait functions to macros

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hi @Luizcarlosqueiroz , if these fixes are needed despite the blocker we can send it. If you are not sure about this, then we can wait until the blocker is closed.

**Comment by Luizcarlosqueiroz** [comment]
> Hi @Luizcarlosqueiroz , if these fixes are needed despite the blocker we can send it. If you are not sure about this, then we can wait until the blocker is closed.

As content performance is working again, I'll run our tests so we can be sure all of them are passing.

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete , indeed the tests are fixed for this PR. The two tests that were expected to fail did it, because of this bug [LPS-151399](https://issues.liferay.com/browse/LPS-151399).

**Pull request closed without merging**
