### PR TITLE
LPS-139947 Execute several search queries to avoid hitting the index.max_result_window Elasticsearch limit

### PR DESCRIPTION
**Pull request by jorgediaz-lr**
Same PR than https://github.com/brianchandotcom/liferay-portal/pull/108838 with Brian changes sent here: https://github.com/jorgediaz-lr/liferay-portal/pull/400 but I have modified the test to reproduce the issue changing the Elasticsearch and Liferay configuration to reproduce the issue without creating 10000 users.

Code changes:
1. Updated all the UserODataRetrieverTest tests to use a new company to execute them => https://github.com/liferay-tango/liferay-portal/commit/6a81703c4e51a6227d16b8bcb12d2cd6600f27db and https://github.com/liferay-tango/liferay-portal/commit/9039d6106fa9d188c84eedb808b6459994ccb264
2. Use ConfigurationTemporarySwapper to change the Elasticsearch configuration before creating the company. Its index will be created with the custom `max_result_window` value => https://github.com/liferay-tango/liferay-portal/commit/3e30a5057a3a592114bd649366c5eaf5ea5bbde7
3. Change the `index.search.limit` portal.properties to match the `max_result_window` value => https://github.com/liferay-tango/liferay-portal/commit/b820df8751a4f19b1dbed9a05ca004694068d8fa 
4. Change test to create only 30 users as now Elasticsearch max_result_window is 10, so we will force to retrieve three pages of users => https://github.com/liferay-tango/liferay-portal/commit/41ffb20f833c6fe526f74f1db3a6005fd55eef80

### CODE REVIEW

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by jorgediaz-lr** [comment]
ci:test:relevant

**Comment by jorgediaz-lr** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:reevaluate:1287401_886

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1287401_886

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:reevaluate:1297401_683

**Comment by jorgediaz-lr** [comment]
ci:forward

**Comment by jorgediaz-lr** [comment]
ci:forward

**Pull request closed without merging**
