### PR TITLE
LPS-162634 Cannot add same asset to more than one personalized variation in manual collection

### PR DESCRIPTION
**Pull request by ricardocousolr**
Motivation
=======
After [LPS-137725](https://issues.liferay.com/browse/LPS-143051), assets in manual collections that are displayed in asset publishers don't show duplicates because they're obtained from a query to Elasticsearch. 

To have this same behavior in the admin view when defining manual collections, [LPS-143051](https://issues.liferay.com/browse/LPS-143051) was added. But this didn't discriminate by personalized variation, i.e. by segment, so one asset could only be added to one personalized variation. Trying to add it to another one would work (although no error or warning would be displayed).

See [LPS-162634](https://issues.liferay.com/browse/LPS-162634) for reproducing steps.

Proposed Solution
========
The solution refines the database query to recover the assets in a given `AssetListEntryAssetEntryRel` to keep only the ones in the given segment (personalized variation).

I've added a new test that captures the issue (`testAssetEntrySelectionAllowSameAssetForDifferentSegments`).

Steps to Verify:
----------------
1. Create a basic web content.
2. Create two segments.
3. Create a manual collection for basic web contents.
4. Add a personalized variation for the first segment and add the content.
5. Add a personalized variation for the second segment and try to add the same content.
Expected with solution: The asset is added to the second personalized variation.
Observed before solution: The asset is not added even though there are no errors.

(These steps are codified in the new test.)

Checklist (optional):
========
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules [doesn't apply]

### CODE REVIEW

**Comment by ricardocousolr** [comment]
ci:test:relevant

**Comment by ricardocousolr** [comment]
ci:test:tango

**Comment by ricardocousolr** [comment]
ci:test:sf

**Comment by ealonso** [comment]
Hey @ricardocousolr,

This pr should go through Echo Team, since it is related with collections. Also, I've already review it, and it LGTM.

cc: @liferay-tango

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
