### PR TITLE
LPS-126971 Refactor ContentDashboardAdminPortletTest (2)

### PR DESCRIPTION
**Pull request by darquesdev**
On top of https://github.com/liferay-tango/liferay-portal/pull/899

This is part of the refactoring of test [ContentDashboardAdminPortletTest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/content-dashboard/content-dashboard-test/src/testIntegration/java/com/liferay/content/dashboard/web/internal/portlet/test/ContentDashboardAdminPortletTest.java)

In this PR:
- [Create mocks for Add mocks for LiferayPortletContext and PortletRequestDispatcher](https://github.com/liferay-tango/liferay-portal/pull/904/commits/3481a0f99ca897855db647293194679824f97825)
- [And use it in the three tests that were using a proxy instead](https://github.com/liferay-tango/liferay-portal/pull/904/commits/abd3456fbee959d3f04b9d446bebdfc86bec893a)

Please see https://github.com/liferay-tango/liferay-portal/pull/889#discussion_r576336744 for further info

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:reevaluate:1032004_9133

**Comment by darquesdev** [comment]
ci:stop

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
