### PR TITLE
LPS-128064 UserODataRetrieverCustomFieldsTest failing with ClassCastException

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**
Fix failing tests. The setup of tests using array of numbers for custom fields were invalid so a ClassCastException was thrown.

**Solution**
Set each test properly, using a numeric array

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Thanks @cgoncas. Exactly, nothing except the tests

**Comment by darquesdev** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
