### PR TITLE
LPS-121385 Delete redundant code.

### PR DESCRIPTION
**Pull request by cgoncas**
**Definition**

A long time ago, when the ODataSearchAdapter interface was implemented, we need to add the code:

```
			PermissionChecker permissionChecker =
				PermissionThreadLocal.getPermissionChecker();

			if (permissionChecker == null) {
				return IndexSearcherHelperUtil.search(searchContext, query);
			}

			if (searchContext.getUserId() == 0) {
				searchContext.setUserId(permissionChecker.getUserId());
			}

			SearchResultPermissionFilter searchResultPermissionFilter =
				_searchResultPermissionFilterFactory.create(
					searchContext2 -> IndexSearcherHelperUtil.search(
						searchContext2, query),
					permissionChecker);

			return searchResultPermissionFilter.search(searchContext);
```

In order to filter the results by permission, but checking with the current Vulcan implementation (com.liferay.portal.vulcan.util.SearchUtil), the one that shares the code with ODataSearchAdapterImpl, we don't need to add this check anymore, we can call 

```
Indexer<?> indexer = _indexerRegistry.getIndexer(className);

			searchContext.setBooleanClauses(
				new BooleanClause[] {
					_getBooleanClause(
						filterString, entityModel, filterParser, locale)
				});

			return indexer.search(searchContext);
```

**How to test it**

As this is just a refactor, is enough running the current test suite

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by darquesdev** [comment]
I like it, it simplifies the code a lot ;)

**Pull request closed without merging**
