### PR TITLE
LPS-159172 | Test Automation Add a share button to the info panel of the content dashboard

### PR DESCRIPTION
**Pull request by rafaellajordao**
JIRA Ticket:
[LPS-152906](https://issues.liferay.com/browse/LPS-152906)
↳ [LPS-159172](https://issues.liferay.com/browse/LPS-159172)
Motivation:
Add a share button to the info panel of the content dashboard

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by Luizcarlosqueiroz — APPROVED** [review]
Good to go!

**Comment by rafaellajordao** [comment]
> ###  ci:test:tango - 171 out of 182 jobs passed in 6 hours 12 minutes
> Click here for more details.

these failures have nothing to do with the test automation :)

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
