### PR TITLE
LPS-124938 Provide a fake category with the count of assets categorized just with one category

### PR DESCRIPTION
**Pull request by darquesdev**
**Motivation**
Currently, the Audit Tool graph is only representing the number of assets with at least one category in each vocabulary. However, it can be also useful to see how many assets there are with assigned categories from just one of the featured vocabularies. 

Given the following Web contents:
image

The audit tool currently shows:
image

With the PR's solution, now the Audit Tools looks like this:
image

*Solution*:

1. [ In order to show the No Audience Category in the x-axis](https://github.com/liferay-tango/liferay-portal/pull/699/commits/6c78b8df780b7f4a9f867d0fa8ed3cab437078e3): It was includes a fake category (none) to show the content uncategorized with the first vocabulary (x-axis) but categorized with the second one (y-axis)

To do so, a new aggregation (`noneCategory`) has been included at top level to find the assets categorized with some y-axis vocabulary categories and none x-axis vocabulary categories. Then, the results have been grouped by the y-axis vocabulary categories with a child aggregation (`childCategories`).

2. [To show the bar with No Stage Category](https://github.com/liferay-tango/liferay-portal/pull/699/commits/1106410495b3d2a1379968c69c76ec581466b7b3): It was included a fake category (none) to show the content uncategorized with the second vocabulary (y-axis) but categorized with the first one (x-axis).

To do so, a new aggregation (`childNoneCategory`) has been added to find the number of assets uncategorized with categories of y-axis vocabulary and categorized with categories from the x-vocabulary, and these counts have been added as a new none category metric with its corresponding category count.

**How to test it**:
New [integration tests](https://github.com/liferay-tango/liferay-portal/pull/699/commits/34af9cdb3547c9101d8f63c13b495017954e64d2) have been added.

### CODE REVIEW

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:bundle

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Hey @darquesdev !!

I have follow the bellow steps to try to validate the requirement:

**Given** any number of web contents that have not an assigned category in be the Vocab 1 or be the Vocab 2
**Then** these contents are represented by a "No [VocabularyName] Category" label in the X axis (assets with no category in the Vocab 2), and a "No [VocabularyName] Category" checkbox above the chart (assets with no category in the Vocab 1)

1. Create a Web Content without any Category (Stage or Audience)
2. Go to the audit tool graph.
3. The message _There is no data_ is shown. But I think these contents should be listed as No Stage Category (axis X) and No Audience Category (axis y)

Screenshot 2020-12-21 at 13 24 16

**Review by cgoncas — COMMENTED** [review]
Hey @darquesdev !!

This is a very beautiful PR (you have described all the steps amazingly in the commits), I have found a problem with a use case, please, let me know what do you think.

Great job!!!

**Comment by cgoncas** [comment]
After talk with Julia, looks like the use case should be rewriten as:

**Given** any number of web contents that have not an assigned category in the vocabulary represented in the X axis (Vocab 2), but have an assigned category in the vocabulary represented above the graph (Vocab 1, checkboxes)
**Then** these contents will be represented by a “No [VocabularyName] Category” label in the X axis, that will show the number of bars and assets corresponding with the number of categories and assets that have no correlate in the Vocab 2

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
