### PR TITLE
LPS-151674 Graph usability improvements

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Improve scalability of the Audit Graph chart
[Link to story or ticket](https://issues.liferay.com/browse/LPS-151674)

Proposed Solution
========
We add a Brush and change graph height if we are visualizing too much data.

Steps to Verify:
----------------
Right now we have a backend limitation of 10 categories per vocabulary, so to test the functionality in the frontend we have mocked the graph data.
1. In `modules/apps/content-dashboard/content-dashboard-web/src/main/resources/META-INF/resources/js/components/AuditGraphApp/AuditBarChart.js` uncomment lines 50 to 69.
1. Inside AuditBarChart component replace all references to `vocabularies` to `voc50x50`.
1. In line 51 and 61 you can change the number of categories per vocabulary.
1. Check that the Brush appears and the graph changes its height when necessary
1. Also check that the legend colors are working again

### CODE REVIEW

**Comment by claraizquierdo** [comment]
@cgoncas I cannot display more than ten vocabularies per axis and I think that the backend is setting that restriction. Could you check it please? 🙏

**Comment by beltranrengifo** [comment]
Hi @claraizquierdo I followed the steps and finally my chart has content 🎉 
But as soon as I hover the bars the chart breaks 🤷 
Using useMemo for the fake properties enables the tooltip to work but if I click the bars the portal breaks...

**Review by beltranrengifo — APPROVED** [review]
Hi @claraizquierdo 
The fake data do not bring consistent behaviour for all the functionalities of the audit chart.
However, what is supposed to be improved in this PR looks fine. So, I think it's safe to proceed to next step

**Comment by claraizquierdo** [comment]
ci:test:sf

**Pull request closed without merging**
