### PR TITLE
LPS-164390 GetContentDashboardItemVersionsResourceCommand Tests

### PR DESCRIPTION
**Pull request by jkappler**
## Motivation

[Link to story](https://issues.liferay.com/browse/LPS-164390)

Adds tests for GetContentDashboardItemVersionsResourceCommand

## Change summary:

* Test that we retrieve the default number of versions (10)
* Test that if we pass the versions to retrieve, that number will be retrieved
* Test that if a content dashboard item is not versionable, nothing is retrieved

### CODE REVIEW

**Comment by jkappler** [comment]
@cgoncas, changed so that we don't depend on an entity, it's all handled with internal classes

**Comment by jkappler** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:forward

**Pull request closed without merging**
