### PR TITLE
LPS-138201 Test Autom. Page Audit Locale

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-138201](https://issues.liferay.com/browse/LPS-138201)
[LPS-119066](https://issues.liferay.com/browse/LPS-119066)

**Motivation**:
Test automation: 'As a content manager, I want to know how many SEO and accessibility related issues my page has'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
