### PR TITLE
LRQA-76693 Change AC branch for Tango tests to more stable version 

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-76693](https://issues.liferay.com/browse/LRQA-76693)

**Test(s) failing:**
 * ACSegmentsInDXP#CheckNotEditableSegmentFromACAtDXP
 * ACSegmentsInDXP#DefaultInstanceNotSynchronizedWithAC
 * ACSegmentsInDXP#PersistSegmentFromACAtDXP
 * ACSegmentsInDXP#RedirectToSegmentPageAC
 * ACSegmentsInDXP#RedirectToSegmentPageErrorAC 
 * ACSegmentsInDXP#ShoudNotRedirectToSegmentPageAC   

**Error:**
`java.lang.Exception: Element is not present at "//div[@class='sidebar-collapse']//li[text()='email']"`

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Comment by pyoo47** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
