### PR TITLE
LPS-137499 Test Autom. for select the 'input type = Submit' elements as a click target. | A/B Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137499](https://issues.liferay.com/browse/LPS-137499)

Motivation:
As a Marketer, I can select "input type = Submit" elements as a click target.

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
