### PR TITLE
LPS-126971 Refactor ContentDashboardAdminPortletTest (3)

### PR DESCRIPTION
**Pull request by darquesdev**
On top of https://github.com/liferay-tango/liferay-portal/pull/904

This is part of the refactoring of test [ContentDashboardAdminPortletTest](https://github.com/liferay/liferay-portal/blob/master/modules/apps/content-dashboard/content-dashboard-test/src/testIntegration/java/com/liferay/content/dashboard/web/internal/portlet/test/ContentDashboardAdminPortletTest.java)

In this PR:
- [Move getProps* test methods to new class ContentDashboardAdminPortletGetPropsTest](https://github.com/liferay-tango/liferay-portal/pull/907/commits/906dbf7eaa78489e545b8e6bf0444e9d027ac818)
- [**Remove** unneeded tests as they are already covered ](https://github.com/liferay-tango/liferay-portal/pull/907/commits/7f0d95f2f5fa53b64e21a1931f9de9a6dc5d37fb)

Please see https://github.com/liferay-tango/liferay-portal/pull/889#issuecomment-779908043 for further info

### CODE REVIEW

**Review by cgoncas — APPROVED** [review]
Very nice pull @darquesdev , only one doubt, do we still need all the params inside the method _getMockLiferayPortletRenderRequest?

Thanks!!!

**Comment by darquesdev** [comment]
Hi. @cgoncas , thanks for the review, indeed, the method `_getMockLiferayPortletRenderRequest`  needs a list of `assetVocabularyNames` to initiate the `PortletPreferences`, and those are created in each method. I could remove `locale`, actually I'm going to do it, thanks!

**Comment by darquesdev** [comment]
ci:test:relavant

**Comment by darquesdev** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
