### PR TITLE
LPS-137436 Test Autom. be able to Sync AC segments per virtual instance | Segmentation

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137436](https://issues.liferay.com/browse/LPS-137436)

Motivation:
Sync AC segments per virtual instance

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
Hey @mateusralv , please remove the ignore = true statement.

**Comment by mateusralv** [comment]
> Hey @mateusralv , please remove the ignore = true statement.
Hi @CarlosBrichete, for the test DefaultInstanceNotSynchronizedWithAC has already been removed.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
