### PR TITLE
LPS-134690 Categories section to be ordered into vocabularies

### PR DESCRIPTION
**Pull request by beltranrengifo**
[See](https://github.com/brianchandotcom/liferay-portal/pull/112720)

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
