### PR TITLE
[Carlos review needed] master-lps-130295

### PR DESCRIPTION
**Pull request by liuxingye**
https://issues.liferay.com/browse/LPS-130327
https://issues.liferay.com/browse/LPS-130334
https://issues.liferay.com/browse/LPS-130293
https://issues.liferay.com/browse/LPS-130294
https://issues.liferay.com/browse/LPS-130306
https://issues.liferay.com/browse/LPS-130302
https://issues.liferay.com/browse/LPS-130309
https://issues.liferay.com/browse/LPS-130310
https://issues.liferay.com/browse/LPS-130311

https://issues.liferay.com/browse/LPS-130295
https://issues.liferay.com/browse/LPS-130296
https://issues.liferay.com/browse/LPS-130297
https://issues.liferay.com/browse/LPS-130298
https://issues.liferay.com/browse/LPS-130299
https://issues.liferay.com/browse/LPS-130300
https://issues.liferay.com/browse/LPS-130301

### CODE REVIEW

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liuxingye** [comment]
ci:test:tango

**Comment by liuxingye** [comment]
ci:test:sf

**Comment by liulukiwi** [comment]
Hi @CarlosBrichete
I rebase and resend it here:
https://github.com/liferay-tango/liferay-portal/pull/1125

**Comment by liulukiwi** [comment]
ci:close

**Pull request closed without merging**
