### PR TITLE
Tango Test Improvement - LPS-177881 | master

### PR DESCRIPTION
**Pull request by ViniLopes20**
Ticket: https://issues.liferay.com/browse/LPS-177881

Hey @CarlosBrichete and @rafaellajordao, I had to make these modifications to the CI rules in the `test.properties` file so that your tests that use AC do not continue to fail in the tango team suite.

After we implemented the new AC and DXP connection screens, it is necessary to use `ASAH` with branch `3.6.x` or higher, so I am changing it and that you make the build AC with branch `3.6.x` which is the most current.

Could you review and forward the PR?

### CODE REVIEW

**Comment by ViniLopes20** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by ViniLopes20** [comment]
Hey @CarlosBrichete, the change is not affecting these tests. My modification is just to change the branch that is used to build the AC when you run `ci:test:tango-analytics-cloud`, when this command is run it will use `Asah 3.6.x` and `Faro 3.1.x` to build the AC.

When you run `ci:test:tango` CI uses the `latest` tag to build `Asah` and `Faro` (this `latest` tag is a more stable version of AC that has the same commits that are in production). So when you ran `ci:test:tango` here, it didn't use the changes that I made. To use the modifications you need to run `ci:test:tango-analytics-cloud`

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Pull request closed without merging**
