### PR TITLE
LPS-174632 Create EventSegmentCriteria

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Create a new EventSegmentCriteriaContributor in order to support EventSegmentCriteria in DXP

[Link to story](https://issues.liferay.com/browse/LPS-171785)
[Link to task](https://issues.liferay.com/browse/LPS-174632)

Proposed Solution
========
Add new criteria type Analytics
Add a new EventSegmentCriteriaContributor of Analytics type that support a download-document-amd-media field.

TODO:
- Add integration tests (I can't add it because the EventSegmentCriteriaContributor is below a FF :()

Steps to Verify:
----------------
1. Activate FF feature.flag.LPS-171722
2. Try to Edit/Create a Segment.
1. Event Segment Criteria should appear in the right panel.

Screencaps:
----------------
Captura de pantalla 2023-02-08 a las 10 50 46

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:Test:Sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango-acceptance

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango-acceptance

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:stop

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango-acceptance

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango-acceptance

**Comment by cgoncas** [comment]
Hey @rafaellajordao and @CarlosBrichete !!

Could you check if the broken tests are related with this PR?

Thanks!!

**Comment by rafaellajordao** [comment]
> Hey @rafaellajordao and @CarlosBrichete !!
> 
> Could you check if the broken tests are related with this PR?
> 
> Thanks!!

Hey @cgoncas, I think it's not related, because these tests are failing in others PRs. Maybe @CarlosBrichete  can confirm this...

**Comment by CarlosBrichete** [comment]
> Hey @rafaellajordao and @CarlosBrichete !!
> 
> Could you check if the broken tests are related with this PR?
> 
> Thanks!!

Yep, I agree with @rafaellajordao! The only suspicious test would be ShoudNotRedirectToSegmentPageAC, but the problem is it has not been run and it happened also in other PRs so I think we should be fine :)

**Comment by cgoncas** [comment]
Send it to brian in: https://github.com/brianchandotcom/liferay-portal/pull/130005

**Pull request closed without merging**
