### PR TITLE
LPS-105733 [Bug] Cursor not-allowed everywhere except for clickable elements

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**
During the review of the clickable elements in AB Testing, we saw that there are some places that the cursor should be: `cursor: not-allowed;`.

**Solution**
Edit non-clickable elements CSS. We decided to not add cursor not-allowed in administration parts like control bar, product menu, or AB Testing sidebar.

**How to test it**
- Connect and sync your Liferay DXP with Analytics Cloud
- Create a page
- Click on the AB Testing button in the control menu
- Create an AB Test with click goal
- Click on the "Set Element" button in the Click Goal section (AB Testing sidebar)

### CODE REVIEW

**Comment by dgarciasarai** [comment]
I let this PR in draft until I review it with @susanavr :)

**Comment by dgarciasarai** [comment]
After reviewing this with @susanavr, she approves the change. Let's start with the code review then :)

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Hey @wincent, can you take a look at this pull request? You were the one setting this CSS for non-clickable elements when you select a Click goal in an AB Test. I added a not-allowed cursor also in the footer and in the search box. Thanks! :)

**Comment by wincent** [comment]
> Hey @wincent, can you take a look at this pull request? You were the one setting this CSS for non-clickable elements when you select a Click goal in an AB Test. I added a not-allowed cursor also in the footer and in the search box. Thanks! :)

Seems reasonable to me. I gather you had to get into a bit of a specificity war to get this to apply, but that's CSS. 😂

**Comment by dgarciasarai** [comment]
Hey @cgoncas, this pull request is ready to be forwarded. Is that ok? Thanks 😄

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
