### PR TITLE
LPS-176122 Unifying integration tests

### PR DESCRIPTION
**Pull request by Mikellorza**
Coming from : https://github.com/liferay-tango/liferay-portal/pull/3314

Motivation
=======
Adding needed integration tests after change in LPS-176122 (whose PR was sent to Tango Repo)
[LPS-17622](https://issues.liferay.com/browse/LPS-176122)

Proposed Solution
========
Added test to verify that still works as expected

Change summary:
---------------
- LPS-176122 Add integration test to Segments Vocabulary Configuration's Listener

**Changes requested in** : 
https://github.com/brianchandotcom/liferay-portal/pull/131203#issuecomment-1455857663
https://github.com/brianchandotcom/liferay-portal/pull/131279#issuecomment-1460061917

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:reevaluate:1407401_516

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
Hi @CarlosBrichete @rafaellajordao,   Can you take a look of the test errors and let me know if we can forward to Brian? 

Thanks

**Comment by CarlosBrichete** [comment]
Hey @Mikellorza, the test is not related to this changes. LGTM :)

**Comment by Mikellorza** [comment]
ci:forward:force

**Pull request closed without merging**
