### PR TITLE
LPS-160028 AC Segments are not being sync with DXP

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
AC Segments are not being sync with DXP[Link to story or ticket](https://issues.liferay.com/browse/LPS-160028)

Proposed Solution
========
We need to set **CheckIndividualSegmentsMessageListener** as **immediate**.

There is no tracker/service looking for this message listener, so as no other OSGi service looks up for it,  it never activates, so the Job that syncs the AC segments is never registered.

Steps to Verify:
----------------
1. Create a Segment at AC
1. Update synchronization time to 1 minute
1. Check segment's admin
1. The segment should be visible in DXP after 1 minute

Notes:
----------------

No integration test has been included, since we can't test that the job is correctly executed.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
Hi @cgoncas! just ckecked it and works fine. In case you missed it you added two commits that do the same.

**Review by Mikellorza — APPROVED** [review]
Hey @cgoncas ,

For me it is working fine.

Regards.

**Review by Stephy6 — APPROVED** [review]
Hi @cgoncas! just ckecked it and works fine. In case you missed it you added two commits that do the same.

**Comment by cgoncas** [comment]
> Hi @cgoncas! just ckecked it and works fine. In case you missed it you added two commits that do the same.

Thanks @Stephy6 !!, I will squash them :)

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:reevaluate:127null_6347

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
As the CI is failing, I am going to send it directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/128263

**Pull request closed without merging**
