### PR TITLE
LPS-119066 [Page Audit] Add details to the current layoutReportsIssues response

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

We need to include details in the list of SEO and Accessibility issues of aPage.

**Proposed Solution**

* The format of the JSON that returns the new Resource Command will be:

The format returned to the frontend will be:
```
{
   "layoutReportsIssues":[
      {
         "total":"5",
         "details":[
            {
               "total":"3",
               "title":"Low contrast ratio",
               "key":"LOW_CONTRAST_RATIO"
            },
            {
               "total":"1",
               "title":"Meta input-ALT attributes",
               "key":"MISSING_INPUT_ALT_ATTRIBUTES"
            },
            {
               "total":"1",
               "title":"Missing video caption",
               "key":"MISSING_VIDEO_CAPTION"
            }
         ],
         "title":"Accessibility",
         "key":"ACCESSIBILITY"
      },
      {
         "total":"7",
         "details":[
            {
               "total":"4",
               "title":"Crawlable Anchors",
               "key":"CRAWLABLE_ANCHORS"
            },
            {
               "total":"1",
               "title":"Font Sizes",
               "key":"FONT_SIZES"
            },
            {
               "total":"1",
               "title":"Links do not have descriptive text",
               "key":"LINKS_DO_NOT_HAVE_DESCRIPTIVE_TEXT"
            },
            {
               "total":"1",
               "title":"Small tap targets",
               "key":"SMALL_TAP_TARGETS"
            }
         ],
         "title":"SEO",
         "key":"SEO"
      }
   ]
}
```

**How to test it**

No Unit/Integration tests have been added to this PR

**_To test it manually_**

Call the new MVC Command:

* http://localhost:8080/web/guest/home?p_p_id=com_liferay_layout_reports_web_internal_portlet_LayoutReportsPortlet&p_p_lifecycle=2&p_p_state=normal&p_p_mode=view&p_p_resource_id=%2Flayout_reports%2Fget_layout_reports_issues&p_p_cacheability=cacheLevelPage&_com_liferay_layout_reports_web_internal_portlet_LayoutReportsPortlet_groupId=20126&_com_liferay_layout_reports_web_internal_portlet_LayoutReportsPortlet_canonicalURL=http%3A%2F%2Fliferay.com&p_p_auth=YfkLrQ8A
_Replacing the groupId with your groupId and the canonicalURL with the canonicalURL you want to check_

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
See https://github.com/liferay-tango/liferay-portal/pull/1161 rebased with updates LPS tickets.

**Pull request closed without merging**
