### PR TITLE
LPS-128439 Use liferay learn module to render documentation link

### PR DESCRIPTION
**Pull request by victorg1991**
# Motivation
Some documentation links are hardcoded in some places of the portal not controlled by the docs team. 

# Proposed Solution
This PR leverages liferay learn module to generate links to the liferay learn docs instead of doing it manually.

### CODE REVIEW

**Comment by victorg1991** [comment]
cc @jkappler

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
@victorg1991, sames tests are failing through executions, could you please take a look and see if they are related?

**Comment by jkappler** [comment]
@Luizcarlosqueiroz, @yang-cao have you seen these issues before? Thanks!

**Comment by victorg1991** [comment]
ci:forward

**Comment by victorg1991** [comment]
I think i have seen this failures in other prs, let’s try one more time

**Comment by victorg1991** [comment]
ci:test:relevant

**Comment by victorg1991** [comment]
ci:test:sf

**Comment by victorg1991** [comment]
ci:reevaluate:1287401_4170

**Comment by victorg1991** [comment]
https://github.com/brianchandotcom/liferay-portal/pull/122456

**Pull request closed without merging**
