### PR TITLE
LPS-149617: Test fix button path to all testing scenarios

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-149617](https://issues.liferay.com/browse/LPS-149617)

**Test(s) failing:**
 * Collections#ManualCollectionInAssetPublisherSegmentTwoPrioritized
 * Collections#DynamicCollectionInCollectionDisplaySegmentTwoPrioritized
 * Collections#DynamicCollectionInAssetPublisherSegmentTwoPrioritized
 * Collections#ManualCollectionInCollectionDisplaySegmentTwoPrioritized

**Error:**
`
java.lang.Exception: Element is not present at "//*[not(self::div)][contains(@class,'btn')][normalize-space()='Add Personalized Variation'][not(contains(@class,'navbar'))]"
`

**Problem:**
After fixed using LPS-149233 , those tests started failing. Their path for the same element are different depending on the property that was set. 

**Fix:**
Created a path that can be use by both cases.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
