### PR TITLE
LPS-134064 Make issues keyboard accesible

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by sandrodw3** [comment]
@victorg1991 🥰

**Review by victorg1991 — APPROVED** [review]

**Comment by victorg1991** [comment]
👏

**Comment by sandrodw3** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:stop

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
