### PR TITLE
LPS-151065 Show the asset's Type to the Content Dashboard's Info Panel

### PR DESCRIPTION
**Pull request by Stephy6**
Motivation
=======
The motivation behind this story is to improve user experience by showing the asset type in the Content Dashboard's info panel.
[LPS-151065](https://issues.liferay.com/browse/LPS-151065)

Proposed Solution
========
The proposed solution consists in adding the asset type beside the asset subtype (already shown) in the top of the panel info view in the Content Dashboard.

Steps to Verify:
----------------
1. Create Display Page Templates for Web Content, Document and Blog Entry (Design -> Page Templates -> Display Page Templates -> Add -> Publish) and mark them as default (Click on ellipsis menu -> Mark ass default)
2. Add a Web Content, some Documents and a Blog Entry (Content&Data -> Web Content/Documents and Media/Blogs)
3. Go to the Content Dashboard, hover over the the content created and click over Info button
4. Check that the type is correctly displayed (*The Blogs don't have Subtype)

Screenshots:
-----------------------
Screenshot 2022-05-11 at 12 31 55
Screenshot 2022-05-11 at 12 31 18
Screenshot 2022-05-11 at 12 30 12

### CODE REVIEW

**Review by claraizquierdo — APPROVED** [review]

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:test:relevant

**Comment by Stephy6** [comment]
ci:test:sf

**Comment by Stephy6** [comment]
ci:forward

**Pull request closed without merging**
