### PR TITLE
LPS-143261 Test Fix: add correct property

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-143261](https://issues.liferay.com/browse/LPS-143261)

**Failing Test**:
- PageAudit#InvalidAPIKeyErrorIsRecovered

**Motivation**:
Test property was incorrect.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
