### PR TITLE
LPS-123845 OData parser: Add new IN and NOT IN operations and move parser to backend

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======
We want to add IN and NOT IN operators in the Segments Editor but the library that we were using on the frontend side called odata-v4-parser does not support those operations. Also, the library is not up-to-date, the last commits are from 2018.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-123845)

Proposed Solution
========

The frontend parser will be replaced by a new backend parser and then, we are going to add those new operators.

This pull removes the frontend parser and uses the backend one. Backend parser was merged here: brianchandotcom#96209.

Steps to Verify:
========
1 - Login the portal
2 - Go to People > Segments 
3 - Everything should work as before but now the Segments Editor uses a backend parser.

In this PR, we also updated vintage code to the actual format rules applied in the project.

Change summary:
---------------

1. LPS-123845 Remove odata-v4-parser library
2. LPS-123845 Remove translateQueryToCriteria use
3. LPS-123845 Check conjunction name in lowercase
4. LPS-123845 Localize true/false values
5. LPS-123845 Fix tests
6. LPS-123845 Fill initialQuery with the right structure, so we avoid calling the parser in the frontend side.
7. LPS-123845 Add test.
8. LPS-123845 Auto sf vintage code

### CODE REVIEW

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:test:tango-acceptance

**Comment by claraizquierdo** [comment]
Everything seems to work fine in the frontend part 👌

**Comment by YurenaC** [comment]
@CarlosBrichete how do we proceed to update the failing poshi test?

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
LGTM :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by YurenaC** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
