### PR TITLE
LPS-144031 Test Autom. to assert that it is not possible to see the author of some pages in the content performance panel | Content Performance

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-144031](https://issues.liferay.com/browse/LPS-144031)

Motivation:
Assert that it is not possible to see the author of some pages in the content performance panel

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete Is the CI not working?

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
hey @mateusralv , this PR seems to have some conflicts. Please rebase with master and resend, thanks :)

**Pull request closed without merging**
