### PR TITLE
LPS-162661 Add help property to specific fields in the frontend

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Help icon is missing from WebDAV field
[Link to story or ticket](https://issues.liferay.com/browse/LPS-162661)

Proposed Solution
========
The specific fields of an asset can now have a help attribute that must display a help icon with a Tooltip.

Steps to Verify:
----------------
- Create a basic document
- Go to Content Dashboard (Liferay Menu > Applications > Content > Content Dashboard)
- Click in the info icon of the document in the table
- In the sidebar click on the details accordion component
- Go to WebDAV URL and check there is a help icon that display a tooltip

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Review by Mikellorza — COMMENTED** [review]
Hey @claraizquierdo ,

The only thing that I have seen of your changes is the name of the method testGetSpecificInformation of the classes : JournalArticleContentDashboardItemTest, BlogsEntryContentDashboardItemTest and FileEntryContentDashboardItemTest.

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
