### PR TITLE
LPS-153059 | Test Automation for LPS-106196: Conjunction selector works as a switch

### PR DESCRIPTION
**Pull request by rafaellajordao**
Hi! :)
This pr is corresponding to this ticket: [LPS-153059](https://issues.liferay.com/browse/LPS-153059)

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by Luizcarlosqueiroz — APPROVED** [review]
Good to go!

**Comment by rafaellajordao** [comment]
ci:forward

**Pull request closed without merging**
