### PR TITLE
LPS-138209 Test Autom. Configure PageSpeed from Instance Settings

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-138209](https://issues.liferay.com/browse/LPS-138209)
[LPS-128383](https://issues.liferay.com/browse/LPS-128383)

**Motivation**:
Test automation: 'As an instance admin, I want to configure PageSpeed from Instance Settings'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz, this PR has some conflicts with master, please rebase master and resend, Thanks!

**Pull request closed without merging**
