### PR TITLE
LPS-152604 Add clear button to TreeFilter

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Add a clear button to the new TreeFilter component in the Content Dashboard
[Link to story or ticket](https://issues.liferay.com/browse/LPS-152604)

**IMPORTANT!!!** We have found a bug in the TreeView and we have opened an issue in Clay's repository: https://github.com/liferay/clay/issues/4874 We hope they will solve it soon.

Proposed Solution
========
We have used a ClayLink component to implement the clear button.

Steps to Verify:
----------------
1. Create a few contents (web contents, documents, external video shortcuts and blogs)
1. Go to the Content Dashboard
1. Open the type filter and select as many nodes as you like and then click Clear All.
1.  Open the type extension and select as many nodes as you like and then click Clear All.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Review by Stephy6 — APPROVED** [review]
Reviewed done, looks great for me!:)

**Comment by YurenaC** [comment]
Stating review ;)

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
LGTM

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
