### PR TITLE
LPS-146545 Fix ChangeLanguageInWidgetPage test property

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LPS-146545](https://issues.liferay.com/browse/LPS-146545)

**Test(s) failing:**
 * ContentPerformance#ChangeLanguageInWidgetPage 

**Error:**
`
com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//[contains(@class,'list-group')]//[@class='list-group-card-item-text' and normalize-space(./text())='Pages']"
`

**Problem:**
 Test is missing property to access System Settings.

**Fix:**
Property fixed.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:test:tango-analyics-cloud

**Comment by CarlosBrichete** [comment]
ci:test:tango-analytics-cloud

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
