### PR TITLE
LPS-162665 WebDAV copy tooltip in wrong position

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-162665)
Applies also for [LPS-162664](https://issues.liferay.com/browse/LPS-162664)

## Motivation

The tooltip in `FileUrlCopyButton` component is missing so the title of the collapsible section is taking its place. 
At the end, the user sees a misplaced tooltip with an irrelevant text.

## Proposed solution

Just adding the title attr to the component with a generic `Copy` text does the job.

## How to verify

- Visit the Content Dashboard
- Open the info panel for a document, for example, an image
- Open the details section panel
- Hover the copy icon icons

**Expected**: a tooltip with the text `Copy`

## Screenshots

image

image

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Rebased & push -f

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Ei Beltrán, I still see sometimes the Details tooltip. It has a weird behaviour:


https://user-images.githubusercontent.com/3276218/190109093-937d113a-dd11-4b8f-90b3-28ccdbb36acc.mp4

**Comment by beltranrengifo** [comment]
> Ei Beltrán, I still see sometimes the Details tooltip. It has a weird behaviour:
> 
>  Screenshare.-.2022-09-14.10_53_10.AM.mp4

Hey @claraizquierdo !
That makes sense as each tab has a title attr.
I'll remove then 👍 
Thanks for the input

**Comment by beltranrengifo** [comment]
> > Ei Beltrán, I still see sometimes the Details tooltip. It has a weird behaviour:
> > Screenshare.-.2022-09-14.10_53_10.AM.mp4
> 
> Hey @claraizquierdo ! That makes sense as each ~tab~ panel has a title attr. I'll remove then 👍 Thanks for the input
> 
> EDIT: I'm recalling now that I added the title for each collapsible panel to handle the unit testing properly, because 'Details' text is now duplicated... I'll try another way

@claraizquierdo I propose to use aria label attr for the collapsible title, this way we can handle the test in a nice way. I think it makes no harm to the AA but let me know your thoughts plz

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
Moving unit tests fixes to its own commit.
Force pushing.

**Comment by beltranrengifo** [comment]
ci:test:sf

**Review by claraizquierdo — APPROVED** [review]
Much better now! 👏

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:reevaluate:1297401_4584

**Comment by beltranrengifo** [comment]
ci:reevaluate:1297401_4584

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
