### PR TITLE
LPS-152366 Fix: Experiences are not shown correctly

### PR DESCRIPTION
**Pull request by lfbesada**
Motivation
=======
To ensure that the SegmentsExperience are always prioritized properly in order to apply it correctly.

https://issues.liferay.com/browse/LPS-152366

Proposed Solution
========

Based on these premises:

- All content type layouts will have at least one segments experience: the default segments experience.
- The default segment experience always will have zero priority, its priority never should be changed.
- All the segments experiences prioritized above the default experience should have a positive value as a priority.
- All the segments experiences prioritized below the default experience should have a negative value as a priority.
- The priority of a segments experience should be unique per layout, which means shouldn't exist more than one segments experiences with the same priority and the same classPK.
- The segment priority change will be incremented or decremented from one to one. 
- The change of the priority of a segments experience shouldn't cause other segments experiences to change their position with respect to the default segments experience, it means, not to cross the zero line because of others.
- The segments priorities should be consecutive.
- The priority order should be maintained always during the update process

In order to accomplish the above premises this solution is based on:

-When updating a segments experience priority, if this value is used as priority for another item, we should release this value in order to be used.
- In order to release the priority without using concurrently a priority for more than one segments experience, we need to create a 'space'. In order to do that:
-> If the new priority is above zero --> all the segments experiences equal or more prioritized should increase its priority (starting with the major priority to avoid duplicate).
-> If the new priority is below zero --> all the segments experiences equal or less prioritized should decrease its priority (starting with the minor priority to avoid duplicate).
- If the updated segments experiences hadn't crossed the zero priority line then the segments experiences that had this priority before should swap its priority for the old priority of the updated item. Otherwise, it shouldn't swap.
- Once ordered properly the segments experience we should remove the created space compacting the priorities. 

Steps to Verify:
----------------

1. Go to Users & Organizations
2. Create 3 different users
3. Go to Liferay > People > Segments
4. Create 3 segments, one for each user
5. Create a Content Page
6. Create 3 experiences, one for each segment
7. Prioritize all the experiences over the default experience
8. Publish
9. Login with each user and visit the Content Page

Expected:
When a user is logged in, the correct experience is shown accordingly.

Hi @liferay-tango 
Thanks for the integration tests, they have been really useful to depurate.
I have found that all cases were covered by them so I just adjust them and added some asserts to ensure the behavior.
Could you please review it? 
Thanks! ❤️ 
Regards

cc: @ealonso

### CODE REVIEW

**Comment by lfbesada** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @lfbesada !!

This PR is beautiful and awesome :). Thanks a lot for the work!!

@CarlosBrichete do you mind to test the priorities in the experiences, so we can send it to master?

Thanks!!!

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
Hi @cgoncas @lfbesada I've just tested it and it is working perfectly! Thanks a lot :D LGTM!

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
