### PR TITLE
LPS-137493 Test Autom. for update empty and success state svgs to have nice colours. | A/B Test

### PR DESCRIPTION
**Pull request by mateusralv**
JIRA Ticket:
[LPS-137493](https://issues.liferay.com/browse/LPS-137493)

Motivation:
Update empty and success state svgs to have nice colours.

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
