### PR TITLE
LPS-133669

### PR DESCRIPTION
**Pull request by jonathanmccann**
Hello,

This is based on the design provided in https://issues.liferay.com/browse/PTR-2464.

Frontend is not my specialty so if anything looks incorrect please feel free to let me know or overwrite my changes.

Thank you.

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test:sf

**Comment by jonathanmccann** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:stable

**Review by sandrodw3 — COMMENTED** [review]
Hi @jonathanmccann! 🙂

LGTM! I only made a little adjustment to the padding classes and updated test snapshots.

Resending it here: https://github.com/liferay-tango/liferay-portal/pull/1258

**Pull request closed without merging**
