### PR TITLE
LPS-150720 Move jsp code to ConnectToAC component

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Fix Performance problem with Experiments Panel
[Link to story or ticket](https://issues.liferay.com/browse/LPS-150720)

Proposed Solution
========
Move the segments_experiment_panel.jsp code to React components and avoid loading the segments experiment panel portlet every time a page is loaded.

Steps to Verify:
----------------

- With DXP not connected to analytics cloud open the segments experiment panel and check that the message is correct
- With DXP connected but not sites synced open the segments experiment panel and check that the message is correct
- With DXP connected and a site synced check that the panel shows the correct information.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
Hi @cgoncas ! we need new props for SegmentsExperimentApp component:

- analyticsCloudTrialURL (string)
- analyticsURL (string)
- hideAnalyticsReportsPanelURL (string)
- isAnalyticsConnected (boolean)
- isAnalyticsSync (boolean)
- pathToAssets (string)

If I can help with anything please let me know :)

**Comment by cgoncas** [comment]
> Hi @cgoncas ! we need new props for SegmentsExperimentApp component:
> 
> * analyticsCloudTrialURL (string)
> * analyticsURL (string)
> * hideAnalyticsReportsPanelURL (string)
> * isAnalyticsConnected (boolean)
> * isAnalyticsSync (boolean)
> * pathToAssets (string)
> 
> If I can help with anything please let me know :)

Hey @claraizquierdo !!!

I. have added to props the fields:

analyticsData {cloudTrialURL, isConnected, isSynced, url}
hideSegmentsExperimentPanelURL
pathToAssets

Let me know if you need something more

Thanks!!!

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by YurenaC** [comment]
Backend changes reviewed, LGTM ;)

**Review by YurenaC — APPROVED** [review]

**Pull request closed without merging**
