### PR TITLE
LPS-152539 Add breacrumb to Assign Roles warning 

### PR DESCRIPTION
**Pull request by cgoncas**
Continuation of https://github.com/brianchandotcom/liferay-portal/pull/117765

### Screenshot

Captura de pantalla 2022-06-15 a las 10 36 38

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
Hey @Luizcarlosqueiroz !!!

could you help me fix the failing test?

thanks!!!

**Comment by Luizcarlosqueiroz** [comment]
ci:test:relevant

**Comment by Luizcarlosqueiroz** [comment]
@cgoncas Fixed!

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
> @cgoncas Fixed!

Thanks a lot @Luizcarlosqueiroz !!!

**Comment by cgoncas** [comment]
> @cgoncas Fixed!

Thanks a lot @Luizcarlosqueiroz !!!

**Pull request closed without merging**
