### PR TITLE
LPS-137430 Test Autom. Combine collections for multisegment-belonging users

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-137430](https://issues.liferay.com/browse/LPS-137430)
[LPS-108368](https://issues.liferay.com/browse/LPS-108368)

**Motivation**:
Test automation: 'Combine content personalizations for multisegment-belonging users'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , some of your tests are failing :(

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! I ran SF locally, and it's working fine.

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz  Hmm the SF failure seems to be related to your PR... Can you please check the error?

**Comment by CarlosBrichete** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete After last changes, SF is correct

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
