### PR TITLE
LPS-113877 [WIP] Flip button to swap axes

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

As a part of the UX improvements in the Content Audit graph, we want to make it easier to change values represented in each of the axes.

**Screenshot**

Screenshot 2020-09-29 at 10 36 12

### CODE REVIEW

**Comment by dgarciasarai** [comment]
Hey @liferay-tango, here is the frontend part for https://issues.liferay.com/browse/LPS-113877. I just added a button with the tooltip "Flip Axes" and an empty `onClick`. These changes need backend code.

Thanks!!

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
https://github.com/liferay-tango/liferay-portal/pull/443

**Pull request closed without merging**
