### PR TITLE
[TS] LPS-160278 User with no permissions can interact with the subscribe button

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
This work solves the problem reported in the [LPS-160278](https://issues.liferay.com/browse/LPS-160278) ticket.
cc: @sontruongces @TaiPhamLR

Proposed Solution
========
What we did to solve this problem.
1. At backend java, class `GetContentDashboardItemInfoMVCResourceCommand`, I check Subscribe Article permission of user and add `disabled` property to ouput Json
2. At frontend, file `Subscribe.tsx`, base on `disabled` property I disable or enable the button.

Steps to Verify
========
1. Create data:
	- 1 Role with only Content Dashboard permissions
	- 1 User with the Role created
	- 1 Web Content
2. Login with the user created
3. Go to Content Dashboard
	- Go to Liferay Menu > Applications > Content > Content Dashboard
4. Open Web Content's info panel
	- Hover the asset > Click at Info icon
5. Click at Subscribe button

- Expected Results: The user should not see the button or be unable to interact with it (or any similar solution).
- Actual Results: The user can interact with the button, with success message, but without permissions and do not affects the subscribe status.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test: tango

**Comment by cgoncas** [comment]
ci:test:tango

**Review by beltranrengifo — COMMENTED** [review]
hey @cgoncas !

Everything seems to work fine.
I would add an extra check for preventing the FE fetching if the html attrs are manually manipulated.
And some small FE test to verify the icon disabled status.
I got this if it's ok with you.

Said that,  for me it's also OK to forward this pull as is, if you prefer.

**Comment by cgoncas** [comment]
> hey @cgoncas !
> 
> Everything seems to work fine. I would add an extra check for preventing the FE fetching if the html attrs are manually manipulated. And some small FE test to verify the icon disabled status. I got this if it's ok with you.
> 
> Said that, for me it's also OK to forward this pull as is, if you prefer.

Hey @beltranrengifo !!

I think it awesome what you said. We can wait until you add the FE code.

Thanks a lot for the review :)

**Comment by beltranrengifo** [comment]
Done @cgoncas !
Running CI again

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1287401_4484

**Comment by cgoncas** [comment]
ci:test:relevan

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
