### PR TITLE
LPS-147233 Performance issue with Combined Segments in Dynamic Collections

### PR DESCRIPTION
**Pull request by YurenaC**
Motivation
=======

Original ticket: https://issues.liferay.com/browse/LPS-147233

After the issue [LPS-104108](https://issues.liferay.com/browse/LPS-104108) was merged into master, the assets started appearing twice in the Asset Publisher.

Analyzing this duplication, we have found also that a big performance issue was related with this duplication, because all the assets of all the segments are in memory (where they are sorted).

Proposed Solution
========
Instead of retrieving the asset for each single segment, what generates several calls to our databases, we retrieve all the assets with a unique call to the database that should also, order them by the variation priority where they belong.

Steps to Verify:
----------------

1. Given a user belonging to Segment 1 and Segment 2
2. And  the configuration to combine assets is enabled
3. When  there's a variation of a dynamic collection targeting segment 1 and segment 2
4. And   there is an asset present in both variations
5. Then   the user will see the asset only once in Asset Publisher / Collection Display Fragment

This code upgrade also resolves https://issues.liferay.com/browse/LPS-147235 (Anyone segment also shown when the user belongs to other segments)

Change summary:
----------------

- LPS-147235 Not showing anyone segment assets when combining assets from all segments in manual collections
- LPS-147233 Avoid retrieve items segment by segment when user belongs to more than one and combined segments check is active

### CODE REVIEW

**Comment by YurenaC** [comment]
@cgoncas 
This is the PR I mentioned you this morning. Just created it as a draft as is still in progress

The performance issue is kind of solved right now, with one call we're retrieving all the assets of all the combined segments where the user belongs to, but the problem here comes with the priority order.

Each asset has a priority field, used in the Asset Publisher, but it is not related at all with the variation priority that we should take into consideration to show all the assets retrieved.

Any assistance in how we can change/modify the _AssetEntryQuery_ to also take into consideration the variation's priority, that is currently stored in _AssetListEntrySegmentsEntryRel_ objects will be very appreciate.

Thanks!

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @YurenaC !!

Could we add some tests to this issues?

The old tests (that duplicate the assets) should not be failing?

Thanks!!

**Comment by YurenaC** [comment]
> Hey @YurenaC !!
> 
> Could we add some tests to this issues?
> 
> The old tests (that duplicate the assets) should not be failing?
> 
> Thanks!!

I was on my way to check that ;)

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:tango

**Comment by YurenaC** [comment]
ci:test:echo

**Comment by YurenaC** [comment]
ci:test:echo

**Comment by YurenaC** [comment]
ci:test:sf

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by YurenaC** [comment]
ci:forward

**Pull request closed without merging**
