### PR TITLE
LPS-131414 We need to initialize the User in the HttpRequest in order to evaluate if the user belongs/doesn't belong to the segment.

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

https://issues.liferay.com/browse/LPS-131414

We have checked that the test **_com.liferay.segments.security.permission.contributor.test.SegmentsEntryRoleContributorTest > testHasPermission_** is working on master just because a entry in the table segmentsEntryRel is created as the same time the segment is created.

**Steps to reproduce it**

1. Comment the next code in  com.liferay.segments.internal.provider.BaseSegmentsEntryProvider 

```
if (segmentsEntryRelLocalService.hasSegmentsEntryRel(
	segmentsEntry.getSegmentsEntryId(),
	portal.getClassNameId(className), classPK) &&
	Validator.isNull(contextFilterString)) {

		return true;
}
```

2. Run the test com.liferay.segments.security.permission.contributor.test.SegmentsEntryRoleContributorTest.testHasPermission
3. The result should be PASSED

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
