### PR TITLE
LPS-176214 Fix at least and at most are not displayed

### PR DESCRIPTION
**Pull request by claraizquierdo**
Included in this PR https://github.com/liferay-tango/liferay-portal/pull/3267

Motivation
=======
When viewing a segment with event criteria, the At least and At most modifiers are not displayed.
[Link to story or ticket](https://issues.liferay.com/browse/LPS-176214)

Proposed Solution
========
We have changed the identifiers for at least and at most modifiers in the constants file. They were 'gt' and 'lt' and now they are 'ge' and 'le'.

Steps to Verify:
----------------
1. Connect and sync AC and DXP
2. Create a segment in AC based on Events using At least or At most
3. In Control Panel -> Job Scheduler -> Scheduled Jobs run the CheckIndividualSegmentsMessageListener job.
4. Go to the segments page and view the sync segment

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by Mikellorza — CHANGES_REQUESTED** [review]
Hi @claraizquierdo ,

I can see the at most and at least but only in english language. If I change the language I still seeing the words in english. Can you review that? 

image


thanks

**Comment by Mikellorza** [comment]
Furthermore, It is strange because I can see some modifiers translated for example between and times but not has and at least and at most not.

**Comment by claraizquierdo** [comment]
> Hi @claraizquierdo ,
> 
> I can see the at most and at least but only in english language. If I change the language I still seeing the words in english. Can you review that?
> 
> image
> 
> thanks

Hi @Mikellorza,
That is because the translation team has not translated yet the new words. the "between" word appears translated because it was already present in the translation files.

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:stop

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Pull request closed without merging**
