### PR TITLE
LRQA-74131: Fix path content display asset summary text

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74131](https://issues.liferay.com/browse/LRQA-74131)

**Test(s) failing:**
 * Collections#DynamicCollectionInCollectionDisplaySegmentTwoPrioritized
 * Collections#DynamicCollectionInCollectionDisplaySegmentNotPrioritized
 * Collections#ManualCollectionInCollectionDisplaySegmentNotPrioritized
 * Collections#DynamicCollectionInCollectionDisplaySegmentPrioritized
 * Collections#ManualCollectionInCollectionDisplaySegmentPrioritized
 * Collections#ManualCollectionInCollectionDisplaySegmentTwoPrioritized

**Error:**
`
java.lang.Exception: Expected text "WC_Title_3" does not match actual text (case insensitive) "WC_Title_3 Showing 1 to 1 of 1 entries. 1" at "//*[contains(@class,'asset-summary')] | //div[contains(@class, 'text-lg-left')]"
`

**Problem:**
 The "CONTENT_DISPLAY_ASSET_SUMMARY_TEXT" path was getting some text that was supposed to. It might have been some changes of the elements of the widget.

**Fix:**
 Fixed path.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
Hey @CarlosBrichete ! Just to let you know, the other Collections tests that are failing are a different path that's causing the error.

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
