### PR TITLE
LPS 134660 Content dashboard sidebar styles

### PR DESCRIPTION
**Pull request by claraizquierdo**
[Jira Link](https://issues.liferay.com/browse/LPS-134660)

This pull unifies the styles between sidebars, taking as a reference the audit sidebar.

- LPS-134660 Unify styles between content sidebar and page audit sidebar
- LPS-134660 Update snapshots

### CODE REVIEW

**Review by beltranrengifo — APPROVED** [review]

**Review by sandrodw3 — APPROVED** [review]
LGTM! 👏🏽 
Happy first PR 🥳

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:relevant

**Comment by sandrodw3** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
