### PR TITLE
Lps 176714 Error appears instead of "commented on blog" event criteria

### PR DESCRIPTION
**Pull request by Mikellorza**
Motivation
=======
An error is showed instead of the segment criteria when a segment is retrieved containing and event "commented on Blog" criteria. 

Story: [LPS-171785 View AC Event Segments in DXP](https://issues.liferay.com/browse/LPS-171785)
Impedibug : [LPS-176714 Error appears instead of "commented on blog" event criteria
](https://issues.liferay.com/browse/LPS-176714)

Proposed Solution
========
-Modify name of the comment on blog event. From AC is coming like commentPosted.
-Add more test to test the impedibug.

Step to reproduce:
========
1-Connect DXP to AC.
2-Create a segment in AC using the event "commented on Blog".
3-Sync segments from AC using Job CheckIndividualSegmentsMessageListener.
4-Go to Control Panel > Segments
5-Open an AC segment that uses a "commented on blog" event
6-View that the error is not appear and you can see the criteria like the screenshot below.

image

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:relevant

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by cgoncas** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:reevaluate:1327401_8414

**Comment by cgoncas** [comment]
ci:forward

**Comment by Mikellorza** [comment]
ci:forward

**Pull request closed without merging**
