### PR TITLE
LPS-163566 Content Dashboard Info Panel loads wrong item after the user subscribes to it

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira issue](https://issues.liferay.com/browse/LPS-163566)

## Solution proposed

Once the sidebar is created the first time, the props will not change because the opening is handled using a `useImperativeHandle` hook which defines an `open` method that operates via arguments, not component props.
This way the `fetchData` method that uses the `Subscribe` component (and all components eventually using that context property) is kind of static as it only receives the `fetchURL` once.

Now, we define a new state property in the `SidebarPanel` component, initially set as the current `fetchURL` but it also gets updated on the next panel openings. This way the prop value is in sync when the `useImperativeHandle` acts.

## How to test

- Navigate to the Content Dashboard
- Open the info panel by clicking in the info icon in a table row, an asset will be displayed in the info panel
- Repeat this step opening another item
- Click on the bell located in the header of the sidebar for this new item displayed in the info panel

**Expected**: after the user loads several items in the info panel and subscribe to them, the item shown in the info panel is the one the user expects to see.

**Actual**: The item loaded in the info panel (after the user loads several items in the info panel and subscribe to them), is wrong

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:reevaluate:1317401_5109

**Comment by beltranrengifo** [comment]
rebasing & push -f

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

Could you add the steps in the description? That would make the review process much faster.

Also, have you only tested the described case in the LPS?

Maybe add a video with the change will be very usefull

Thanks!!

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo !!
> 
> Could you add the steps in the description? That would make the review process much faster.
> 
> Also, have you only tested the described case in the LPS?
> 
> Maybe add a video with the change will be very usefull.
> 
> Also, why this PR doesn't include unit tests?
> 
> Thanks!!

Hey @cgoncas !

Sure I'll add the steps, sorry I skipped that part :(


Uhmmm, yes I've only tested the described case. Not sure if there's any other case to test, only web contents allow the subscription IIRC. Anyway, this fix should cover all cases. Is there anything else you think I can test?

I added a video in the LPS, maybe is that enough?

I'm afraid we are not able to cover this case with FE unit tests. Correct me if Im wrong.
Maybe @CarlosBrichete can help us here 🙌

**Review by claraizquierdo — APPROVED** [review]
LGTM! Great work finding and fixing this @beltranrengifo!

**Comment by beltranrengifo** [comment]
> LGTM! Great work finding and fixing this @beltranrengifo!

Nice @claraizquierdo !
The I ship this one an discuss how to prepare some test with @CarlosBrichete or @Luizcarlosqueiroz

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
