### PR TITLE
LPS-134961 Content of the page is not pushed when the page first load and admin panel is open

### PR DESCRIPTION
**Pull request by sandrodw3**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
@sandrodw3 see https://github.com/liferay-tango/liferay-portal/pull/1369/commits/e74f3b7d3958b3bfd15be7de6904fb561dba6451. This is needed for the `@Reference` to find the component.

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by sandrodw3** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by sandrodw3** [comment]
cc @YurenaC

**Comment by sandrodw3** [comment]
ci:forward

**Pull request closed without merging**
