### PR TITLE
LPS-167023 Move Segmentation from People to the Control Panel.

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
In order to Unify Segmentation, we need to move the Segmentation Portlet Access from Site level to the Control Menu.

The reason to do that is to support Commerce and AC use case.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-167023)

Proposed Solution
========

Once the FF LPS-167023 is set to true SegmentsPanelApp is moved from Site >  People > Segments to Control Panel > Users > Segments

We also have need to change the way we retrieve Segments in view.jsp, as now all the Segments of the company will be visible.

The new service methods have been created in: https://github.com/liferay-tango/liferay-portal/pull/3041

Steps to Verify:
----------------
1. Set feature.flag.LPS-166954=true in portal-ext
1. Go to Control Panel > Users > Segmentation
1. The Segments can be created without issues.

Screenshots:
-----------------------
Captura de pantalla 2022-11-16 a las 10 02 04

Captura de pantalla 2022-11-18 a las 11 21 37

Note:
-----------------------
The included tests, are general, tests, since we have the FF, and the default behaviour won't last long. Once we delete the FF, the test will test that the Portlet is displayed in the right section.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by Mikellorza** [comment]
Hey @cgoncas ,

I am not able to see created segments that I had in guess site. I have created a segment from the new place and I can see it there. It seems that the segments are created under the control Panel site . I guess that it is normal and we have to change something in the segments-web module.

**Review by Mikellorza — CHANGES_REQUESTED** [review]
Hey @cgoncas ,

I am not able to see created segments that I had in guest site. I have created a segment from the new place and I can see it there. It seems that the segments are created under the control Panel site . I guess that it is normal and we have to change something in the segments-web module.

**Comment by claraizquierdo** [comment]
> Hey @cgoncas ,
> 
> I am not able to see created segments that I had in guest site. I have created a segment from the new place and I can see it there. It seems that the segments are created under the control Panel site . I guess that it is normal and we have to change something in the segments-web module.

The same happened to me 👍

**Comment by cgoncas** [comment]
Hey @claraizquierdo and @Mikellorza !!

I have fixed the problem, more integration tests need to be added, but could you take a look and check if everything works propertly?

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@cgoncas 

Now I am able to see created sites from differents sites but I can not delete some segments some of them, specially those from sites because I can delete segments for global site.

image

In the other hand, I do not why but I am not able to synchronize AC segments but this is happen to me also with master.

**Comment by cgoncas** [comment]
> @cgoncas
> 
> Now I am able to see created sites from differents sites but I can not delete some of them, specially those from sites because I can delete segments for global site.
> 
> image
> 
> In the other hand, I do not why but I am not able to synchronize AC segments but this is happen to me also with master.

ohh!!

Good catch, I will analyxe this problem, in the mean time, I will send the new methods in a separate PR, so we can start merging some code.

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> > @cgoncas
> > Now I am able to see created sites from differents sites but I can not delete some of them, specially those from sites because I can delete segments for global site.
> > image
> > In the other hand, I do not why but I am not able to synchronize AC segments but this is happen to me also with master.
> 
> ohh!!
> 
> Good catch, I will analyxe this problem, in the mean time, I will send the new methods in a separate PR, so we can start merging some code.

Hey @Mikellorza !!

Could you record a video?, I can delete them without any problems

Thanks!!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:bundle

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
Hey @cgoncas, testing the bundle I see that is not possible to create variations for Collections :(

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@CarlosBrichete I have added some changes to the PR,  can you test again all the things that you saw?

Thanks in advance.

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
Hi @Mikellorza ,

when I create a new segment from the control panel, its segment is "Control Panel" and I cannot see those segments in other places like collections variations:

Captura de pantalla 2022-11-30 a las 17 07 10

Also, a small detail: if i don't have the FF activated, I still see the scope column in the segments list.

**Comment by Mikellorza** [comment]
Hey @claraizquierdo ,

Thanks for your feedback,

For the first question, this is normal, this is something that it will fix when we will have the site selector in the segment creation view. Now the segment portlet has been moved to the control panel and it was developed to create segments in sites, so for that reason , when you are creating a new segment there you are seeing Control Panel in the site column.

For the second question, I have to check it and I think that I will have to add an FF condition check.

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
@CarlosBrichete  can you take a look of the functional test failures?

Thanks in advance.

**Comment by Mikellorza** [comment]
ci:reevaluate:1297401_5618

**Comment by claraizquierdo** [comment]
Hi @Mikellorza ,

If I disable the feature flag look how the segment page looks:


https://user-images.githubusercontent.com/3276218/205270777-d8f84c26-1f85-418a-a061-5635f5e990d0.mp4



I loose the site menu en the header is changed, is if we were in the control menu.

**Comment by Mikellorza** [comment]
@claraizquierdo  thanks for your feedback , now it is fixed.

**Review by claraizquierdo — APPROVED** [review]
Everything seems to be working!! 🥳

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by claraizquierdo** [comment]
@Luizcarlosqueiroz could you have a look at the tests that are failing in the tango suite please?

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1317401_6242

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
@Luizcarlosqueiroz could you help us checking why the CI is failing? It seems not related to our PR but better to be sure.

**Comment by Luizcarlosqueiroz** [comment]
Hey @claraizquierdo ! The tests that are failing are related to LPS-160028, not with the changes in this PR.
image

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
@CarlosBrichete @Luizcarlosqueiroz @rafaellajordao could you have a look at the relevant tests that are failing so that we can send this PR directly to Brian?

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo, the tests failures are occurring in integration backend tests, so I think a backend developer should take a look to check if they are related.

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Review by Mikellorza — APPROVED** [review]
Hey @cgoncas ,

I have added some changes because it was not possible to add segments in the global site and now for me everything looks good.

Today I am not able to compile the asset-list-web module because I am getting this error:

 _Task :apps:asset:asset-taglib:compileJava FAILED
/Users/mikellorza/liferay-portal-development/liferay-tango-portal-development/liferay-portal/modules/apps/asset/asset-taglib/src/main/java/com/liferay/asset/taglib/internal/display/context/InputAssetLinksDisplayContext.java:358: error: cannot find symbol
                PortletURL portletURL = assetRendererFactory.getItemSelectorURL(
                                                            ^
  symbol:   method getItemSelectorURL(com.liferay.portal.kernel.portlet.LiferayPortletRequest,com.liferay.portal.kernel.portlet.LiferayPortletResponse,long,java.lang.String,com.liferay.portal.kernel.model.Group,boolean,long)_

Maybe the above error will not fail tomorrow or maybe it is an error of my local. Could you compile the asset-list-web module?

Thanks.

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_7663

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1297401_5993

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Send to Brian without forward, because failing tests are not related with this PR: https://github.com/brianchandotcom/liferay-portal/pull/128264

**Pull request closed without merging**
