### PR TITLE
LPS-150725 Use OData for asset list filtering

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-150725)

## Motivation

Use OData for sending the filtering criteria from the FE to the BE

## How to test

No UI or visible changes

- Create a new public vocabulary with two categories
- Create two tags
- Create two web contents:
- - Winter for the title and Snow for the content, use first category and tag
- - Summer for the title and Beach for the content, use second category and tag
- Navigate to Site builder > Collections, and create a Dynamic Collection 
- Choose Web Content Article > Basic web content as the type
- Play with the filters

### Expected
- The view items btn works as expected.
- A valid OData query is sent through the network as an `assetListFilter` property

### CODE REVIEW

**Comment by beltranrengifo** [comment]
Rebased & force pushed

**Comment by beltranrengifo** [comment]
Rebase & force pushing

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
Rebased with https://github.com/liferay-echo/liferay-portal/pull/8611 after approval.
Force pushed.

**Comment by cgoncas** [comment]
Rebased with master to solve conflict 
Force pushed.

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

I have trying to implement the backend of this PR, but I have found a problem

Captura de pantalla 2022-07-11 a las 14 41 53


The expression is: 

(assetTags eq 'tag') and (assetTags eq 'tag2') and (not(keywords/any(k:contains(k, 'keyword'))))

and it should be:

((assetTags eq 'tag') and (assetTags eq 'tag2')) and (not(keywords in ('keyword')))

Could you fix it?

Thanks!!

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

I think not, because we will use the StringQuery ES, that is exactly the same query that AssetQueries are using.

Also, assetTags, should be assetTagIds, and return the ID of the tag, do you have access to the ID of the tag, maybe we should change something in the ItemSelector or something

Thanks!!

**Comment by cgoncas** [comment]
Hey @beltranrengifo !!

Also, if I stop sending the parameter rules and use assetListFilter instead to call the js/components/AssetFilterBuilder/index component, no filter is loaded!!

Thanks!!

**Comment by cgoncas** [comment]
> Hmmm, about the ids, looking at the `getAutoFieldRulesJSONArray` method, the ids never get available in the front end

Instead check the getAutoFieldRulesJSONArray, could you check the result of the item selector?, if they are not available, then we should add it.

Thanks!!

**Comment by beltranrengifo** [comment]
> Hey @beltranrengifo !!
> 
> Also, if I stop sending the parameter rules and use assetListFilter instead to call the js/components/AssetFilterBuilder/index component, no filter is loaded!!
> 
> Thanks!!

Not sure to understand this @cgoncas 🤔

**Comment by cgoncas** [comment]
Closed as discharted

**Pull request closed without merging**
