### PR TITLE
[TS] LPS-160278 User with no permissions can interact with the subscribe button

### PR DESCRIPTION
**Pull request by beltranrengifo**
[See Original PR](https://github.com/liferay-tango/liferay-portal/pull/2851)

Resending due to rebase errors.

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:forward

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
hey @cgoncas 
I had to rebase this pr several times and add a commit deleting things as the SF was complaining.
Do you mind to take a quick look?
Thxs!

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
