### PR TITLE
LPS-130103 Use Item Selector instead our custom Organization Selector

### PR DESCRIPTION
**Pull request by 4lejandrito**
**Motivation**

Currently, in the Segment Editor, we use a custom organization select to select an organization for OrganizationSegmentsFieldCustomizer.

**Proposed Solution**

Remove all our code and reuse the Organization Item Selector, so we don't need to maintain this code anymore.

**How to test it**

1. Create a segment.
2. Add an Organization/Organization condition.
3. Click on select.
4. Select 1 or more organizations.
5. Ensure they are properly selected and populated in the condition.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @cgoncas,

The selection works fine with the view from `﻿﻿organizations-item-selector-web`. I tried both single and multiple selection and the conditions are properly populated. However, the view is a bit outdated (it uses the old management toolbar) and looks worse than the one we had:

Screenshot 2021-04-06 at 17 31 20

We can forward this pull request today and create a ticket to update the view in `organizations-item-selector-web`. I can spend some time tomorrow to do it.

What do you think?

**Comment by cgoncas** [comment]
Hey @4lejandrito !!

As we are trying to release GA1, maybe it is a little bit risky to send this change without the changes in the Organization Item Selector, what do you think if we implement first the changes in the UI and then we apply it to the Segment Editor.

Also, we usually follow the template defined in https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews in order to help team mates review our pull request.

Thanks!!

**Comment by dgarciasarai** [comment]
This pull request is related to https://github.com/liferay-tango/liferay-portal/pull/1040.

**Comment by cgoncas** [comment]
> This pull request is related to #1040.

Hey @dgarciasarai !!

If the pull you mentioned used our custom selector, this change should be discharded, as we are going to move to the item selector.

Thanks!!

**Comment by 4lejandrito** [comment]
Makes sense @cgoncas. I'll apply the changes tomorrow and send everything in one pull request.

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
This is how it will look like now:

Screenshot 2021-04-07 at 13 20 01

**Review by dgarciasarai — COMMENTED** [review]
Hey @4lejandrito, much better know! 😄 

I saw the new management toolbar markup but I don't know if it's the complete new one. As I understand, the new one has a "Clear" action next to the message when you select some/all items. As Ambrin changes for Segments list:

Screenshot 2021-04-07 at 14 10 03

But I don't see that in Organization item selector 🤔 

Screenshot 2021-04-07 at 14 09 51

Maybe I'm wrong or there is something missing. I hope you clarify my mind 😛 

Thanks!

**Comment by 4lejandrito** [comment]
🤔 You are right. I copied it from another module, but I think we have to use the `-v2` one. I'll fix and push force. 

Thanks @dgarciasarai!

**Comment by 4lejandrito** [comment]
@dgarciasarai see https://github.com/liferay-tango/liferay-portal/pull/1051/commits/c001af69d140175f5621c2b16f48e5188dcfb8ee.

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Review by dgarciasarai — APPROVED** [review]
Niiiiice!!! Thanks @4lejandrito 🎉 😄 🚀

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Anything more here @cgoncas or we can forward it when the CI is green? Thanks!

**Comment by cgoncas** [comment]
> Anything more here @cgoncas or we can forward it when the CI is green? Thanks!

I totally trust you guys with everything, if you think is OK, for me it is perfect :)

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:test:tango

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:forward

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
