### PR TITLE
LPS-132254 - Test Autom. Pagination in Content Dashboard

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**JIRA Ticket:**
LPS-132254
LPS-111324 

**Motivation:**
Test automation for the story "As a content author, I want my list to be paginated"

### CODE REVIEW

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:test:tango

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
hey @Luizcarlosqueiroz can you take a look to this PR? It is not passing the SF check

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete Can you call liferay-continuous-integration again?

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
