### PR TITLE
LPS-167108 Add the selected experience to aria-label

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Screen reader does not read the selected experience in the experience selector, it just reads "experience".
[Link to story or ticket](https://issues.liferay.com/browse/LPS-167108)

Proposed Solution
========
We have updated the aria-label so that it includes the name of the experience selected.

Steps to Verify:
----------------

- Go to page editor and create one experience.
- Select the new created experience and close the experience list modal.
- Navigate with a screen reader and check if it reads the selected experience when focusing on the experience selector button.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — APPROVED** [review]
hi @claraizquierdo !
the fix looks fine, the exp name is found by the screen reader 👏 
image

**Comment by claraizquierdo** [comment]
ci:reevaluate:1327401_6609

**Comment by claraizquierdo** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
@CarlosBrichete @Luizcarlosqueiroz we have some tests failing in this PR. Could you have a look please?

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo! I've ignored some of the tests because they need a fix after your changes. This one DisplayPageTemplatesWithMapping#ViewTypesDuringCreation seems to be not related to your changes, so with my commit it should be good to go :)

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
