### PR TITLE
[TS] [Bug: 7.3.x, master] LPS-127308 Category Filters are removed when doing a text search in Content Dashboard

### PR DESCRIPTION
**Pull request by balazssk**
Hi Team,

Can you please review?
https://issues.liferay.com/browse/LPS-127308

As I'm editing ManagementToolbarTag as well, If you are ok with the changes, can you please forward this for review to someone in the frontend team as well?

Thanks,
Balázs

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Review by cgoncas — APPROVED** [review]
Hey @balazssk !!

Thanks a lot for your PR.

i just simplify a little bit your code in Content Dashboard and add the same logic for Tags and Authors.

I resent it to Frontent infra in https://github.com/liferay-frontend/liferay-portal/pull/773

Thanks!!

**Comment by balazssk** [comment]
Cheers @cgoncas !
Thanks for the followup on tags and authors!
I was thinking of using streams as well but couldn't come up with `toArray(String[]::new)`, thanks for the hint!

**Pull request closed without merging**
