### PR TITLE
LRQA-75280 Test fix for Collections#ViewAllTwoCategoriesInDynamicCollection

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:** [LRQA-75280](https://issues.liferay.com/browse/LRQA-75280)

**Test(s) failing:**
 * Collections#ViewAllTwoCategoriesInDynamicCollection

**Problem:**
Changes after [LPS-147515](https://issues.liferay.com/browse/LPS-147515).

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
