### PR TITLE
LPS-143333 Unify p_s_e_id and segmentsExperienceId to fix the edition of variants in ab testing

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-143333)

Proposed Solution
========
We decided tu unify p_s_e_id and segmentExperienceId into one param called: segmentExperienceId. In the page`s edition page we had to check if the id provided in the param is from an experience or from a AB test variant.

### CODE REVIEW

**Comment by ealonso** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by brianchandotcom** [comment]
@claraizquierdo 

_reservedParams.add("segmentsExperienceId"); // LPS-143333

I generally try to avoid params in PortalImpl like that. I'd prefer to keep it as p_s_e_id if it's some global var, or find another solution.

@ealonso fyi

**Comment by sophia6497** [comment]
@claraizquierdo, 
      
    This PR also causes New Blocker [LPS-143431](https://issues.liferay.com/browse/LPS-143431), can you fix that as well? Thank you.

**Comment by ealonso** [comment]
ci:close

**Pull request closed without merging**
