### PR TITLE
LRQA-74184 Test Fix: tests related to Collections priorization

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket:**
[LRQA-74184](https://issues.liferay.com/browse/LRQA-74184)

**Test(s) failing:**
 * Collections#UseManualCollectionAtPortlet 
 * Collections#NotCombineContentForMultisegmentManualCollection 

**Error:**
`
    com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@data-fragments-editor-item-type,'fragments-editor-mapped-item')][*//*[contains(@class,'asset-title')][normalize-space(text())='WC WebContent Title']]//div[contains(@class,'asset-content')]"
`

`
    com.liferay.poshi.runner.exception.ElementNotFoundPoshiRunnerException: Element is not present at "//div[contains(@data-fragments-editor-item-type,'fragments-editor-mapped-item')]//*[contains(@class,'asset-title')][normalize-space(text())='WC_Title_1']"
`

**Problem:**
After LPS-108368, to stories must be prioritized above default variation/segment.

**Fix:**
Prioritized variation/segment.

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
