### PR TITLE
LPS-144020 Is possible to set two vocabularies from different sites in content dashboard's audit graph

### PR DESCRIPTION
**Pull request by beltranrengifo**
[Jira ticket](https://issues.liferay.com/browse/LPS-144020)

### CODE REVIEW

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Review by claraizquierdo — CHANGES_REQUESTED** [review]
I cannot select two vocabularies from the same site (not global)

**Review by claraizquierdo — APPROVED** [review]

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:test:sf

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
