### PR TITLE
LPS-166099 Replace deprecated method with getCompanyCountries

### PR DESCRIPTION
**Pull request by MirnaGama**
https://issues.liferay.com/browse/LPS-166099

**Bug found:** When using a virtual instance, the country list in IP Geocoder cannot be fetched 

**Steps to reproduce:**
- Connect the portal with a MySQL database
- Add include-and-override=portal-liferay-online.properties to portal-ext.properties
- Go to Control Panel > System > Virtual Instances > Create a new virtual instance
- Access the Virtual Instance
- Go to People > Segments > Create a new User Segment with the condition: IP Geocoder Country

**Expected Results**
We can see the list of countries.

**Actual Results**
We can't see the list of countries.

### CODE REVIEW

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by MirnaGama** [comment]
ci:test:sf

**Comment by MirnaGama** [comment]
ci:test:relevant

**Comment by tayannasotero** [comment]
Hey tango team <3 

Just a heads-up to this ticket: its a fix for the issue that the IP Geocoder cannot be fetched in LXC pure environment. It is expected by the Vale Customer (golive on 11/18). 

Thanks so much for all help <3 <3 <3

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
looks good @MirnaGama, @tayannasotero, forwarding to BChan

@cgoncas, we need tests for this, will add a task to create them

For future references:

Deprecated code calls the default company, so that's why it's not retrieved

`@Deprecated
	@Override
	public List<Country> getCountries() {
		return getCompanyCountries(PortalInstances.getDefaultCompanyId());
	}`

**Pull request closed without merging**
