### PR TITLE
LPS-167440 Change scroll behavior in segments editor sidebar 

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Users on right navigation menu bar are not available when page is zoomed to 200%
[Link to story or ticket](https://issues.liferay.com/browse/LPS-167440)

Proposed Solution
========
We have changed the scroll behavior in the segment editor sidebar so that we have scroll in the list of property groups instead of having scroll in each collapsible group. We have followed this design https://www.figma.com/file/CCp5zGMJCVnFtlF8hn8Hhu/%F0%9F%9F%A0--Segment-editor-sidepanel---scrolling?node-id=3%3A18137&t=Q2nQ6n5M8qp2VGj4-0

Steps to Verify:
----------------

1. Access Liferay Portal using Chrome in this case and not set it to maximize
2. Navigate to People > Segments > click the "+" to add a new User Segment
3. Zoom the page to 200% and open the collapsible element in the properties sidebar.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:reevaluate:1267401_5993

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by Stephy6 — COMMENTED** [review]
Hi @claraizquierdo, I'm seeing some things happening that I'm not sure if are working properly or not:
1) With the zoom at 100%, when I click on '+' to add a Segment and go to the Segments Edit view the group of User properties is extended (which I think is correct right?) and the last properties of the list have borders (I think is related to the screen size):
Screenshot 2022-11-18 at 13 33 06

2) With zoom at 200% happens the same behaviour as in (1): 
Screenshot 2022-11-18 at 13 37 08
and with the Segments group poperties the message(Inherited attributes are not taken into account to include members in segments.) is displayed like this:
Screenshot 2022-11-18 at 13 38 09

**Comment by claraizquierdo** [comment]
> Hi @claraizquierdo, I'm seeing some things happening that I'm not sure if are working properly or not:
> 
> 1. With the zoom at 100%, when I click on '+' to add a Segment and go to the Segments Edit view the group of User properties is extended (which I think is correct right?) and the last properties of the list have borders (I think is related to the screen size):
>    Screenshot 2022-11-18 at 13 33 06
> 2. With zoom at 200% happens the same behaviour as in (1):
>    Screenshot 2022-11-18 at 13 37 08
>    and with the Segments group poperties the message(Inherited attributes are not taken into account to include members in segments.) is displayed like this:
>    Screenshot 2022-11-18 at 13 38 09

You are totally right @Stephy6 , I forgot to commit one change. Could you review again now please?

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango

**Comment by Stephy6** [comment]
Hey @claraizquierdo ! LGTM 🎉

**Comment by claraizquierdo** [comment]
@CarlosBrichete could you have a look at the tests that are failing?

**Comment by CarlosBrichete** [comment]
yeah, those tests are also failing in our daily routine :(, not related with this PR. I hope we can fix them this week

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
