### PR TITLE
LPS-149174 Auto

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
Improve SegmentsExperience API (addSegmentsExperience and appendSegmentsExperience) to accept userId and groupId, since in some situations service context is not properly initialized, like when we are calling the json api to create entities or when we are creating the initial site with WelcomeSiteInitializer.

[Link to the issue](https://issues.liferay.com/browse/LPS-149174) 

Proposed Solution
========
Update addSegmentsExperience and appendSegmentsExperience adding userId and groupId to methods signature in SegmentsExperienceServiceImpl and SegmentsExperienceLocalServiceImpl.

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:reevaluate:1377401_972

**Comment by ealonso** [comment]
ci:reevaluate:1377401_972

**Comment by cgoncas** [comment]
Hey @ealonso !!

Thanks a lot for this PR; the changes have a lot of sense, my only concern is that it would be hard to back port. have you talked with Support about it?


Thanks!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
> IMHO

I think the same, we will see :)

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by ealonso** [comment]
ci:forward

**Pull request closed without merging**
