### PR TITLE
LPS-168718 - Content Performance Side Panel cannot be opened using the Keyboard

### PR DESCRIPTION
**Pull request by ethib137**
https://issues.liferay.com/browse/LPS-168718

**Steps to Reproduce:**
1. Login to Liferay as an admin.
2. Using the keyboard tab until you reach the "Content Performance" button in the Control Menu.
3. Once it is focused, press enter.

**Expected Result:**
- The "Content Performance" side panel should open.

**Actual Result:**
- The "Content Performance" side panel does not open.

### CODE REVIEW

**Comment by ethib137** [comment]
ci:test:sf

**Comment by ethib137** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Review by claraizquierdo — APPROVED** [review]
Everything works perfect! Thank you @ethib137 .

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
