### PR TITLE
LPS-171760  Implement Move the Segmentation Portlet Access from Site level to the Control Menu.

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
In order to Unify Segmentation, we need to move the Segmentation Portlet Access from Site level to the Control Menu.

The reason to do that is to support Commerce and AC use case.

[Link to story or ticket](https://issues.liferay.com/browse/LPS-167023)

Proposed Solution
========

Once the FF LPS-167023 is set to true SegmentsPanelApp is moved from Site >  People > Segments to Control Panel > Users > Segments

We also have need to change the way we retrieve Segments in view.jsp, as now all the Segments of the company will be visible.

The new service methods have been created in: https://github.com/liferay-tango/liferay-portal/pull/3041

Steps to Verify:
----------------
1. Set feature.flag.LPS-166954=true in portal-ext
1. Go to Control Panel > Users > Segmentation
1. The Segments can be created without issues.

Screenshots:
-----------------------
Captura de pantalla 2022-11-16 a las 10 02 04

Captura de pantalla 2022-11-18 a las 11 21 37

Note:
-----------------------
The included tests, are general, tests, since we have the FF, and the default behavior won't last long. Once we delete the FF, the test will test that the Portlet is displayed in the right section.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
Original PR: https://github.com/liferay-tango/liferay-portal/pull/3158#issuecomment-1380185317

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @CarlosBrichete and @rafaellajordao !!

Could you take a look to the failing tests to check if they are related with this PR?

Thanks!!

**Comment by CarlosBrichete** [comment]
Hey @cgoncas ! There are no poshi tests failing due this PR's changes. There are some integration tests failing though, but I'm not sure if they are related or not. If you need I can give you a list of all these tests, just in case you cannot access to Testray.

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
Hey @CarlosBrichete and @rafaellajordao !!

Could you take a look to this PR and check if the failing tests are related with this PR?

Thanks!!

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Hey @cgoncas! The tests failing in the Tango suite are not related to this PR. The ci:test:relevant is throwing different test failures each run, so I think something's wrong with the CI, not sure if related with your changes :(

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_8250

**Comment by cgoncas** [comment]
Sent directly to Brian: https://github.com/brianchandotcom/liferay-portal/pull/129289, after review that the failing tests are not related with this PR.

**Comment by cgoncas** [comment]
Continue https://github.com/liferay-tango/liferay-portal/pull/3195

**Pull request closed without merging**
