### PR TITLE
LPS-160790 Extract ContentDashboardItemSearchClassMapperTracker to Info Framework

### PR DESCRIPTION
**Pull request by jkappler**
### Motivation

ContentDashboardItemSearchClassMapperTracker provides a flexible way of interchanging between a searchClassName (used mainly for asset searching) and a className (used in info framework). Since it's in content dashboard other places cannot benefit from it.

The goal of the task is to extract the logic to the info framework so that it can be used in other places

More info in the task: [LPS-160790](https://issues.liferay.com/browse/LPS-160790)

### Proposed Solution

Copy logic from ContentDashboardItemSearchClassMapperTracker to InfoSearchClassMapperTracker and replace usages

### Note

No functional tests, integration tests have been provided with this PR.

Check that nothing was broken was made here: https://github.com/liferay-echo/liferay-portal/pull/9325. 
Issues with compiling tests was not related to the changes, and PR was sent here: https://github.com/liferay-tango/liferay-portal/pull/2705

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:sf

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@cgoncas, I sent to Echo first, and no issues were found. So I wanted to pass this through you first to check if everything makes sense 😄  

Please let me know what you think and if changes are needed, will gladly change them

**Review by cgoncas — APPROVED** [review]
Hey @jkappler !!

This is an amazing job, I totally love the approach, I trust Lourdes and you with everything related with the code and the quality of the solution, and I can't find anything that I would change.

Thanks!!

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
will fix, something looks wrong

**Comment by jkappler** [comment]
bad rebase from my side...

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:tango

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
some day it will work.....

**Comment by jkappler** [comment]
fixed rebase baseline issues

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1267401_4557

**Comment by jkappler** [comment]
Hi @liulukiwi, these tests for Add and Edit categories seem weird. Could they be related to the PR? Thanks!

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by liulukiwi** [comment]
Hi @jkappler , those has been fixed in [LRQA-76609](https://issues.liferay.com/browse/LRQA-76609), not related to your pull.

**Comment by cgoncas** [comment]
ci:forward

**Comment by jkappler** [comment]
Finally green! Thanks @cgoncas!

**Comment by jkappler** [comment]
> Hi @jkappler , those has been fixed in [LRQA-76609](https://issues.liferay.com/browse/LRQA-76609), not related to your pull.

Thanks @liulukiwi!

**Comment by jkappler** [comment]
ci:forward

**Comment by jkappler** [comment]
ci:stop

**Comment by jkappler** [comment]
ci:close

**Comment by jkappler** [comment]
ci got stucked, so rebased and resent here https://github.com/liferay-tango/liferay-portal/pull/2722

**Pull request closed without merging**
