### PR TITLE
LPS-152542 Add breadcrumbs to Instance Settings alerts

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

As a Segmentation Admin,
I want to be able to navigate to System Settings from the alerts,
so that easily re-enable Segments Service configurations at the System level.

https://issues.liferay.com/browse/LPS-152542

### Proposed solution

Rename the provider method getConfigurationURL to getCompanyConfigurationURL so we can add a new method getConfigurationURL that returns the system level configuration URL

### How to test it 

Integration have been added.

To manually test it:

1. Deactivate segmentation and roles segmentation at system level
2. Go to Instance Settings
3. A link is provided to enable both configuration at system level

### Screencaps

Captura de pantalla 2022-06-30 a las 16 53 11

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Review by beltranrengifo — APPROVED** [review]
hi @cgoncas !
everything looks fine to me 🎉

**Comment by beltranrengifo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
One thing I just realize @cgoncas 
In the designs, title and paragraph go in separate lines
image
Adding the link instead of a paragraph makes all in the same line.
Probably we should place the link inside the paragraph so we keep the line break...

**Review by beltranrengifo — CHANGES_REQUESTED** [review]
~~Styles need minor fixes~~

Update: I can see it's already done, sorry about the noise

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
> ~Styles need minor fixes~
> 
> Update: I can see it's already done, sorry about the noise

NP.

**Pull request closed without merging**
