### PR TITLE
LPS-172371 | Test Fix | Master

### PR DESCRIPTION
**Pull request by rafaellajordao**
# Element is not present at Collections#ViewVariationsIndicatorOnSelectModal

Hi! :)
This pr is corresponding to this ticket: **[LPS-172371](https://issues.liferay.com/browse/LPS-172371)**

### Problem:
The path is not finding the element on the page. There was a behavior change in the collections selection modal. The "List" view option no longer exists.

### Fix:
A refactor was needed in the macros used in the test. Swap the macros from List to Table and the assertions in the table.

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by CarlosBrichete — APPROVED** [review]

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
