### PR TITLE
LPS-167647 Change ContentDashboardItemVersionActionProvider service rankings to avoid duplicates

### PR DESCRIPTION
**Pull request by Mikellorza**
[Task](https://issues.liferay.com/browse/LPS-166995)
[Subtask](https://issues.liferay.com/browse/LPS-167647)

Coming from this merged PR : https://github.com/liferay-tango/liferay-portal/pull/2986 

## Motivation 
We have to change the service rankings of ContentDashboardItemVersionActionProvider to avoid rankings duplicates.

## Solution proposed

Modify service ranking property to the osgi annotation of the provider classes and set a value that is unused.

### CODE REVIEW

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:sf

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
Hi @Luizcarlosqueiroz  and @CarlosBrichete ,

Can I forward this PR to Brian ? I have seen that some test have failed but I do not know them.

Thanks in advance :)

**Comment by CarlosBrichete** [comment]
Hey @Mikellorza those errors seems to be not related to Poshi. Try to trigger the ci:test:relevant again

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by Mikellorza** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
