### PR TITLE
LPS-151911 Test Autom. for LPS-144732: Content Dashboard shows error when displaying details of article whose authors has been deleted

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
Motivation
=======
[LPS-151911](https://issues.liferay.com/browse/LPS-151911): Test Automation for LPS-144732:
↳[LPS-144732](https://issues.liferay.com/browse/LPS-144732): Content Dashboard shows error when displaying details of article whose authors has been deleted

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
ci:reevaluate:1307401_3108

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
@Luizcarlosqueiroz check the SF, it seems it is failing

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
