### PR TITLE
LPS-152539 Add link to instance settings in experience selector warning message and display context refactor

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
Add breadcrumb to Segments Disabled warning in experience selector. Also reduce technical debt included in https://github.com/liferay-tango/liferay-portal/pull/2572/
[Link to story or ticket](https://issues.liferay.com/browse/LPS-152539)

Proposed Solution
========
Update the alert with a link to instance settings if the user have permission to access instance settings. If not, it will show a text informing the user to contact the system administrador.

Steps to Verify:
----------------
1. Log in with Test user
1. In Instance settings disable segmentation
1. Go to the home page edition, open the experience selector panel and check that the warning shows a link to instance settings
1. Create a user with no permissions for instance settings and repeat the previous steps. Check that the warning does not show a link. (People -> Membership, select the user and assign roles as Site Owner)

Screenshots (optional):
-----------------------

Captura de pantalla 2022-06-23 a las 14 43 47

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by beltranrengifo** [comment]
ci:forward

**Pull request closed without merging**
