### PR TITLE
LPS-144030 Test Autom. for all assets with display page template in content performance panel | Content Performance

### PR DESCRIPTION
**Pull request by mateusralv**
**JIRA Ticket:**
[LPS-144030](https://issues.liferay.com/browse/LPS-144030)

**Motivation:**
Content performance panel for all assets with display page template.

**Tests created:**
- 1 MetricsIconNotVisibleInDocumentDisplayPageWithoutAC   
- 2 MetricsIconVisibleInDocumentDisplayPage 
- 3 PanelInformationInDocumentDisplayPage
- 4 ViewsGraphInDocumentDisplayPage
- ~5 Not Possible to automate~
- 6 ChangeLanguageInDocumentDisplayPage 
- 7 MetricsIconNotVisibleInBlogDisplayPageWithoutAC
- 8 MetricsIconVisibleInBlogDisplayPage 
- 9 PanelInformationInBlogDisplayPage
- 10 IntervalSelectorInBlogDisplayPage
- 11 ViewsGraphInBlogDisplayPage
- 12 ChangeLanguageInBlogDisplayPage

### CODE REVIEW

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete

**Comment by CarlosBrichete** [comment]
Hey @mateusralv, it seems these tests are failing:
6 ChangeLanguageInDocumentDisplayPage
7 MetricsIconNotVisibleInBlogDisplayPageWithoutAC
12 ChangeLanguageInBlogDisplayPage

Please check, thanks :)

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:sf

**Comment by mateusralv** [comment]
ci:test:tango-analytics-cloud

**Comment by mateusralv** [comment]
@CarlosBrichete all tests are passing on CI 🎉🎉

**Comment by CarlosBrichete** [comment]
ci:forward

**Pull request closed without merging**
