### PR TITLE
LPS-160232 Use searchClassNames instead of the original classNames

### PR DESCRIPTION
**Pull request by jkappler**

### CODE REVIEW

**Comment by jkappler** [comment]
ci:test:relevant

**Comment by jkappler** [comment]
@Tim-Cao, in case you want to check the other issues

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by Tim-Cao** [comment]
Perfect fix @jkappler. The fix works for all three scenarios mentioned in ticket.

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
