### PR TITLE
LPS-159251 | Audit and refactor tests for SegmentationDisabled.testcase

### PR DESCRIPTION
**Pull request by rafaellajordao**
JIRA Ticket:
[LPS-159249](https://issues.liferay.com/browse/LPS-159249)
↳ [LPS-159251](https://issues.liferay.com/browse/LPS-159251)
Motivation:
Audit and refactor tests for SegmentationDisabled.testcase

### CODE REVIEW

**Comment by rafaellajordao** [comment]
ci:test:sf

**Comment by rafaellajordao** [comment]
ci:test:tango

**Comment by rafaellajordao** [comment]
ci:test:tango

**Review by Luizcarlosqueiroz — APPROVED** [review]
Good to go!

**Comment by Luizcarlosqueiroz** [comment]
ci:forward

**Pull request closed without merging**
