### PR TITLE
LPS-144029 Test Autom: Widget page metrics

### PR DESCRIPTION
**Pull request by Luizcarlosqueiroz**
**Ticket**:
[LPS-144029](https://issues.liferay.com/browse/LPS-144029)
[LPS-126047](https://issues.liferay.com/browse/LPS-126047)

**Motivation**:
Test automation: 'As a marketer, I want to see content performance metrics also in the context of widget pages'

### CODE REVIEW

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
ci:stop

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
ci:test:tango-analytics-cloud

**Comment by Luizcarlosqueiroz** [comment]
@CarlosBrichete :)

**Comment by CarlosBrichete** [comment]
ci:forward

**Comment by CarlosBrichete** [comment]
Hey @Luizcarlosqueiroz , this PR has some SF failures, please fix, thank you :)

**Comment by Luizcarlosqueiroz** [comment]
> Hey @Luizcarlosqueiroz , this PR has some SF failures, please fix, thank you :)

Fixed!

**Comment by Luizcarlosqueiroz** [comment]
ci:test:ci

**Comment by Luizcarlosqueiroz** [comment]
ci:test:sf

**Pull request closed without merging**
