### PR TITLE
LPS-176937 Dates should be translated to the User's language

### PR DESCRIPTION
**Pull request by ces-locpham**
Hi team,
Please help me review this ticket.
Ticket: https://issues.liferay.com/browse/LPS-176937
Thanks,
Loc
cc:@tototrinh

### CODE REVIEW

**Comment by claraizquierdo** [comment]
Thank you for your PR @locpham97 , we will have a look at it asap. Next time, if you could follow our PR template we will appreciate it 😄  https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews

**Review by claraizquierdo — APPROVED** [review]
Everything seems to be working fine 👍

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Comment by claraizquierdo** [comment]
ci:test:tango-acceptance

**Comment by claraizquierdo** [comment]
ci:reevaluate:1377401_9816

**Comment by claraizquierdo** [comment]
@rafaellajordao @CarlosBrichete could you have a look at the failing tests in the tango suite 🙏 ?

**Comment by CarlosBrichete** [comment]
Hey @claraizquierdo, no unique failures occurred because of this PR, so LGTM :)

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
