### PR TITLE
LPS-161227

### PR DESCRIPTION
**Pull request by mbowerman**
Motivation
=======
In [LPS-154892](https://issues.liferay.com/browse/LPS-154892), we added some caching logic for the SegmentsEntryIds, so that the SegmentsEntryIds did not need to be recomputed. However, we mistakenly reused the cached SegmentsEntryIds for the "SEGMENTS_EXPERIENCE_IDS" parameter, which is incorrect, as a Segments Entry and a Segments Experience are two different things. This causes many bugs in which we attempt to look up a SegmentsExperience by a segmentsEntryId, which can result in a NoSuchExperienceException.

One such manifestation of this bug is that when the "Enable Assign Roles by Segment" configuration is enabled, content pages cannot be edited. Attempting to edit the content page will result in a "Content Page Editor is temporarily unavailable." error appearing in the UI, and a NoSuchExperienceException along with a stacktrace appearing in the logs.

[LPS-161227](https://issues.liferay.com/browse/LPS-161227)

Proposed Solution
========
Removed the bug introduced by rewriting the `_getSegmentsExperienceIds` method so that it could not inadvertently return the cached SegmentsEntryIds, but instead merely reused the cached segmentsEntryIds for the purpose of calculating and returning the segmentsExperienceIds (which I assume was the original intention of https://github.com/liferay/liferay-portal/commit/c9cc3cf8581408c932c8f1725e74bc376cf4ebef).

Steps to Verify:
----------------
1. Start up Liferay and log in as the admin user.
2. Navigate to [Global Menu] > Control Panel > System Settings > Segments > Segments Service.
3. Check the Enable Assign Roles by Segment checkbox and click the Save button.
4. Navigate back to the Home page of the default Site.
5. Click the Edit icon to attempt to edit the page.
6. Verify that the page loads successfully and that there are no errors in the logs.

Change summary (optional):
---------------
* Rewrote the `_getSegmentsExperienceIds` method so that it always returns a segmentsExperienceIds array and never a segmentsEntryIds array.
* Added integration test

Checklist (optional):
========
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [N/A] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by mbowerman** [comment]
ci:test

**Comment by cgoncas** [comment]
Hey @mbowerman !!

Thanks a lot for the contribution :). Here in the Tango Team we follow this [Play](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews) to open a PR,  could you follow the same process?

Also, it is possible to add a test to this bug?

Thanks!!

**Comment by mbowerman** [comment]
Hi @cgoncas,

I have several questions about the documentation that you linked:

At the beginning it says:

> 1. Create a new PR in the[ liferay-tango](https://docs.google.com/document/d/1COqaW0Ws_oJv3mppYTToiyuyvlpVBrzpDzrgIToE954/edit) user, remember to push the branch to [liferay-tango](https://docs.google.com/document/d/1COqaW0Ws_oJv3mppYTToiyuyvlpVBrzpDzrgIToE954/edit), not your personal fork:

However, I do not have access to the Google Doc that is linked by "liferay-tango". Could I please be granted access to it?

I attempted to run the command `git push git@github.com:liferay-tango/liferay-portal.git LPS-16122` to push my branch to the `liferay-tango` user, rather than my origin, as the documentation says to do. However, I was met with a permissions error:
```
ERROR: Permission to liferay-tango/liferay-portal.git denied to mbowerman.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Step 3 says:

> 3. Add reviewers that could provide the best feedback for your PR.

How do I do that? I've never used the "add reviewers" feature before when sending pull requests to other Liferay Product Teams, so I am not familiar with it. Also, I'm wondering which reviewers I should add? I don't see any recommendations in that document about which reviewers should review which pull requests, or even anywhere that lists what reviewers are available.

**Comment by mbowerman** [comment]
Hi @cgoncas,

I have added the requested test here: https://github.com/liferay-tango/liferay-portal/pull/2728/commits/f9aed112aa330ba07a3b1f45d59a604f9906f504, and I verified that it failed before my changes and passed after my changes.

I will run the ci tests requested in the [Play](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews) document; however, I am at present unable to fully follow the Play document as I do not seem to have permissions to push to the `liferay-tango` user repo.

IMO this bug is a very bad bug, so we should strive to get this fix merged as quickly as possible. It would be a real shame if this fix failed to make the next Update because of some permissions issue that prevents me from following the team's pull request policy (which is not a policy I've seen from any other team).

**Comment by mbowerman** [comment]
ci:test:sf

**Comment by mbowerman** [comment]
ci:test:relevant

**Comment by mbowerman** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
> Hi @cgoncas,
> 
> I have added the requested test here: [f9aed11](https://github.com/liferay-tango/liferay-portal/commit/f9aed112aa330ba07a3b1f45d59a604f9906f504), and I verified that it failed before my changes and passed after my changes.
> 
> I will run the ci tests requested in the [Play](https://liferay.atlassian.net/wiki/spaces/ENGTANGO/pages/1368786134/Play+Pull+Request+Reviews) document; however, I am at present unable to fully follow the Play document as I do not seem to have permissions to push to the `liferay-tango` user repo.
> 
> IMO this bug is a very bad bug, so we should strive to get this fix merged as quickly as possible. It would be a real shame if this fix failed to make the next Update because of some permissions issue that prevents me from following the team's pull request policy (which is not a policy I've seen from any other team).

Hey @mbowerman !!

Thanks a lot for trying to follow the play, thanks to you we have discovered that the last update is not applicable for people outside the Tango Team, I am updating the documentation, the important part for you is to follow the steps described, you don't need to create the branch in the liferay-tango user :).

We request to you to follow the Play, because it is really hard to know the what, how and why of your changes, that is the reason we need you fill the next template:

Motivation
=======
What is the problem this work solves, including
[Link to story or ticket](https://issues.liferay.com/browse/LPS-XXXX)

Proposed Solution
========
What I/we did to solve this problem

Steps to Verify:
----------------
1. A setup step / beginning state
1. What to do next
1. Any other instructions
1. Expected behavior
1. Suggestions for testing

Change summary (optional):
---------------
* Tidy, well formulated commit message
* Another great commit message
* Something else I/we did

Screenshots (optional):
-----------------------
Show-n-tell images/animations here

Checklist (optional):
========
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

That is also the reason we request (when possible) a test, so we can do a faster review.

Thanks a lot for your contribution, once you fill the template we will proceed with reviewing your code, so we can do a very fast review.

**Comment by cgoncas** [comment]
@Luizcarlosqueiroz could you verify that the failing tests are not caused by this PR?

Thanks!!!

**Comment by mbowerman** [comment]
Hi @cgoncas I have copied the information from the LPS ticket into the template that you wanted and edited the top comment of the pull.

**Review by cgoncas — APPROVED** [review]
Nicely done @mbowerman !!

LGTM :)

**Comment by liferay-tango** [comment]
ci:forward

**Comment by Luizcarlosqueiroz** [comment]
Hey @cgoncas @mbowerman !
The failures seams unrelated to the changes made at this PR. To only difference is a test related to Collections that appears to be a flaky issue.

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
Hey @mbowerman !!

ci:forward is not working for this PR, could you send this PR directly to Brian.

thanks!!!

**Comment by mbowerman** [comment]
Manually forwarded to Brian at https://github.com/brianchandotcom/liferay-portal/pull/122181

**Pull request closed without merging**
