### PR TITLE
LPS-160241 Move File Extension Selector to Documents Library Module in the Content Dashboard.

### PR DESCRIPTION
**Pull request by cgoncas**
### Motivation

As a content marketer, I want to see the type of document in the info panel, so that I can better understand the asset I am previewing.

More info in the story: [LPS-153204](https://issues.liferay.com/browse/LPS-153204)

### Proposed Solution

We need to move the File ExtensionItem Selector to their own module, so the file extension classification code can be used to print the subtype of the document.

### How to test it

No functional tests, integration tests have been provided with this PR.

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1377401_4315

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1267401_4562

**Comment by cgoncas** [comment]
ci:reevaluate:1267401_4562

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
ci:reevaluate:1267401_4562

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1387401_3118

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:tango

**Comment by cgoncas** [comment]
The CI got stuck, resend https://github.com/liferay-tango/liferay-portal/pull/2731

**Comment by Luizcarlosqueiroz** [comment]
Hey @cgoncas ! None of the tests that are failing are associated with the changes of this PR.

**Pull request closed without merging**
