### PR TITLE
LPS-139996 Remove duplicated code for Session Property Vocabularies configuration

### PR DESCRIPTION
**Pull request by 4lejandrito**
See https://issues.liferay.com/browse/LPS-139996.

### CODE REVIEW

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:stop

**Comment by 4lejandrito** [comment]
ci:test:sf

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:test:relevant

**Comment by CarlosBrichete** [comment]
Just started reviewing :)

**Comment by CarlosBrichete** [comment]
I've tested it manually and everything seems to be working fine :)

**Comment by CarlosBrichete** [comment]
ci:test:relevant

**Comment by 4lejandrito** [comment]
ci:forward

**Pull request closed without merging**
