### PR TITLE
LPS-113393 Remove feature flag to enable TRAFFIC SOURCES in Content Performance panel

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Remove the feature flag to show the traffic sources metrics in the Content Performance panel.

@cgoncas @darquesdev

### CODE REVIEW

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:stop

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
Continues in https://github.com/liferay-tango/liferay-portal/pull/73

**Pull request closed without merging**
