### PR TITLE
LPS-117492 Add Integration tests for traffic sources

### PR DESCRIPTION
**Pull request by cgoncas**
**Motivation**

Is it very hard to create a functional test to test the Traffic Sources functionality (we need to have a display page indexed on Liferay), We have decided it is better to have at least one integration test.

**Proposed Solution**

Ass an Integration test that Mocks the Http request to AC, this way we can almost test this functionality full circle. 

**How to test it**

This pull add an integration tests

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
ci:test:relevant

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Sorry, one commit was not pushed with this pull request, that is strange :).

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by dgarciasarai** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by cgoncas** [comment]
Maybe you need to deploy portal-test? @dgarciasarai

**Comment by darquesdev** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by darquesdev** [comment]
ci:forward

**Pull request closed without merging**
