### PR TITLE
LPS-143212 Remove segmentsExperienceId parameter from simulation iframe

### PR DESCRIPTION
**Pull request by claraizquierdo**
Motivation
=======
[Link to story or ticket](https://issues.liferay.com/browse/LPS-143212)

Proposed Solution
========
We have removed segmentsExperienceId param from simulation iframe.

### CODE REVIEW

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:sf

**Comment by claraizquierdo** [comment]
ci:test:relevant

**Review by beltranrengifo — COMMENTED** [review]
🎉

**Review by beltranrengifo — APPROVED** [review]

**Comment by claraizquierdo** [comment]
ci:forward

**Pull request closed without merging**
