### PR TITLE
LPS-145283 Check if the type settings are copied from default segments entry when we are creating a new variation

### PR DESCRIPTION
**Pull request by ealonso**
Motivation
=======
It is trying to fix an inconsistency caused when we are creating a new variation for manual asset entry list. 

The first time we create a new manual asset entry list, we need to select the supported item types:

Manual_4_-_Liferay

Then if we are create a new variation of an asset entry list we are creating it with empty type settings.

This value is important because we are using it to show the available item types on select dropdown.

Manual_4_-_Liferay

Since the value of type settings for classNameIds and classTypeIds is empty we are using the default value to show the available item types, in this case, all item types.

[Link to ticket](https://issues.liferay.com/browse/LPS-145283)

Proposed Solution
========
I've modified the code to copy the type settings from default segments entry when we are creating a new variation.

Steps to Verify
----------------
1. Go to Site Builder > Collections
2. Create a Manual collection
3. Select and asset for Anyone segment
4. Create a variation using a segment
5. Check the database the type settings column for the new created variation (AssetListEntrySegmentsEntryRel table)

### CODE REVIEW

**Comment by ealonso** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
cie:test:relevant

**Comment by cgoncas** [comment]
Hey @ealonso !!!

Sorry I was waiting for the results of the ci:test:relevant but I never started those tests :(.

This is the most beatifull pull I have never seen.

Thanks a lot for the work :)

**Review by cgoncas — APPROVED** [review]
LGTM

**Comment by ealonso** [comment]
Thanks you very much for your advice, @cgoncas now I'm a new developer, 😂, more examples of my new pulls to other teams because of you ❤️ 

https://github.com/liferay-lima/liferay-portal/pull/2662
https://github.com/liferay-upgrades/liferay-portal/pull/233
https://github.com/liferay-search/liferay-portal/pull/246

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1327401_2154

**Comment by cgoncas** [comment]
ci:test:relevant

**Comment by cgoncas** [comment]
ci:reevaluate:1287401_1657

**Comment by ealonso** [comment]
ci:test:relevant

**Comment by ealonso** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
