### PR TITLE
LPS-119066 [Page Audit] Display the Google PageSpeed issues sections with total count

### PR DESCRIPTION
**Pull request by dgarciasarai**
**Description**

Page Audit allows to make a quick check of that compliance and get warnings and tips to improve each one of the categories. Once the API Key is enabled, the Page Audit panel will show the detail of the issues in two sections: Accessibility and SEO.

**Within this pull request**

- Include `layoutReportsIssuesURL` in each canonicalURL (backend stuff)
- Create LayoutReportsIssuesList component to show the sections and issues of the canonicalURL provided
- Create store to avoid prop-drilling information (it will be a detail view for each issue)
- Style adjustments (sidebar body padding, vertically center basic information, etc)
- Add new message keys with its proper buildLang
- Fix and add new frontend tests

**Screenshot**

Screenshot 2021-04-27 at 18 15 23

### CODE REVIEW

**Comment by dgarciasarai** [comment]
cc: @sandrodw3

**Comment by sandrodw3** [comment]
Updated with new no issues message and issues reloading when changing language 🙂

**Comment by dgarciasarai** [comment]
ci:test:sf

**Comment by dgarciasarai** [comment]
LGTM 🚀  Let's forward this!

**Comment by dgarciasarai** [comment]
ci:forward

**Pull request closed without merging**
