### PR TITLE
LPS-138663 Delete reads metrics for documents

### PR DESCRIPTION
**Pull request by cgoncas**
Motivation
=======
Documents should not include reads metrics in the content performance panel

[Link to story or ticket](https://issues.liferay.com/browse/LPS-138663)

Proposed Solution
========
Don't fill the read metrics for Documents in the Content Performance Panel

Steps to Verify:
----------------
1. Create a Display Page for Documents
1. Mark it as default
1. Create a Document
1. Create a Content Page with an Asset Publisher fragment.
1. Click on the title of the document in the Asset Publisher
1. Open the Content Performance panel for the document
1. Read metrics are not shown in the content performance panel

Screencaps:
----------------
Screenshot 2022-02-08 at 15 58 18

### CODE REVIEW

**Comment by cgoncas** [comment]
ci:test:sf

**Comment by cgoncas** [comment]
ci:test:relevant

**Review by YurenaC — APPROVED** [review]

**Comment by YurenaC** [comment]
LGTM

**Comment by CarlosBrichete** [comment]
LGTM 👍

**Comment by cgoncas** [comment]
ci:forward

**Comment by cgoncas** [comment]
ci:forward

**Pull request closed without merging**
